### PR TITLE
Remove trailing slash: check for match

### PR DESCRIPTION
**Pull request by tobymackenzie**
A 301 seems to imply that the redirect target exists.  Redirecting to a 404 page is all the same to a normal end user, but it seems Google will see it as a crawl error.  This change just makes sure that there is a route that will match the redirected URL; otherwise a 404 is thrown.

### CODE REVIEW

**Comment by xabbuh** [comment]
Could we maybe think about changing this to an event listener instead that would only be executed when there actually is a controller for the URL being accessed?

**Comment by tobymackenzie** [comment]
Is this for performance reasons?  I'm not sure I know how to go about implementing that.  Regardless, it is possible to create routes without controllers, for the case when another application is fielding those routes and you just want to have them in this application for generating URL's.

**Review by javiereguiluz — APPROVED** [review]
I'd fix a bit the code syntax (some spaces are missing) and I'd also add a short comment before the new code to explain why it's needed.

**Comment by tobymackenzie** [comment]
Made some changes.  Let me know if the comment is too long.  I'm not great with brevity.

**Comment by weaverryan** [comment]
I'm 👎 on this right now. It's a really interesting situation: if you 301 redirect to a 404, Google sees that as a broken link. But, in order for this to happen, Google must already be following a link to *get* to this controller in the first place. 

Said differently, the problem described here is that Google goes to `/foo/` and we 301 redirect to `/foo` (which is a 404). But, how did Google know to go to `/foo/` in the first place? There must be a link to this page, right? In that case, we really *do* have a broken link somewhere, a link to `/foo/`?

@tobymackenzie do I misunderstand the situation? Let me know :).

**Comment by tobymackenzie** [comment]
That's basically correct.  However, two circumstances complicate that:

- External links to your site pointing there.  You don't really have control over this.
- You once had a page with trailing slash already indexed by Google.  This could be because of a different architecture for the previous version of your site or whatever.  Google remembers this even though no pages still have that link.  Google goes there, sees the 301, follows it, and assumes there should be something there.  Now, because there is a "link" to the page and whatever magic a 301 gives it, it seems to stay forever.

**Comment by javiereguiluz** [comment]
I'm closing this because there's no consensus around it and it has some downvotes for Docs Core team. @tobymackenzie I'm sorry, but rest assured that we'll reconsider this decision if we receive more reports about this in the future. Thanks!

**Pull request closed without merging**
