### PR TITLE
Wrap the instantiation in parenthesis, and chain away

### PR DESCRIPTION
**Pull request by yceruto**

### CODE REVIEW

**Review by javiereguiluz — COMMENTED** [review]
This doesn't work in old PHP versions, right? If I'm right, we still use old PHP in the docs. Maybe we should discuss about this and start using more modern PHP features?

**Comment by xabbuh** [comment]
Javier is right. This does not work for PHP 5.3: https://3v4l.org/BdRT4

But I am not sure if we should really care about that. I mean we already started to use the `class` constant for example.

**Comment by yceruto** [comment]
[This works for PHP 5.4+](https://3v4l.org/tkgcq) but this is a bugfix for the previous code that [doesn't works for neither PHP versions](https://3v4l.org/opq0u) though :stuck_out_tongue_winking_eye: hence, any decision that taken here involves changes in these examples.

**Comment by xabbuh** [comment]
Thanks @yceruto. I have merged this as having a solution for PHP 5.4+ is better than invalid code. :) If someone thinks, we should show PHP 5.3 compatible examples, I'll happily merge such a PR.

**Pull request merged**
