### PR TITLE
Updated the screenshot of exceptions in dev environment

### LINKED ISSUE #7778: Redesigned the exception pages
See https://github.com/symfony/symfony/pull/20951  We must update the screenshots of the exceptions.

I will take care of this and I've put it "on hold" because we'll make some tweaks until Symfony 3.3 is released.

### PR DESCRIPTION
**Pull request by javiereguiluz**
This fixes #7778.

### CODE REVIEW

**Comment by apfelbox** [comment]
Not sure whether this is a thing that is currently in use in the symfony docs, but minifying this image reduces its size by around 50%.

2017-07-04 at 17 33

**Comment by javiereguiluz** [comment]
@apfelbox is that a lossless compression? Because I always use ImageOptim to compress images (without losing quality) and this was the best it could do:

image-compression

**Comment by apfelbox** [comment]
It is not lossless, but you can compare the images and in several hundred images I minified I had exactly 1 image that had a *visual degradation*.

So technically not lossless, but visually sort-of-lossless.

**Comment by javiereguiluz** [comment]
@apfelbox you are right ... the visual differences I see between the two versions are minimal, so I'm using your compressed version. Thanks!

**Review by xabbuh — APPROVED** [review]

**Review by OskarStark — APPROVED** [review]

**Comment by xabbuh** [comment]
Thank you Javier.

**Pull request closed without merging**
