### PR TITLE
Update templating.rst

### PR DESCRIPTION
**Pull request by asandjivy**
Fixed bad div tags count

### CODE REVIEW

**Comment by wouterj** [comment]
Wow, amazing catch!

However, instead of making it a bit more complex (11 is more complex than 10), what about changing the code instead?

```diff
- {% for i in 0..10 %}
-   <div class="{{ cycle(['odd', 'even'], i) }}">
+ {% for i in 1..10 %}
+   <div class="{{ cycle(['even', 'odd'], i) }}">
      <!-- some HTML here -->
    </div>
  {% endfor %}
```

**Comment by asandjivy** [comment]
Yes i thought about it.
But maybe  just to specify that it is possible to count from 0 and the result is 11.
If you prefer to start from 1, no problem ;)

**Comment by asandjivy** [comment]
My friend suggests:

**Comment by wouterj** [comment]
`0 .. 9` is fine by me as well, although I think `1 .. 10` is the most explaining (you can just look at the last number and know how many times the element is printed). Please note that we're specificly documenting Symfony here, not Twig. So we don't have to document the possibility to count from `0`, that's up to Twig's docs.

**Comment by asandjivy** [comment]
ok fine ;) let's go for 1 .. 10

**Comment by wouterj** [comment]
👍 
status: reviewed

Thanks!

**Comment by weaverryan** [comment]
Great catch @asandjivy! And I also like the solution that you ended with. Thanks!

**Pull request closed without merging**
