### PR TITLE
[Mailer] document FileTransport

### PR DESCRIPTION
**Pull request by Kocal**
Hi, this time it's not a Encore PR :smile: 

It needs https://github.com/symfony/symfony/pull/31947.

Thanks!

### CODE REVIEW

**Review by noniagriconomie — APPROVED** [review]

**Comment by noniagriconomie** [comment]
Can also be usefull in dev env
Maybe add a more generic sentence for both env?

**Comment by Kocal** [comment]
I don't really know why you can use this in dev env, but I may be wrong. :disappointed_relieved: 
What can be your use case for example?

**Comment by noniagriconomie** [comment]
Because you may not have install any mailer soft
And want to check the rendered email

The idea is to not document as « only for test env » and let developers choose, of course test env is the best usage but other can be usefull also :)

**Comment by Kocal** [comment]
Hum that's right :+1: 
I've updated the documentation

**Comment by OskarStark** [comment]
The code-PR is closed. Can we close here @Kocal ?

**Comment by Kocal** [comment]
Ah yes we can close it, I forgot about it.

**Pull request closed without merging**
