### PR TITLE
Improved the Process component documentation

### PR DESCRIPTION
**Pull request by javiereguiluz**
This is related to #8879 and, if merged, it must be merged after it.

### CODE REVIEW

**Review by TomasVotruba — COMMENTED** [review]
Awesome :+1:

**Comment by xabbuh** [comment]
I think we should merge this PR and #8879 into the `3.4` branch.

**Comment by TomasVotruba** [comment]
I've added Rector for this: https://github.com/rectorphp/rector/pull/188

Could you confirm there I got it right? Also more cases would be great

**Comment by javiereguiluz** [comment]
@xabbuh I'm sorry but I'm merging this into 4.0 because the related #8879 PR was merged into 4.0 too instead of 3.4.

**Comment by TomasVotruba** [comment]
Thanks @javiereguiluz

**Pull request merged**
