### PR TITLE
Added a new short article about linting translation files

### LINKED ISSUE #7536: Document the lint:xliff command
See https://github.com/symfony/symfony/pull/21578 and http://symfony.com/blog/new-in-symfony-3-3-xliff-linter

### PR DESCRIPTION
**Pull request by javiereguiluz**
This fixes #7536.

### CODE REVIEW

**Review by HeahDude — APPROVED** [review]

**Comment by xabbuh** [comment]
Can we merged this into the `3.2` branch?

**Comment by javiereguiluz** [comment]
No. It's a 3.3 feature.

**Comment by xabbuh** [comment]
I'd say let's add a `versionadded` directive then.

**Comment by xabbuh** [comment]
And `lint:yaml` command was already present in Symfony 2.7. Shouldn't we not document that command in older versions of the docs too?

**Comment by javiereguiluz** [comment]
@xabbuh can we merge this ... and then create a new simple PR based on this (mentioning only the `lint:yaml` command) and merge it in 2.8?

**Comment by xabbuh** [comment]
Thank you Javier.

**Comment by javiereguiluz** [comment]
Thanks for merging. I'm going to create the new PR now.

**Comment by javiereguiluz** [comment]
Done in #7801.

**Pull request closed without merging**
