### PR TITLE
Added a note about using ":" in Redis passwords

### LINKED ISSUE #7531: RedisTrait::createConnection() does not support password with ":"
See https://github.com/symfony/symfony/issues/21745 for details.

### PR DESCRIPTION
**Pull request by javiereguiluz**
This fixes #7531.

### CODE REVIEW

**Review by viviengaetan — APPROVED** [review]
:+1:

**Review by xabbuh — APPROVED** [review]

**Comment by xabbuh** [comment]
Thank you Javier.

**Comment by weaverryan** [comment]
I don't know enough about Redis, but is this correct? Is there never a username? SncRedisBundle seems to suggest that there *can* be a username: https://github.com/snc/SncRedisBundle/blob/master/Tests/DependencyInjection/Configuration/RedisDsnTest.php#L203-L204

If you *can* have a username, then this needs to be tweaked. If you cannot have a username, then the master branch needs some work - it has expanded redis details (`redis_apdapter.rst` not sure why it's so different on master) that show the use of a username

**Comment by xabbuh** [comment]
@nicolas-grekas Can you help us here?

**Comment by nicolas-grekas** [comment]
No username, only a password

**Comment by viviengaetan** [comment]
They are only speaking about password in their [manual](https://redis.io/topics/security#authentication-feature)

**Pull request merged**
