### PR TITLE
Added php start tag to page_creation.rst

### PR DESCRIPTION
**Pull request by PhoneixS**
| Q | A |
| --- | --- |
| Doc fix? | yes |
| New docs? | no |
| Applies to | all |
| Fixed tickets |  |

I have added the php start tag `<?php` to the code fragments of the file `src/AppBundle/Controller/LuckyController.php` as newcomers can forget it.

### CODE REVIEW

**Comment by javiereguiluz** [comment]
@PhoneixS thanks for proposing this improvement.

Although it's true that for a newcomer this may be useful, right now in the Symfony docs we never use the opening PHP tag (except when explaining the PHP templates vs Twig templates and in the chapter dedicated to newcomers: http://symfony.com/doc/current/book/from_flat_php_to_symfony2.html). I think we should keep using this convention, but let's wait and see what do doc managers think about this idea.

**Comment by PhoneixS** [comment]
Maybe is better to add a note about it instead of adding the start tag.

**Comment by xabbuh** [comment]
I am :-1: on this too (I am sure we discussed that some time ago but I cannot find that PR again).

In my opinion, PHP developers know that they have to use the opening tag and thus we do not need to clutter our examples with it. We could add a note somewhere, though what would be the best place for it?

**Comment by WouterJ** [comment]
This has been discussed within the doc team a couple of times (Can't find the PR/issue either) and I'm :-1: too.

There are a couple reasons to not use these start tags:

 * The PHP start tag is a very basic PHP thing. People working with Symfony should already have a certain knowledge of the PHP language, so 100% change they know the PHP start tag is needed. When it's forgotten, it's also pretty easy to find out.
 * It breaks the PHP code highlighter, meaning we have to change every code example to use `html+php`
 * It makes all code examples 2 lines longer, which isn't worth it considering (1).
 * If we are going to change it, we have to change it for all PHP code examples. After merging this PR, things would be very consistent, resulting in probably even more errors.

As 3 doc team contributors have voted -1, I'm going to close this PR. This doesn't mean we don't like the effort you put in trying to make the docs better (we love it!), I hope to see you back with a PR that we can merge!

If you still feel like it's a better idea to add the PHP start tag, feel free to comment after closure. There always is a reopen button :)

**Comment by PhoneixS** [comment]
You have convinced me. What about adding a note about it?

**Pull request closed without merging**
