### PR TITLE
Update serverVersion for MariaDB

### PR DESCRIPTION
**Pull request by louismariegaborit**

### CODE REVIEW

**Comment by MrYamous** [comment]
Seems related to #19138 

If we're sure this change happened with DBAL 3.7, i think we should update the 4.X mention in [Doctrine Configuration Reference](https://symfony.com/doc/current/reference/configuration/doctrine.html#doctrine-dbal-configuration) page too

**Comment by javiereguiluz** [comment]
I think @MrYamous comment is important. Also, I can't find any reference to this change id DBAL 3.7 release notes: https://github.com/doctrine/dbal/releases/tag/3.7.0

@louismariegaborit can you please link to the specific commit or release notes that mention this change? Thanks!

**Comment by MrYamous** [comment]
IIUC [this is the relevant PR](https://github.com/doctrine/dbal/pull/5844) in doctrine/dbal 3.6

This seems to be confirmed by the discussion in #18395

**Review by OskarStark — APPROVED** [review]

**Comment by OskarStark** [comment]
Thank you Louis-Marie.

**Pull request merged**
