### PR TITLE
Fix new instance of a class name

### PR DESCRIPTION
**Pull request by peaceant**
Fix for #11824

### CODE REVIEW

**Comment by OskarStark** [comment]
cc @Nyhoim, but I think this fix is correct

**Review by Nyholm — APPROVED** [review]
Thank you for the ping. 

Yes. That is correct. Thank you for improving the docs!

**Review by OskarStark — APPROVED** [review]

**Comment by javiereguiluz** [comment]
@peaceant thanks for this fix (we merged it in 3.4 branch) and congrats on your first Symfony Docs contribution!

**Comment by Nyholm** [comment]
Wohoo! =)

**Comment by Art4** [comment]
@javiereguiluz Why did you changed the merging branch from `4.3` to `3.4`? 

There is no `Psr16Adapter` in 3.4, 4.0, 4.1 and 4.2. It was introduced in 4.3, see https://github.com/symfony/symfony/pull/29236

**Pull request merged**
