### PR TITLE
[Encore] fix typo fronts instead of fonts

### PR DESCRIPTION
**Pull request by nclsHart**

### CODE REVIEW

**Review by OskarStark — APPROVED** [review]

**Comment by OskarStark** [comment]
Thank you Nicolas.

**Comment by OskarStark** [comment]
I fixed the length of the underline in https://github.com/symfony/symfony-docs/commit/77744242d2ac155c265ad2bc785c31adfb5819cc

**Comment by nclsHart** [comment]
Oops, thank you for correcting my mistake.

**Comment by OskarStark** [comment]
No problem, thank you for your time to make this contribution 👍

**Pull request merged**
