### PR TITLE
Remove reference to profiler lifetime property that was removed in 3.x

### LINKED ISSUE #6889: Profiler storage lifetime
According to [3.0 documentation](http://symfony.com/doc/3.0/reference/configuration/framework.html#lifetime), `profiler` configuration can specify `lifetime`
However, in [code for 3.0.9](https://github.com/symfony/framework-bundle/blob/v3.0.9/DependencyInjection/Configuration.php#L194) I see no such node.

Thus, attempt to use it in my application triggers `Unrecognized option "lifetime" under "framework.profiler"`

Either documnetation or ode should be updated.

PS. Did not check this, but seems like `3.1.x` should be affected as well

### PR DESCRIPTION
**Pull request by jameshalsall**
Fixes #6889

### CODE REVIEW

**Comment by stof** [comment]
``username`` and ``password`` are gone as well

**Comment by wouterj** [comment]
👍 Thanks for updating these! We should also create another PR to add a `.. caution::` box that this options are deprecated and will be removed in Symfony 3.

status: reviewed

**Comment by jameshalsall** [comment]
I'll create another PR for the caution boxes

**Comment by wouterj** [comment]
Thanks! This one is now merged as well.

**Pull request closed without merging**
