### PR TITLE
Remove not existing response constant

### PR DESCRIPTION
**Pull request by amansilla**
| Q | A |
| --- | --- |
| Doc fix? | yes |
| New docs? | no |
| Applies to | 2.3 |
| Fixed tickets | #5770 |

### CODE REVIEW

**Comment by javiereguiluz** [comment]
:+1: thanks for reporting and fixing this issue.

**Comment by xabbuh** [comment]
:+1:

**Comment by stof** [comment]
this should be reverted when merging in newer branches though

**Comment by xabbuh** [comment]
Thank you @amansilla for this nice catch and the perfect pull request. I spotted another use of a non-existing constant and removed it in 63f44e38bd82b497c64e969a5bd01c338a9d8288.

These changes have been reverted in the `2.7` branch after merging up in 98967bf6ab219f7c9e63d8fc408d245dd3d95ff9 and a6cbbb2644bce2827e4907692d6eb1e2bc5ce14b.

**Pull request merged**
