### PR TITLE
Updated the release process image

### PR DESCRIPTION
**Pull request by javiereguiluz**
In #5471 we tried to update the image of this page: http://symfony.com/doc/current/contributing/community/releases.html

It's clear that I made some mistake with the image path, because the old image is still displayed. This is a second attempt at updating that image.

### CODE REVIEW

**Comment by WouterJ** [comment]
:+1:

**Comment by dupuchba** [comment]
@javiereguiluz what is the tool you use to create this img ?

**Comment by javiereguiluz** [comment]
@dupuchba Apple Keynote

**Comment by dupuchba** [comment]
ok lol. Thx

**Comment by xabbuh** [comment]
:+1: Let's see if merging it has any effect.

**Comment by xabbuh** [comment]
Looks great now: http://symfony.com/doc/current/contributing/community/releases.html#schedule

**Pull request merged**
