### PR TITLE
[Fix] add/remove fields is possible on FormEvents::SUBMIT

### PR DESCRIPTION
**Pull request by B-Galati**
| Q | A |
| --- | --- |
| Doc fix? | yes |
| New docs? | no |
| Applies to | tested on 2.6.9, need more tests I think |
| Fixed tickets | no |

### CODE REVIEW

**Comment by xabbuh** [comment]
@B-Galati Can you show the code that you used to test this?

**Comment by B-Galati** [comment]
@xabbuh Of course ! This example has been tested with LTS version 2.7.5. Not a very good usecase because but the tag attribute would never be set.. Perhaps it's a bug in symfony and doc should not be changed.. 

```php
class ArticleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', 'text')
            ->add('submit', 'submit')
            ->addEventListener(FormEvents::SUBMIT, function (FormEvent $event) {
                $form = $event->getForm();

                $form->add('tag', 'choice', [
                    'choices' => [
                        'music' => 'Music',
                        'foo' => 'Foo',
                        'bar' => 'Bar',
                    ],
                    'placeholder' => '--',
                ]);
            })

        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
           'data_class' => 'AppBundle\Entity\Article',
           'allow_extra_fields' => true
        ]);
    }

    public function getName()
    {
        return 'article';
    }
}
```

**Comment by xabbuh** [comment]
> Not a very good usecase because but the tag attribute would never be set..

What do you mean with that?

**Comment by B-Galati** [comment]
@xabbuh I mean the field will be added in the view, but the value of the added field would never be set in the entity

**Comment by xabbuh** [comment]
That because the data mapping has been taking place and why you cannot effectively add new form types in this event. Do you think it is something that should be reworded to make that more clear?

**Comment by B-Galati** [comment]
@xabbuh I think the best solution would be to have the same kind of error `POST_SUBMIT` event thrown.

Example with `POST_SUBMIT` event we have : `throw new AlreadySubmittedException('You cannot add children to a submitted form');`

What do you think ?

**Comment by B-Galati** [comment]
@xabbuh So what is the best solution for you ? Reword the doc or throw an exception ?

**Comment by xabbuh** [comment]
@B-Galati Sorry, I missed your answer. I guess throwing an exception would be better user experience, but probably there was a good reason not do that (maybe @webmozart can help us with some insight).

**Comment by B-Galati** [comment]
@xabbuh You welcome. I am also sorry, I was thinking something went wrong with this PR. I hope @webmozart could clarify the situation :smiley:

**Pull request closed without merging**
