### PR TITLE
Added filename references to examples

### PR DESCRIPTION
**Pull request by raitocz**

### CODE REVIEW

**Comment by xabbuh** [comment]
It's true that this is the standard location of the files when using the Symfony Standard Edition. However, this article also applies to the component being used standalone. So I have no clear opinion if we want to merge this.

**Comment by javiereguiluz** [comment]
@xabbuh we have this recurring doubt about using the standard file locations and examples (services.yml, routing.yml, AppBundle, etc.) in the components section. My opinion is: if you are advanced enough to use the Symfony Components without the Symfony Framework, you should be smart enough to figure out that you must update the suggested file paths accordingly.

I don't know if you agree with the above, but these past weeks I've used the documentation of other technologies and it's infinitely frustrating to read docs that tell you to copy some code but they don't tell you where. They (wrongly) assume that all readers know where to put things and that's why they never show you the file paths of the code samples. 😡

**Comment by RaitoCZ** [comment]
@javiereguiluz I agree on that. This was exactly my case on this, so I wanted to help anyone else having same problem. I know that doc about routes might reference to routing configuration files but I was not sure and I had to just blindly try it, which was my first experience of this kind in otherwise well written docs, everywhere else using this helpful default config file names comments.

**Comment by xabbuh** [comment]
Sounds convincing to me. 👍 then

Status: Reviewed

**Comment by xabbuh** [comment]
Thank you @RaitoCZ.

**Pull request closed without merging**
