### PR TITLE
Improve functional test workflow example

### PR DESCRIPTION
**Pull request by JeroenDeDauw**
The example used to be Arrange Act Assert Act Assert, rather than http://wiki.c2.com/?ArrangeActAssert

### CODE REVIEW

**Comment by javiereguiluz** [comment]
@JeroenDeDauw thanks for proposing this change to improve Symfony Docs. However, the link you shared (http://wiki.c2.com/?ArrangeActAssert) is for unit tests and this doc is for functional tests, so I'm not sure about the proposed change.

**Comment by JeroenDeDauw** [comment]
Oh, I did not see this particular article is about unit tests specifically. The AAA pattern does not just apply to unit tests. The benefits are just the same for unit tests, integration tests and edge-to-edge tests like the ones this section is about.

**Comment by javiereguiluz** [comment]
I'm afraid we're going to close this without merging. I know it's sad to do that ... but the mentioned workflow is the one used throughout the docs and it's very popular among Symfony developers. I hope you understand it. Thanks!

**Comment by JeroenDeDauw** [comment]
If an anti-pattern is present through the documentation then it is not surprising it will be used by many developers. Not sure how the wide usage of an anti-pattern is a reason for recommending it in the documentation. I doing so is rather harmful, which is why I created this PR. I hope you reconsider.

**Comment by Ocramius** [comment]
This should likely be re-considered, as the AAA approach is indeed something to strive for in test automation, while multiple actions lead to quite messy test scenarios (both to be read and to be debugged). This applies to any level of testing, as it keeps pre-conditions, mutations and post-conditions atomic.

**Comment by javiereguiluz** [comment]
@JeroenDeDauw thanks for the details! I understand you now. I thought you wanted to remove the *"Click on a link or submit a form"* step ... but that's not true. You want to remove the first *"Test the response"* to not make too many things in the same test. I fully agree, so I have tweaked a bit the original pull request. Thanks!

**Pull request closed without merging**
