### PR TITLE
[Config] Update definition.rst

### PR DESCRIPTION
**Pull request by helmis123**

### CODE REVIEW

**Review by helmis123 — COMMENTED** [review]
Selecting the second child in the tree

**Comment by javiereguiluz** [comment]
@helmis123 thanks a lot for this contribution!

I was trying to merge your Pull Request, but the tool we use to do that told me that I can't push to your contribution. This is needed for the tool to squash the two commits into one automatically.

Apparently, you can fix that by checking the "Allow edits from maintainers" option in the GitHub interface:



If you can't see that option or if it doesn't work, please tell me. Thanks!

**Comment by helmis123** [comment]
Thanks @javiereguiluz . Sorry i cant see this option too. I can close this pull-request and open another with a single commit if that fixes the problem.

**Comment by wouterj** [comment]
Hi! Seems like your branch somehow got disconnected from this PR. I've fetched these changes locally, squashed and rebased them and created a new PR: #16393 . The commit is still yours, so you still get full credits for these nice bug fixing changes. 

Thanks for the PR and welcome tp the list of documention contributors :)

**Pull request closed without merging**
