### PR TITLE
Updates to cookbook

### PR DESCRIPTION
**Pull request by carlcasbolt**
As a result of using the documentation to build something recently I wanted
to update some of the content to reflect modern code standards.
- example code update, doc blocks added, and array() syntax updated to []

### CODE REVIEW

**Comment by javiereguiluz** [comment]
@carlcasbolt thanks for this contribution!

Sadly these changes could be rejected:

1. In the past it was decided to keep using `array()` instead of `[]` to match the style used by Symfony for its code.
2. Adding the PHPdoc information could be interesting in some cases ... but generally we try to avoid that because it means to duplicate the same information that can be found in the code and it's very hard to maintain updated.

So, let's wait and see what Doc Maintainers decide about this proposal before doing any further changes. Thanks!

**Comment by carlcasbolt** [comment]
Hi Javier, thanks for the feedback, I can understand on the `array()` vs `[]` as the preference for them seems to differ from who I speak to these days. I used to be firmly on the `array()` camp a year ago, but from using more and more PHP7 I've come to like the short hand version.

If it's approved then I'll continue to change the other rst files, if it's rejected then that's OK, I'm sure I can contribute to the docs in other ways later on.

**Comment by carlcasbolt** [comment]
I'll close this in light of the new documentation structure.

**Comment by javiereguiluz** [comment]
@carlcasbolt one of the main goals of the new docs is to keep moving explanations from text to code blocks. That's why, even if we generally avoid putting PHPdoc contents, sometimes it may be a good idea to do that to simplify explanations. In any case, I'd recommend you to open an issue with your proposal instead of making the pull request. Thanks!

**Pull request closed without merging**
