### PR TITLE
Fixed broken links for nginx & FastCgiExternalServer

### PR DESCRIPTION
**Pull request by finchmeister**

### CODE REVIEW

**Review by HeahDude — APPROVED** [review]
Awesome! Thanks!

**Review by xabbuh — APPROVED** [review]

**Review by javiereguiluz — COMMENTED** [review]
Is this a duplicate of #7088 ?

**Comment by HeahDude** [comment]
@javiereguiluz it seems so but this one fixes both broken links, maybe we should close the other?

**Comment by javiereguiluz** [comment]
I've closed the other one ... but please let's merge this one soon. Thanks!

**Comment by xabbuh** [comment]
Thank you @finchmeister.

**Pull request closed without merging**
