### PR TITLE
[Dotenv] Add `SYMFONY_DOTENV_PATH`

### LINKED ISSUE #19366: [Dotenv] Add `SYMFONY_DOTENV_PATH`, consumed by `debug:dotenv` for cust…
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#52638
| PR author(s) | @GromNaN
| Merged in    | 7.1

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 7.1 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

### PR DESCRIPTION
**Pull request by alexandre-daubois**
Fix #19366

### CODE REVIEW

**Review by OskarStark — COMMENTED** [review]
Env var -> environment variable

**Comment by alexandre-daubois** [comment]
Updated 👍

**Comment by javiereguiluz** [comment]
Alex, thanks a lot for documenting this new feature so fast.

While merging I did some very minor changes ((https://github.com/symfony/symfony-docs/commit/e926d7cec47260fc30d8edb5d9fd659c43810b58)) ... but I also promoted the mention about where to define this new env var to a `caution` because I think this is important to avoid readers frustration (e.g. if they define this env var in the default `.env` file thinking that Symfony will read that value and load the custom file).

**Comment by alexandre-daubois** [comment]
Thanks Javier!

**Comment by GromNaN** [comment]
Hello and sorry, this feature has been misinterpreted. The variable can't be set before calling `DotEnv`. It's only an internal variable, like `SYMFONY_DOTENV_VARS`, that is set by the `DotEnv` class when a file is loaded.
You can document how to change the path to the `.env` file:

> The custom path can be set in many ways:
> - Doing a call to `(new Dotenv())->bootEnv(dirname(__DIR__).'my/custom/path/to/.env');`
> - In composer.json: `"extra": { "runtime": { "dotenv_path": "my/custom/path/to/.env" }`
> - With the env var: `$_SERVER['APP_RUNTIME_OPTIONS'] = ['dotenv_path' => 'my/custom/path/to/.env'];`

**Comment by alexandre-daubois** [comment]
I'll send another PR to fix this, thanks for the explanation Jérôme!

**Comment by nicolas-grekas** [comment]
I'm sorry but this description is wrong. This var is not about changing the location of the dot env files. It's about exposing where the dotenv files are so that the apps itself can know about it.
/cc @GromNaN

**Pull request merged**
