### PR TITLE
[Form] Add PHP Attributes example to forms

### PR DESCRIPTION
**Pull request by wkania**

### CODE REVIEW

**Comment by OskarStark** [comment]
Please check the CI, thanks

**Comment by wkania** [comment]
@OskarStark Look at CI error, it's related [to](https://github.com/symfony/symfony-docs/pull/15002)
From what I understand, not my Pull request introduced this error.

**Comment by OskarStark** [comment]
Indeed, can you please rebase?

**Comment by wkania** [comment]
Unlucky PR. Another [error](https://github.com/symfony/symfony-docs/pull/15005) @OskarStark .

**Review by OskarStark — APPROVED** [review]

**Review by xabbuh — APPROVED** [review]

**Comment by javiereguiluz** [comment]
And another nice PR! Thanks a lot @wkania!

**Pull request merged**
