### PR TITLE
Fixes for 2.3 branch

### PR DESCRIPTION
**Pull request by ifdattic**
| Q | A |
| --- | --- |
| Doc fix? | yes |
| New docs? | no |
| Applies to | 2.3 |
| Fixed tickets |  |

### CODE REVIEW

**Comment by ifdattic** [comment]
On components/console/introduction.rst line 471 isn't it bad that original `$input` variable is replaced?

**Comment by WouterJ** [comment]
> On components/console/introduction.rst line 471 isn't it bad that original $input variable is replaced?

I'm +1 for using another variable. (`$innerInput`?)

**Comment by ifdattic** [comment]
In one of my projects I'm using `$commandInput`

**Comment by weaverryan** [comment]
And +1 for changing the variable name!

**Pull request merged**
