### PR TITLE
Add the possibility to prefix URLs and routes name

### PR DESCRIPTION
**Pull request by ismail1432**
I saw this issue https://github.com/symfony/symfony-docs/issues/8358 and I want to solve it  but I am not sure if it's the good place to add this information 😀

### CODE REVIEW

**Comment by javiereguiluz** [comment]
@ismail1432 I like this. Thanks for contributing! However, I'd like to propose to change the location of this change. The `routing.rst` file is mainly for newcomers and this feature is mostly for advanced users and edge cases. I propose to do the following:

1. Remove all the changes from `routing.rst`.
2. Edit the `routing/external_resources.rst` file and add this example in the configuration block of the `Prefixing Imported Routes` section. We show YAML, XML and PHP ... we need to add a new config format called `.. code-block:: php-annotations` inside the existing `.. configuration-block::`. You just need to update the example contents to match the existing config example.

If you need any help with this, please tell me. Thanks!

**Comment by ismail1432** [comment]
Ok I'll do that 
Thanks

**Comment by javiereguiluz** [comment]
Please don't make any change yet! I think I'm messing things 😅 

There are two features (URL prefix, route name prefix) and two different scenarios (config files, @Route annotation).

In the past we had: URL prefix + config files or @Route ... in 3.4 we added route name prefix + @Route and in 4.1 we added route name prefix + config files. So, the changes are more complex than I imagined. We'd need to:

1. In 2.7 branch, update `routing/external_resources.rst` and add an example of PHP annotations for the existing example. And rename the section from `Prefixing Imported Routes` to `Prefixing the URLs of Imported Routes`
2. In 3.4 branch, update `routing/external_resources.rst` and add a new section called `Prefixing the Names of Imported Routes` and add only the example of PHP annotations (according to https://symfony.com/blog/new-in-symfony-3-4-prefix-all-controller-route-names).
3. In 4.1 branch, update `routing/external_resources.rst` and in the section added above (`Prefixing the Names of Imported Routes`) add the example of the config files (according to https://symfony.com/blog/new-in-symfony-4-1-prefix-imported-route-names).

So, in this PR you can take care of 2. and we'll finish 1. and 3. in separate PRs. Thank you and I'm sorry for all the trouble.

**Comment by ismail1432** [comment]
Ok, thanks for clarification.
I'll do the step 2
Have a nice day

**Comment by ismail1432** [comment]
Hi @javiereguiluz I create a new  [PR](https://github.com/symfony/symfony-docs/pull/9186) https://github.com/symfony/symfony-docs/pull/9186 for step 2

**Comment by javiereguiluz** [comment]
Closing as fixed because the three issues are now fixed and merged:

1) #9241
2) #9186
3) #9242

Thanks!

**Pull request closed without merging**
