### PR TITLE
[3.0] Removed 2.x versionadded directives

### PR DESCRIPTION
**Pull request by wouterj**

### CODE REVIEW

**Comment by WouterJ** [comment]
To explain: I think we should start with a clean docs in 3.0, only adding changes of 3.0.

**Comment by javiereguiluz** [comment]
@WouterJ I agree 100% with you! This is a great idea!

**Comment by stof** [comment]
:+1:

**Comment by xabbuh** [comment]
:+1: We just need to be aware do this again when new features are documented on the `2.x` branches (we have pending pull requests for `2.6` and there will very likely new features in `2.7`).

**Comment by fabpot** [comment]
This is indeed a good idea, but I think that everytime we remove a versionadded directive, we also should remove the old way. If you merge this PR as is, it will be much more difficult to this afterwards.

If you take for instance the `reference/twig_reference.rst` file, you removed the following directive:

```
.. versionadded:: 2.6
     The ``app.security`` global is deprecated as of 2.6. The user is already available
     as ``app.user`` and ``is_granted()`` is registered as function.
```

It's very clear that all references to `app.security` must be removed from the docs or replaced by the better alternatives. But without this directives, it's much harder to know what is obsolete and what is not. In this specific case, it's quite simple as it's about removing the docs for `app.security`, but it can be more subtle elsewhere.

**Comment by WouterJ** [comment]
That a great point I didn't think about. If I'm correct, we have always removed old behaviour, but I'll check it again and open other PRs to fix them. Until that's done, I label this as on hold.

**Comment by xabbuh** [comment]
@WouterJ Yes, usually we did. Last weekend I checked the pull request on the code repository that removed deprecated features in the 3.0 branch and we already covered most of them. There were only a few things left and we now have pull requests for them.

**Comment by WouterJ** [comment]
Closing in favor of https://github.com/symfony/symfony-docs/pull/5585

**Pull request closed without merging**
