### PR TITLE
remove space before self closing xml tag

### PR DESCRIPTION
**Pull request by OskarStark**
to be consistent throughout the docs

### CODE REVIEW

**Comment by HeahDude** [comment]
I am not sure about that one, because I think we need no space only for multilined opening tags:
```xml
<tag name="xx"
    class="xxx">
...
```
Versus
```xml
<tag name="xx" class="xxx" />
```

**Comment by OskarStark** [comment]
Hey @HeahDude 

Sorry I don't really get what you mean. This change will only bring consistency throughout the docs, that all self closing (no matter if they are written multiline or not) xml tags look like `/>` instead of ` />` (with a space).

After that one we can enforce it by tool, have less merge conflicts, better diffs and we are less error prone by humans (lets call it an error if someone will write ` />` in the future 😄 ).

I already talked to @weaverryan @javiereguiluz and @xabbuh before I created this PR.

But maybe I missunderstand your comment 😄 🍺

**Comment by wouterj** [comment]
Thanks Oskar! I fully agree with these changes, the space was only added to not confuse the HTML parser in xHTML documents, we should not use it in XML.

Note that I have been a very lazy merger. I've not bothered looking at the 50+ merge conflicts and instead ran `git checkout --ours .`. So all merge conflicts now are solved using the 4.2 version, instead of the modified 3.4 version of this PR. However, I assume you use a tool to create this diff, so you should be able to redo all those changes on the 4.2 branch easily.

**Comment by OskarStark** [comment]
> so you should be able to redo all those changes on the 4.2 branch easily.

sure thing, I will check the `4.2` branch 👍

**Pull request merged**
