### PR TITLE
Fix RST

### PR DESCRIPTION
**Pull request by kenjis**
See http://symfony.com/doc/current/create_framework/routing.html

The line `* Route names are used for template names;` is code.

### CODE REVIEW

**Comment by javiereguiluz** [comment]
:+1: that's a good catch! Thanks.

**Comment by xabbuh** [comment]
Good catch, thanks @kenjis.

**Comment by kenjis** [comment]
I'm sorry I should have sent this PR to version `2.3`.

We need fix:
http://symfony.com/doc/2.3/create_framework/routing.html
http://symfony.com/doc/2.6/create_framework/routing.html

What should I do?

**Comment by xabbuh** [comment]
@kenjis Thank you for noticing. I actually missed that when I merged your PR. I now cherry picked your commit on the older branches. Everything should be fine now.

**Pull request merged**
