### PR TITLE
[DependencyInjection][Improve] Constant YAML with expression language

### PR DESCRIPTION
**Pull request by 20uf**
Hi here,

Ï notice two things about this documentation.
http://symfony.com/doc/current/service_container/parameters.html#constants-as-parameters

- The first is that it is possible to retrieve a constant in a YAML with language expression since version 2.4 and that this solution is not indicated.
- The second is that since version 3.2 there is a new way to do it, see http://symfony.com/blog/new-in-symfony-3-2-php-constants-in-yaml-files

@javiereguiluz Is it an oversight or is there a reason that is not specified ?
Can I add this documentation that you have indicated in your news ?

Regards,

### CODE REVIEW

**Comment by 20uf** [comment]
Hello @javiereguiluz @xabbuh ,

Concerning this PR, do we agree on the substance?

Regards,

**Comment by GuilhemN** [comment]
As there is already `!php/const` I don't think we should document this, it would only be misleading imo.

**Comment by xabbuh** [comment]
We could add a YAML code block to the configuration block, make use of the expression there, but add a caution below that you must have the ExpressionLanguage component installed. We should then also add a tip that this is supported natively by the YAML parser starting with 3.2 and then update the example after merging up to not make use of the expression anymore.

**Comment by javiereguiluz** [comment]
@xabbuh but we already document "PHP constants in YAML" in https://github.com/symfony/symfony-docs/commit/9635f0f51cac8183308d8e8149df27d84f4ba40c#diff-122786a4391045b1aa3edea4ab2e676f ... maybe we shouldn't care about that in this PR ... which by the way, should be merged in 2.7 instead of 3.2, right?

**Comment by xabbuh** [comment]
@javiereguiluz Yeah, I think this should be done for 2.7 and 2.8 where you couldn't use the native parser feature.

**Comment by 20uf** [comment]
Hi,

Does NOT merge that into 3.x.
New PR is open  for 2.7 & 2.8.

Regards,

**Pull request closed without merging**
