### PR TITLE
Update form_customization.rst

### PR DESCRIPTION
**Pull request by vudaltsov**
| Q | A |
| --- | --- |
| Doc fix? | yes |
| New docs? | no |
| Applies to | >= 2.8 |
| Fixed tickets |  |

### CODE REVIEW

**Comment by xabbuh** [comment]
Thanks for your contribution @vudaltsov. Can you explain why you think we need to make this change? As you can see in the list right below the paragraph we actually have five form themes.

**Comment by vudaltsov** [comment]
@xabbuh yes, there are five themes in the list, but `four` is used in the sentence "Symfony comes with **four** built-in form themes". I suggest changing `four` to `five`

**Comment by xabbuh** [comment]
Of course you are right. :+1:

**Comment by vudaltsov** [comment]
@WouterJ, I am sorry, I should have suggested that for 2.8, right?
The foundation theme appered in 2.8 - that's why I wrote `>= 2.8`

**Comment by xabbuh** [comment]
@vudaltsov Don't worry, we were able to apply the changes to the `2.8` branch nonetheless. But that's why your PR is shown as closed instead of merged (you will still get the full credit for your contribution though).

**Pull request closed without merging**
