### PR TITLE
Add tip about bundles for console error logging

### PR DESCRIPTION
**Pull request by aschempp**
| Q | A |
| --- | --- |
| Doc fix? | no |
| New docs? | yes |
| Applies to | all |
| Fixed tickets | - |

I just stumbled over this use case and thought to myself _why not create a reusable bundle_. And then I went on and searched Packagist first…

### CODE REVIEW

**Comment by xabbuh** [comment]
👍 That's a good tip imo.

**Comment by WouterJ** [comment]
The problem here is that this bundle doesn't seem to be a very active one:

 * There is no `1.0` release yet
 * It only has 2 contributors
 * It has just 4 stars
 * Only one PR was opened

**Comment by javiereguiluz** [comment]
I agree with @WouterJ. And by the way, not having this basic feature looks like a Symfony bug to me.

**Comment by aschempp** [comment]
I can't tell why this is not standard behavior in the console. Maybe because a console user would see errors and not need them logged? Maybe logging should automatically be enabled if console is running in headless mode (`--no-interaction`)?

**Comment by WouterJ** [comment]
I'm going to close this pull request as 2 doc maintainers voted against it. However, this has nothing to do with you of course. I hope to see you back with more PRs in the future!

Btw, can you maybe create an issue in `symfony/symfony` to ask about adding this feature into Symfony core?

**Comment by aschempp** [comment]
no worries, I'm very much used to closing "stupid" PRs myself ;-)
I'll create a `symfony/symfony` issue as soon as I figured out a better way than using that bundle (like what I mentioned with `--no-interaction`).

**Pull request closed without merging**
