### PR TITLE
Corrected model folder inside bundle

### PR DESCRIPTION
**Pull request by sfdumi**
According to the best practices, I believe that Entity or Document folders should be used.

### CODE REVIEW

**Comment by xabbuh** [comment]
I would not make this change. The term model here refers to classes that are the model of your domain. That's doesn't tell you anything about whether they are mapped to a database using an object-relational mapper or using something like MongoDB (which would be the case when making this change). As a bundle author I even might not care at all if a concrete project maps model objects to MySQL, MongoDB, or a PHPCR backend (see FOSUserBundle for such an example).

**Comment by javiereguiluz** [comment]
I agree with @xabbuh but I understand @sfdumi concerns. We could:

* Leave `Model/` but improving a bit its description (if possible)
* Add `Entity/` for `Doctrine ORM entities`
* Add `Document/` for `Doctrine ODM documents`

**Comment by sfdumi** [comment]
Sounds reasonable. The fact that model could be used without Doctrine slipped me. Thank you, @xabbuh . :) 
I recommend adding Entity and Document, alongside Model, as @javiereguiluz uggested. Suggestion for `Models` description: Domain models, not mapped by Doctrine. Eg: models used in internal processing and not persisted, passed to external services etc.
How do you feel about this?

**Comment by WouterJ** [comment]
I'm actually not sure why we would document the specific location of domain models: Place them anywhere you think makes much sense would be the best option here imo.

Can't we simply remove the "Models" row and add `Entity/` and `Document/` as proposed by @javiereguiluz?

If you agree, can you maybe update this PR, @sfdumi? I know this PR is stalled for a long time. If you don't have the time to work on it anymore, just leave a comment and we'll finish this.

**Comment by xabbuh** [comment]
I think I agree with @WouterJ. For your own model classes that are not coupled to a specific backend, there are no rules where to store them. Only the location of Doctrine entities and document is important if you do not want to configure all mapping information explicitly.

**Comment by javiereguiluz** [comment]
Closing it in favor of #7156 to make the changes requested by doc maintainers. @sfdumi I'm sorry but I couldn't reuse your original commits because the doc structure changed completely since you created this PR.

**Pull request closed without merging**
