### PR TITLE
Update http-foundation.rst

### PR DESCRIPTION
**Pull request by jezemery**
Just fixed a small grammatical error

### CODE REVIEW

**Comment by javiereguiluz** [comment]
@jezemery thanks for this fix, congrats on your first contribution and welcome to the big family of Symfony Contributors!

Once this change is merged, if you have a [SensioLabs Connect](https://connect.sensiolabs.com/) profile with the same email as your GitHub account, you'll receive the cool [Symfony Doc Contributor badge](https://connect.sensiolabs.com/badge/36/symfony-documentation-contributor).

**Comment by xabbuh** [comment]
:+1: nice one @jezemery 

@javiereguiluz Was that a +1 from you?

**Comment by jezemery** [comment]
Thanks guys. I didn't realise there were contribution docs online before I did this so I think the format is off. Sorry!

**Comment by WouterJ** [comment]
No worries, Jeremy. This PR is very easy to merge and probably didn't take long to create, and that's the most important bit of contributing. I've now patched it into the 2.3 branch (which is the lowest version that we still maintain) and will merge it up to the master version from there (this is why the PR is shown as closed instead of merged). Thanks!

**Pull request closed without merging**
