### PR TITLE
[Notifier] [SmsBiuras] add docs

### PR DESCRIPTION
**Pull request by StaffNowa**

### CODE REVIEW

**Comment by OskarStark** [comment]
Can you please rebase? Thanks

**Review by OskarStark — APPROVED** [review]

**Comment by StaffNowa** [comment]
@OskarStark sure, easy :)

**Review by OskarStark — APPROVED** [review]

**Comment by OskarStark** [comment]
It took time, but here we go, this is in now. Thank you very much Vasilij.

**Comment by javiereguiluz** [comment]
Thanks for the contribution and the merge. In https://github.com/symfony/symfony-docs/commit/eb3accd083240339e36f2574291e678036b8acb2 we've added `SmsBiuras` to the `versionadded:: 5.3` directive.

**Pull request merged**
