### PR TITLE
[Cookbook][Bundles] clarify bundle installation instructions

### PR DESCRIPTION
**Pull request by xabbuh**
| Q | A |
| --- | --- |
| Doc fix? | no |
| New docs? | no |
| Applies to | all |
| Fixed tickets | https://github.com/symfony/MonologBundle/pull/124#discussion_r31257059 |

### CODE REVIEW

**Comment by WouterJ** [comment]
"clarify bundle deprecation instructions" -> "clarify bundle installation instructions" ? :smile:

**Comment by xabbuh** [comment]
ha ha, indeed :D

**Comment by WouterJ** [comment]
:+1:

**Comment by jakzal** [comment]
:+1:

**Comment by weaverryan** [comment]
Easy win :)

**Pull request merged**
