### PR TITLE
added Abdellatif as a core team member

### PR DESCRIPTION
**Pull request by fabpot**
| Q | A |
| --- | --- |
| Doc fix? | no |
| New docs? | no |
| Applies to | all |
| Fixed tickets | n/a |

### CODE REVIEW

**Comment by xabbuh** [comment]
Congratulations @aitboudad. :)

**Comment by javiereguiluz** [comment]
:+1: Abdellatif is doing a great job with the Translator component!

**Comment by weaverryan** [comment]
Happy to merge this. Welcome @aitboudad!

**Comment by aitboudad** [comment]
:+1: Thank you

**Comment by WouterJ** [comment]
Congratz @aitboudad !

**Pull request merged**
