### PR TITLE
[Workflow] PlantUML Dump documentation

### PR DESCRIPTION
**Pull request by Plopix**
Documentation related to https://github.com/symfony/symfony/pull/24705
This PR aims to explain that the PlantUML dump format is available.

Platform.sh URL: http://pr-9220-x7nzdnq-6qmocelev2lwe.eu.platform.sh/workflow/dumping-workflows.html

### CODE REVIEW

**Comment by Plopix** [comment]
Ok ready to review. cc @lyrixx @Nyholm

**Review by javiereguiluz — APPROVED** [review]
I like this. It's nicely explained. @Plopix thanks for implementing this feature and providing the docs too.

**Review by Nyholm — APPROVED** [review]
Awesome, thank you

**Review by lyrixx — APPROVED** [review]
Nice. Thanks you.

But **warning**, the target branch `4.0` is wrong. it should be `master`. Could you update it ? Thanks

**Comment by javiereguiluz** [comment]
@Plopix it's true that the branch should be master (as @lyrixx said) but don't worry, we can change the branch when merging your work. There's nothing left to do on your side. Thanks!

**Comment by javiereguiluz** [comment]
Thanks Sébastien.

**Pull request closed without merging**
