### PR TITLE
[Logger] Fixing code typo

### PR DESCRIPTION
**Pull request by ThomasLandauer**

### CODE REVIEW

**Comment by javiereguiluz** [comment]
Good catch, thanks Thomas.

**Comment by javiereguiluz** [comment]
@Nyholm just asking: since these changes were made automatically ... could this be a bug in the code that generates the config builders ... or is it just a typo? Thanks!

**Comment by Nyholm** [comment]
Are you referring to the big PR where I added this typo?

If so, they are not automated. I was writing all those PR by hand. That why this error snuck in.

**Comment by javiereguiluz** [comment]
Ah sorry! I thought there was some automation supervised manually. I'm sorry. And, again, a million thanks for your work updating all these docs 🙇

**Comment by Nyholm** [comment]
hehe. 
No worries. I wish it was automated =)

**Pull request merged**
