### PR TITLE
Fixed syntax error in 5.2

### PR DESCRIPTION
**Pull request by Nyholm**
Here are the syntax errors I found when running the parser (#15257) on 5.2.

### CODE REVIEW

**Comment by Nyholm** [comment]
I dont understand the build failure from Sphinx. I do change that file but 300 lines way from where Sphinx complain.

**Comment by OskarStark** [comment]
Is 5.2 stable maybe failing?

**Review by OskarStark — APPROVED** [review]

**Comment by Nyholm** [comment]
Yes. The failure is not related to this PR. 

Thank you

**Comment by javiereguiluz** [comment]
Nice fixes again! Thank you

**Pull request merged**
