### PR TITLE
Clean up

### PR DESCRIPTION
**Pull request by carusogabriel**
Following #8948, suggested by @xabbuh

### CODE REVIEW

**Review by xabbuh — APPROVED** [review]

**Comment by xabbuh** [comment]
Thank you @carusogabriel.

**Comment by xabbuh** [comment]
and in `master` :)

**Comment by carusogabriel** [comment]
@xabbuh @wouterj `master` does not have things to clean up. Thanks for guide me through the branches guys :100:

**Comment by xabbuh** [comment]
Thank you so much for all the work you did! That's really appreciated.

**Pull request closed without merging**
