### PR TITLE
Improve cookbook form unit testing

### PR DESCRIPTION
**Pull request by cn0047**
| Q | A |
| --- | --- |
| Doc fix? | yes |
| New docs? | no |
| Applies to | all |
| Fixed tickets |  |

I tweak this example from cookbook, and receive error:

```
Symfony\Component\Form\Exception\UnexpectedTypeException: Expected argument of type "string", "AppBundle\Form\CategoryType" given
```

and i just fix it like in this pr - and all become ok.

### CODE REVIEW

**Comment by javiereguiluz** [comment]
@cn007b thanks for sending this improvement.

Sadly, there was some error with the pull request and it contains some commits that don't belong to this fix. But don't worry, this happens some times (it has happened to me lots of times). Besides, it's possible to fix it without creating a new pull request.

To fix it, execute these commands:

```
$ git rebase -i HEAD~7

(now delete the lines that correspond to the commits that don't
belong to this fix ... all except one)

(save changes)

$ git push -f
```

The `-f` in the last command means "force" and it's needed when doing this rebase. If you need any help, just ask.

**Comment by cn007b** [comment]
First of all thanks for help!)
And i've done all commands...

**Comment by javiereguiluz** [comment]
@cn007b thanks! It seems that the error persist. Let's see if @WouterJ or @xabbuh can tell us the right solution for this issue.

**Comment by WouterJ** [comment]
Either try `git rebase --onto origin/master origin/2.3` (where 2.3 is the original base of this PR, change it to your base, probably 2.3, 2.7 or 2.8).

Or bruteforce things by doing this:
```
# create a temporary branch from the current branch of this PR
$ git checkout -b temp-6203

# delete the original branch of the PR
$ git branch -D improve_cookbook_form_unit_testing

# checkout master and create the PR branch from master
$ git checkout master
$ git checkout -b improve_cookbook_form_unit_testing

# cherry-pick the commit
$ git cherry-pick 63d751b

# remove the temp branch
$ git branch -D temp-6203

# push branch to github
$ git push -f
```

**Comment by xabbuh** [comment]
closing in favour of #6210

**Pull request closed without merging**
