### PR TITLE
Clean up

### PR DESCRIPTION
**Pull request by carusogabriel**
I've removed all white spaces and extra lines from our documentation :smile:

### CODE REVIEW

**Review by javiereguiluz — APPROVED** [review]
@carusogabriel this is really nice! If you tell GitHub review to ignore white space changes (https://github.com/symfony/symfony-docs/pull/8944/files?w=1) it's easy to verify that all changes are correct 👍 

I hope it's mergeable for our doc maintainers (sometimes these PRs with lots of minor changes everywhere are a nightmare to merge into upper branches).

**Comment by carusogabriel** [comment]
@javiereguiluz Oh, okay, I’ll look into that, thank you!

**Comment by carusogabriel** [comment]
@javiereguiluz Thanks so much for this tip. I'll use it in bigger PR that only trail whitespaces :smiley:

**Comment by wouterj** [comment]
Love it! I assume you have a script for this? Can you please run it on the 2.8 branch, now that I merged up your PR? Then we can work together and get all currently maintained branches fixed :)

**Comment by carusogabriel** [comment]
@wouterj Sure, will be my pleasure. Open that PR in a minute 👨‍💻

**Pull request closed without merging**
