### PR TITLE
Export workflow chart to SVG

### PR DESCRIPTION
**Pull request by analogic**
It should be encouraged to use SVG since SVG is better format suited for vector graphics and widely supported now.

### CODE REVIEW

**Review by javiereguiluz — APPROVED** [review]
I agree ... but let's ask to our workflow expert @lyrixx if he sees any drawback to this proposal. Thanks!

**Comment by lyrixx** [comment]
Good catch. But I would keep both format, png is easier to open I guess

**Comment by javiereguiluz** [comment]
What if we show both PNG and SVG the first time and then we use any format (e.g. SVG) in the rest of commands.

**Review by lyrixx — APPROVED** [review]

**Comment by javiereguiluz** [comment]
@analogic thanks for helping us improve the docs. We finally merged this on 3.4 (the oldest maintained branch where this change is applicable) and we'll merge it automatically to the other upper branches. Also, congrats on your first Symfony Docs contribution!

**Pull request closed without merging**
