### PR TITLE
Added setup instructions for composer for multi-PHP setup

### PR DESCRIPTION
**Pull request by pau1phi11ips**
Added setup instructions for composer if system has more than one version of PHP available.

### CODE REVIEW

**Review by javiereguiluz — COMMENTED** [review]
I'm 👎  about this change. Why? Because this use case looks very rare to me and the `setup.rst` article is extremely important for because it's the starting point for Symfony newcomers. This information would look "complicated".

Of course I could be wrong and this use case be more common than I think. So let's wait for more opinions.

**Comment by pau1phi11ips** [comment]
As a Symfony newcomer myself I spent about an hour yesterday trying to figure out how to get 3.2 installed because Composer was defaulting to the base PHP version on the OS which is 5.4 (hence installing 2.8). Maybe additional the Plesk specific example was a bit much but if it helps get people up and running quicker it can't hurt?

**Comment by HeahDude** [comment]
Maybe a simple note would be enough, saying that the command uses the default php process which can be explicit when running it (path to composer looks useless in this case there should not be different versions installed).

**Comment by xabbuh** [comment]
I think a detailed example would belong to the Composer documentation. We could add a small tip to the Symfony docs though (and possibly link it to the Composer documentation).

**Comment by javiereguiluz** [comment]
After thinking again about this, I'm afraid I must close it as "won't fix".

@pau1phi11ips your proposal is technically correct and I thank you for your contribution, but let me explain why I don't think this belongs to the Symfony docs.

Our resources are very limited and we want to reduce the things we document. When dealing with PHP, our premise was always that you have a working PHP installation in the `php` console command. The only differences that we may document are the ones imposed by the operating systems, because there are a lot of people using Windows, Linux and macOS and sometimes those differences are important.

But regarding your own PHP installation, we don't care and we never mention or explain anything about that. Maybe you compiled PHP yourself, or installed a prepackaged version, or you have more than one version installed (the case you want to document), or run it in a process executed in a Docker container, etc. That's why we can't explain all those use cases and that's why we simply assume that the reader of the docs has a working PHP installation and knows the binary to execute to run PHP.

I hope you understand this decision. Thanks!

**Pull request closed without merging**
