### PR TITLE
minor [#14292] UserProvider::supportsClass

### PR DESCRIPTION
**Pull request by CharlyPoppins**
https://github.com/symfony/maker-bundle/pull/532

### CODE REVIEW

**Comment by CharlyPoppins** [comment]
`Build documentation` failed do I need to change something ?

**Comment by javiereguiluz** [comment]
Charly, thanks for this contribution. The build error is unrelated to your changes (it was a temporary issue in another article).

While we wait to see if this feature is merged in Maker bundle, we'll need to update something in this pull request: 

`|| is_subclass_of($class, <?= $user_short_name ?>::class;` -> `|| is_subclass_of(User::class);`

You used the code that Maker runs to generate the code, but in the Symfony Docs we should display instead the result of executing that code.

**Comment by CharlyPoppins** [comment]
> You used the code that Maker runs to generate the code, but in the Symfony Docs we should display instead the result of executing that code.

Silly me...

I tought `<?= $user_short_name ?>` was something generated with/by `.rst ` files

**Comment by CharlyPoppins** [comment]
Hum, squashing made unwanted changes... I don't know how to handle this.

I created a new PR : https://github.com/symfony/symfony-docs/pull/14304

Which on of these both should be closed ?

**Comment by javiereguiluz** [comment]
No worries. By the way, there's no need to squash changes because the tool we use to merge PRs does that automatically for us. Closed in favor of #14304.

**Pull request closed without merging**
