### PR TITLE
[Serializer] use the `NormalizerAwareInterface` to prevent circular references

### PR DESCRIPTION
**Pull request by xabbuh**
see symfony/maker-bundle#1252

### CODE REVIEW

**Comment by derrabus** [comment]
This implementation would cause an infinite recursion because the serializer would inject itself as normalizer and dispatch the normalize call to our custom normalizer again.

**Comment by chalasr** [comment]
The infinite recursion can be avoided with this trick: https://symfonycasts.com/screencast/api-platform-security/normalizer-aware#avoiding-recursion-with-a-context-flan

**Comment by mtarld** [comment]
As written in the [API Platform documentation](https://api-platform.com/docs/core/serialization/#changing-the-serialization-context-on-a-per-item-basis), this way to do is actually working if adding a flag in the context.

**Comment by HeahDude** [comment]
I guess we can close here and open a new PR to document https://github.com/symfony/symfony/pull/46625.

**Comment by chalasr** [comment]
@HeahDude Not sure actually :) This example is what prevents us from enabling the serializer panel by default as it builds on an autowired concrete class instead of an interface. 

The alternatives I can think of:
- Use the NormalizerAwareInterface as currently proposed (with the suggested context flag trick to avoid recursion)
- Change the parameter type declaration from `ObjectNormalizer` to `NormalizerInterface` and add the config needed to make it gets the `serializer.normalizer.object` service injected

If we are not happy with both approaches, that probably means we need to work on adding a better way to give `ObjectNormalizer` capabilities to a userland normalizer (e.g. a trait or a more scoped interface)

**Review by mtarld — APPROVED** [review]

**Review by maxhelias — CHANGES_REQUESTED** [review]
> As written in the API Platform documentation, this way to do is actually working if adding a flag in the context.

So we need to add a mention like the API P doc to explain the flag in context.

**Comment by chalasr** [comment]
Thinking twice about this, I'd advocate for the explicit DI approach (second alternative in https://github.com/symfony/symfony-docs/pull/16826#issuecomment-1151587036)

**Comment by javiereguiluz** [comment]
What should we do with this PR? Merge, close or keep working on it? Thanks!

**Comment by mtarld** [comment]
I think it misses two things:
1. Add a flag in a context to prevent infinite recursions (here, the normalizer will call himself infinitely)
2. Maybe add an example to inject a specific implementation of a normalizer thanks to container configuration (here it'll call the chain normalizer)

At least one of these points should be done to prevent infinite recursion.
Either using a flag or injecting a specific implementation will solve that issue, but IMHO, both of these methods might be documented.

**Comment by xabbuh** [comment]
closing as I think this has been fixed in #19532

**Pull request closed without merging**
