### PR TITLE
Use DOCtor-RST 1.37.0

### PR DESCRIPTION
**Pull request by OskarStark**

### CODE REVIEW

**Comment by javiereguiluz** [comment]
Oskar thanks for updating this ... and thanks to you and the other contributors of the DOCtor-RST project.

**Comment by OskarStark** [comment]
Oh, this one shouldn't be merged I just wanted to see if everything is green again, but I think we have a bug in DOCtor, which I am currently fixing.

**Comment by OskarStark** [comment]
I will revert this one

**Comment by OskarStark** [comment]
> and thanks to you and the other contributors of the DOCtor-RST project.

You are welcome 🙏

**Pull request merged**
