### PR TITLE
[Routing] Add URI scheme enforcement annotation example

### PR DESCRIPTION
**Pull request by michaelperrin**

### CODE REVIEW

**Review by HeahDude — APPROVED** [review]

**Review by javiereguiluz — APPROVED** [review]

**Comment by michaelperrin** [comment]
I may change `HTTPS` to `https` to match the other format examples.

**Comment by HeahDude** [comment]
Indeed :)

**Comment by michaelperrin** [comment]
@HeahDude done :)

**Comment by xabbuh** [comment]
Thank you @michaelperrin.

**Pull request merged**
