### PR TITLE
Bumped symfony version number to 2.6 in flat php composer.json example

### PR DESCRIPTION
**Pull request by TSchuermans**
| Q | A |
| --- | --- |
| Doc fix? | yes |
| New docs? | no |
| Applies to | 2.6.* |
| Fixed tickets | / |

### CODE REVIEW

**Comment by stof** [comment]
I suggest using a semver constraint instead. This way, we won't need to update it all the time

**Comment by TSchuermans** [comment]
@stof something like ^2.0?

**Comment by WouterJ** [comment]
I'm against using a version constraint. We have decided to have versioned documentation. That implies that 2.3 documentation will really tell you about 2.3 and not about 2.6. When using `2.*` as a constraint, you'll install 2.6 with the 2.3 installation constructions. I think that'll introduce lots of confusion over time.

And yeah, there are more places where we need to update it each time. It isn't very nice, but we have to life with it. Clear and correct documentation is the most important part imo

**Comment by TSchuermans** [comment]
True, when using ^2.0 you would get the latest version even when you're looking at the documentation for 2.3. 
This will be confusing to a lot of people using the documentation.

**Comment by WouterJ** [comment]
Btw, :+1: for the current changes in this PR.

**Comment by TSchuermans** [comment]
@WouterJ Thx, this is my first contribution to SF.
Hoping to contribute a lot more in the future.

**Comment by WouterJ** [comment]
Congratz, your first contribution has just been merged into the documentation!

**Comment by javiereguiluz** [comment]
@TSchuermans thanks for your first contribution! In a few hours, you'll receive the [Symfony Documentation Contributor Badge](https://connect.sensiolabs.com/badge/36/symfony-documentation-contributor) in [your SensioLabsConnect profile](https://connect.sensiolabs.com/profile/tschuermans).

**Comment by TSchuermans** [comment]
@javiereguiluz sweet! I have not received a badge though :-(

**Comment by javiereguiluz** [comment]
@TSchuermans I've asked around and the problem is that the email that you used to register on SensioLabsConnect (which is `t...+sensiolabs@gmail.com`) doesn't match the email that you used to make this contribution (which is the email you used to register in GitHub: `t...@gmail.com`).

The solution is to add the first email as an additional email address of your SensioLabsConnect profile. You can do that very easily at https://connect.sensiolabs.com/#!email

**Comment by WouterJ** [comment]
maybe it's better to allow the `+...` suffix difference on e-mails, as both are the same

**Comment by xabbuh** [comment]
@WouterJ Afaik it depends on how the mail server is configured if `+` treated as the separator charactor for mail address extensions.

**Comment by TSchuermans** [comment]
@javiereguiluz ah right, makes sense. Added an extra email address.

**Pull request merged**
