### PR TITLE
Jquery datePicker syntax update

### PR DESCRIPTION
**Pull request by lwillems**
http://api.jqueryui.com/datepicker/#option-dateFormat

### CODE REVIEW

**Comment by weaverryan** [comment]
In the article, we mention bootstrap-date picker, not jQuery UI's date picker. So I think it's correct as is

**Comment by weaverryan** [comment]
But we should remove the "assuming you're using jQuery" part. Of course you are, as Bootstap requires this. I think this is the confusing part. We should also add an in-code comment in JS that mentions again this is code for the bootstrap-datepicker

**Comment by weaverryan** [comment]
@bart0356 can you make these changes? Thanks!

**Review by javiereguiluz — APPROVED** [review]
I've reverted the original fix and made the changes requested by Ryan. Thanks!

**Comment by xabbuh** [comment]
Thank you @bart0356.

**Pull request closed without merging**
