### PR TITLE
[Messenger] added example for limit consuming to specific queue / queues

### PR DESCRIPTION
**Pull request by dimadeush**

### CODE REVIEW

**Review by Nyholm — APPROVED** [review]
I like that we are explicit here. It is not obvious how to pass an array to `queues` input. This will save the users a lot of searching around the docs.

**Comment by javiereguiluz** [comment]
Dmitriy, thanks for improving the docs and congrats on your first Symfony Docs contribution 🎉 

Please note that while merging we tweaked this a bit to merge the two commands into a single `.. terminal` directive, which is something that we commonly do in Symfony Docs. See https://github.com/symfony/symfony-docs/commit/e16818e446ee53865d21b16f7a4fd8043fae7c0d

**Comment by Nyholm** [comment]
Wohoo. Awesome!

Thank you @javiereguiluz for merging and BIG THANK YOU @dimadeush for improving the docs after you found the solution to your issue.

**Comment by dimadeush** [comment]
Thank you too. It just for beginning and there is long way and ideas how and where I can help to Symfony community.

**Pull request merged**
