### PR TITLE
Use ::class whenever it's possible

### PR DESCRIPTION
**Pull request by javiereguiluz**

### CODE REVIEW

**Comment by wouterj** [comment]
👍 

A simple grep gives a lot more cases that we can fix: https://gist.github.com/wouterj/ff66784866817e0d6aedafeaa29ffa8a But that doesn't have to be done in this PR imo

status: reviewed

**Comment by xabbuh** [comment]
@javiereguiluz Do you want to update the other places too?

**Comment by javiereguiluz** [comment]
@xabbuh I agree with @wouterj and I prefer to do that in a separate PR. Thanks!

**Comment by xabbuh** [comment]
Thank you Javier.

**Pull request merged**
