### PR TITLE
Fix extra colon in custom_constraint block

### LINKED ISSUE #6839: Some block tags should not appear
[This chapter](https://symfony.com/doc/current/validation/custom_constraint.html#constraint-validators-with-dependencies) lets appear one `.. configuration-block::` tag that should not be displayed.

I didn't open a PR simply because I can't figure how to fix it, as I didn't find any problem in [the corresponding file](https://github.com/symfony/symfony-docs/blob/master/validation/custom_constraint.rst) (line 163).

I guess the issue has been introduced in the same time as the new doc, but not sure.
If I find another one, I'll reference it here.

### PR DESCRIPTION
**Pull request by chalasr**
Closes #6839

### CODE REVIEW

**Comment by chalasr** [comment]
@wouterj Thank you for the solution.

Unrelated but do you still maintain branches < 2.7, as they exist?

**Comment by xabbuh** [comment]
👍 

Status: Reviewed

@chalasr No, we only update the docs for Symfony versions that haven't reached end of maintenance yet.

**Comment by wouterj** [comment]
👍

**Comment by javiereguiluz** [comment]
I'm sorry ... but this looks like a duplicate of the earlier #6833.

**Comment by chalasr** [comment]
Sure, I didn' see it.

**Pull request closed without merging**
