### PR TITLE
Remove isSubmitted call

### PR DESCRIPTION
**Pull request by DanielSiepmann**
Streamline with http://symfony.com/doc/current/book/forms.html#handling-form-submissions
There is no need for `isSubmitted` as this is done inside `isValid`

### CODE REVIEW

**Comment by dosten** [comment]
But this is intended, because is considered a best practice. http://symfony.com/doc/current/best_practices/forms.html

> We recommend using $form->isSubmitted() in the if statement for clarity. This isn't technically needed, since isValid() first calls isSubmitted(). But without this, the flow doesn't read well as it looks like the form is always processed (even on the GET request).

**Comment by DanielSiepmann** [comment]
Okay ... but then this should be changed in the referenced documentation http://symfony.com/doc/current/book/forms.html#handling-form-submissions, shouldn't it?

**Comment by dosten** [comment]
Yes, you're right. If you can do it would be great!

**Comment by DanielSiepmann** [comment]
Done within 5972 I'll close this pull request.

**Comment by DanielSiepmann** [comment]
Following #5972 I've swapped the order of call.

**Comment by xabbuh** [comment]
:+1:

**Comment by WouterJ** [comment]
Great, thanks Daniel!

**Pull request closed without merging**
