### PR TITLE
"setup" is a noun or adjective, "set up" is the verb

### PR DESCRIPTION
**Pull request by carlos-granados**
Also, I don´t see any need for this to be capitalized

### CODE REVIEW

**Comment by carlos-granados** [comment]
I intended to merge this with branch 2.3, not sure what I did wrong

**Comment by javiereguiluz** [comment]
:+1: for the fixed typo.

Regarding the title case, Symfony uses a very strange title case variant which is mentioned here (http://symfony.com/doc/current/contributing/documentation/standards.html#english-language-standards). My guess is that this title:

```
How to set up before and after Filters
```

Should be spelled instead as:

```
How to Set Up Before and After Filters
```

**Comment by carlos-granados** [comment]
@javiereguiluz You are right about these weird english capitalization rules, changed to what you suggested

**Comment by xabbuh** [comment]
:+1:

**Comment by xabbuh** [comment]
Actually, aren't "before" and "after" closed class words and need to be lowercased?

**Comment by carlos-granados** [comment]
Maybe you are right... what about "up"? Probably it should not be uppercase either. 
OMG this is turning more complicated than what it sounded :-)

**Comment by xabbuh** [comment]
I am always confused about this rule too. :) Though I think "Up" should be uppercased as it is part of the verb.

**Comment by xabbuh** [comment]
@GuGuss Is there an issue with our service hook or is there some other thing going wrong with our platform.sh integration?

**Comment by carlos-granados** [comment]
I found these pages with rules for capitalization: 

http://www.grammarcheck.net/capitalization-in-titles-101/
http://web.archive.org/web/20130117225252/http://writersblock.ca/tips/monthtip/tipmar98.htm

According to them the capitalization is correct now

**Comment by GuGuss** [comment]
@xabbuh You're right this time ;) PRs aren't built anymore. I'll check what's happening.

**Comment by weaverryan** [comment]
Thanks Carlos! This works for me!

**Pull request closed without merging**
