### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by KatharinaSt**
Fixed "DoctrieMongoDBMappingsPass" to "DoctrineMongoDBMappingsPass"

### CODE REVIEW

**Review by javiereguiluz — APPROVED** [review]
👍  nice catch for a very tricky issue!

Status: reviewed

**Comment by KatharinaSt** [comment]
My pleasure. :-)

@javiereguiluz I noticed it afterwards: Is it true that I should have created my pull request on branch 2.7 (oldest maintained) rather than on 3.2?

**Comment by javiereguiluz** [comment]
**Note to mergers**: this must be merged in **2.7**

---

@KatharinaSt yes, you are right! Typos are fixed in *"the oldest branch that contains the error and it's still maintained"*. so this should go to 2.7 ... but we can change this while merging. Thanks!

**Comment by xabbuh** [comment]
Good catch, thanks @KatharinaSt.

**Pull request closed without merging**
