### PR TITLE
Remove ProgressHelper page

### PR DESCRIPTION
**Pull request by afurculita**
ProgressHelper is a feature from Symfony 2, removed in Symfony 3. So it can be removed from the docs from Symfony 3.* . This can be merged in 3.0 and after that merged with the other 3.* branches

### CODE REVIEW

**Comment by wouterj** [comment]
:+1: Agreed! Except that we no longer maintain the 3.0, 3.1 and 3.2 versions of the documention, so we should merge this into 3.3. We can easily switch that during the merge, so you won't have to do anything :)

status: reviewed

**Comment by afurculita** [comment]
@wouterj I know that 3.0 is no longer maintained, but the problem is that SensioLabs offers certification for Symfony 3.0 and when you study for it you need to use the documentation for 3.0. Thus I think 3.0 should still be maintained.

**Comment by wouterj** [comment]
If I understand correctly, SensioLabs offers Symfony 3 certificates. These are about Symfony 3.x, not about 3.0 specifically (some questions can be outdated though). If that's not the case, we should indeed rethink our support process.

(@javiereguiluz please confirm)

**Comment by javiereguiluz** [comment]
I'm going to ask internally about this and I'll come back to comment.

**Comment by hhamon** [comment]
Hi guys,

The certification is on Symfony **3.0** only!

**Comment by weaverryan** [comment]
Just merged #8402  :)

**Comment by xabbuh** [comment]
@weaverryan But then we should merge this one too, right?

**Comment by weaverryan** [comment]
Ah, thanks! I was thinking this was a duplicate. I just merged this into 3.3 as well.

**Pull request closed without merging**
