### PR TITLE
change app/check.php for 3.0

### PR DESCRIPTION
**Pull request by nanocom**

### CODE REVIEW

**Comment by OskarStark** [comment]
but the docs are for 2.8 and 3.0, so app is still available IMO

maybe adding a note for 3.0 stuff instead or explain the difference?

**Comment by xabbuh** [comment]
Makes sense to me to make this change for the `3.0` documentation.

**Comment by xabbuh** [comment]
:+1:

**Comment by WouterJ** [comment]
:+1: 

If you're using 2.8, then you should read the 2.8 docs and not 3.0/current.

**Comment by xabbuh** [comment]
Good catch, thanks @nanocom.

**Pull request merged**
