### PR TITLE
[Dotenv] Fix `SYMFONY_DOTENV_PATH` purpose

### PR DESCRIPTION
**Pull request by alexandre-daubois**
After https://github.com/symfony/symfony-docs/pull/19371#issuecomment-2139129136, sorry for the misunderstanding on this feature!

I guess https://symfony.com/blog/new-in-symfony-7-1-misc-improvements-part-2#custom-env-path will also need an update.

cc @nicolas-grekas

### CODE REVIEW

**Review by nicolas-grekas — APPROVED** [review]

**Review by alamirault — APPROVED** [review]

**Review by OskarStark — APPROVED** [review]

**Comment by OskarStark** [comment]
Thank you Alexandre.

**Comment by javiereguiluz** [comment]
Now I understand this feature even less 😐 

Nicolas' comment at https://github.com/symfony/symfony-docs/pull/19371#issuecomment-2139129136

> This var is not about changing the location of the dot env files. It's about exposing where the dotenv files are so that the apps itself can know about it.

But, how do you change the location of the `.env` files?

**Comment by alexandre-daubois** [comment]
You can change the location of `.env` files with the two solutions proposed in the "Storing Environment Variables In Other Files" section. And if you need to get, in your app, the `.env` files paths used by Symfony at runtime, then you can read the `SYMFONY_DOTENV_PATH` env var. Is it clearer to you?

**Comment by javiereguiluz** [comment]
Thanks Alex! It's clear now 👍  I've updated the blog post too.

**Pull request merged**
