### PR TITLE
Symfony Installer Instructions for Windows

### PR DESCRIPTION
**Pull request by robwent**
Related to issue #7961

Changes command to write symfony file with UTF8 encoding and adds
instructions to create symfony.bat file to use the command globally

### CODE REVIEW

**Review by javiereguiluz — APPROVED** [review]
Even if we add this to the docs, keep in mind that the installer is completely deprecated ... and all this will be removed in the Symfony 4 docs, which will use Composer to create Symfony projects with Flex. Thanks!

**Comment by robwent** [comment]
It may help people save a few hours wondering why it's not working as stated (as happened to me).

Symfony 4 is another thing altogether and isn't going to work on windows out of the box as there is no native 'make' command so flex can't work.

**Comment by javiereguiluz** [comment]
@robwent don't worry ... you don't need "make" to make Symfony 4 work. It's totally optional and for unimportant things.

**Comment by robwent** [comment]
@javiereguiluz that's great news. I was starting to worry after having a test.

**Comment by xabbuh** [comment]
Thank you @robwent.

**Pull request closed without merging**
