### PR TITLE
Wrap the table creation inside the class extending Command, so users …

### PR DESCRIPTION
**Pull request by harikt**
…know where the  comes. They can use it as standalone when needed.

This PR is with the changes mentioned in https://github.com/symfony/symfony-docs/pull/4812

### CODE REVIEW

**Comment by WouterJ** [comment]
:+1:

For your information, 2.6 is still maintained, so it's going to be merged in that branch. However, you don't have to worry about it as we have a nice tool that makes it really easy to patch PRs into other branches.

**Comment by harikt** [comment]
Hey thank you @WouterJ . So any further PR's should go to 2.6 ?

**Comment by xabbuh** [comment]
@harikt Actually that depends on the affected versions. But the general rule is to open a PR for the lowest affected version (higher versions will get the changes when branches are merged up). Currently, supported versions are 2.3, 2.6 and 2.7.

**Comment by xabbuh** [comment]
By the way: :+1: :)

**Comment by harikt** [comment]
@xabbuh , 

Is there a way to find the supported versions ? So people can understand easily to where the PR need to be initialized ?

Thank you.

**Comment by xabbuh** [comment]
@harikt You can have a look at http://symfony.com/roadmap or http://symfony.com/doc/current/contributing/community/releases.html.

**Comment by xabbuh** [comment]
Thank you @harikt.

**Pull request closed without merging**
