### PR TITLE
remove versionadded for unmaintained versions

### PR DESCRIPTION
**Pull request by xabbuh**
| Q | A |
| --- | --- |
| Doc fix? | yes |
| New docs? | no |
| Applies to | all |
| Fixed tickets |  |

### CODE REVIEW

**Comment by Ener-Getick** [comment]
Isn't it a problem that symfony 2.3 is still supported?

**Comment by xabbuh** [comment]
@Ener-Getick That's not a problem. In the 2.3 docs, these things were never included and they won't be.

**Comment by Ener-Getick** [comment]
Ah right then :+1:

**Comment by WouterJ** [comment]
:+1:

**Pull request merged**
