### PR TITLE
[Mercure] Invalid namespace and method name

### PR DESCRIPTION
**Pull request by zspine**

### CODE REVIEW

**Comment by OskarStark** [comment]
cc @chalasr and @dunglas are you able to verify this PR?

**Review by dunglas — APPROVED** [review]

**Comment by dunglas** [comment]
Good catch @zspine.
@OskarStark could you also merge https://github.com/symfony/symfony-docs/pull/15460 at the same time? It also contains some fixes and is ready.

**Review by OskarStark — APPROVED** [review]

**Comment by OskarStark** [comment]
In this case this should target `4.4` @dunglas ?

**Comment by dunglas** [comment]
yes indeed

**Comment by OskarStark** [comment]
Thanks M#3.

**Pull request merged**
