### PR TITLE
[Reference][HttpClient] Auth basic is a scalar type

### PR DESCRIPTION
**Pull request by gilles-g**
Auth basic is a scalar type

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
an array works too :)

**Comment by nicolas-grekas** [comment]
oh no, not using configuration!

**Review by nicolas-grekas — APPROVED** [review]

**Review by OskarStark — APPROVED** [review]

**Comment by javiereguiluz** [comment]
Are we 100% sure about this? It as a string at first but then was changed to an array, right?

**Comment by OskarStark** [comment]
> Are we 100% sure about this?

Yes, https://github.com/symfony/symfony/blob/4.4/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php#L1411

**Comment by nicolas-grekas** [comment]
It's pretty straigtforward to confirm:

**Comment by OskarStark** [comment]
Thank you @spike31 for taking care of this regression.

**Pull request merged**
