### PR TITLE
Prepare security.rst for Symfony 5.4

### PR DESCRIPTION
**Pull request by gnito-org**
I thought I'd make a first pass at modifying security.rst for 5.4. It's far from perfect, but I think it's a solid base to work from.

I tried to adapt my software to 5.4 using the existing security.rst and found it a frustrating process. Hence the effort to rewrite some sections.

### CODE REVIEW

**Comment by gnito-org** [comment]
Is there any Linux tool or app, or any other way, that can show an actual preview of the final page?

The preview function of PHPStorm's RestrcuturedText plugin is broken. 

ReText on Linux is useless for previewing because it freaks out about broken links.

**Comment by gnito-org** [comment]
I'm not sure how to fix the CI / Code Blocks errors because it does not tell me the line numbers where it found the errors.

**Comment by wouterj** [comment]
Hi @gnito-org. I'm really very sorry, but work on this has already started some time ago in https://github.com/symfony/symfony-docs/pull/15503 . We're rewriting all security docs as, like you said, they are a bit frustrating as a whole (not only because they are outdated, but also because the sections and scattered small guide articles aren't up to standard anymore). We hope to finish the work shortly.
I'll have a close look at your changes to see if I can include some of them in the rewrite, so your work isn't completely at a loss.

In the future, I recommend you first have a look at the issues/PRs to see if work has already started or, like I recommended in the GitHub discussions, ask a doc team member about it before starting such a big work.

**Comment by gnito-org** [comment]
@wouterj No problem. Time spent was an education fee, and I learned a lot.

**Pull request closed without merging**
