### PR TITLE
[Notifier] Add from in SmsMessage and support it in bridge transports

### PR DESCRIPTION
**Pull request by alamirault**
If PR [#45987](https://github.com/symfony/symfony/pull/45987) looks good. I will change docs

### CODE REVIEW

**Comment by OskarStark** [comment]
These changes look totally unrelated 🙄

**Comment by javiereguiluz** [comment]
The related code PR was merged: https://github.com/symfony/symfony/pull/45987 🎉 

@alamirault would you have time to finish this PR? If you can't fix the git issues with the unrelated commits, it's OK to delete this PR and create a new one. Thanks.

**Comment by alamirault** [comment]
I'm not sure where I have to do changes.

Is edit SmsMessage example is enough ? https://github.com/symfony/symfony-docs/blame/6.2/notifier/texters.rst#L22 (Like in PR description) ?

**Comment by alamirault** [comment]
@javiereguiluz I rebased and changed documentation

**Comment by wouterj** [comment]
Thanks @alamirault!

**Pull request merged**
