### PR TITLE
Documentation for debug:event-dispatcher command

### PR DESCRIPTION
**Pull request by matthieuauger**
See https://github.com/symfony/symfony-docs/issues/4230

As my english is far from perfect, I tried to make it short. Any feedback/suggestions welcome

### CODE REVIEW

**Comment by adamelso** [comment]
I just tried to use this in Sylius, which is Symfony 2.3, then realized this is a new command (I wondered why I had never used it before :). I think it would be worth adding a note that this command is only available since Symfony 2.6. Although I should be aware that I was browsing the Symfony 2.6 documentation, one of the most helpful aspects of the Symfony docs I found, was being able to see the notes which indicated what version new features were introduced.

**Comment by xabbuh** [comment]
@adamelso You're right. Can you please open an issue of even better a pull request?

**Comment by adamelso** [comment]
@xabbuh A pull request, I can do :)

**Comment by xabbuh** [comment]
Whatever you prefer :)

**Pull request merged**
