### PR TITLE
Remove double spaces in some YAML configuration

### PR DESCRIPTION
**Pull request by michaelperrin**
That makes things easier when copying and pasting ;)

There will be some conflicts when merging on the master branch. I can rebase and open an other PR on an other branch if needed.

### CODE REVIEW

**Comment by xabbuh** [comment]
👍 

Status: Reviewed

**Comment by javiereguiluz** [comment]
👍

**Comment by wouterj** [comment]
A great batch of fixes, @michaelperrin! Thanks a lot.

I'll take care of fixing the conflicts while merging after I've merged a couple other PRs. You'll hear from me if I need your help fixing them :)

**Comment by michaelperrin** [comment]
Thanks @wouterj !

**Pull request merged**
