### PR TITLE
Add default_path option reference

### PR DESCRIPTION
**Pull request by yceruto**
https://github.com/symfony/symfony/pull/24179

### CODE REVIEW

**Review by javiereguiluz — COMMENTED** [review]
Thanks for documenting this feature!

We'll need an additional comment explaining the difference between `default_path` and `paths`. Maybe it's as easy as removing the hardcoded `templates/` dir in `paths` option and replacing it with "the value of the "default_path" option".

I suggest to add in "path" option a list of the directories in the same order used by Symfony. Example:

```rst
This option defines the directories where Symfony will look for Twig templates
in addition to the default locations. Symfony looks for the templates in the
following order:

1. The directories defined in this option;
2. The ``src/Resources/views/`` directory of the application;
3. The directory defined in the ``default_path`` option;
4. The ``Resources/views/`` directories of the bundles used in the application.
```

**Comment by yceruto** [comment]
Thanks @javiereguiluz, updated.

**Comment by javiereguiluz** [comment]
@yceruto thanks! I have two more comments:

1) In my previous comment, I made up the priority of Twig directories. I don't know if that's the right order, so we must double check it.
2) Instead of this comment in the config sample: `# The following was added in Symfony 3.4.` it's better to add a `.. versionadded:: 3.4` directive. Something like this: https://github.com/symfony/symfony-docs/blob/3.3/reference/configuration/framework.rst#json_manifest_path

**Comment by yceruto** [comment]
> In my previous comment, I made up the priority of Twig directories. I don't know if that's the right order, so we must double check it.

Yes, it's right :)

> Instead of this comment in the config sample: # The following was added in Symfony 3.4. it's better to add a .. versionadded:: 3.4 directive.

Done. Thanks!

**Comment by yceruto** [comment]
However there is other paths that have not been mentioned here, such as:
```
* The ``src/Resources/<BundleName>/views/`` directories to override templates of the bundles used in the application.
* The ``<default_path>/bundles/<BundleName>/`` directories to override templates of the bundles used in the application.
```
Do you think we should add them?

**Comment by weaverryan** [comment]
Hmmm, I don’t think so. Let’s keep/add that info to wherever we talk about overriding bundles. And in that spot, we probably do need to update it for the new paths :). We could do that here or in another pr

**Comment by yceruto** [comment]
Agree, so I finished here :)

**Review by javiereguiluz — APPROVED** [review]

**Comment by xabbuh** [comment]
Thank you @yceruto.

**Pull request merged**
