### PR TITLE
Reduce ambiguity of encore installation

### PR DESCRIPTION
**Pull request by DerMonozukurist**

### CODE REVIEW

**Comment by weaverryan** [comment]
This is great! I've just added one other change - to add `yarn install` after installing via Flex.

I'm actually not sure if having two commands inside a `code-block:: terminal` is legal... but I think it is :)

Status: Reviewed

**Comment by weaverryan** [comment]
Yep, the multi-line terminal block is ok. This is ready!

**Comment by xabbuh** [comment]
Thank you @mahalay.

**Comment by mahalay** [comment]
Thank you as well.

**Pull request closed without merging**
