### PR TITLE
Add fe80::1

### PR DESCRIPTION
**Pull request by j-d**
Same reason as in https://github.com/symfony/symfony-standard/blob/2.8/web/app_dev.php#L15

### CODE REVIEW

**Comment by javiereguiluz** [comment]
:+1: I think it makes sense to be consistent here.

**Comment by OskarStark** [comment]
:+1:

**Comment by xabbuh** [comment]
For consistency, it makes sense to add it here to. However, what was the actual reason to add it to the front controller?

**Comment by j-d** [comment]
This was the original reason: https://github.com/symfony/symfony-standard/commit/2c844059730cd793c868e7015b1f660933be0552

**Comment by xabbuh** [comment]
Thanks for providing the background here. This looks like a reasonable change then. :+1:

**Comment by xabbuh** [comment]
Thanks for providing this update @j-d. I have merged this into the `2.3`. Then realised that we need to make the same change for the other configuration formats and that we an example similar to the dev front controller from the standard edition. I made those tweaks in 0ea34918b42898f94bbd428cc522444cbb55fa99.

**Pull request closed without merging**
