### PR TITLE
Fix EntityManager namespace

### PR DESCRIPTION
**Pull request by JhonnyL**
| Q | A |
| --- | --- |
| Doc fix? | yes |
| New docs? | no |
| Applies to | all |
| Fixed tickets | - |

### CODE REVIEW

**Comment by javiereguiluz** [comment]
@JhonnyL thanks for reporting this issue. Although your solution works, this other solution is also possible:

```php
use Doctrine\Common\Persistence\ObjectManager;
```

And of course, change the typehint from `EntityManager` to `ObjectManager` in the method. What do you think?

**Comment by stof** [comment]
and I think the current buggy code comes from a failed attempt at migrating from the ORM-specific typehint to the common interface.

**Comment by JhonnyL** [comment]
It was changed from ```ObjectManager``` to ```EntityManager``` in https://github.com/symfony/symfony-docs/pull/5456.

**Comment by JhonnyL** [comment]
@javiereguiluz @stof It was changed to ```EntityManger``` in a previous commit cause of inconsistency with the variable name. 

Typehinting the ```ObjectManger``` is probably better, but then I should also change the variable name to ```$manager```. What do you think?

**Comment by javiereguiluz** [comment]
@JhonnyL to me it makes sense to rename it to `$manager`

**Comment by xabbuh** [comment]
:+1:

**Comment by WouterJ** [comment]
Thanks, it looks perfect now!

**Pull request closed without merging**
