### PR TITLE
[Console] Update monolog_console.rst

### PR DESCRIPTION
**Pull request by ibukichi-jp**
Regarding https://symfony.com/doc/5.x/logging/monolog_console.html, current sample doesn't work properly.
Added "parent::__construct();" to sample code.

### CODE REVIEW

**Review by xabbuh — APPROVED** [review]

**Comment by masaharu-suizu** [comment]
@xabbuh ,
Thank you for checking this pull request!

**Review by alamirault — APPROVED** [review]

**Comment by masaharu-suizu** [comment]
@alamirault 
Thank you for checking this pull request!

**Comment by javiereguiluz** [comment]
Good catch Masaharu! Thanks ... and congrats on your first Symfony Docs contribution 🎉

**Comment by masaharu-suizu** [comment]
@javiereguiluz 
Thank you for supporting!

**Pull request merged**
