### PR TITLE
Added Vagrant configuration cookbook

### PR DESCRIPTION
**Pull request by wcluijt**
| Q | A |
| --- | --- |
| Doc fix? | no |
| New docs? | yes |
| Applies to | all |
| Fixed tickets | n/a |

A new cookbook article was added with an example Vagrant configuration that can be used with the Symfony Standard Edition.

### CODE REVIEW

**Comment by WouterJ** [comment]
@weaverryan can you please share your opinions on this?

**Comment by weaverryan** [comment]
Hey guys!

I'm sorry to be the blocker on this - I simply haven't had enough time (and don't have enough expertise) to get a reply back. I will say that I talked to Taylor yesterday, and he mentioned that Homestead now has Symfony support out of the box - thanks to laravel/homestead#243. 

Homestead looks like an easy win. But I would be open to any proposal that can get the user up-and-running quickly. I'm still -1 on a huge article. There could be a mixture: if we showed how to use Homestead, there could be sections in that cookbook showing common customizations.

@wcluijt what do you and others think? Again, I'm very sorry for the complete silence - your wall of text was too great for me :)

**Comment by WouterJ** [comment]
Homestead is now documented in the Symfony documentation: https://github.com/symfony/symfony-docs/pull/5655

What shall we do with this PR?

**Comment by WouterJ** [comment]
ping @symfony/team-symfony-docs

**Comment by xabbuh** [comment]
I am not sure. I don't like Puppet and I am not sure if this doesn't add to much confusion (and Vagrant can be used with a lot of other provisioning solutions).

**Comment by fabpot** [comment]
I would also close this one as a won't fix. Homestead is a good solution, providing an out-of-the-box solution like Homestead or one based on Docker would be also better than documenting how to do it.

**Comment by WouterJ** [comment]
Hi @wcluijt! Thanks for starting this big and interesting discussion. As we now have documentation about homestead, I'm going to close this PR.

I hope I'll see you back with more great PRs in the future!

**Pull request closed without merging**
