### PR TITLE
[Mailer] Add new email testing functions

### PR DESCRIPTION
**Pull request by JohJohan**
Refs symfony/symfony#50200

### CODE REVIEW

**Comment by JohJohan** [comment]
I updated target branch to 6.3 and rebased.

**Review by ndench — APPROVED** [review]
Thanks!

**Comment by OskarStark** [comment]
Please target 6.4 branch, thanks

**Comment by ghost** [comment]
@OskarStark the code is now merged can this also be merged?

**Review by OskarStark — APPROVED** [review]

**Comment by OskarStark** [comment]
I am on holiday, but @javiereguiluz can merge it 👍🏻
Thanks for this contribution 😎🙏🙌

**Comment by JohJohan** [comment]
@OskarStark happy holiday :tropical_drink:

**Comment by javiereguiluz** [comment]
Johan, thanks for contributing this feature and the docs for it.

A minor note: while merging we added the missing `versionadded` directive (see https://github.com/symfony/symfony-docs/commit/175231293441f3eaa8705f56939695e25ccc02f4)

**Pull request merged**
