### PR TITLE
Update voters.rst

### PR DESCRIPTION
**Pull request by asandjivy**

### CODE REVIEW

**Comment by wouterj** [comment]
Makes sense to me 👍 

status: reviewed

**Comment by javiereguiluz** [comment]
👍 

If possible, let's replace this:

```
The ``denyAccessUnlessGranted()`` function and the ``isGranted()`` function ...
```

by this:

```
The ``denyAccessUnlessGranted()`` and ``isGranted()`` functions ...
```

**Comment by asandjivy** [comment]
I agree with you. it's better :)

**Comment by asandjivy** [comment]
ok done :+1:

**Comment by xabbuh** [comment]
Thanks @asandjivy! I have merged your changes into the `2.8` branch and made some minor tweaks in b5fe1b49d85dec8d8542b1f4ef9b19c3339f15db.

**Pull request closed without merging**
