### PR TITLE
Shortening code block for PHP

### PR DESCRIPTION
**Pull request by ThomasLandauer**
If you agree, I'll shorten YAML and XML too.

### CODE REVIEW

**Review by xabbuh — APPROVED** [review]
looks good to me

**Comment by xabbuh** [comment]
@symfony/team-symfony-docs What's your opinion here?

**Comment by wouterj** [comment]
I agree, this looks much better to me :)

**Comment by xabbuh** [comment]
@ThomasLandauer Can you update the other formats as you suggested?

**Comment by ThomasLandauer** [comment]
There you go :-)

**Comment by wouterj** [comment]
Thanks @ThomasLandauer.

**Pull request merged**
