### PR TITLE
namespace fix

### PR DESCRIPTION
**Pull request by OskarStark**
Greetings from Symfony Live Berlin 2015 - Hack Day :smile:

### CODE REVIEW

**Comment by javiereguiluz** [comment]
:+1: 

@OskarStark is you are in the Hack Daya, could you convince someone to take a look at this issue? https://github.com/symfony/symfony/issues/15583  If this is truly a bug, it should be fixed or reverted before the stable release. It's critical!

**Comment by OskarStark** [comment]
@javiereguiluz will check that with @mvhirsch

**Comment by mvhirsch** [comment]
:+1:

**Comment by xabbuh** [comment]
:+1:

**Comment by xabbuh** [comment]
Thank you Oskar.

**Comment by OskarStark** [comment]
:+1:  Thank you!

**Pull request closed without merging**
