### PR TITLE
Update name of the webpack encore package

### PR DESCRIPTION
**Pull request by tbredillet**
webpack-encore is not used in composer

### CODE REVIEW

**Comment by javiereguiluz** [comment]
It's true that recently we changed the docs to always use the real package name instead of the Flex shortcut ... but maybe here we want to make an exception? Let's ask @weaverryan if he opposes to this. Thanks!

**Comment by weaverryan** [comment]
I *do* disagree with this change. This install doc is all about using Symfony Flex. And so, that package name will work.

But, I realize that this is the 3.4 branch, where Flex is not assumed as the default. So, I think we should re-work JUST this branch's docs to make that more obvious.

@razbounak Was this the issue? You're on a Symfony 3.4 project, and so aren't using Symfony Flex? Or was there something else confusing?

**Comment by razbounak** [comment]
@weaverryan yes It's only for 3.4

**Comment by javiereguiluz** [comment]
Thanks Thomas.

**Pull request merged**
