### PR TITLE
[Form] Documented the setInvalidMessage() method for data transformers

### LINKED ISSUE #11559: [Form] TransformationFailedException: Support specifying message to display
See https://github.com/symfony/symfony/pull/20978 and https://symfony.com/blog/new-in-symfony-4-3-more-form-improvements

### PR DESCRIPTION
**Pull request by javiereguiluz**
This fixes #11559.

### CODE REVIEW

**Comment by wouterj** [comment]
`TransformationFailedException`  should be used when transformation failed. Data mappers shouldn't transform data, DataTransformers should. DataMappers should only map (the transformed) data to the subject (entity, DTO, array, etc).

So 👍 for documenting this feature, but please add it to the DataTransformer article to not advocate wrong usage

**Comment by javiereguiluz** [comment]
Wouter, thanks for the review ... I've reverted the changes to explain this in the data transformers article.

**Review by OskarStark — APPROVED** [review]

**Review by xabbuh — APPROVED** [review]

**Review by OskarStark — APPROVED** [review]

**Review by wouterj — APPROVED** [review]
Looks good. I'll merge later today, I want to do a minor reword while merging :)

**Comment by xabbuh** [comment]
@javiereguiluz Could you reword the commit message to talk about data transformers instead of data mappers? Might be less confusing for some future reader of the git history. :)

**Comment by xabbuh** [comment]
Ah, maybe that's not necessary. I edited the PR title and during merge we will squash anyway (which should take the PR title as the commit message if I am not mistaken)

**Comment by wouterj** [comment]
Thank you @javiereguiluz! I've added a bit more info on transformer errors in e33b5b2 and also used a slightly different reason to use exceptions: to show specific errors and include user information, instead of showing a static error.

**Pull request merged**
