### PR TITLE
14123 Document denormalize groups value '*'

### LINKED ISSUE #14123: [Serializer] Add special '*' serialization group that allows any group
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#33540
| PR author(s) | @nrobinaubertin
| Merged in    | 5.2-dev

### PR DESCRIPTION
**Pull request by JohJohan**
Fixes https://github.com/symfony/symfony-docs/issues/14123.

### CODE REVIEW

**Review by tarlepp — COMMENTED** [review]
For me this looks just fine.

**Review by HeahDude — APPROVED** [review]
(Should target 5.4). Thank you for that PR!

**Review by Ahummeling — APPROVED** [review]
Looks good to me

**Comment by JohJohan** [comment]
@HeahDude i changed target branch to 5.4

**Comment by javiereguiluz** [comment]
Thanks Johan! ... and sorry it took us so long to merge your contribution 🙏

**Comment by JohJohan** [comment]
No worries! Just glad I can contribute a little :)

**Pull request merged**
