### PR TITLE
Syntax Error on "Options FollowSymlinks"

### PR DESCRIPTION
**Pull request by Balamung**
A missing "s" made the VirtualHost crash when symlink lines were uncommented.

### CODE REVIEW

**Comment by Balamung** [comment]
Just learned about the whole process, I should have done this change on 2.3 branch, sorry ! :(

**Comment by xabbuh** [comment]
@Balamung Don't worry. We can easily pick your changes and merge them into the `2.3` branch though. Anyway, thank you for noticing this bug and providing a patch for it. We really appreciate it! :+1:

**Comment by javiereguiluz** [comment]
@Balamung nice catch! This article is very important, so it should be flawless. Thanks!

**Comment by ricardclau** [comment]
There is actually a second commented Apache config section with the same issue. @Balamung Can you please update that one as well? Nice catch!

**Comment by Balamung** [comment]
@ricardclau I updated the 3 occurences that were in the file at the moment of my fork, but since then, another one was added, and I don't find how to get the patch branch back in sync to add the 4th :(

Sorry by the way for not checking the whole page before trying to correct, my bad !

**Comment by ricardclau** [comment]
The 4th section is like a second part of the subsection "Apache with mod_php/PHP-CGI" where it mentions the possibility to disable the .htaccess file to scratch some extra performance (You can read it here http://symfony.com/doc/current/cookbook/configuration/web_server_configuration.html)

It appears in the 2.6 branch https://github.com/symfony/symfony-docs/tree/2.6/cookbook/configuration but not in this PR, so it looks like it was added after your catch

What you need to do is to update your 2.6 fork so that it is up to date with the symfony repo one, merge it back to your branch, add this final typo and then rebase these 2 commits with your final one.

Do you need any help on these Git steps?

**Comment by Balamung** [comment]
Thank you a lot for providing the steps !

Should be good now =)

**Comment by ricardclau** [comment]
I think @xabbuh and @javiereguiluz will ask you to rebase your 3 commits into 1 as well but it is good to go!

**Comment by javiereguiluz** [comment]
@ricardclau you are right ... but lately we no longer ask users to squash their commits. The tool we use to manage Symfony repos can do that automatically, so we don't bother users :)

**Comment by ricardclau** [comment]
Awesome then! :)

**Comment by xabbuh** [comment]
:+1:

**Comment by WouterJ** [comment]
Hi @Balamung! For some reason, the tool wasn't able to merge this into the 2.3 branch. I've rebased your commits and created a new PR (with you still having the credits!): https://github.com/symfony/symfony-docs/pull/5211 I'll close this PR and merge that one. Thanks for fixing the bugs and your quick actions!

**Pull request closed without merging**
