### PR TITLE
Flex: Update links to Symfony 5.3

### PR DESCRIPTION
**Pull request by Seb33300**

### CODE REVIEW

**Comment by OskarStark** [comment]
Can you please explain your change? Right now this is pinned to a commit which will never change, after your change its not which could lead to errors/understanding problems in the future.

Thanks

**Comment by Seb33300** [comment]
They are links to Symfony 4.1, 4.2 and 5.1

**Comment by Seb33300** [comment]
Just modified the 2 links to use commit link instead of branch

**Review by OskarStark — APPROVED** [review]
Thanks

**Comment by javiereguiluz** [comment]
Thank you Sébastien.

**Pull request merged**
