### PR TITLE
[Serializer] Deprecate ``AdvancedNameConverterInterface``

### LINKED ISSUE #20266: [Serializer] Deprecate `AdvancedNameConverterInterface`
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#58308
| PR author(s) | @mtarld
| Merged in    | 7.2

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 7.2 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

### PR DESCRIPTION
**Pull request by mdoutreluingne**
Fix #20266 

Here, I don't know if I should modify or delete the `.. note::` block, what do you think?

### CODE REVIEW

**Comment by mtarld** [comment]
IMO yes, you should delete that note block.
And I think you should update the `OrgPrefixNameConverter` example as well

**Comment by mdoutreluingne** [comment]
I've also deleted the `deprecated` block that I'd added because `AdvancedNameConverterInterface` no longer refers to it in the documentation, so I don't think it's relevant to leave it.

Why do I need to update the example `OrgPrefixNameConverter`? `AdvancedNameConverterInterface` does not refer in this example

I may have not understood the changes that could occur with your PR, could you explain?

**Comment by mtarld** [comment]
It is because the `NameConverterInterface` signature has changed as well and triggers deprecations if not updated:
```php
    public function normalize(string $propertyName/* , ?string $class = null, ?string $format = null, array $context = [] */): string;
```

It now must be used as the `AdvancedNameConverterInterface` was (same for the denormalization)

**Comment by mdoutreluingne** [comment]
Thank you for taking the time to explain

I've updated the `OrgPrefixNameConverter` example. do you approve?

**Review by xabbuh — APPROVED** [review]

**Review by mtarld — APPROVED** [review]
LGTM! Thanks @mdoutreluingne :slightly_smiling_face:

**Comment by OskarStark** [comment]
Thank you @mdoutreluingne.

**Pull request merged**
