### PR TITLE
[Lock] Remove mention off DBAL Connection support for locking

### LINKED ISSUE #15952: [Lock] Remove support of Doctrine DBAL in PostgreSqlStore
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#43587
| PR author(s) | @GromNaN
| Merged in    | 6.0

### PR DESCRIPTION
**Pull request by JohJohan**
Fixes #15952 & #15950

### CODE REVIEW

**Comment by GromNaN** [comment]
Since these features are deprecated in 5.4 and replaced by `DoctrineDbalStore` and `DoctrineDbalPostgreSqlStore`, this PR may target branch 5.4.

Also, the new classes needs to be documented. (related to #15903)

**Comment by JohJohan** [comment]
@GromNaN if you think its a good idea to write all documentation in one pull request? There are multiple open issue to write documentation for this see: https://github.com/symfony/symfony-docs/issues/15952 & https://github.com/symfony/symfony-docs/issues/15950 & https://github.com/symfony/symfony-docs/issues/15945

**Comment by OskarStark** [comment]
Can you please rebase on top of 6.3 branch? Thanks

**Comment by JohJohan** [comment]
@OskarStark done :)

**Comment by alexandre-daubois** [comment]
Any news on this PR? This would close 6.0 milestone and two more issues :muscle:

**Comment by OskarStark** [comment]
Thank you Johan.

**Pull request merged**
