### PR TITLE
A bracket was missed

### PR DESCRIPTION
**Pull request by hpatoio**
In the code example a bracket was missed. 

Do I have to send a PR for all branches or you ave a system to updated all affected branch automatically ?

### CODE REVIEW

**Comment by wouterj** [comment]
Good catch, you're 100% correct! However, can you please revert the CS changes (you probably didn't do this on purpose):

 * Please remove the trailing whitespace on line 134
 * Please bring the indentation back one level again, just like it was originally. The final line would change from `);` to `]);` to fix the missing bracket.

You can push commits to the branch of this PR to update this pull request.

Also, if you have the time to do it, please change this to use the old `array()` syntax again to be consistent.

If you don't have time to update your PR, we can also do these things during merging.

status: needs work

**Comment by wouterj** [comment]
Oh and to answer your question:

 > Do I have to send a PR for all branches or you ave a system to updated all affected branch automatically ?

After some merges, we'll merge all branches from the oldest to the newest supported versions. So when submitting changes in the future, please submit the pull request against the oldest support version (2.7 now).

Thanks for your PR!

**Comment by wouterj** [comment]
👍 Thanks for your quick actions!

status: reviewed

**Comment by javiereguiluz** [comment]
👍

**Comment by xabbuh** [comment]
Thank you @hpatoio. I have merged your changes into the 2.7 branch and will merge them up to master from there. That's why your PR is shown as closed instead of merged, but you will still get the credits for your contribution nonetheless.

**Pull request closed without merging**
