### PR TITLE
Update security.rst

### PR DESCRIPTION
**Pull request by meelijane**
"setup" is a noun. "To set up" is a verb. "To set up" is an action statement, and should not use the noun form.

### CODE REVIEW

**Comment by meelijane** [comment]
http://www.future-perfect.co.uk/grammar-tip/is-it-setup-set-up-or-set-up/

**Comment by xabbuh** [comment]
Nice catch @meelijane :+1:

**Comment by WouterJ** [comment]
Thank you! With such a nice description, I can't do anything else than merging it :wink:

**Comment by WouterJ** [comment]
:wink

**Pull request closed without merging**
