### PR TITLE
Update argument_value_resolver.rst

### PR DESCRIPTION
**Pull request by asandjivy**

### CODE REVIEW

**Comment by snoek09** [comment]
Thanks @asandjivy :+1: 

Status: reviewed.

**Comment by wouterj** [comment]
Thanks, seems like this was not updated when the tag was renamed. I've now merged this into the main docs.

**Comment by asandjivy** [comment]
Thank you ;) is it possible to have a badge ? ;)

2016-08-11 12:18 GMT+02:00 Wouter J <notifications@github.com>:

**Comment by wouterj** [comment]
> Thank you ;) is it possible to have a badge ? ;)

If the email connected to your commit (see `git config --global user.email`) is also configured as an email (primary or secondary) on SensioLabs connect, you should recieve the badge automatically.

**Comment by asandjivy** [comment]
Thank you ! I got the badge :D

**Pull request merged**
