### PR TITLE
[Scheduler] remove example using not existing timezone property

### PR DESCRIPTION
**Pull request by xabbuh**
see symfony/symfony#57249

### CODE REVIEW

**Comment by xabbuh** [comment]
@alexandre-daubois FYI (related to #19444) :)

**Comment by alexandre-daubois** [comment]
Oops, don't know where I saw this, thanks!

**Review by alexandre-daubois — APPROVED** [review]

**Comment by xabbuh** [comment]
maybe a copy-and-paste mistake from the `AsCronTask` attribute

**Review by OskarStark — APPROVED** [review]

**Comment by OskarStark** [comment]
Thank you Christian.

**Pull request merged**
