### PR TITLE
Update questionhelper.rst

### PR DESCRIPTION
**Pull request by yceruto**
Add missed variable `$helper` in some examples.

### CODE REVIEW

**Comment by javiereguiluz** [comment]
Not sure about this ... because the previous example doesn't include it either. This `$helper` var is defined at the very beginning of the article.

**Comment by yceruto** [comment]
Well, I could say: I'm sure, because the next example include it :smile: and the [2nd][1] and [3rd][2] ...

As I can understand, this article doesn't have a tutorial format, where we always need to start with the first step to complete the rest, so each example is independent and should work as is, plus if each sub-topic is linkable, I didn't like to review the whole article to make it work... I'd like just copy & paste the code example, you don't think?

 [1]: https://github.com/yceruto/symfony-docs/blob/c1a039542b64f684c26e41d1e95d91256d739edd/components/console/helpers/questionhelper.rst#asking-the-user-for-confirmation
 [2]: https://github.com/yceruto/symfony-docs/blob/c1a039542b64f684c26e41d1e95d91256d739edd/components/console/helpers/questionhelper.rst#asking-the-user-for-information

**Comment by yceruto** [comment]
I just update other examples, note that were not all, the other half had included ;)

**Comment by weaverryan** [comment]
I like this. Thanks @yceruto!

**Pull request closed without merging**
