### PR TITLE
[Contributing] [Standards] Added entry and example for sorting "use" declarations

### PR DESCRIPTION
**Pull request by phansys**
Added entry and example for sorting `use` declarations

| Q | A |
| --- | --- |
| Doc fix? | yes |
| New docs? | no |
| Applies to | 2.8+ |
| Fixed tickets |  |

### CODE REVIEW

**Comment by javiereguiluz** [comment]
@phansys sorry for not having commented in your pull request earlier.

To be honest, personally I don't care at all about the `use` statements, but I know that lots of people do care. So my questions are: is there any official PHP standard about this? If not, is the proposed alphabetical sorting the most common convention used to sort `use` statements? Does Symfony code follows or enforces any sorting? Thanks.

**Comment by phansys** [comment]
@javiereguiluz, thanks for your feedback; there is no problem about delay :)
I'm trying to find an example in Symfony codebase where this order is encouraged (at least in a commit comment), but sincerely, I don't remember from where I took this rule.
Checking [php-cs-fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/fbca2593178d02d77c06a7351dabb4e32d58590e/README.rst#usage) (**ordered_use [contrib]**), it seems not to be part of Symfony's CS, so I'll try to keep searching.

**Comment by phansys** [comment]
Just found a comment of @fabpot, who told that order hasn't any reason in Symfony: https://github.com/symfony/symfony/pull/1167#issuecomment-1273024

**Comment by javiereguiluz** [comment]
Maybe we can create a quick RFC issue in `symfony/symfony` repo to ask for the opinion of Symfony deciders/mergers about this?

**Comment by phansys** [comment]
That would be great. I'll try to create the RFC soon.

**Comment by nicolas-grekas** [comment]
The merge strategy of Symfony would make this apply to 2.3+, not just 2.8+

**Comment by phansys** [comment]
@nicolas-grekas, I took this a "new feature" instead a "bugfix", since there is nothing solid about this standard in current docs or elsewhere.
BTW, I could just close this one and open a new PR against 2.3 if the RFC is approved.
What do you think?

**Comment by nicolas-grekas** [comment]
Waiting for progress on the RFC before spending more time here looks good.

**Comment by fabpot** [comment]
I won't change the Symfony code base to order the use statements. That would be a huge mess when merging back into newest branches, ans frankly, not worth it. Let's stop waisting our time on things that we should not care about.

**Comment by phansys** [comment]
Closing since the [RFC](https://github.com/symfony/symfony/issues/15062) was closed.

**Pull request closed without merging**
