### PR TITLE
[Validator] Remove extra space in the message

### PR DESCRIPTION
**Pull request by wkania**

### CODE REVIEW

**Review by OskarStark — APPROVED** [review]
Nice catch

**Comment by javiereguiluz** [comment]
@wkania thanks for this improvement. For future pull requests, please note that Symfony 3.4 is no longer maintained, so new pull requests should be mage against a supported branch. Here you can find the list of currently maintained branches: https://symfony.com/releases Thanks!

**Comment by wkania** [comment]
@javiereguiluz Thank you for the info. My knowledge about the oldest maintened version was from the [documentation](https://symfony.com/doc/current/reference/constraints.html). From what I see it's still maintened for few more days.

image

**Comment by javiereguiluz** [comment]
@wkania you are absolutely right! I'm sorry.

3.4 is STILL maintained for a few days (until November 2020 ends). However, we decided to no longer merge changes in that branch to avoid introducing mistakes now that we're so close to end its support. So, you did it perfectly right (thanks for that!) but we prefer to no longer merge in 3.4. Cheers!

**Pull request merged**
