### PR TITLE
Minor fixes for the QuestionHelper documentation

### PR DESCRIPTION
**Pull request by javiereguiluz**
| Q | A |
| --- | --- |
| Doc fix? | yes |
| New docs? | no |
| Applies to | all |
| Fixed tickets | - |

### CODE REVIEW

**Comment by WouterJ** [comment]
-1 on adding `$helper = ...` in all code-blocks, the first code blocks show the helper and all other code blocks include `// ...`, indicating that this is an extension of the previous code block.

**Comment by javiereguiluz** [comment]
To be honest, I find this article great and "awful" at the same time. If you are using the Console component inside a Symfony application, this article is great. You can copy+paste the examples and everything works perfectly.

However, if you are using this outside Symfony, this article is "awful", because you copy/paste the examples and nothing works. Sometimes the `$this->getHelper()` instruction is missing, other times you realize that `$this->getHelper()` doesn't work at all and you need `$helper = new ...` and my favorite: `$input` and `$output` are "magic" variables which are available nowhere and they don't explain you what to do to create them outside Symfony.

**Comment by WouterJ** [comment]
What do you mean with "outside Symfony"? When using Console component standalone, things still work as documented.

**Comment by javiereguiluz** [comment]
Imagine that I want to make a Symfony Console command to ask information to the user. I read this article and I copy/paste the following:

ask_information

Nothing works :sob: 

This is the real code that I must use:

```php
use Symfony\Component\Console\Question\Question;
use Symfony\Component\Console\Helper\QuestionHelper;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Output\ConsoleOutput;

$helper = new QuestionHelper();
$question = new Question('Enter the name of the bundle: ', '');
$bundle = $helper->ask(new ArgvInput(), new ConsoleOutput(), $question);
```

**Comment by WouterJ** [comment]
Yeah, what we actually need is to wrap at least the first example in a class + execute() method and the following examples in an execute() method.

**Comment by WouterJ** [comment]
On the other hand, when you're trying to use symfony console standalone, you first read the introduction and you'll learn about the execute method. So it's quite obvious that the code shown here shouldn't live somewhere random in a php script

**Comment by javiereguiluz** [comment]
Wouter, when someone uses Symfony Console component, they Google for "symfony console ask user" or something like that and they arrive at this page. People don't follow the logical path, they just use Google or StackOverflow.

-----

What would you think about completing the Symfony Components docs as follows:

sf_framework

sf_component

**Comment by OskarStark** [comment]
:+1: nice idea @javiereguiluz

**Comment by WouterJ** [comment]
If you use Symfony console standalone, you'll end up doing exact the same as using Symfony Console inside a symfony full-stack. the only difference is that you have to create your own front controller and have to register commands yourself doing `$app->add(new XyzCommand())`.

The only time you'll end up having to instantiate ArgvInput and ConsoleOutput yourself is when using the console component beyond normal usage, not using the Command class or the simple callback functions.

If you end up using it that way, which is btw not documented at all, you must have enough experience with the Console component to find out what `$input` and `$output` mean.

---

Now, what I propose is to emphasize the Command usage. In the first example on the page, show the full class definition:
```php
// ...
use Symfony\Component\Console\Question\ConfirmationQuestion;

class YourCommand extends Command
{
    // ...

    public function execute(InputInterface $input, OutputInterface $output)
    {
        $helper = $this->getHelper('question');
        $question = new ConfirmationQuestion('Continue with this action?', false);

        if (!$helper->ask($input, $output, $question)) {
            return;
        }
    }
}
```

And in the other examples, only add the method definition:
```php
use Symfony\Component\Console\Question\Question;

// ...
public function execute(InputInterface $input, OutputInterface $output)
{
    // ...
    $question = new Question('Please enter the name of the bundle', 'AcmeDemoBundle');

    $bundle = $helper->ask($input, $output, $question);
}
```

This gives enough context to the code example to avoid confusion.

**Comment by javiereguiluz** [comment]
@WouterJ I think you are right. The use case that I exposed was too advanced. You always use this code inside a consome command, being a Symfony app or not.

**Comment by javiereguiluz** [comment]
I've made the changes proposed by @WouterJ. This is ready for the final ewview. Thanks.

**Comment by xabbuh** [comment]
:+1:

**Comment by WouterJ** [comment]
:+1:

**Comment by WouterJ** [comment]
Thanks Javier! I've added 2 use statements for the Input/Output interfaces in c93a948

**Pull request closed without merging**
