### PR TITLE
Add the diversity guidance team

### PR DESCRIPTION
**Pull request by fabpot**
/cc @nicolas-grekas @TimoBakx @lsmith77 @michellesanver @zanbaldwin

### CODE REVIEW

**Comment by zanbaldwin** [comment]
Where are the usernames going to link to?
GitHub, SymfonyConnect, etc?

**Comment by TimoBakx** [comment]
> Where are the usernames going to link to?
> GitHub, SymfonyConnect, etc?

Currently, they link to github.

**Comment by fabpot** [comment]
Links fixed

**Review by TimoBakx — APPROVED** [review]

**Review by zanbaldwin — APPROVED** [review]

**Review by nicolas-grekas — APPROVED** [review]

**Comment by javiereguiluz** [comment]
Thanks Fabien. Merged in 3.4.

**Pull request closed without merging**
