### PR TITLE
deprecated 'datettime' Form Type

### PR DESCRIPTION
**Pull request by dsmink**
'datettime' to DateTimeType::class

### CODE REVIEW

**Comment by xabbuh** [comment]
:+1:

**Comment by javiereguiluz** [comment]
👍

**Comment by OskarStark** [comment]
typo in the commit message -> datet**t**ime, same in the PR title and the PR body

**Comment by WouterJ** [comment]
Thanks @dsmink, great catch! I've merged this into 2.8, where form type names were deprecated.

**Comment by OskarStark** [comment]
you missed the typo 😢

**Comment by WouterJ** [comment]
I didn't miss it, but I don't care about typos in git history. The documentation is important, the commits aren't imo.

**Comment by OskarStark** [comment]
> I didn't miss it, but I don't care about typos in git history. The documentation is important, the commits aren't imo.

ok

**Pull request closed without merging**
