### PR TITLE
Removed the Propel chapter from the Symfony book

### PR DESCRIPTION
**Pull request by javiereguiluz**
| Q | A |
| --- | --- |
| Doc fix? | no |
| New docs? | no |
| Applies to | all |
| Fixed tickets | - |

This is the first step into updating the Symfony Book. Most of these updates will consist on removing things.

The two main reasons for this change are: 1) the traffic to that book chapter is marginal; 2) Propel is a second or third class citizen in Symfony, whereas Doctrine is a first-class citizen.

One of the positive outcomes of this change is that we now have a cookbook section about Propel. This means that we could publish more short articles about Propel + Symfony and, in the long term, increase Propel awareness among Symfony community.

### CODE REVIEW

**Comment by stof** [comment]
Should we create a cookbook section about Propel or move this to the PropelBundle and render the bundle doc on the website ? The advantage of putting this in the bundle is that the Prople team could provide the Propel2 version of the same cookbooks (in the 2.0 branch of the bundle)

**Comment by WouterJ** [comment]
I'm :+1: for using the PropelBundle docs instead of the Propel cookbook

**Comment by javiereguiluz** [comment]
I've removed the proposed Propel cookbook section

**Comment by WouterJ** [comment]
@javiereguiluz this requires a rebase. Could you please also create a ticket in the propel repository, so they don't forget to add it to their docs?

I also think their docs is linking to this doc?

**Comment by javiereguiluz** [comment]
The PR is now rebased and the issue has been opened in the PropelBundle repository: https://github.com/propelorm/PropelBundle/issues/323

**Comment by WouterJ** [comment]
@javiereguiluz sorry for not flagging this as finished earlier, but this PR has some conflicts again.

**Comment by javiereguiluz** [comment]
I've rebased the PR to fix conflicts.

**Comment by weaverryan** [comment]
@javiereguiluz I don't like that an existing page will 404. Could we add just a little bit of content on the page that links over to the Propel docs? (https://github.com/propelorm/PropelBundle/blob/1.4/Resources/doc/index.markdown)

Thanks!

**Comment by WouterJ** [comment]
Hi @javiereguiluz. Can you please rebase this PR and apply what @weaverryan suggested?

**Comment by stof** [comment]
@javiereguiluz ping

**Comment by javiereguiluz** [comment]
Closing it in favor of #5369

**Pull request closed without merging**
