### PR TITLE
moved XSD to HTTPS

### PR DESCRIPTION
**Pull request by OskarStark**
as @fabpot did this in the code base, I think we should reflect the changes in the docs, too.

Refs https://github.com/symfony/symfony/pull/30434

### CODE REVIEW

**Review by fabpot — APPROVED** [review]

**Review by HeahDude — APPROVED** [review]

**Comment by OskarStark** [comment]
added some more missing, should be ready to merge now

**Comment by javiereguiluz** [comment]
Thank you Oskar.

**Comment by javiereguiluz** [comment]
@OskarStark this has been merged up ... and I also updated the remaining URLs in 4.2 and master branches.

**Comment by OskarStark** [comment]
> @OskarStark this has been merged up ... and I also updated the remaining URLs in 4.2 and master branches.

Great job, thank you 👍

**Pull request merged**
