### PR TITLE
Method "$this->getMock()" is deprecated

### PR DESCRIPTION
**Pull request by JohnnyEvo**

### CODE REVIEW

**Comment by javiereguiluz** [comment]
👍  `getMock()` is deprecated since PHPUnit 5.4.0. However, I wonder if we should use `createMock()` or `getMockBuilder()`:

> The PHPUnit\Framework\TestCase::getMock() method has been deprecated. Please use PHPUnit\Framework\TestCase::createMock() or PHPUnit\Framework\TestCase::getMockBuilder() instead.

Source: https://github.com/sebastianbergmann/phpunit/wiki/Release-Announcement-for-PHPUnit-5.4.0#changes

**Comment by ogizanagi** [comment]
👍  for using `createMock()`

**Comment by ousmaneNdiaye** [comment]
👍

**Comment by JohnnyEvo** [comment]
@ogizanagi Why use `createMock()` instead of `getMockBuilder()` ? I didn't know `createMock()` but `createMock()` doesn't invoke the constructor it seems to me, so it's possible that there are bad surprises.

**Comment by ogizanagi** [comment]
@JohnnyEvo : Right, but `ObjectManager` is an interface anyway. So using `->createMock()` won't cause any issue. Also unless you do partial mocking on objects, most of the time the `__construct` call is not necessary.

**Comment by JohnnyEvo** [comment]
Ok, thank you for your explanation 👍

**Comment by weaverryan** [comment]
Thanks guys! I've also updated a number of other `getMock()` usages at sha: c52839a6461c1cadb41b98497efd56bcd8bfa3f9

Cheers!

**Pull request closed without merging**
