### PR TITLE
Update entity_provider.rst

### PR DESCRIPTION
**Pull request by asandjivy**

### CODE REVIEW

**Comment by wouterj** [comment]
I don't think it's really needed to link to it. However, you're the doc user and you probably wanted to check the API link here. So 👍  :)

status: reviewed

**Comment by javiereguiluz** [comment]
👍 

Unrelated to this ... but if we could make some minor changes in this paragraph when merging it:

```
If your User implements ... -> If your user implements ...
```

and this:

```
... is simply called, and ...-> ... is called, and ...
```

**Comment by asandjivy** [comment]
ok done ;)

**Comment by xabbuh** [comment]
Thank you @asandjivy.

**Pull request closed without merging**
