### PR TITLE
deprecated use of 'datetime' for Type

### PR DESCRIPTION
**Pull request by dsmink**
'datetime' --> \Symfony\Component\Form\Extension\Core\Type\DateTimeType::class

### CODE REVIEW

**Comment by javiereguiluz** [comment]
Instead of this:

```php
\Symfony\Component\Form\Extension\Core\Type\DateTimeType::class
```

What about using:

```php
'Symfony\Component\Form\Extension\Core\Type\DateTimeType'
```

or:

```php
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;

// ...

DateTimeType::class
```

**Comment by dsmink** [comment]
Javier,

I prefer the latter, but that is debatable. The main thing is that The
example is incorrect.

Kind regards,

Dennis Smink
Op 23 mei 2016 3:39 p.m. schreef "Javier Eguiluz" <notifications@github.com

**Comment by xabbuh** [comment]
If I am not mistaken, we always have `use` statements where we did the change.

**Comment by javiereguiluz** [comment]
We can close this in favor of the newer #6608.

**Comment by xabbuh** [comment]
You are right. Thanks for creating this PR @dsmink. I am closing here in favour of your other PR which we'll merge soon.

**Pull request closed without merging**
