### PR TITLE
[Validator] Add `pattern` in `Regex` constraint violations

### PR DESCRIPTION
**Pull request by alamirault**
For 6.3

https://github.com/symfony/symfony/pull/48232

Waiting Code merge (Is there a tip in order to set label at PR creation ?)

### CODE REVIEW

**Review by OskarStark — APPROVED** [review]

**Comment by 94noni** [comment]
> Is there a tip in order to set label at PR creation ?

Perhaps create a new carsonbot action that detect the symfony/symfony PR number, and check its state if merged or not ^^

**Review by 94noni — APPROVED** [review]

**Comment by OskarStark** [comment]
We created the `6.3` branch, can you please retarget your PR? Thanks

**Comment by alamirault** [comment]
@OskarStark I rebased on 6.3

**Comment by OskarStark** [comment]
It took time, but here we go, this is in now. Thank you very much Antoine.

**Pull request merged**
