### PR TITLE
mention composers autoload apcu functionality

### PR DESCRIPTION
**Pull request by SimonHeimberg**
Using composer is officially recommended starting with symfony 3.3

### CODE REVIEW

**Comment by SimonHeimberg** [comment]
Using [`ApcClassLoader`](http://api.symfony.com/master/Symfony/Component/ClassLoader/ApcClassLoader.html) is deprecated since version 3.3, to be removed in 4.0.

After merging this commit, the file must must be adapted for 4.0 and maybe mention deprecation for 3.3.

**Comment by SimonHeimberg** [comment]
Unsure if the proposed text is fine.

**Comment by SimonHeimberg** [comment]
change log of composer mentioning apcu: https://github.com/composer/composer/blob/9ae434c/CHANGELOG.md#130-rc---2016-12-11

**Comment by xabbuh** [comment]
Thank you for this pull request @SimonHeimberg. But actually we already have an open PR that tackles this (see #7960). So I am sorry but I need to close here. Hope to see you back soon with some other changes. :)

**Pull request closed without merging**
