### PR TITLE
form standalone csrf updates

### PR DESCRIPTION
**Pull request by mmamedov**
| Q | A |
| --- | --- |
| Doc fix? | yes |
| New docs? | no |
| Applies to | 2.8 |
| Fixed tickets |  |

### CODE REVIEW

**Comment by mmamedov** [comment]
It is confusing for a beginner to start working with Symfony components outside Symfony framework. I am using Form component in a standalone mode, inside my own framework, and documentation lacks a lot loops one must jump through in order to make it work. This update in docs helps with one of them.

**Comment by xabbuh** [comment]
The components section describes using the different components standalone. So I think we can just expand the existing code example with what you added below (so we would only have one code block with a bit more details). What do you think?

**Comment by mmamedov** [comment]
I think that is exactly what I am trying to say, we need to expand code here the edit I am proposing: http://symfony.com/doc/2.8/components/form/introduction.html 

I am using Twig, and Form in standalone mode (among other components too), and the edit I am making is the way I have successfully imported them into my project (any project in that sense). I first used it with Symfony 2.6, and then updated to 2.8 recently. Code I am submitting is a working code for Symfony 2.8 for those who uses Form and Twig components. 

** I think we should also open a section of how to incorporate a standalone Form component with all the whistles (validation, security, translation, etc..) into a project, because "composer require symfony/form" simply doesn't cut it. But that's another topic, and if you think it will be beneficial for the community I could work on it.

**Comment by WouterJ** [comment]
I'm :-1: on this one. Tip boxes are related to their context. Just before this box, an example is shown with all variables and method calls. The tip box hides these lines of code in order to keep it small (the `// ...` is used throughout the docs to indicate something is hidden and already explained in the chapter).

 > ** I think we should also open a section of how to incorporate a standalone Form component with all the whistles (validation, security, translation, etc..) into a project, because "composer require symfony/form" simply doesn't cut it. But that's another topic, and if you think it will be beneficial for the community I could work on it.

Afaik, the sections in this components article contain this information? (both the require and the set up of specific extensions) If not, please tell which details you are missing or submit a PR adding the missing bits.

**Comment by mmamedov** [comment]
Existing code snippet, doesn't clearly show how to use NativeSessionTokenStorage, and Twig part on the same page uses a non-existent $csrfProvider variable (it is not defined anywhere on that page), $csrfProvider was used in Symfony 2.6 and in 2.8 gives an error. "new FormExtension(new TwigRenderer($formEngine, $csrfManager))" csrfManager should be used instead. That section is also updated.

Following docs it is not always easy to use standalone components. For example on the same very page it shows how to install twig-bridge, but the translation component section is missing crucial part which allows "trans" filter to be used in twig files. This is the missing code -  "$twig->addExtension(new TranslationExtension($translator));". 

There are some examples on the web, but most are outdated. I think Symfony community itself should be the source for such valuable information, this will make integration of Symfony components much easier.

**Comment by xabbuh** [comment]
@mmamedov Well, @WouterJ is indeed right that the newly added example is basically the same as the example above expect that the `SessionTokenStorage` was replaced with the `NativeSessionStorage`.

**Comment by mmamedov** [comment]
@xabbuh I guess you are right. The NativeSession and that Twig update are the only tweaks. It's safe to close this issue, those who use standalone component will figure it out themselves.

**Comment by xabbuh** [comment]
@mmamedov I am sorry that your changes didn't make it this time. But we are looking forward to see more contributions from you.

**Comment by mmamedov** [comment]
Sure, ok.

**Pull request closed without merging**
