### PR TITLE
Add documentation CouchbaseBucketAdapter for cache system.

### PR DESCRIPTION
**Pull request by ajcerezo**
With this pull request add documentation CouchbaseBucketAdapter for cache system.

### CODE REVIEW

**Comment by OskarStark** [comment]
Please rebase and target 4.4 branch 👍🏻

**Comment by ajcerezo** [comment]
Hi @OskarStark,

This is done.

Thank you.

**Review by OskarStark — APPROVED** [review]
Thank you!

**Comment by OskarStark** [comment]
It took time, but here we go, this is in now. Thank you very much Antonio.

**Comment by ajcerezo** [comment]
@OskarStark Thank you very much.

**Pull request merged**
