### PR TITLE
[Templating] [Templates] Replace Webpack with AssetMapper (minor)

### PR DESCRIPTION
**Pull request by smnandre**
Feature AM (as the "recommanded" choice) in this small note in the [Templating](https://symfony.com/doc/7.1/templates.html#build-versioning-more-advanced-css-javascript-and-image-handling) page.

(No need to change the link URL: it targets the shared "[frontend](https://symfony.com/doc/7.1/frontend.html)" page that present both solutions)

### CODE REVIEW

**Review by 94noni — APPROVED** [review]
What about still, during a period of time, document both options to let ppl decide what they really need for their apps?

**Comment by smnandre** [comment]
> What about still, during a period of time, document both options to let ppl decide what they really need for their apps?
> 
> 

The linked page is done for that :) i just update the "default value"

**Comment by 94noni** [comment]
of course I got the primer idea, nonetheless here you change one to another
why not writing then "read more about symfony frontend doc" ?

**Comment by smnandre** [comment]
Because as for Symfony 6.4 AssetMapper is the recommanded / default way of handling front-end assets :)

**Comment by javiereguiluz** [comment]
I understand @94noni's comments ... but here we're making the change in the 7.1 branch ... so I agree with @smnandre and I think it's fine to "push" AssetMapper a bit here and recommend it as the default solution to manage assets because that matches reality. Thanks!

**Comment by javiereguiluz** [comment]
Thanks Simon.

**Pull request merged**
