### PR TITLE
Testing: Fix typo from #6427

### PR DESCRIPTION
**Pull request by alexisLefebvre**
Fix typo introduced in #6427: `$this->request` → `$request`

### CODE REVIEW

**Review by HeahDude — APPROVED** [review]
Good catch! Thanks

**Comment by alexislefebvre** [comment]
@HeahDude I introduced the typo by myself in my previous PR, it was easy to catch. :wink:

**Review by javiereguiluz — APPROVED** [review]
👍

**Comment by xabbuh** [comment]
Thank you @alexislefebvre.

**Pull request merged**
