### PR TITLE
configure CSRF protection under framework.form

### PR DESCRIPTION
**Pull request by xabbuh**
| Q | A |
| --- | --- |
| Doc fix? | yes |
| New docs? | no |
| Applies to | all |
| Fixed tickets | symfony/symfony#9252 |

### CODE REVIEW

**Comment by stof** [comment]
This looks wrong to me. the CSRF layer is available outside the form layer since Symfony 2.4+

**Comment by xabbuh** [comment]
@stof But it's deprecated: https://github.com/symfony/symfony/blob/2.8/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php#L48-L55

**Comment by javiereguiluz** [comment]
I think this change is correct. This is only about adding CSRF automatically to forms or not. But you can deal with the CSRK tokesn yourself outside the forms and without considering this config option.

**Comment by stof** [comment]
@xabbuh you are confusing enabling the CSRF system and configuring the field_name for its integration in forms

**Comment by xabbuh** [comment]
@stof You are probably right now that I look at this again. Though we removed this option entirely in symfony/symfony#15695. I guess we need to fix that and also revert symfony/symfony-standard#879 then, right?

**Comment by WouterJ** [comment]
So this can be closed?

**Comment by xabbuh** [comment]
I don't think so. We first have to agree if we revert the code change or if we update the documentation.

**Comment by WouterJ** [comment]
Code has been reverted

**Pull request closed without merging**
