### PR TITLE
Add "YourAwesomeCoolClass" example for "symfony/property-info" component

### PR DESCRIPTION
**Pull request by liviubalan**
See:
http://docs.phpdoc.org/references/phpdoc/tags/var.html

### CODE REVIEW

**Review by javiereguiluz — COMMENTED** [review]
I'm not sure that we need a concrete example here. Besides, in the rest of the article we show results that have nothing to do with this class code. Example:

```php
     $properties = $propertyInfo->getProperties($class);
     /*
       Example Result
       --------------
       array(3) {
         [0] => string(8) "username"
         [1] => string(8) "password"
         [2] => string(6) "active"
       }
     */
```

That could be confusing for users.

**Comment by liviubalan** [comment]
Thanks for the info! I will create a separate _Learn more_ article named _How to Use PhpDoc Extractor_. Is it ok this approach? You can reject the current pull request.

**Comment by javiereguiluz** [comment]
@liviubalan we're aggressively minimizing the Symfony Docs contents to help with its maintenance (we have little resources at the moment). If the feature you mention is important, then of course it's OK to add new contents. However, instead of adding a new article, we should consider if it's possible to add a short section about it in some existing article. Thanks!

**Comment by liviubalan** [comment]
Thanks for the info @javiereguiluz! You can close the current pull request.

**Comment by javiereguiluz** [comment]
@liviubalan closing then. I see that you are creating new pull requests, so thank you!

**Pull request closed without merging**
