### PR TITLE
[Form] Add note about Intl component

### PR DESCRIPTION
**Pull request by Nyholm**
Documentation for PR https://github.com/symfony/symfony/pull/40298

The Intl component is not a dependency of the form component anymore.

### CODE REVIEW

**Comment by javiereguiluz** [comment]
Tobias, thanks for proposing these changes. However, in my opinion, we shouldn't merge this. Why? Because this feature has a perfect error message, so I don't think these docs are needed.

If a user tries to use this and doesn't have the Intl component installed, they'll see this message:

https://github.com/symfony/symfony/blob/f0e076a013064b9a1c4c34e1faed8481e10c9988/src/Symfony/Component/Form/Extension/Core/Type/CountryType.php#L32-L34

Although it's concise, it perfectly explains the problem and shows the solution, so I'd say that's enough. But let's wait for other opinions. Thanks!

**Comment by Nyholm** [comment]
That is fair. But it should definitely be merged in 6.x

**Comment by Nyholm** [comment]
> That is fair. But it should definitely be merged in 6.x

Oh, my bad. I though this was a comment on a different PR. 

Im fine with not merging this PR. Im not sure what the praxis is in this scenario. I'll leave this open for a second opinion.

**Comment by maxhelias** [comment]
I agree with @javiereguiluz 👍  It will mean less maintenance to be done on the documentation

**Comment by Nyholm** [comment]
Okey. Thank you for the reviews and input.

**Pull request closed without merging**
