### PR TITLE
Replace XLIFF number ids by strings

### PR DESCRIPTION
**Pull request by Mx-Glitter**
| Q | A |
| --- | --- |
| Doc fix? | yes |
| New docs? | no |
| Applies to | all |
| Fixed tickets | #6341 |

### CODE REVIEW

**Comment by javiereguiluz** [comment]
:+1: nice improvement! Thanks @Triiistan.

**Comment by WouterJ** [comment]
:+1:

**Comment by xabbuh** [comment]
:+1:

**Comment by xabbuh** [comment]
Thank you @Triiistan.

**Pull request merged**
