### PR TITLE
extend profiler article about how to use the stopwatch

### PR DESCRIPTION
**Pull request by SimonHeimberg**

### CODE REVIEW

**Comment by SimonHeimberg** [comment]
alternative to #9320, was suggested there

**Review by ndench — APPROVED** [review]
Looks good to me. Thanks for the contribution :+1:

**Review by ndench — CHANGES_REQUESTED** [review]
Actually, the build is failing because `stopwatch.rst` is not being included anywhere:
```
/home/travis/build/symfony/symfony-docs/profiler/stopwatch.rst:: WARNING: document isn't included in any toctree
```

Can you include it in `profiler.rst` the same as the other profiler docs?

**Comment by SimonHeimberg** [comment]
Finally done. The bot is pleased. Sorry for force-pushing this often. I first did not know how to resolve the merge conflict.
Current branch is the original commit merged with 2.8, and then two commits.

**Comment by SimonHeimberg** [comment]
What does failure of `platformsh` mean?

**Comment by ndench** [comment]
Do you want to update profiler.rst to have a link to stopwatch.rst?

**Comment by xabbuh** [comment]
Thank you for the PR. Do you think we still need it now that #10259 is merged?

**Comment by SimonHeimberg** [comment]
The profiler page would be nice since this is the place I would probably start searching. (Suggested to place the info there in https://github.com/symfony/symfony-docs/pull/9320#pullrequestreview-103635691.) But duplicating the information is no help, a link is sufficient.
But [`dump()`](https://symfony.com/doc/4.1/components/var_dumper.html#the-dump-function) is not mentioned on the profiler page. And this is the simplest way to add custom info to the profiler. Should we remain consistent?

##### summary of history

Well, not sure anymore how history was. I made several PR concerning this topic:
on 2018-02-23 #9320, closed in favour of this one
on 2018-09-05 #10259, merged on 2018-11-30, very similar to #9320, no link to the other two
on 2018-09-12 this one, opened because suggested in https://github.com/symfony/symfony-docs/pull/9320#pullrequestreview-103635691

I guess I created #10259 without remembering the first PR. And having forgotten to mention it when replacing the 1st one. So there were probably two plans...

**Comment by javiereguiluz** [comment]
@SimonHeimberg thanks for this contribution! You are right that this is a bit confusing and it's not easy to know where to put things. So, in #10970 we're revamping the main Profiler article. I've been inspired by your work here to create a section about the Stopwatch integration in the profiler. so, we can close this in favor of #10970. Thanks!

**Pull request closed without merging**
