### PR TITLE
Fixed a broken link to FastCgiExternalServer directive documentation

### LINKED ISSUE #7080: FastCgiExternalServer link dont work
Hello,
in file /setup/web_server_configuration.rst 
the link FastCgiExternalServer is broken.
The link is : http://www.fastcgi.com/mod_fastcgi/docs/mod_fastcgi.html#FastCgiExternalServer
and return 404.

### PR DESCRIPTION
**Pull request by javiereguiluz**
This fixes #7080.

---

The previous official website (`fastcgi.com`) is down and I can't find this doc on the official Apache website. This is the only link that I found.

### CODE REVIEW

**Comment by xabbuh** [comment]
What about linking https://wiki.apache.org/httpd/HelpOnInstalling/FastCgi#FastCgiExternalServer instead?

**Comment by javiereguiluz** [comment]
@xabbuh is that wiki reliable? It doesn't look like an official doc. Besides, it only explains 2 config options, and the Oracle doc explains 6 options and seems to explain things better.

**Comment by wouterj** [comment]
What about http://htmlpreview.github.io/?https://github.com/FastCGI-Archives/mod_fastcgi/blob/master/docs/mod_fastcgi.html#FastCgiExternalServer ? This seems to be the official archive of the page we linked to.

**Comment by javiereguiluz** [comment]
@wouterj the `http://htmlpreview.github.io` website doesn't look very reliable to me and it doesn't look official. I'd go for the URL proposed by Christian or the one Oracle.com one.

**Comment by xabbuh** [comment]
Then let's go with the Oracle one.

**Comment by javiereguiluz** [comment]
Rebased to fix conflicts.

**Review by xabbuh — APPROVED** [review]

**Review by HeahDude — APPROVED** [review]

**Comment by javiereguiluz** [comment]
Closing it in favor of #7791.

**Pull request closed without merging**
