### PR TITLE
[Finder] minor CS fix

### PR DESCRIPTION
**Pull request by dunglas**
| Q | A |
| --- | --- |
| Doc fix? | yes |
| New docs? | no |
| Applies to | all |
| Fixed tickets | n/a |

### CODE REVIEW

**Comment by xabbuh** [comment]
:+1:

**Comment by WouterJ** [comment]
I don't think it's a real CS fix. We use both quotes throughout the source and docs afaik.

**Comment by stof** [comment]
@WouterJ in the code, we use double quotes only when they are necessary to be able to use escape sequences (strings containing ``\n`` most of the time). Otherwise, the rule is to use single quotes everywhere (and PHP-CS-Fixer is fixing it for us in most places)

**Comment by WouterJ** [comment]
Thanks for the correction @stof. Let's merge it then, thanks Kévin!

**Pull request merged**
