### PR TITLE
[Book][Testing] remove Symfony core testing note

### PR DESCRIPTION
**Pull request by xabbuh**

### CODE REVIEW

**Comment by javiereguiluz** [comment]
👍 

Some quick questions: does the PHPUnit wrapper used by Symfony itself affect us here? Should we rewrite everything to forget about the regular PHPUnit and explain instead how to use "the Symfony's PHPUnit" ?

**Comment by xabbuh** [comment]
No, the chapter itself otherwise is fine. Using the PHPUnit wrapper to test your own application is not necessary. We need it for the core to be able to test everything from our code base (as PHPUnit depends on, for example, `symfony/yaml` itself).

**Comment by javiereguiluz** [comment]
OK then.

Status: reviewed.

**Comment by WouterJ** [comment]
Wanted to do this while merging, seems like I forgot. Thanks Christian!

**Pull request merged**
