### PR TITLE
Minor phrasing

### PR DESCRIPTION
**Pull request by shreypuranik**

### CODE REVIEW

**Comment by javiereguiluz** [comment]
I agree that the original wording is not perfectly clear ... but the new proposed wording isn't much better to me. @OskarStark what do you think about this? Thanks.

**Comment by OskarStark** [comment]
I agree with Shrey and with you, what about:

```
- This article
- explains how to create and load those bundle services files.
+ explains how to create and load service files from the bundle directory structure.
```

**Comment by shreypuranik** [comment]
I really like this @OskarStark. Only minor suggestion from me would be: 

- This article explains how to create and load service files from the bundle directory structure.
+ This article explains how to create and load service files using the bundle directory structure.

How is that? //cc @javiereguiluz

**Comment by javiereguiluz** [comment]
Yes, I like the new proposals. The latest from @shreypuranik sound better to me, but both are great. Thank you!

**Comment by shreypuranik** [comment]
Thanks @javiereguiluz . 

@OskarStark  are you happy for me to amend the PR with this re-phrasing?

**Comment by OskarStark** [comment]
> @OskarStark are you happy for me to amend the PR with this re-phrasing?

Yes, thank you 👍

**Comment by shreypuranik** [comment]
Thanks @OskarStark @javiereguiluz . I have updated the Pull Request with the re-phrasing.

**Review by OskarStark — APPROVED** [review]

**Comment by wouterj** [comment]
Thanks a lot for improving the docs and your fast reactions! It's now merged into 4.2, and I'll take care of merging it into the newer versions from there.

**Pull request merged**
