### PR TITLE
Fix composer require doctrine/annotations command.

### PR DESCRIPTION
**Pull request by serundeputy**

### CODE REVIEW

**Comment by javiereguiluz** [comment]
We recently removed most Symfony Flex shortcuts ... but we left some of them on purpose to at least mention them. This is one of those cases. In theory, it should be OK because in a paragraph below everything is explained:

flex-shortcut

But in practice it looks like this is causing some confusion, so we may need to do something about it.

**Comment by serundeputy** [comment]
I guess I don' have Flex.

**Comment by javiereguiluz** [comment]
@serundeputy then the problem will be harder to fix. This article assumes that the reader has created the Symfony project as explained in https://symfony.com/doc/current/setup.html

Could you please tell us which command did you run to create the project? Thanks!

**Comment by serundeputy** [comment]
`composer create-project symfony/website-skeleton mfsa`

**Comment by serundeputy** [comment]
@javiereguiluz I just tried two more times.

```bash
composer create-project symfony/website-skeleton tflex
composer require annotations
```

It worked both times so docs are fine. PEBKATC

**Pull request closed without merging**
