### PR TITLE
[Security] add the `$token` argument to `checkPostAuth()`

### LINKED ISSUE #20062: [Security] pass the current token to the `checkPostAuth()` method of us…
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#57773
| PR author(s) | @xabbuh
| Merged in    | 7.2

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 7.2 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

### PR DESCRIPTION
**Pull request by xabbuh**
fixes #20062

### CODE REVIEW

**Comment by Timherlaud** [comment]
Hello, 

You can add the import of TokenInterface 
```
use Symfony\Component\Security\Core\Authentication\Token\TokenInterface;
```


I think we can add a notice version : 
```
.. versionadded:: 7.2

  The token argument for checkPostAuth function was introduced in Symfony 7.2.

```

And maybe an example of usage in function : 

```
use Symfony\Component\Security\Core\Exception\AccessDeniedException;

if (!\in_array('foo', $token->getRoleNames())) {
                throw new AccessDeniedException('...');
            }

```

**Comment by alamirault** [comment]
@xabbuh Do you have time to apply suggestions ?

(If not I can take care of this)

**Comment by javiereguiluz** [comment]
Thanks Christian!

@Timherlaud while merging I did all the changes that you suggested. Thanks a lot!

Antoine, if you think there's something else that should be documented about this, please create a new PR. Thanks!

**Comment by xabbuh** [comment]
Thank you Javier!

**Pull request merged**
