### PR TITLE
Update multiple_kernels.rst

### PR DESCRIPTION
**Pull request by amine-betari**
Error: Class App\ApiKernel contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (App\ApiKernel::configureRoutes)

N.B :
An abstract method can not contain a body, its presence simply indicates that each non-abstract daughter class will have to redefine this method by respecting its signature.

### CODE REVIEW

**Comment by OskarStark** [comment]
Thanks for your contribution. Can you explain why we should add this? Thanks

**Comment by amine-betari** [comment]
@OskarStark 

Because without the added code, we will have the following error :

Error: Class App\ApiKernel contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (App\ApiKernel::configureRoutes)

N.B : 
An abstract method can not contain a body, its presence simply indicates that each non-abstract daughter class will have to redefine this method by respecting its signature.

**Comment by javiereguiluz** [comment]
@amine-betari thanks for this contribution ... but I'm having some problems trying to understand the change.

In this example, the code extends from `Kernel` (https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/Kernel.php) which doesn't define these methods as abstract. When using the MicroKernelTrait (https://symfony.com/doc/current/configuration/micro_kernel_trait.html) you import the MicroKernelTrait (https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/Kernel/MicroKernelTrait.php) which defines an abstract `configureContainer()` method, but `configureRouting ()` is not abstract.

**Comment by amine-betari** [comment]
Hi @javiereguiluz 

it's normal because your links pointenst to master which is branch 5.0 I think

On the other hand if you check the version by putting 4.3 or 4.4 you will have well the error

https://github.com/symfony/symfony/blob/4.4/src/Symfony/Bundle/FrameworkBundle/Kernel/MicroKernelTrait.php

**Comment by javiereguiluz** [comment]
@amine-betari sorry! You are right.

However, in this article we don't use the MicroKernelTrait but the normal Kernel class, right?

**Comment by amine-betari** [comment]
Hi @javiereguiluz 

For me, you just have to add
use MicroKernelTrait;

also add the configureRoutes method

Why ?

Because if you do not use the **MicroKernelTrait** and extend the Kernel class you will have another problem which is the following one:

Error: Class App\ApiKernel contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Symfony\Component\HttpKernel\KernelInterface::registerContainerConfiguration)

Because the **MicroKernelTrait**  defines the method: **registerContainerConfiguration**


Exemple
`class ApiKernel extends BaseKernel
{
   use MicroKernelTrait;

    private const CONFIG_EXTS = '.{php,xml,yaml,yml}';

    public function registerBundles(): iterable
    {
        $contents = require $this->getProjectDir().'/config/bundles.php';
        foreach ($contents as $class => $envs) {
            if ($envs[$this->environment] ?? $envs['all'] ?? false) {
                yield new $class();
            }
        }
    }

    public function getProjectDir(): string
    {
        return \dirname(__DIR__);
    }

    public function getCacheDir()
    {
        return dirname(__DIR__).'/var/cache/api/'.$this->getEnvironment();
    }

    public function getLogDir()
    {
        return dirname(__DIR__).'/var/log/api';
    }

    protected function configureContainer(ContainerBuilder $container, LoaderInterface $loader): void
    {
        // load only the config files strictly needed for the API
        $confDir = $this->getProjectDir().'/config';
        $loader->load($confDir.'/api/*'.self::CONFIG_EXTS, 'glob');
        if (is_dir($confDir.'/api/'.$this->environment)) {
            $loader->load($confDir.'/api/'.$this->environment.'/**/*'.self::CONFIG_EXTS, 'glob');
        }
        $loader->load($confDir.'/{services}'.self::CONFIG_EXTS, 'glob');
    }


    protected function configureRoutes(RouteCollectionBuilder $routes): void
    {
        $confDir = $this->getProjectDir().'/config';

        $routes->import($confDir.'/{routes}/'.$this->environment.'/**/*'.self::CONFIG_EXTS, '/', 'glob');
        $routes->import($confDir.'/{routes}/*'.self::CONFIG_EXTS, '/', 'glob');
        $routes->import($confDir.'/{routes}'.self::CONFIG_EXTS, '/', 'glob');
    }


}
`

**Comment by OskarStark** [comment]
Close/reopen because Travis was stuck

**Comment by amine-betari** [comment]
@ostark @javiereguiluz  any news ?

**Comment by amine-betari** [comment]
@ostark  @javiereguiluz  any news please ?

**Comment by ostark** [comment]
FYI @amine-betari you used the wrong handle, I'm not Oskar.

**Comment by OskarStark** [comment]
It’s me 😊

I am currently on a phone 📱 but will have a look later

**Comment by HeahDude** [comment]
@amine-betari, thank you for working on this. I agree we should update the example to use the `MicroKernelTrait` instead.

But I propose the following changes:
```php
public function registerBundles(): iterable
{
    $contents = require $this->getProjectDir().'/config/api_bundles.php';
    // ...
}

// ...

protected function configureContainer(ContainerBuilder $container, LoaderInterface $loader): void
    {
        $container->addResource(new FileResource($this->getProjectDir().'/config/api_bundles.php'));
        $container->setParameter('container.dumper.inline_factories', true);
        $confDir = $this->getProjectDir().'/config/api';

        $loader->load($confDir.'/{packages}/*'.self::CONFIG_EXTS, 'glob');
        $loader->load($confDir.'/{packages}/'.$this->environment.'/*'.self::CONFIG_EXTS, 'glob');
        $loader->load($confDir.'/{services}'.self::CONFIG_EXTS, 'glob');
        $loader->load($confDir.'/{services}_'.$this->environment.self::CONFIG_EXTS, 'glob');
    }

protected function configureRoutes(RouteCollectionBuilder $routes): void
{
    $confDir = $this->getProjectDir().'/config/api';
    // load specific api routes
}
```

We could even add the routes configuration since we fully implement `configureContainer`, for completeness?

**Comment by wouterj** [comment]
Hi @amine-betari! Do you have any time/motivation to finish this PR based on the comments by @HeahDude? 

(please also explicitly add `use MicroKernelTrait;` to the example, to make it clear that the example is based on the micro kernel)

**Comment by amine-betari** [comment]
@wouterj 
I'll do this ASAP (this week).   We like community so we're ready to give our time :)

**Comment by amine-betari** [comment]
> FYI @amine-betari you used the wrong handle, I'm not Oskar.

Sorry man :)

**Comment by amine-betari** [comment]
@wouterj   done :)

**Comment by wouterj** [comment]
Thank you Amine! Fyi, I've tweaked the diff slightly during the merge.

**Pull request merged**
