### PR TITLE
Change setException to setError

### PR DESCRIPTION
**Pull request by Landerstraeten**
#SymfonyConHackDay2018

### CODE REVIEW

**Comment by Landerstraeten** [comment]
Thank you @kunicmarko20. After validating my own pr I saw:

- The code example for `ConsoleExceptionEvent` is correct in 3.4
- The is no code example for `ConsoleErrorEvent` since it's an improved version of the `ConsoleEvents::EXCEPTION` event
- The class `ConsoleExceptionEvent` does not exist anymore in 4.1
- The code example for `ConsoleErrorEvent` is wrong for 4.1. Fixed **in this PR**
- The code example for `ConsoleErrorEvent` is wrong for 4.2. But should be fixed if 4.1 is merged into 4.2
- The code example for `ConsoleErrorEvent` is wrong for 4.3. But should be fixed if 4.1 is merged into 4.3

**Comment by Landerstraeten** [comment]
@javiereguiluz what do you suggest?

**Comment by stof** [comment]
The 3.4 doc should indeed be updated to showcase the non-deprecated version of it.

**Comment by javiereguiluz** [comment]
@Landerstraeten thanks for improving 3.4 code and fixing the other branches code (we'll do that when merging this into 4.1 and higher). Also, congrats on your first Symfony dDocs contribution!

**Pull request merged**
