### PR TITLE
Fixes deprecated ProcessBuilder usage

### PR DESCRIPTION
**Pull request by guillbdx**

### CODE REVIEW

**Comment by Simperfit** [comment]
This one is not needed, the documentation team will take care of merging the 3.4 branch in the 4.0 and master branch ;). 


Thanks for the contribution anyway!

**Comment by xabbuh** [comment]
@guillbdx Thank you for the PR, but as @Simperfit said we regularly merge branches up. :)

**Comment by javiereguiluz** [comment]
@guillbdx thanks for your contribution! As others said, we regularly merge changes from lower to upper branches until we reach `master`, so this shouldn't be needed.

But I can't remember a recent pull request that made these changes and was merged in lower branches ... so this may be a problem that won't be fixed waiting for the upper branches merges. I'm reopening so we can look closely at this. Thanks!

**Comment by Simperfit** [comment]
There is a open PR with the sames change targeting 3.4
Le mar. 6 mars 2018 à 11:26, Javier Eguiluz <notifications@github.com> a
écrit :

**Pull request closed without merging**
