### PR TITLE
Fixed yaml configuration of app.exception_controller

### PR DESCRIPTION
**Pull request by a-ast**
| Q | A |
| --- | --- |
| Doc fix? | yes |
| New docs? | no |
| Applies to | 2.3+ |
| Fixed tickets | - |

Fixed yaml code-block for app.exception_controller service: indented lines with 'class' and 'arguments' configuration to make this example functional.

### CODE REVIEW

**Comment by xabbuh** [comment]
Good catch @AAstakhov! Actually, we usually use four spaces to indent YAML config examples. Do you want to change that here too (we can do that during merging otherwise).

**Comment by javiereguiluz** [comment]
:+1: thanks @AAstakhov

**Comment by AAstakhov** [comment]
Hi, @xabbuh, I hope this time I did it correctly using github online editor.

BTW, I'd like to contribute more to docs. Where is the right place to ask and discuss some ideas? IRC?

**Comment by xabbuh** [comment]
Perfect! :+1: 

You can best ask questions here on GitHub or join us on IRC in #symfony-docs.

**Comment by WouterJ** [comment]
Thanks @AAstakhov, it's looking perfect now. I've just merged your fix into the documentation.

It's good to hear you want to help with the documentation! We discuss all things in the issue tracker on GitHub: http://github.com/symfony/symfony-docs/issues If you have any question or want to discuss something, you can create a new issue. You can also join us at #symfony-docs on IRC (it's not active, but most of the time xabbuh or me are in there).

**Comment by AAstakhov** [comment]
Explain me pls. My fix was applied to 2.3 but not to other versions (e.g. not to 3.0). Should I do something to fix it everywhere?

**Comment by theofidry** [comment]
@AAstakhov IIRC everything is merged back to older versions afterwards, but not immediately.

**Comment by WouterJ** [comment]
@AAstakhov  we always merge fixes into the oldest maintained branch that they apply to. Then we merge branches from oldest to the newest every so often. In this case, I only merged a couple PRs and didn't merge everything up.

**Pull request closed without merging**
