### PR TITLE
Update example for method requirements

### PR DESCRIPTION
**Pull request by carlos-granados**
The example was not doing what the text said it did, as it did not have two routes with the same url but different methods. Updated all four examples (annotations, yaml, xml and php)

### CODE REVIEW

**Comment by OskarStark** [comment]
This is a duplicate, a PR with this code change already exists... let me have a look....

**Comment by OskarStark** [comment]
It has something in common with #5201, but in a reverse way :smile:

**Comment by carlos-granados** [comment]
OK, I see that in 2.3 this was changed from something similar to what I am suggesting to the current example. I see in the comments of that PR that this was done to give an example of a route that accepted several methods. I agree this is OK, but then you would need to change the text associated with this example, because what it describes is not what you see in the example. Let me try to change the text so that the explanation and the example say the same thing and I will submit a new commit

**Comment by carlos-granados** [comment]
Probably I will better send a new PR, I am closing this one

**Pull request closed without merging**
