### PR TITLE
Cache Component: Fix SQLite3Cache instanciation

### PR DESCRIPTION
**Pull request by ReDnAxE**
My first small contribution ^^
`new SQLite3Cache()` instead of `new SQLite3()` according to the use statement

### CODE REVIEW

**Comment by WouterJ** [comment]
👍 Looks completely valid to me: https://github.com/doctrine/cache/blob/master/lib/Doctrine/Common/Cache/SQLite3Cache.php

Thanks for submitting the fix and congratz with your first contribution! (it looks perfect)

Status: reviewed

**Comment by javiereguiluz** [comment]
👍 nice catch! Thanks @ReDnAxE.

**Comment by WouterJ** [comment]
Thanks again @ReDnAxE! Your first contribution has now made it in the repository. I hope to see you back with more contributions!

**Comment by ReDnAxE** [comment]
Thank you @WouterJ and @javiereguiluz for your review, yes I hope also :)

**Pull request merged**
