### PR TITLE
Simplified the Quick tour explanation about Symfony Installation

### PR DESCRIPTION
**Pull request by javiereguiluz**
| Q | A |
| --- | --- |
| Doc fix? | yes |
| New docs? | no |
| Applies to | all |
| Fixed tickets | - |

### CODE REVIEW

**Comment by DQNEO** [comment]
:+1:

**Comment by OskarStark** [comment]
:+1:

**Comment by WouterJ** [comment]
@javiereguiluz can you please rebase?

**Comment by javiereguiluz** [comment]
Rebased.

**Comment by WouterJ** [comment]
Looks like this one is ready. :+1:

**Comment by xabbuh** [comment]
:+1:

**Comment by WouterJ** [comment]
Great job, thanks Javier! I've patched this into 2.3

**Pull request closed without merging**
