### PR TITLE
Add a note on "--no-plugins" Composer option effects on runtime component

### PR DESCRIPTION
**Pull request by andrea-cristaudo**

### CODE REVIEW

**Comment by IonBazan** [comment]
I think you should rebase your commit onto `4.4` and target that branch too. Currently your PR contains changes from `5.4` and targets `5.3` which is incorrect.

```
git checkout 4.4
git cherry-pick 8bc6ed9
git push origin 4.4:patch-1 -f 
```

**Comment by andrea-cristaudo** [comment]
> I think you should rebase your commit onto `4.4` and target that branch too. Currently your PR contains changes from `5.4` and targets `5.3` which is incorrect.
> 
> ```
> git checkout 4.4
> git cherry-pick 8bc6ed9
> git push origin 4.4:patch-1 -f 
> ```

Thanks.
Since symfony/runtime is a 5.3 new component I thought 5.3 was the right target branch.

**Comment by IonBazan** [comment]
Sorry, you're right, should be 5.3!

**Comment by javiereguiluz** [comment]
Thanks Andrea! This is now merged.

**Pull request merged**
