### PR TITLE
removed squashing stuff. fixes #5368

### PR DESCRIPTION
**Pull request by OskarStark**
added explanation, why it is no longer necessary

### CODE REVIEW

**Comment by WouterJ** [comment]
:+1: Ready imo

**Comment by OskarStark** [comment]
ping

@javiereguiluz @xabbuh @stof

**Comment by javiereguiluz** [comment]
:+1: it looks OK to me.

@OskarStark thanks for this. I'm sure that this will be merged soon. Stay tuned!

**Comment by WouterJ** [comment]
Another try, hopefully I'll merge the correct PR now. I've reverted the previous wrong merge. Thanks again!

**Comment by OskarStark** [comment]
great :smile:

**Pull request closed without merging**
