### PR TITLE
change line

### PR DESCRIPTION
**Pull request by fialean**
not executed the command without assignment symbol

### CODE REVIEW

**Comment by WouterJ** [comment]
That's really weird, as it should be handled perfectly without `=`, as shown in http://symfony.com/doc/current/components/console/console_arguments.html

**Comment by xabbuh** [comment]
@fialean Did you get any error messages when executing the command without the equals sign?

**Comment by OskarStark** [comment]
both versions work for me:
bildschirmfoto 2015-08-11 um 12 10 24

IMO i would not merge this PR

**Comment by OskarStark** [comment]
@fialean which OS are you running?

**Comment by xabbuh** [comment]
@fialean I'm closing here as I think this isn't a bug. But please feel free to provide more information if you don't agree.

**Pull request closed without merging**
