### PR TITLE
Missing dev settings

### PR DESCRIPTION
**Pull request by todstoychev**
The settings are missing in the case when you plan to use AsseticBundle in dev environment.

### CODE REVIEW

**Comment by xabbuh** [comment]
I haven't used Assetic in a while so I might be mistaken. But hostly I fail to see why this change is necessary.

**Comment by todstoychev** [comment]
If try to use Assetic in development it fails. It is good to see how 
this is working on development. So I think there should be a section 
with the necessary settings for Assetic in dev, since it fails on dev 
when you installed it in the normal way.

**Comment by javiereguiluz** [comment]
I'm not sure about this change either. I use Assetic and I don't need to add that to `routing_dev.yml`. @todstoychev which error do you get when you don't add that config? Thanks!

**Comment by todstoychev** [comment]
It can not reconize the {%stylesheets %}. The twig raises an that he doesnt know
how to handle this command.

Sent using CloudMagic Email
[https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.1.32&pv=4.4.4&source=email_footer_2] On вт, март 01, 2016 at 11:25 PM, Javier Eguiluz < notifications@github.com [notifications@github.com] > wrote:
I'm not sure about this change either. I use Assetic and I don't need to add
that to routing_dev.yml . @todstoychev [https://github.com/todstoychev] which error do you get when you don't add that config? Thanks!

—
Reply to this email directly or view it on GitHub
[https://github.com/symfony/symfony-docs/pull/6312#issuecomment-190912103] .[https://github.com/notifications/beacon/AESmG63G_quVcSryEGk7y2Ye-lYHzO8Oks5ppK7kgaJpZM4HlyDG.gif]

**Comment by todstoychev** [comment]
The twig raises an error that can not recognize the command for including
stylesheets. If i do not forgot will try to reproduce it in the next few days
and send you the exact response.

Sent using CloudMagic Email
[https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.1.32&pv=4.4.4&source=email_footer_2] On вт, март 01, 2016 at 11:41 PM, Admin < todstoychev@gmail.com [todstoychev@gmail.com] > wrote:
It can not reconize the {%stylesheets %}. The twig raises an that he doesnt know
how to handle this command.

Sent using CloudMagic Email
[https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.1.32&pv=4.4.4&source=email_footer_2] On вт, март 01, 2016 at 11:25 PM, Javier Eguiluz < notifications@github.com [notifications@github.com] > wrote:
I'm not sure about this change either. I use Assetic and I don't need to add
that to routing_dev.yml . @todstoychev [https://github.com/todstoychev] which error do you get when you don't add that config? Thanks!

—
Reply to this email directly or view it on GitHub
[https://github.com/symfony/symfony-docs/pull/6312#issuecomment-190912103] .[https://github.com/notifications/beacon/AESmG63G_quVcSryEGk7y2Ye-lYHzO8Oks5ppK7kgaJpZM4HlyDG.gif]

**Comment by WouterJ** [comment]
IIRC, this change is needed when using the controller in development (rather than dumping the assets).

This code was included by default, but removed now Assetic was removed from the SE. I think it makes sense to include it. However, we should not say it's for development, as it's just when setting `assetic.use_controller` to `true` in your configuration.

**Comment by todstoychev** [comment]
Hm, very strange... I tried to reproduce this one at the weekend and it 
seems to work now with no problems. I suspect that it was an problem 
with the caching or something. I am sure that I have this error for not 
recognized tag in Twig... So anyway... This can be closed.

**Comment by xabbuh** [comment]
Thank you for the confirmation @todstoychev. Anyway, if you can ever reproduce your initial issue, feel free to come back to us and give us some steps to reproduce it so that we can improve the documentation accordingly.

**Comment by todstoychev** [comment]
Thanx guys! If something pops up will inform you.

  

> On Mar 7 2016, at 11:18 am, Christian Flothmann
&lt;notifications@github.com&gt; wrote:  

>

> Thank you for the confirmation
[@todstoychev](https://github.com/todstoychev). Anyway, if you can ever
reproduce your initial issue, feel free to come back to us and give us some
steps to reproduce it so that we can improve the documentation accordingly.

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/symfony
/symfony-docs/pull/6312#issuecomment-193174343).

**Pull request closed without merging**
