### PR TITLE
Fixed the YAML syntax for service references

### PR DESCRIPTION
**Pull request by javiereguiluz**
| Q | A |
| --- | --- |
| Doc fix? | yes |
| New docs? | no |
| Applies to | all |
| Fixed tickets | - |

See https://github.com/symfony/symfony/pull/16285 and https://github.com/symfony/symfony/pull/16353 for context. I've just found two issues, but it's possible that this syntax is used in more places.

### CODE REVIEW

**Comment by WouterJ** [comment]
Please use double quotes, as that's the standard we use in the docs (not sure why, but let's not confuse users).

**Comment by javiereguiluz** [comment]
Fixed. Thanks

**Comment by WouterJ** [comment]
:+1:

**Comment by xabbuh** [comment]
Thank you @javiereguiluz.

**Pull request closed without merging**
