### PR TITLE
Update migration.rst

### PR DESCRIPTION
**Pull request by gpetraroli**
Change return type of handleRequest to void

### CODE REVIEW

**Comment by OskarStark** [comment]
Should target 5.4 branch, right?

**Comment by gpetraroli** [comment]
Only 6.3 doc is concerned I think

**Review by artyuum — APPROVED** [review]

**Comment by artyuum** [comment]
@gpetraroli there is another type error here (in case you want to fix that as well), the function return type is set as `string` but it's not returning anything:
https://github.com/symfony/symfony-docs/blob/b3d1030ff27376bdfc06841557280791e2e70bfd/migration.rst?plain=1#L463-L473

**Comment by gpetraroli** [comment]
Thank you, I will

**Review by artyuum — APPROVED** [review]

**Review by xabbuh — APPROVED** [review]

**Review by alamirault — APPROVED** [review]

**Comment by javiereguiluz** [comment]
Thanks Giuseppe and congrats on your first Symfony Docs contribution 🎉

**Pull request merged**
