### PR TITLE
adds info string hex literals and unicode

### PR DESCRIPTION
**Pull request by dimkir**
Adds info on how to put special characters into string using hex and how to insert Unicode characters using their unicode codepoint.

### CODE REVIEW

**Comment by javiereguiluz** [comment]
I have mixed feelings about this proposal. Your explanation makes a lot of sense for examples like `I ♥ Symfony` but I find it confusing for the white space and the `ñ` example. My concern is that some users may interpret this wrong and think that instead of optional, it's mandatory to encode chars like the white space.

**Comment by dimkir** [comment]
@javiereguiluz you're right, my initial problem was to put a unicode codepoint into YAML, so this what caused me to write this addition. The hex-example I only added as preamble. Would you believe that removing hex-part and just leaving unicode would be a better option?

**Comment by javiereguiluz** [comment]
@dimkir yes I do. Your second paragraph is lovely. The only thing I may add is a very short explanation of the problem that you are solving. This is a very informal version of the explanation I'm proposing: "You can put *I ♥ Symfony* in your YAML and everything will work. But this is super risky because some of your servers may loose that information because it doesn't support those characters. Better be safe by encoding those risky Unicode chars."

**Comment by dimkir** [comment]
@javiereguiluz after your suggestions here's what I propose:

I can create a new pull request with this text.

----
[remove the hex part]

Unicode character insertion is also simple. To create string ``"I ♥ Symfony"`` which uses unicode character ``"♥"`` - "black  heart suit" with unicode codepoint ``\U+2665`` there are two options:

  * Simply put ``"I ♥ Symfony"`` in your YAML and everything will work. But this is super risky because some of your servers may not support these characters
  * To be safe - insert unicode chars using their codepoint - ``"I \U00002665 Symfony"``
(mind that the unicode codepoint must be represented by 8 zero-padded hex digits, otherwise it will not work).

---

**Comment by javiereguiluz** [comment]
@dimkir you can make the changes in this very same pull request, so there is no need to create a new one :)

Regarding the new contents ... I'm not happy with some parts (e.g. "super risky") because as a I told you, it's very informal. Anyway, it's just a matter of rewording it a bit. Let's ask our doc managers (@xabbuh and @WouterJ) to help us with this. Thanks!

**Comment by xabbuh** [comment]
Actually, I am not sure if I understand what you mean with "some of your servers may not support these characters". What do you mean with it? Did you make any bad experiences with it?

**Comment by javiereguiluz** [comment]
@xabbuh instead of servers, I mean *"pieces of software that may process/manipulate your code in any way between your computer and the end-user"*. It can be the web server, the script that copies the code your code to production server, etc. If any software in the middle doesn't support UTF-8 right or mangles these "strange characters", you'll lose information. I suffered this problems in the past, but honestly I didn't suffer them recently.

**Comment by xabbuh** [comment]
Well, in those cases I assume that you will get lots of other issues too and you should rather fix your toolchain then work around that. My concern with this change simply is that people might thing they should always use unicode sequences to be on the safe sight which soon leads to unreadable files.

**Comment by dimkir** [comment]
Well my best guess would be that on some (legacy?) systems, where default
locale is not set to be UTF8, in case you operate with the file via console
(cat|grep|nano) it may show garbage or incorrectly resave the file. I guess
modern systems (I checked my ubuntu 14.04 and my locale is
`LANG=en_IE.UTF-8` so once it is utf it should work fine).

Another case I can image may be when someone uses misconfigured `putty` to
ssh into instance and tries to edit config files directly, he may not be
shown the character correctly and maybe even byte by byte and thus may
corupt it.
HTH

**Comment by javiereguiluz** [comment]
What if we reword this a bit and say something like:

```
If you have any problem storing Unicode characters in YAML files (because some
legacy system doesn't support them) you can encode these characters. Just replace
the Unicode char with its zero-padded 8-byte codepoint. For example, `I ♥ Symfony`
can be encoded as `I \U00002665 Symfony` because `♥` char is `\U+2665` and the
zero-padded codepoint is `\U00002665`.
```

**Comment by xabbuh** [comment]
I still would not add this. If storing YAML files does not work properly, what happens with other data you need to handle and you cannot control? What if Symfony at some point dumped YAML? You would have no control about the data being dumped and your application would probably fail with errors that are maybe not so easy to solve or for which it is hard to find the cause. I really do not think we should educate people how to work around badly configured systems, but rather help them getting their environments configured properly.

**Comment by javiereguiluz** [comment]
@xabbuh if we don't add this ... what should we add instead to "educate" (or "warn") our users about configuring things properly? Thanks!

**Comment by xabbuh** [comment]
Honestly, I don't think we should do anything about that. It's not the job of the Symfony documentation to explain all the pitfalls that there are when it comes to properly configuring your server. There are dedicated resources that one should refer to. And configuring your server to properly handle UTF-8 nowadays is no rocket science.

**Comment by javiereguiluz** [comment]
Let's close it then. Thanks!

@dimkir I'm sorry this time your contribution didn't make it.

**Pull request closed without merging**
