### PR TITLE
Order takes one argument, 'allow,deny', 'deny,allow', or 'mutual-failure...

### PR DESCRIPTION
**Pull request by fpondepeyre**
| Q | A |
| --- | --- |
| Doc fix? | yes |
| New docs? | no |

Syntax error : order takes one argument, 'allow,deny', 'deny,allow', or 'mutual-failure'

### CODE REVIEW

**Comment by xabbuh** [comment]
:+1: good catch @fpondepeyre

**Comment by xabbuh** [comment]
@fpondepeyre In https://github.com/symfony/symfony-docs/pull/5203#issuecomment-95196061 it was suggested to uppercase the option value to.Will you be able to make this change?

**Comment by xabbuh** [comment]
ping @fpondepeyre

**Comment by WouterJ** [comment]
I'm closing this PR in favor of #5203. It was just a little more complete and because we get a lot of bug fixes about this problem, I want to fix this bug as quick as possible.

Anyway, thanks for noticing and fixing this bug @fpondepeyre!

**Pull request closed without merging**
