### PR TITLE
[DX] [Security] Renamed key to secret

### PR DESCRIPTION
**Pull request by SongoQ**
| Q | A |
| --- | --- |
| Doc fix? | no |
| New docs? | yes symfony/symfony#15141 |
| Applies to | 2.8+ |
| Fixed tickets | n/a |

### CODE REVIEW

**Comment by xabbuh** [comment]
:+1: Thank you for this change @SongoQ.

Could you please check if we could update other files too?

**Comment by SongoQ** [comment]
@xabbuh ok :)

**Comment by SongoQ** [comment]
@xabbuh I checked and corrected all files

**Comment by xabbuh** [comment]
:+1: looks good

I am just wondering if we should also mention that the name of the option has changed (for users who upgrade existing applications).

@weaverryan @WouterJ @javiereguiluz What do you think?

**Comment by WouterJ** [comment]
:+1: for merging this PR and adding a versionadded afterwards (or add it in this PR, if @SongoQ wants to do it).

**Comment by xabbuh** [comment]
Thank you for the perfect pull request @SongoQ. I have merged it and added the `versionadded` directive in 6e8d5fc.

**Pull request merged**
