### PR TITLE
Use HTTPS links when possible

### PR DESCRIPTION
**Pull request by stof**

### CODE REVIEW

**Review by OskarStark — APPROVED** [review]
Great work, thanks @stof 👍

**Comment by OskarStark** [comment]
Thank you @stof.

**Comment by OskarStark** [comment]
I upmerged up to 6.3

**Comment by stof** [comment]
I checked the 6.2 and 6.3 branches after the upmerge, and I'm happy to report that there is no additional URLs to upgrade to HTTPS in those branches.

**Comment by OskarStark** [comment]
Thanks for double checking 👍 🚀

**Pull request merged**
