### PR TITLE
Rename content_type header to content-type

### PR DESCRIPTION
**Pull request by ottaviano**

### CODE REVIEW

**Review by javiereguiluz — APPROVED** [review]
Nice! I think we should do this.

I'm not entirely sure about adding the comment about underscored HTTP headers. @xabbuh do you think we should add it ... or better remove it to lower our readers' cognitive load? Thanks!

**Review by kunicmarko20 — COMMENTED** [review]
I think the comment is not needed, it could confuse people.

**Comment by ottaviano** [comment]
agree, will remove it

**Review by kunicmarko20 — APPROVED** [review]

**Review by xabbuh — APPROVED** [review]

**Comment by xabbuh** [comment]
Thank you @ottaviano.

**Pull request closed without merging**
