### PR TITLE
[Security] Firewall context stateless tip

### PR DESCRIPTION
**Pull request by geoffrey-brier**
I recently faced this situation.
Only took me a few minutes to find out why but IMO it's worth adding a note ;)

### CODE REVIEW

**Review by javiereguiluz — APPROVED** [review]
:+1:

**Comment by javiereguiluz** [comment]
Thinking about this help note, don't you think this is a Symfony bug? If the "context" option only works when doing some things, shouldn't Symfony check if you have done those things and warn you if you haven't?

**Comment by geoffrey-brier** [comment]
@javiereguiluz Not sure if it's a bug but that may be a good idea to check that.

**Comment by xabbuh** [comment]
Thank you @geoffrey-brier.

**Pull request merged**
