### PR TITLE
Use AppBundle instead of AcmeDemoBundle for consistency

### PR DESCRIPTION
**Pull request by snamor**

### CODE REVIEW

**Comment by stof** [comment]
:+1:

**Comment by xabbuh** [comment]
Nice catch @snamor. :+1:

**Comment by snamor** [comment]
Thanks! Read the book 3 times and this is the first time I see this... I'll notify if I find more typos :)

**Comment by Rvanlaak** [comment]
Will the plan be to get rid of all Acme occurences? Found a lot more of them ;)

https://github.com/symfony/symfony-docs/search?utf8=%E2%9C%93&q=Acme

**Comment by javiereguiluz** [comment]
@Rvanlaak some uses of the `Acme` vendor may be legitimate. We must evaluate them on a case by case basis. In any case, one thing we don't want is a massive PR which makes thousands of small changes across documentation. That kind of PR really complicates the work of our dear doc maintainers.

**Comment by Rvanlaak** [comment]
You're right :+1: maybe this is something for the 3.0 branch?

**Comment by stof** [comment]
@Rvanlaak doing it only for the 3.0 branch is even worse for maintenance because it will make it impossible to merge branches together.

The right way to handle this is to send a PR updating 1 chapter (and making sure there is no pending PR doing it already). And it is easier to start with chapters which don't have a pending PR (no conflict for them). However, for such task, it is better to ask the doc maintainers first to know their plan (they might want to update some parts first for instance)

**Comment by weaverryan** [comment]
Yea, wow - great catch @snamor! And yea, we're working through the sections one-by-one. There's nothing wrong with something like AcmeDemoBundle, so we're migrating a section at a time. Keeping individual sections accurate and consistent is the key :). But of course, if someone finds an entry that doesn't use AppBundle and wants to change all the occurrences in that entry, that's a *huge* help! Cheers!

**Pull request merged**
