### PR TITLE
Simplify example of GulpBusterVersionStrategy

### PR DESCRIPTION
**Pull request by bocharsky-bw**
It seems we can simplify the code in `applyVersion()` or am I missing something?

Link to the related docs page:
https://symfony.com/doc/current/frontend/custom_version_strategy.html

### CODE REVIEW

**Comment by javiereguiluz** [comment]
I don't know if both codes are equivalent in all cases ... but I think they are both wrong in the following case:

```php
$format = '/%s/%s';
$path = '/foo';
$version = '3';

// Old code:
$versionized = '/foo/3';
return: '//foo/3'

// New code:
return: '//foo/3'
```

**Comment by bocharsky-bw** [comment]
But you're using a different format `/%s/%s`. In this example, the default format is `%s?%s`, and the format we're using is `%s?version=%s`.  If you expect a URL like `/foo/3` - you need to use `%s/%s` format instead and the example will still work.

As I understand, this `GulpBusterVersionStrategy` is nothing more like just take some given path (and we expect the given path is correct, i.e. devs should care about what path to give `/foo/bar` or `foo/bar`) and adds a version of assets to it. I would not expect from this class that it adds the leading slash for me. Or it should always make sure the leading slash exist?

**Review by javiereguiluz — APPROVED** [review]
Victor, you are right. I didn't check the entire article. I agree that the format used in this example allows to make this refactorization 👍

**Comment by bocharsky-bw** [comment]
OK, perfect. Thanks for the review, Javier!

**Comment by OskarStark** [comment]
Thank you Victor.

**Pull request merged**
