### PR TITLE
Fixed the explanation about PHPUnit event listeners in PHPUnitBridge

### LINKED ISSUE #7411: PHPUnit Bridge does not register the PHPUnit event listener automatically
The [PHPUnit Bridge documentation](http://symfony.com/doc/master/components/phpunit_bridge.html) says *“Once the component installed, it automatically registers a PHPUnit event listener which in turn registers a PHP error handler”*.

This didn’t work for me, the error handler gets registered via the bootstrap.php file, but I had to register the PHPUnit event listener in the phpunit.xml file in order to get the `@expectedDeprecation` annotations working:

```xml
<listeners>
    <listener class="Symfony\Bridge\PhpUnit\SymfonyTestsListener" />
</listeners>
```

### PR DESCRIPTION
**Pull request by javiereguiluz**
This fixes #7411.

@nicolas-grekas if you have some time, please review this change. Thanks!

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
I don't know what causes the linked issue, but the listener *is* registered automatically, that the job of this logic:
https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/PhpUnit/TextUI/TestRunner.php

**Comment by xabbuh** [comment]
@nicolas-grekas That only happens when you use the `simple-phpunit` wrapper script but not when using PHPUnit directly, right?

**Comment by nicolas-grekas** [comment]
Indeed

**Comment by xabbuh** [comment]
@javiereguiluz I think we can point it out that you only need to adapt your config if you do not want to make use of the wrapper script.

**Comment by javiereguiluz** [comment]
Thanks for your help and comments. I've reworded this.

**Review by xabbuh — APPROVED** [review]

**Review by nicolas-grekas — APPROVED** [review]

**Comment by xabbuh** [comment]
Thank you Javier.

**Pull request closed without merging**
