### PR TITLE
fix link to `ChainAdapter::prune` method

### PR DESCRIPTION
**Pull request by pableu**
The link doesn't work otherwise.

### CODE REVIEW

**Review by maxhelias — APPROVED** [review]
Should be in 3.4

**Comment by pableu** [comment]
Should I make the PR against another branch?

**Comment by maxhelias** [comment]
No this can be changed during the merge

**Review by xabbuh — APPROVED** [review]

**Comment by javiereguiluz** [comment]
Merged in 3.4! Thanks Pablo.

**Pull request merged**
