### PR TITLE
Update registration_form.rst

### PR DESCRIPTION
**Pull request by mchahed99**
Fixed minor errors.

### CODE REVIEW

**Review by kunicmarko20 — APPROVED** [review]
Thanks @beamop and congrats on your first contribution!

**Comment by beamop** [comment]
Thanks @kunicmarko20!

**Review by xabbuh — APPROVED** [review]

**Comment by javiereguiluz** [comment]
@beamop super nice first contribution to Symfony Docs! Thanks a lot and congrats! (Note: we merged this into 3.4 branch; that's why GitHub shows it as closed instead of merged ... but it's merged).

**Comment by beamop** [comment]
Ok thanks @javiereguiluz!

**Pull request closed without merging**
