### PR TITLE
14448 - Document http_codes supports passing methods

### PR DESCRIPTION
**Pull request by JohJohan**

### CODE REVIEW

**Comment by JohJohan** [comment]
If everthing is okay could you add label `hacktoberfest-accepted`? I am participating https://hacktoberfest.digitalocean.com/details

**Comment by javiereguiluz** [comment]
@JohJohan there's no need for that label because the entire Symfony Docs repo is labeled with the Hacktoberfest label. See https://hacktoberfest.digitalocean.com/details#details

**Comment by jderusse** [comment]
Duplicate of #14449

**Comment by javiereguiluz** [comment]
Johan, we're really sorry but this pull request was a duplicate of another one which was merged. We're looking forward to other contributions from you so we can merge them and help you in your Hacktoberfest efforts. Thanks for understanding!

**Pull request closed without merging**
