### PR TITLE
Update event_listeners_subscribers.rst

### PR DESCRIPTION
**Pull request by hamzahanafi11**
By using $args->getEntity() you can have access to the generated id (primary key) of the object

### CODE REVIEW

**Comment by weaverryan** [comment]
That's a great idea! Both methods do the same thing, but this is indeed more expressive to me.

Further up, we also use `getObjectManager()`. Could you change that `getEntityManager()`?

**Comment by weaverryan** [comment]
Status: Needs work

**Comment by hamzahanafi11** [comment]
@weaverryan changes done, I also edited the one inside the function named `index()`
I think these changes must be done for all symfony versions not only `symfony:3.3`

**Comment by weaverryan** [comment]
You're right! I've merged this into 2.7 (and we'll merge up to the other branches). Thank you @hamzahanafi11!

**Pull request closed without merging**
