### PR TITLE
Warning about zombie child processes

### PR DESCRIPTION
**Pull request by hgiesenow**

### CODE REVIEW

**Comment by javiereguiluz** [comment]
@kuborgh-hgiesenow thanks for sending this pull request. Before considering it for merging, we need you to make two small changes in its syntax:

1) Code should be encoded with two pairs of backticks instead of just one (as in Markdown):

```
`$process->isRunning()`  --> ``$process->isRunning()``
```

2) The content lines must be broken at the 80th character to prevent long lines which are difficult to read. In this case, please break your content in two lines.

**Comment by WouterJ** [comment]
(2) in @javiereguiluz's list is a little bit incorrect, you need to add a line break after the first word that passes the 72th character.

**Comment by kuborgh-hgiesenow** [comment]
Changes are applied. The lines are now not longer than 80 characters. Do I really need to break the sentence for the last word to keep it under 80 characters?

**Comment by OskarStark** [comment]
thank you @kuborgh-hgiesenow

**Comment by xabbuh** [comment]
I honestly don't understand this change. Isn't it exactly the task of the `wait()` method to properly clean up child processes? Why should I also execute `isProcessRunning()` afterwards?

**Comment by xabbuh** [comment]
ping @kuborgh-hgiesenow Can you provide some more insights here?

**Comment by kuborgh-hgiesenow** [comment]
In my case there is a long running script and i want to do async processing. As i spawn lots of child processes, there is no point i can wait for a single child.

**Comment by xabbuh** [comment]
Well, you can store references to all child processes in an array and call `wait()` on each child process at the end of your script (you would also have to keep references to the child processes if you were to call `isProcessRunning()` at the end).

**Comment by kuborgh-hgiesenow** [comment]
The script is an endless loop, so there is no end, where to call wait(). That's also the main problem with zombies, as they are stacking up until the server runs out of PIDs.
The isRunning() call is very useful, as it can be done periodically in the main loop.

**Comment by xabbuh** [comment]
Well, I think that use case is a bit special. I am fine with adding a note for such a use case but imho this should not be a general recommendation.

**Comment by WouterJ** [comment]
I agree with @xabbuh here. It seems like a very special case, to specific to document in a generic way. For now, I'm closing this. Feel free to leave a comment if you still think it should be documnted.

Thank you for proposing this change and explaining why it is needed.

**Pull request closed without merging**
