### PR TITLE
[FormType] Add help_attr documentation 

### PR DESCRIPTION
**Pull request by mpiot**
Add documentation about the new feature symfony/symfony#27043

### CODE REVIEW

**Comment by javiereguiluz** [comment]
@mpiot thanks for another nice contribution! In fb22ceff61c7fec413597a4661fd019a5622cbbc we made a minor reword and removed the PHP template example, because we no longer want to show PHP templates and we've removed most of them (and we'll remove all of them soon). Thanks!

**Comment by mpiot** [comment]
@javiereguiluz Your welcome :-) Ok, I note that for the next time :)

**Comment by mpiot** [comment]
@javiereguiluz I've seen your reword, and there is a typo. This is my typo, but I've just see that when I've read your commit... I've write:

    'label_attr': {'class': 'CUSTOM_LABEL_CLASS'}

in place of

    'help_attr': {'class': 'CUSTOM_LABEL_CLASS'}

That's because I've copy/paste the label_attr page as an exemple of presentation... Sorry :-(

I redo a fix, or maybe you redo that faster than me ? As you whish :-)

**Comment by javiereguiluz** [comment]
@mpiot thanks for reporting this! We've fixed this issue committing directly in https://github.com/symfony/symfony-docs/commit/a97dc74631efc126f47957146b28d2618241f790

**Pull request closed without merging**
