### PR TITLE
Remove deprecated parameters

### PR DESCRIPTION
**Pull request by norkunas**
| Q | A |
| --- | --- |
| Doc fix? | yes |
| New docs? | no |
| Applies to | master |
| Fixed tickets | - |

### CODE REVIEW

**Comment by javiereguiluz** [comment]
@norkunas thanks for fixing this error! I see that you committed these changes to the `master` branch. However, changes should always be submitted to *"the oldest maintained branch which needs that change"*. This usually means to use the `2.3` branch, except for the new features, that usually go to `2.6` or `2.7`.

In this case, the change should be made in the `2.7` branch, but don't worry because our doc maintainers will change the branch when merging it. But for complex pull requests is better to target the right branch. Thanks!

**Comment by norkunas** [comment]
I thought that if these params are available then it should be documented, that's why i commited to master. Thanks for clarifying :)

**Comment by WouterJ** [comment]
I agree with you, @norkunas. These should be merged into master (and maybe just `(deprecated)` in the parameter list on the 2.7 branch).

:+1:

**Comment by WouterJ** [comment]
Thank you @norkunas! Great PR and a quick win!

I've added the deprecated notice in 2.7 in 40d8d00 and did not remove the options, they are still valid.

**Comment by norkunas** [comment]
:+1:

**Pull request merged**
