### PR TITLE
Update factories.rst

### PR DESCRIPTION
**Pull request by muhammedeminakbulut**
the `:` part of the yaml should be `::`

### CODE REVIEW

**Comment by xabbuh** [comment]
This doesn't look right to me. Using two colons means referencing a static method in a class, but here we do refer to a method of a service. the code handling this can be found here: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php#L574-L586

**Comment by muhammedeminakbulut** [comment]
I was actually calling a static method see:
https://github.com/thephpleague/csv/blob/master/src/AbstractCsv.php#L168 

but it was not clear to me the single colon would call a function and a double colon a static method. There are a lot of classes in the wild having a static method to get an instance. could it be an improvement if we mention the single and double colon. or a reference to the documentation on refering to code in yaml?

**Comment by xabbuh** [comment]
What about updating the first example to also make use of the string syntax but using two colons and add a comment in both examples explaining the difference?

**Comment by maxhelias** [comment]
This PR is outdated for me because we are now passing a array

**Comment by weaverryan** [comment]
Closing - we now show an array syntax, which includes when your method is static and when it is non-static. Thanks for opening the PR - it wasn't merged, but the problem *has* now been solved

**Pull request closed without merging**
