### PR TITLE
Document changes in the deprecation error handler

### PR DESCRIPTION
**Pull request by greg0ire**
Documents https://github.com/symfony/symfony/pull/29211
See RFC:  https://github.com/symfony/symfony/issues/28048

### CODE REVIEW

**Review by TimoBakx — APPROVED** [review]
Very clear documentation.

**Comment by llaakkkk** [comment]
Thank you very much for your pull request!

As part of the Symfony EU funded hackathon (https://symfony.com/blog/the-symfony-and-api-platform-hackathon-is-coming), we were able to assemble most of the core team and big contributors in one place. Our goal is to finish as many open issues and PRs as possible.

*Your commits will not be lost and you will therefore get credit for your work*. All that will happen is that your commits will be moved to a new PR where all remaining concerns will be addressed.

Without your work this would not have been possible. So thank you once again!

**Comment by OskarStark** [comment]
This one looks finished and the code is merged

**Comment by greg0ire** [comment]
@llaakkk made a PR that supersedes this one, don't merge!

**Comment by OskarStark** [comment]
Ok so this one can be closed?

**Comment by greg0ire** [comment]
It will be autoclosed when the other one is merged

**Pull request closed without merging**
