### PR TITLE
[Form] Remove timezone options from DateType and TimeType

### PR DESCRIPTION
**Pull request by jakzal**
| Q | A |
| --- | --- |
| Doc fix? | yes |
| New docs? | no |
| Applies to | 2.6+ |
| Fixed tickets | - |

re https://github.com/symfony/symfony/pull/12404

### CODE REVIEW

**Comment by xabbuh** [comment]
I wish you a happy 2015 @jakzal! Can you update the pull request to also apply the note to the `BirthdayType`?

@WouterJ @weaverryan Should we consider to merge this into the `2.3` branch given that people otherwise would break their applications when they used these options and update to Symfony 2.6?

**Comment by weaverryan** [comment]
Hi guys!

We should also add an entry to the `UPGRADE-2.6.md` file in the symfony repo. I'm doing that now, but I need some help, because I don't quite understand what to tell people.

If I were previously using one of these options, what should I do now? Is the difference that before, we would use `model_timezone` to convert the DateTime object, then `view_timezone` to convert it again to show the user? So for example, if I have a datetime stored in UTC in the database, I *would* previously have set `model_timezone` to UTC. Then, if I want my users to select the time in US Eastern, I might set `view_timezone` to `America/New_York`. Is that right? So with these options gone, is it correct to say that it is my responsibility to convert my DateTime object (from the database) to a US Eastern DateTime, and then convert it back on submit to UTC? Or am I over-thinking this?

@xabbuh I think we should pretend like these options were deprecated in 2.3, and add deprecations notices in 2.3.

Thanks!

P.S. @jakzal can you delete the `view_timezone.rst.inc` and `model_timezone.rst.inc` files?

**Comment by jakzal** [comment]
Sorry for delay. I'll update this PR in the evening.

**Comment by jakzal** [comment]
Unless #4763 replaces this PR?

**Comment by xabbuh** [comment]
@jakzal I suggest to wait for the final decision on the code repository and based on this merge one or the other. Does that make sense to you?

**Comment by jakzal** [comment]
Yept. Thanks.

**Comment by fabpot** [comment]
We are going to revert the change as per symfony/symfony#13241

**Comment by xabbuh** [comment]
Going to close here then. Anyway, thanks for the pull request @jakzal.

**Pull request closed without merging**
