### PR TITLE
Remove `index` directive

### PR DESCRIPTION
**Pull request by alamirault**
Directive `index` is not used anymore https://github.com/symfony/symfony-docs/issues/18122#issuecomment-1484663042

Fix https://github.com/symfony/symfony-docs/issues/18122

### CODE REVIEW

**Comment by OskarStark** [comment]
Can we have a configurable rule to disallow certain directives ?

**Comment by javiereguiluz** [comment]
Antoine, thanks a lot for taking the time to remove all these index directives from all the docs.

**Comment by javiereguiluz** [comment]
This was upmerged to 6.2 and 6.3. In 6.2 there were some conflicts and also, there were more `index` directives to remove. In 6.3 there were none, so we're good. Thanks.

**Comment by OskarStark** [comment]
@javiereguiluz we created a rule:
* https://github.com/OskarStark/doctor-rst/pull/1360

**Pull request merged**
