### PR TITLE
Remove all 6.x `versionadded` on 7.0

### PR DESCRIPTION
**Pull request by alexandre-daubois**
:blush:

### CODE REVIEW

**Comment by OskarStark** [comment]
I would keep this PR on hold and only do this change close to a 7.0 release because we have a lot of merge conflicts with no reason in between

**Comment by alexandre-daubois** [comment]
@OskarStark alright got it, thanks!

**Comment by alexandre-daubois** [comment]
I rebased on 7.0. As feature freeze is now here, I think it's safe to update this PR now :slightly_smiling_face:

**Comment by OskarStark** [comment]
Please update `.doctor-rst.yaml` file too

**Comment by alexandre-daubois** [comment]
Here you go :)

**Review by OskarStark — APPROVED** [review]

**Comment by OskarStark** [comment]
Thank you Alexandre.

**Comment by javiereguiluz** [comment]
Alex, thanks a lot for taking the time to do all these changes ❤️

**Pull request merged**
