### PR TITLE
[Messenger] Tiny language fix in messenger.rst

### PR DESCRIPTION
**Pull request by manuelkiessling**
Really just a tiny correction.

### CODE REVIEW

**Review by OskarStark — APPROVED** [review]

**Comment by OskarStark** [comment]
Good catch, thanks Manuel.

**Comment by manuelkiessling** [comment]
My bad - it should actually be merged into 6.1 imho, I wrongly targeted the PR at 5.4 because that was the default.

**Comment by OskarStark** [comment]
> My bad - it should actually be merged into 6.1 imho, I wrongly targeted the PR at 5.4 because that was the default.

Why, `5.4` is the lowest maintained branch which contains the "error" 🤷‍♂️ , it will be upmerged automatically

**Comment by manuelkiessling** [comment]
Ah, understood, thanks - I thought the process would be the other way round, start at latest and then propagate down as far as possible. I made a mental note for next time!

**Pull request merged**
