### PR TITLE
Latest demo has no bin folder

### PR DESCRIPTION
**Pull request by Jace25**
Latest demo has no bin folder. Console is located inside the app folder.

### CODE REVIEW

**Comment by xabbuh** [comment]
Thank you for providing this patch @Jace25. That's a good catch as the demo application indeed does not make use of Symfony 3 yet.

**Comment by Jace25** [comment]
Yes, I have also wondered about this because I just saw that my fresh created project has a bin folder.
So maybe my pull request is wrong in longterm and a pull request regarding the demo would be better.

**Comment by xabbuh** [comment]
I guess it will still take some time till the demo application switches to Symfony 3 (see symfony/symfony-demo#248) so we should merge this and remember to revert the change when the demo is updated.

**Comment by xabbuh** [comment]
Thank you @Jace25.

**Pull request merged**
