### PR TITLE
internal web server ran with dev environment by default

### PR DESCRIPTION
**Pull request by rmed19**
| Q | A |
| --- | --- |
| Doc fix? | yes |
| New docs? | no |
| Applies to | 2.3+ |
| Fixed tickets | #5611 |

### CODE REVIEW

**Comment by javiereguiluz** [comment]
@rmed19 thanks for submitting this pull request!

I like the idea that you propose here. However, the title of the changed sidebar is *"What's the ``app_dev.php`` in the URL?"*  So we should probably introduce more changes to completely update this explanation. In any case, before doing any other change, let's wait to know the opinion of the doc managers @WouterJ and @xabbuh.

**Comment by xabbuh** [comment]
We could remove the `app:dev.php` front controller from the URL as you will probably start the internal web server in the dev environment. The sidebar Javier mentions is then no longer necessary. We could replace it with another one named something like "Accessing different Environments". Here we can explain how to access your application in different environments through the built-in web server. What do you think?

**Comment by rmed19** [comment]
Hi, 
We shold remove all app_dev.php from internal web server url in this chapter, not only one url like I did.
IMO the sidebar haven't any more sense it should be removed or changed to some thing else

**Comment by WouterJ** [comment]
Hi @rmed19! I've taken your commits and put them in a new PR, updating all examples in the page creation book and the sidebar: https://github.com/symfony/symfony-docs/pull/6239 I'm going to close this PR in favor of this one (your commit is included, so you'll get all credits for finding this inconsistentcy!).

Thank you for submitting an issue and PR and helping us improve one of the most important articles of the docs (first impression is everything).

**Pull request closed without merging**
