### PR TITLE
[Runtime] Fix typo php-fpm => php-pm

### PR DESCRIPTION
**Pull request by wadjeroudi**

### CODE REVIEW

**Review by OskarStark — APPROVED** [review]

**Comment by wouterj** [comment]
I don't think this is a typo and "php-fpm" was meant to be used here (which is the most common way to run Symfony).

**Comment by wadjeroudi** [comment]
@wouterj php-fpm doesn't need the runtime autoloader, even if it should work.
why would you use autoload_runtime on php fpm ?

From my understanding it was meant for PHP "servers" using ReactPHP technology.

Maybe @nicolas-grekas can clarify the first purpose of this component.

**Review by nicolas-grekas — APPROVED** [review]
This is correct :)

**Comment by javiereguiluz** [comment]
@wadjeroudi thanks for fixing this typo ... and congrats on your first Symfony Docs contribution 🎉

**Pull request merged**
