### PR TITLE
[VarDumper] little optim

### PR DESCRIPTION
**Pull request by lyrixx**
| Q | A |
| --- | --- |
| Doc fix? | no |
| New docs? | no |
| Applies to | 2.7+ |
| Fixed tickets | - |

related to https://github.com/symfony/symfony/pull/14137
and asked by @nicolas-grekas

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
:+1:

**Comment by javiereguiluz** [comment]
:+1:

(I know that you like contractions a lot, but maybe the title of this PR should be longer than "Optim" to help doc maintainers)

**Comment by lyrixx** [comment]
@javiereguiluz oups, I forgot to updated the title; Thanks.

**Comment by xabbuh** [comment]
We can merge this into the branch for Symfony 2.6, can't we?

**Comment by nicolas-grekas** [comment]
yes we can

**Comment by xabbuh** [comment]
:+1: Nice!

**Comment by WouterJ** [comment]
It's merged now. Thanks Grégoire and Nicolas!

**Pull request closed without merging**
