### PR TITLE
[Console] Create consistent console screenshots/recordings

### PR DESCRIPTION
**Pull request by wouterj**
The, honestly quite minor, issue with inconsistent terminal screenshots/recordings has been bugging me for quite some time. When creating the recording for my most recent console PR, I managed to get something set-up that can be replicated by others - although the rendering is a bit tricky.

The only remaining recording is the progress bar. At the moment, my terminal emulator crashes when displaying emoji's, so I have some trouble creating the asciicast file for it :smile:

The color scheme is based on the dark theme terminal color scheme in the Symfony docs. I'm not totally convinced about the green color, which is too dark when used as foreground but the bright one is too light when used as background. If someone has a better suggestion, please let me know

### CODE REVIEW

**Comment by javiereguiluz** [comment]
Thanks for contributing this improvement and thanks for the effort you put on it. I like the overall consistency and also that we have the sources of the recordings as editable text.

About the missing one, do you want to wait until you find a solution for it or do you think we could merge this now and try to fix the missing recording in a later PR? Thanks.

**Comment by wouterj** [comment]
Thanks Javier.

I've just finished this PR:
* Added JetBrains Mono font
* Added the progressbar example (a bit simplified)

**Review by OskarStark — APPROVED** [review]
Wow <3

**Comment by javiereguiluz** [comment]
It's merged! Thanks Wouter!!

**Comment by OskarStark** [comment]
Great work, thanks 🙏

**Pull request merged**
