### PR TITLE
fix README requirements link

### PR DESCRIPTION
**Pull request by garak**
| Q | A |
| --- | --- |
| Doc fix? | yes |
| New docs? | no |
| Applies to | 2.8, 2.7, 2.3 |
| Fixed tickets |  |

The "requirements" secion is not in README anymore, so we need to point to specific version

### CODE REVIEW

**Comment by javiereguiluz** [comment]
We could even link to the doc page that explains Symfony requirements: http://symfony.com/doc/current/reference/requirements.html

**Comment by garak** [comment]
@javiereguiluz this PR is just about that page (not the one on master, anyway)

**Comment by WouterJ** [comment]
:+1:

**Comment by xabbuh** [comment]
Thank you @garak. I have merged your PR and made similar changes for the `2.3` and `2.7`  branches in 2efa5f8d63a17aa89c08715c6a054cd42a2b18c8 and c441f6d0f0829309107f35af9b7a9a2085d2295d.

**Pull request merged**
