### PR TITLE
Removing AcmeDemoBundle related sections from security.yml

### PR DESCRIPTION
**Pull request by zebba**
| Q | A |
| --- | --- |
| Doc fix? | yes |
| New docs? | no |
| Applies to | 2.3+ |
| Fixed tickets | #5080 |

### CODE REVIEW

**Comment by zebba** [comment]
Ping @WouterJ

**Comment by xabbuh** [comment]
@zebba To me it looks like something went wrong here. At least, I don't understand how the data transformers documentation is related to what was the old content of this file.

**Comment by zebba** [comment]
I totally agree and just realized now. I guess I'm going to relabel this and update the list and figure out where the original thing went. My bad.

**Comment by WouterJ** [comment]
@zebba did you find some time to fix this PR?

**Comment by zebba** [comment]
I'll get to it this weekend.

**Comment by WouterJ** [comment]
Closing this PR, as something wrong has happend with the commits

**Pull request closed without merging**
