### PR TITLE
[Console] Update the doc for automatic console logging

### PR DESCRIPTION
**Pull request by chalasr**
In https://github.com/symfony/symfony/pull/21003 we are going to provide automatic error/exception logging for the console, similar to what is done in an HTTP context.

In the docs, there is a whole chapter dedicated to this topic. Right now I just removed it, maybe it should be done differently or mentioned somewhere that error/exceptions are automatically logged on the `console` channel?

Thanks

### CODE REVIEW

**Comment by javiereguiluz** [comment]
Yes, we should remove the contents of this article ... but maybe it's too son to remove the article itself. Otherwise, all the `.../current/console/logging.html` links will break. What if we just add the following content to the article:

```
In Symfony versions prior to 3.3, the Console component didn't provide any
logging capabilities out of the box and you had to implement your own exception
lister for the console.

Starting from Symfony 3.3, the Console component provides automatic error and
exception logging. <Here a link to read more details about enabling/configuring this>
```

**Comment by chalasr** [comment]
@javiereguiluz Let's do it like that 👍 
However, I have no idea of where should lead the "read more" link you mentioned (nor what it should contain) :/ 
It is not planed to make this feature opt-in (AFAIK it is not for exception logging in HTTP context), exceptions will be logged as any other.
Maybe could we add it this link at first, and see for a more detailed reading if the feature becomes configurable?

**Comment by javiereguiluz** [comment]
@chalasr then we can remove the link entirely and add it later if needed:

```
In Symfony versions prior to 3.3, the Console component didn't provide any
logging capabilities out of the box and you had to implement your own exception
lister for the console.

Starting from Symfony 3.3, the Console component provides automatic error and
exception logging.
```

**Comment by chalasr** [comment]
Oops, that's what I mean, but forget "without"  in my last sentence :) I made the change

**Review by javiereguiluz — APPROVED** [review]
👍

**Comment by chalasr** [comment]
I re-added the page title so that other pages can have links to, the travis build was failing if missing.

**Comment by chalasr** [comment]
https://github.com/symfony/symfony/pull/21003 has been merged, this is no longer on hold.

**Comment by xabbuh** [comment]
Thank you @chalasr.

**Pull request merged**
