### PR TITLE
added link to 30 days trial on platform.sh

### PR DESCRIPTION
**Pull request by OskarStark**

### CODE REVIEW

**Review by xabbuh — APPROVED** [review]

**Review by javiereguiluz — CHANGES_REQUESTED** [review]
@OskarStark I thank you for contributing to improve Symfony Docs ... but I'm :-1: about this change. The reason is that this link can be outdated soon (what if they create other promotions, or extend/reduce the trial period?)

I propose the following reword:

Before:

```rst
You need to subscribe to a `Platform.sh project`_ (or use a free `30 days trial`_). 
Choose the development plan and go through the checkout process. Once your project is +
ready, give it a name and choose: **Import an existing site**.

.. _`Platform.sh project`: https://accounts.platform.sh/platform/buy-now
.. _`30 days trial`: https://accounts.platform.sh/platform/trial/general/setup
```

After:

```rst
You need to `subscribe to a Platform.sh plan`_ and go through the checkout process.
Once your project is ready, give it a name and choose: **Import an existing site**.

.. _`subscribe to a Platform.sh plan`: https://accounts.platform.sh/platform/buy-now
```

**Comment by OskarStark** [comment]
@xabbuh are you fine with the proposal of @javiereguiluz ?
If yes, I will change it accordingly

**Comment by xabbuh** [comment]
@OskarStark fine for me

**Comment by OskarStark** [comment]
done

**Review by javiereguiluz — APPROVED** [review]

**Comment by xabbuh** [comment]
Thank you @OskarStark.

**Pull request closed without merging**
