### PR TITLE
KernelTestCase::createKernel() is static, $this->createKernel() -> static::createKernel()

### PR DESCRIPTION
**Pull request by baruica**

### CODE REVIEW

**Review by xabbuh — APPROVED** [review]
:+1:

**Review by javiereguiluz — APPROVED** [review]
:+1:

**Review by linaori — APPROVED** [review]
Not sure if static vs self is important here, but the end-result would be the same. This change looks correct to me.

**Review by HeahDude — APPROVED** [review]
👍

**Comment by xabbuh** [comment]
Good catch, thanks @baruica.

**Pull request closed without merging**
