### PR TITLE
Update service_decoration.rst

### PR DESCRIPTION
**Pull request by bricelalu**
Add missing colon ":" to yaml service definition & add missing  "s" in xml service definition

### CODE REVIEW

**Review by javiereguiluz — APPROVED** [review]
Nice fixes! Thanks @bricelalu.

**Comment by xabbuh** [comment]
If I am not mistaken, we already fixed that on all maintained branches, didn't we?

**Comment by javiereguiluz** [comment]
@bricelalu I'm afraid that @xabbuh is right. We only make changes in the docs of the maintained branches (which at the moment are: 2.7, 2.8, 3.3, 3.4, 4.0 and master). This bug was indeed fixed in all maintained branches. See for example: https://github.com/bricelalu/symfony-docs/blob/2.7/service_container/service_decoration.rst

Therefore, I must sadly close this as "won't merge" because the 3.0 branch is no longer supported. I'm sorry!

**Comment by bricelalu** [comment]
@javiereguiluz Ok I understand, thank you.

Sorry :)

**Pull request closed without merging**
