### PR TITLE
Update standards.rst

### PR DESCRIPTION
**Pull request by dawkaa**
Sorry, many conflicts arose, so I closed merge requests.

### CODE REVIEW

**Comment by javiereguiluz** [comment]
Thanks for this contribution!

Sadly, I don't know what to do here. This looks consistent with the usage of other tools in the Symfony Docs ... but at the same time, PHP CS Fixer recommends installing it in a directory inside the project (https://github.com/PHP-CS-Fixer/PHP-CS-Fixer#installation) and it's also common to install i globally via the downloadable PHAR.

Let's ask the Docs Team what to do there. Thanks!

**Comment by OskarStark** [comment]
TBH I mostly use it calling `vendor...` instead of the PHAR 🤷‍♂️

**Comment by dawkaa** [comment]
> TBH I mostly use it calling `vendor...` instead of the PHAR man_shrugging

Yes of course :+1:

**Comment by xabbuh** [comment]
Well, as this chapter is about contributing to the Symfony code I'd vote to keep the current example. Otherwise, we advocate for adding dependencies to Symfony's `composer.json` file (otherwise the files wouldn't be present in `vendor`) which is then easily committed accidentally.

**Pull request closed without merging**
