### PR TITLE
Removed the Stable API chapter from the Symfony book

### PR DESCRIPTION
**Pull request by javiereguiluz**
| Q | A |
| --- | --- |
| Doc fix? | no |
| New docs? | no |
| Applies to | all |
| Fixed tickets | - |

The two main reasons for this change are: 1) the traffic to that book chapter is almost zero; 2) all the things explained in this "chapter" are better explained in the BC Promise article. A redirection to that article has been setup.

### CODE REVIEW

**Comment by WouterJ** [comment]
The chapter does however not list the components which have a stable API. We should add that list imo

**Comment by stof** [comment]
@WouterJ the list is totally outdated though

**Comment by javiereguiluz** [comment]
@WouterJ I don't understand your comment. If you say that the removed chapter contains wrong information ... well it doesn't matter because we're removing the chapter.

If you mean that the BC Promise article doesn't list the components with stable API, I guess we can tackle that in another issue.

**Comment by stof** [comment]
This list is not necessary anymore IMO. It was useful at the time where we were providing BC only for some components. But as of Symfony 2.3, the BC promise covers all components

**Comment by WouterJ** [comment]
@stof yeah, but the BC promise is quite a lot stricter for stable API components than for non stable API components.

@javiereguiluz I indeed meant to move the list to the bc article. Why doing that in another PR, isn't it a very simple change?

**Comment by stof** [comment]
@WouterJ but giving a list of components with a tagged stable API does not help much. Most components have it, and this does not mean that everything is tagged as such in the component. It is not a component-level flagging but a class-level one.

**Comment by WouterJ** [comment]
Okay :+1:

**Comment by weaverryan** [comment]
Thanks Javier!

**Pull request merged**
