### PR TITLE
Remove unused links

### PR DESCRIPTION
**Pull request by OskarStark**
Refs https://github.com/OskarStark/doctor-rst/issues/249

There are a lot more

### CODE REVIEW

**Comment by OskarStark** [comment]
@javierequiluz, this one is now ready to merge

**Review by javiereguiluz — APPROVED** [review]
Looks great! Thanks Oskar.

I also think we are sure this doesn't break anything because if we removed some still-used link, we'd see a build error 👍

**Comment by OskarStark** [comment]
> I also think we are sure this doesn't break anything because if we removed some still-used link, we'd see a build error 👍

Yes a lot of them occured while doing this change, so now we are safe!

Could you do me a favor and do the merge? 😃 Afterwards I will do the same against `4.3`.

**Comment by javiereguiluz** [comment]
Thanks Oskar.

**Comment by javiereguiluz** [comment]
This has been merged up to `master` branch.

**Pull request merged**
