### PR TITLE
Automate deployment tool

### PR DESCRIPTION
**Pull request by julienj**
Mention Automate (https://automatephp.github.io/automate/) as one of deployment options.

Thanks

### CODE REVIEW

**Review by weaverryan — APPROVED** [review]
Hmm... it seems like the is not used by a lot of people on GitHub (just 4 stars). But, it looks nice enough - I like the YAML file syntax. So, I think I'm willing to add it. Anyone disagree?

**Comment by weaverryan** [comment]
Status: Reviewed

**Comment by wouterj** [comment]
Hmm, I disagree. While being a nice project, it doesn't seem to be used that much and it is maintained by only one contributor.
I think projects first have to be production-tested, more mature and with a bigger community before we can officially recommend using it.

This is nothing against the project or you, @julienj, of course. It's just that as soon as we recommend it in the official docs, it should work 99% and should be updated quickly for a long period. From my personal projects, I know that this might not always be the case if you're the only contributor.

**Comment by weaverryan** [comment]
I think that makes sense. I hope you'll get more users @julienj and we can add it in the future :)

**Comment by julienj** [comment]
I understand the choice. I hope too :)

**Pull request closed without merging**
