### PR TITLE
Add Twitter Bootstrap form theme example

### PR DESCRIPTION
**Pull request by bocharsky-bw**
Also add Twitter Bootstrap 3 themes to it (http://symfony.com/blog/new-in-symfony-2-6-bootstrap-form-theme).

### CODE REVIEW

**Comment by stof** [comment]
-1 for showing the deprecated way of configuring form themes

**Comment by WouterJ** [comment]
I agree with @stof. As of Symfony 2.6, the option `twig.form.resources` was renamed to `twig.form_themes`. This option is shown in the lines above the added lines.

However, I'm +1 for adding the bootstrap to this `twig.form_themes` option. Can you please update your PR?

**Comment by bocharsky-bw** [comment]
Thanks @WouterJ, I have updated it.

**Comment by bocharsky-bw** [comment]
Thanks @WouterJ ! I have updated my PR

**Comment by WouterJ** [comment]
Thank you @bocharsky-bw! Seems like we missed this bit in the past.

**Pull request merged**
