### PR TITLE
[Security] Add argument `$exceptionCode` to `#[IsGranted]`

### PR DESCRIPTION
**Pull request by alexandre-daubois**
Fixes https://github.com/symfony/symfony-docs/issues/18097

### CODE REVIEW

**Comment by WebMamba** [comment]
I think we should also add something about the statusCode argument. I am not sure we have something about it

**Comment by alexandre-daubois** [comment]
@WebMamba Good idea! This must be done in 6.2. Here you are :slightly_smiling_face: ! https://github.com/symfony/symfony-docs/pull/18103

**Comment by OskarStark** [comment]
https://github.com/symfony/symfony-docs/pull/18103 should be merged first

**Comment by OskarStark** [comment]
Rebase unlocked ✅

**Comment by alexandre-daubois** [comment]
Rebased and updated :pray:

**Comment by javiereguiluz** [comment]
Thanks Alex for contributing this in two different PR and for rebasing and updating as needed 🙏

**Pull request merged**
