### PR TITLE
[FrameworkBundle] Replace render() with new renderForm() in form documentation

### PR DESCRIPTION
**Pull request by MrYamous**
This is the documentation for #14844

### CODE REVIEW

**Comment by Nyholm** [comment]
Thank you. 

Im not too confident/knowledgeable about this feature, but should it be applied everywhere? Or is it only for some specific use cases?

**Comment by MrYamous** [comment]
I think both are possible. 
In my opinion, it can be a good thing to show this method by default as it allows to introduce natively a difference between the initially returned form and the one returned when the submission is invalid.

**Comment by xabbuh** [comment]
IMO we should document this only once. Not sure though what would be the best place for it.

**Comment by javiereguiluz** [comment]
@MrYamous thanks a lot for taking care of updating this!

Some other changes were required to finish this update. Describing them in this PR was complex and I tried, but failed, to add some commits to this Pull Request.

That's why I've created #15217 based on this PR. The new PR contains your original commit, so you get full credit for your work. That's why I'm closing this one. Thanks!

**Pull request closed without merging**
