### PR TITLE
There are 5 events listed and not 4

### PR DESCRIPTION
**Pull request by scriptibus**
There are 5 events listed and not 4

### CODE REVIEW

**Review by xabbuh — COMMENTED** [review]
I would change the text to something like "provides the following authentication events".

**Comment by scriptibus** [comment]
> I would change the text to something like "provides the following authentication events".

@xabbuh Yes, sounds better and doesn't contain a number that might be wrong one day.

**Review by xabbuh — APPROVED** [review]

**Review by javiereguiluz — APPROVED** [review]

**Review by OskarStark — APPROVED** [review]

**Comment by javiereguiluz** [comment]
@scriptibus thanks ... and congrats on your first Symfony Docs contribution!

**Comment by scriptibus** [comment]
@javiereguiluz Thank you!

**Pull request merged**
