### PR TITLE
Fix missing namespace and other wrong wording from Security and Serializer context

### PR DESCRIPTION
**Pull request by TheGarious**

### CODE REVIEW

**Comment by javiereguiluz** [comment]
Thanks for this contribution!

I like the idea of always showing the file path ... but the "namespace" is not always displayed. If an article is always showing the same example, we use `// ...` in the following examples to hide the "namespace" and the previous "use" (we only display the new "use").

Also, this kind of PRs are tricky because they can introduce several merge conflicts, so it's better to create them in the lowest maintained branch that needs these changes (e.g. 4.4.)

**Comment by TheGarious** [comment]
No problem @javiereguiluz,

I see many page where namespace and filepath is always implemented and the other page not. 
I was thinking is better to add all time. 
I correct relicat Bundle present into security/named_encoders.rst.

I need to change the branch target ?

**Comment by TheGarious** [comment]
@javiereguiluz @xabbuh  up

**Review by maxhelias — APPROVED** [review]

**Comment by javiereguiluz** [comment]
Thanks Gary! Merged in 4.4 and up.

**Pull request merged**
