### PR TITLE
Update routing.rst

### PR DESCRIPTION
**Pull request by micter59**
Add a note about allowing the http_method_override in the framework.yml file 
https://github.com/symfony/symfony/issues/48658

### CODE REVIEW

**Comment by MatTheCat** [comment]
Given the option was disabled in the 5.3 recipe (cf. https://github.com/symfony/recipes/pull/892) I think this PR should target the `5.4` branch.

Also it concerns form usage so maybe it would be better to add something like

> `framework.http_method_override` needs to be set for this to work.

at the bottom of the existing tip.

**Comment by micter59** [comment]
Sorry, i don't know how to make the modification now. If I change from symfony:6.2 to 5.4, this makes a lot of modification that I don't want.

**Comment by MatTheCat** [comment]
I think the simplest way would be to reset your branch on `5.4`, then you can (re)add your changes, force-push and change the PR’s target.

**Comment by micter59** [comment]
I'm a bit lost with Git & Github. Sorry for the mess I do. I just wanted to help.
I've open a new PR targeting the 5.4.
I hope it will be ok this time.

**Pull request closed without merging**
