### PR TITLE
Database insulation section

### PR DESCRIPTION
**Pull request by Renrhaf**
Adding a recipe to add database insulation to functionnal tests.

### CODE REVIEW

**Comment by Renrhaf** [comment]
Any updates on how to improve this ? 
I found out that a recent update (https://github.com/doctrine/DoctrineBundle/commit/2f8d7263c4c44445b51fc2d9bf71d21f7016347d) break this and I'm trying to find a workaround with the author of the commit.

**Comment by weaverryan** [comment]
@Renrhaf So this current approach no longer works? Then what about the "in-memory SQLite" approach that Javier talked about (http://blog.sznapka.pl/fully-isolated-tests-in-symfony2/).

Basically, I think it would be cool to find one nice approach and go with it. If this approach no longer works, then I think we could try something else. I was also never too find of this approach for the core docs (not to say it isn't great in a project, however). The reason is that I'm not clear which DB's this would support or what other issues you'd run into with rolling back transactions.

Anyone have an objection to the in-memory SQLite approach shown above? I've never used *any* of these - just trying (along with @Renrhaf) to poke this along :)

**Comment by Renrhaf** [comment]
I just read the article and will try it soon to give some feedbacks. I agree with you that my method may not be robust enough to work for all situations.

**Comment by weaverryan** [comment]
Thanks @Renrhaf :)

**Comment by WouterJ** [comment]
Hi @Renrhaf! Do you have some time to update this PR?

We have a [doc sprint day](http://symfony.com/blog/symfony-docs-hack-day-needs-you-on-may-23rd) on May 23rd. It would be great to have this PR finished at the end of the day! If you don't have any time soon, please say so. We can then assign it to someone else during the sprint day.

Thanks!

**Comment by Renrhaf** [comment]
Hello @WouterJ I am currently unavailable until the 26th May.

**Comment by weaverryan** [comment]
Closing this old PR. See #480 for a related issue

**Pull request closed without merging**
