### PR TITLE
updated validation.rst

### PR DESCRIPTION
**Pull request by issei-m**
I'm not sure this change is correct but FieldError was renamed to FormError, right?

### CODE REVIEW

**Comment by javiereguiluz** [comment]
The UPGRADE guide doesn't say anything about this change: https://github.com/symfony/symfony/blob/2.8/UPGRADE-2.8.md :confused:

**Comment by issei-m** [comment]
@javiereguiluz I'm not sure where this PR should be merged to, but FieldError class is not found in Symfony projects anywhere.
But I'm guessing this class had been introduced in a early stage of development, thereafter renamed.

**Comment by issei-m** [comment]
ping @webmozart

**Comment by WouterJ** [comment]
This change is 100% correct and a left-over from way before 2.0.0: https://github.com/symfony/Form/commit/889a1600e6aa878331be8da65a4dac0210801dcb

So big :+1: and thanks @issei-m for finding & fixing this very old issue.

**Comment by WouterJ** [comment]
Thanks again @issei-m, I've now merged it into the docs in version 2.3 (the oldest, still maintained, version) and will merge it up the other versions from there.

**Pull request closed without merging**
