### PR TITLE
fix code example for property info

### PR DESCRIPTION
**Pull request by OskarStark**

### CODE REVIEW

**Comment by javiereguiluz** [comment]
I think there's been a mistake here. "Analyze" is a verb, not a noun. "Analyzes" is the third-person form of the verb or the plural of a [misspelling of analysis](https://en.wiktionary.org/wiki/analyzis#English).

In American English it's OK to calle it "analysis" (singular) / "analyses" (plural).

**Comment by javiereguiluz** [comment]
Looking at the original code ... it looks like it's wrong too. It should be:

* Property in singular `private $analysis`
* Methods in plural: `addAnalyses()`, `removeAnalyses()`

**Comment by OskarStark** [comment]
> Looking at the original code ... it looks like it's wrong too. It should be:

Yes, I think the same, I need to dive into this topic twice today to find the right approach, but I think you are right 👍 

Shall I fix it in this PR?

**Comment by OskarStark** [comment]
> Property in singular private $analysis

I think the property needs to be plural, , the adder/remover needs to be plural, the argument needs to be singular, right?

**Comment by javiereguiluz** [comment]
I wonder if we still need the `foot / feet` example. It looks like the usual "silly" and forced example that you can find in some programming books. We already show an irregular transformation "analyses/analysis", so that may be enough.

**Comment by OskarStark** [comment]
I removed it

**Comment by javiereguiluz** [comment]
Thanks Oskar.

**Pull request merged**
