### PR TITLE
Multiple entity managers and shared entities management

### PR DESCRIPTION
**Pull request by ipernet**
Multiple entity manager doc improvement related to the discussion _With multiple Entity Managers (EM) the Repository uses only the mapped EM for the Entity_ (#9878)

### CODE REVIEW

**Comment by wouterj** [comment]
Hi @ipernet! I'm sorry you didn't receive any comment from us on this PR. It's quite a difficult topic and quite a big diff, seems like we all somehow lost this PR.

Do you have any motivation to work on this PR? If so, I would like to say some comments on how to improve this:

I think we should make this more concise. We don't have to show all different ways to get the repository - that'll only confuse the user ("which one is the correct/recommended way?"). I think the most important thing here is that you can't use `ServiceEntityRepository` if the entity is managed by more than one entity manager - it'll always default to the first configured entity manager. The solution is to use `EntityRepository` and not use autowiring. I think we can say all this in a ``.. caution::`` directive after line 256 (so keep your changes till line 256, tell what doesn't work (`ServicEntityRepository` with an entity managed by multiple managers) and then show the `EntityRepository` code example of 558 - 567).

I can also imagine if you no longer have time to work on this PR, please say so then I can take over and make the necessary changes. Seems like there are quite some users running into this issue.

**Comment by ipernet** [comment]
Hi @wouterj 

I can still provide support on this PR,  I'll have a look later in the day about your feedback, for a start!

**Comment by ipernet** [comment]
Hi @wouterj 

Based on the current documentation, your feedback is about adding a single warning, as you explained it very well:

> "You can't use `ServiceEntityRepository` if the entity is managed by more than one entity manager - it'll always default to the first configured entity manager. The solution is to use EntityRepository and not use autowiring.

But this would mean that no further details (rather than just showing a basic `EntityRepository` class) would be provided to the users reading the doc, while the main purpose of the proposed changes was indeed to provide a deeper understanding of what remains an advanced usage of entity managers for users who opened/follow issues related to the lack of documentation on the subject. 

So I would suggest to add the notice on top of the existing doc then close the PR without merging. It will still be a reference for those digging in the related issues.

**Comment by wouterj** [comment]
Hi @ipernet. Thanks for your quick responses.

I have never been in a situation with multiple entity managers (let alone having an entity in multiple managers). Do you with your experience think that it's enough to add the small note, or would that not have helped you in the situation you had a year ago? 
We (of course) try to keep the docs small (nobody likes reading), but we shouldn't make this so small that it becomes useless (current situation).

**Comment by ipernet** [comment]
@wouterj Yes, the main issue to me was to understand that a `ServiceEntityRepository` only uses the first configured EntityManager. Adding a small note mentioning it and the use of an `EntityRepository` as a workaround as well would be a time saver without making the doc too coumbersome.

**Comment by wouterj** [comment]
Thanks for your feedback again!

I've created a new PR based on your commit: https://github.com/symfony/symfony-docs/pull/14336 This way, I can still give you the credits you deserved (this PR was copy/pasting your examples)!

**Pull request closed without merging**
