### PR TITLE
default value of csrf_token_id

### PR DESCRIPTION
**Pull request by zairigimad**

### CODE REVIEW

**Comment by javiereguiluz** [comment]
I don't know much about this, so I can be totally wrong ... but these docs refer to logout config options ... and I looked for in the Symfony 5.0 source code and found this:

csrf-token-id

So, maybe the current docs are correct?

**Comment by zairigimad** [comment]
@javiereguiluz yes you are right there is two parameters csrf_token_id for two sections, in this case under form_login, it must be `authenticate` as declared in the code and in the config reference.
Capture d’écran 2020-06-10 à 09 39 38
Capture d’écran 2020-06-10 à 09 38 59

**Comment by javiereguiluz** [comment]
I think there's been some misunderstanding. This option: https://symfony.com/doc/current/reference/configuration/security.html#csrf-token-id. is related to logout. The headline is very small, so maybe you missed it? (or maybe I'm the one missing something 🤔  ?)

image

**Comment by zairigimad** [comment]
@javiereguiluz ah you are right, didn't see this small title to logout configuration 👍🏻

**Pull request closed without merging**
