### PR TITLE
Update configuration.rst and deployment.rst for dotenv:dump command

### PR DESCRIPTION
**Pull request by mertingen**
It changes from "composer dump-env prod" to "php bin/console dotenv:dump prod"

### CODE REVIEW

**Comment by wouterj** [comment]
Hi!

This command is a bit special, as we need to register it first (see the PR description in https://github.com/symfony/symfony/pull/42610#issue-973109927):

> The command is not registered by default. In order to enable it, one must add it to their `services.yaml` file:
>
> ```yaml
> services:
>     Symfony\Component\Dotenv\Command\DotenvDumpCommand:
>         - '%kernel.project_dir%/.env'
>         - '%kernel.environment%'
> ```

I think we should document this only once, in the configuration article. And then in the deployments article, we should only add a small tip like: "If Composer is not available during deployment, you can also use the `dotenv:dump` command. Read ... for more information."

**Comment by mertingen** [comment]
Hi,

If I get the PR description without changing it and put it into the configuration documentation directly, do you mind? Because it is really good enough explicit.

I'll add the following tip in the deployment but how can I handle "read ... for more information"? Should I give the "configuration" page URL directly there?

"If Composer is not available during deployment, you can also use the dotenv:dump command. Read ... for more information."

**Comment by wouterj** [comment]
> If I get the PR description without changing it and put it into the configuration documentation directly, do you mind? Because it is really good enough explicit.

Fine by me (I would replace "one must" with "you must" though).

> I'll add the following tip in the deployment but how can I handle "read ... for more information"? Should I give the "configuration" page URL directly there?

You can use `` :ref:`configuration-env-var-in-prod` `` to link directly to the correct section in the configuration page.

**Comment by mertingen** [comment]
hi @wouterj 

Thanks for the answer. I have got a quick question regarding **deployment.rst**. We edited it like the image.



Should we add **composer** tip here? Because we already recommend using dotenv command for dumping.

**Comment by wouterj** [comment]
I think we can keep composer at first, and then reference the configuration section to say "if you don't have composer, use this command". Anyway, feel free to update the PR as you like it best. We can apply little reorganizations during the merge, if we think something else is better.

**Comment by javiereguiluz** [comment]
Mert, thanks for this contribution! While merging I did the final change asked by Wouter (see https://github.com/symfony/symfony-docs/commit/679be09e566e61f8287f00648c10722d650b9838)

**Comment by mertingen** [comment]
Brilliant! Thank you actually.

**Pull request merged**
