### PR TITLE
Use new Event names

### PR DESCRIPTION
**Pull request by OskarStark**
Based on https://github.com/symfony/symfony/pull/28920

@symfony/team-symfony-docs shall we add `versionadded` directives?

### CODE REVIEW

**Comment by OskarStark** [comment]
Friendly ping @nicolas-grekas for a review 😄

**Comment by javiereguiluz** [comment]
I remember merging a few PRs updating this ... and closing other ones for already having done the proposed changes. Please, double check that what you are changing isn't already changed in the latest version of 4.3 branch. Thanks!

**Review by nicolas-grekas — APPROVED** [review]

**Comment by OskarStark** [comment]
Thanks for you approval Nicolas 👍 

> I remember merging a few PRs updating this ... and closing other ones for already having done the proposed changes. Please, double check that what you are changing isn't already changed in the latest version of 4.3 branch. Thanks!

I remembered the same, but didn't found the PR's. Anyway I updated the 4.3 branch to the latest remote version before creating this PR 👍

**Comment by OskarStark** [comment]
I added the deprecation here: https://github.com/symfony/symfony-docs/pull/12007/commits/d20e0df389ab05583541d99788e2c88f5aa7dab1

Ready to merge from my side!

**Review by xabbuh — APPROVED** [review]

**Pull request merged**
