### PR TITLE
Update custom_normalizer.rst

### PR DESCRIPTION
**Pull request by zulkris**
$context is not supported by Symfony 3.4

### CODE REVIEW

**Comment by javiereguiluz** [comment]
If I'm right, this interface doesn't pass `$context` in any version, including `master` (https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Serializer/Normalizer/NormalizerInterface.php). To get the `context` you need to use the "context aware" interface.

@zulkris thanks and congrats on your first Symfony Docs contribution!

**Comment by javiereguiluz** [comment]
Thank you @zulkris.

**Comment by xabbuh** [comment]
IIRC this change was suggested in the past and reject because this argument was added in 4.0 and adding it in custom implementations in 3.4 allowed a deprecation-free upgrade.

**Comment by xabbuh** [comment]
Nope, I was mistaken. That was only true for the `normalize()` method.

**Pull request merged**
