### PR TITLE
Update create_form_type_extension.rst

### PR DESCRIPTION
**Pull request by atailouloute**
Remove extra ";"

### CODE REVIEW

**Review by HeahDude — APPROVED** [review]
👍, alias must be removed when merging in 2.8.

**Comment by atailouloute** [comment]
@HeahDude Must be removed in other commit ?

**Comment by HeahDude** [comment]
@atailouloute No, this is just a note to the merger when he'll need to resolve the conflict.

**Comment by atailouloute** [comment]
I see, Thanks @HeahDude

**Review by javiereguiluz — APPROVED** [review]
👍

**Comment by xabbuh** [comment]
Thank you for the many good catches and improvements @atailouloute! To ease the merging of all the small fixes I will combine your PRs in a single PR (see #7737) and merge that one instead.

**Pull request closed without merging**
