### PR TITLE
Added possible values for access_decision_manager.strategy

### PR DESCRIPTION
**Pull request by a-ast**
| Q | A |
| --- | --- |
| Doc fix? | yes |
| New docs? | no |
| Applies to | 2.3+ |
| Fixed tickets | n/a |

Added a comment with the list of possible values for access_decision_manager.strategy (like for session_fixation_strategy)

### CODE REVIEW

**Comment by xabbuh** [comment]
:+1: (even if this isn't part of the output of the `debug:config` command, it's still useful for readers)

**Comment by ogizanagi** [comment]
@xabbuh, @AAstakhov  : Maybe this should conform the `config dump-reference security` output then:

```yml
    access_decision_manager:
        strategy:             affirmative # One of "affirmative"; "consensus"; "unanimous"
        allow_if_all_abstain:  false
        allow_if_equal_granted_denied:  true
```

**Comment by xabbuh** [comment]
@ogizanagi Indeed, good idea

**Comment by weaverryan** [comment]
Thanks Andrey! I

**Pull request merged**
