### PR TITLE
Ifdattic's fixes

### PR DESCRIPTION
**Pull request by wouterj**
This combines most of @ifdattic's fixes in one PR, to make it easier to merge and review.

| Q | A |
| --- | --- |
| Doc fix? | yes |
| New docs? | no |
| Applies to | all |
| Fixed tickets | - |

### CODE REVIEW

**Comment by stof** [comment]
:+1: but this needs a rebase

**Comment by WouterJ** [comment]
@stof thanks for notifying me, did it now

**Comment by ifdattic** [comment]
Sorry for a lot of small PRs, I just find a workflow of using online GitHub that works very well when making these small changes to documentation :)

**Comment by weaverryan** [comment]
There are a lot of great fixes here - thanks so much @ifdattic and  Wouter for the team work on this one!

**Pull request merged**
