### PR TITLE
Document the validator's switch to PSR-6

### LINKED ISSUE #12275: [Validator] Deprecated CacheInterface in favor of PSR-6
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#33459
| PR author(s) | @derrabus
| Merged in    | 4.4

### PR DESCRIPTION
**Pull request by derrabus**
This PR documents symfony/symfony#33459 and fixes #12275.

### CODE REVIEW

**Comment by OskarStark** [comment]
Hi 👋 and thanks for your PR.
The only thing which is missing from my side is a versionadded directive.

**Comment by derrabus** [comment]
Thank you for your review, @OskarStark. I've added that directive, but I'm a bit unsure about the wording. Should I somehow mention the old behavior as well or do we expect users to look this up in the older branch of the documentation should they need it?

**Review by xabbuh — APPROVED** [review]

**Comment by OskarStark** [comment]
We could, but to me it’s ok to just mention the “as is”/“current recommendation” 👍🏻🤞🏻

Thanks

**Review by OskarStark — APPROVED** [review]

**Comment by javiereguiluz** [comment]
Thank you Alexander!

**Pull request merged**
