### PR TITLE
[Notifier] remove extra backtick character

### PR DESCRIPTION
**Pull request by hhamon**

### CODE REVIEW

**Comment by OskarStark** [comment]
cc @alamirault could be spotted by DOCtor, right?

**Review by OskarStark — APPROVED** [review]

**Comment by alamirault** [comment]
> cc @alamirault could be spotted by DOCtor, right?

I created PR https://github.com/OskarStark/doctor-rst/pull/1519, there are 3 occurrences of this mistake here (but we can fix it when we will upgrade doctor-rst)

**Review by alamirault — APPROVED** [review]

**Comment by OskarStark** [comment]
I released 1.51.0

**Comment by javiereguiluz** [comment]
Thanks Hugo!

**Pull request merged**
