### PR TITLE
Add TokenProcessor

### PR DESCRIPTION
**Pull request by maidmaid**
cf https://github.com/symfony/symfony/pull/21086

### CODE REVIEW

**Review by javiereguiluz — COMMENTED** [review]
@maidmaid thanks for this contribution!

We usually explain a new feature and then add the versionadded mentioning when it was added ... but in this case, the versionadded directive tries to explain the feature and show when it was added. I think it's missing some context or explanation.

**Comment by maidmaid** [comment]
How to do? Add a new ``Registering an Existing Processor`` chapter?

**Comment by javiereguiluz** [comment]
@maidmaid I don't know exactly how to do it. I'm going to think about this, but maybe @xabbuh has some ideas too.

An example of what I wanted to explain: https://github.com/symfony/symfony-docs/pull/8146/files  In that PR we explain the new feature very briefly and then we say that it's new in Symfony 3.4.

**Comment by xabbuh** [comment]
I think the best solution would be to have a paragraph explaining how to enable this processor and then add a `versionadded` directive after that which mentions the Symfony version it was added.

**Comment by HeahDude** [comment]
Agreed with @xabbuh.

**Comment by nicolas-grekas** [comment]
ping @maidmaid :)

**Comment by wouterj** [comment]
Hi @maidmaid. Thanks for submitting this documentation, some months ago we merged https://github.com/symfony/symfony-docs/pull/11328 which was based on your work in here. So I'm going to close this one. Hope to see you back in the future with more contributions!

**Pull request closed without merging**
