### PR TITLE
Reorder methods to be close to the given example

### PR DESCRIPTION
**Pull request by OskarStark**

### CODE REVIEW

**Comment by javiereguiluz** [comment]
I'd prefer to not sort methods differently. They are now sorted alphabetically, which is what we usually do in the docs. The other change look good to me.

**Comment by OskarStark** [comment]
Ok, shall I then move the code between the methods and keep the order?
I mean the example shows the usage of the method 🤔

**Comment by javiereguiluz** [comment]
I wouldn't change it either: code samples and descriptions are usually related, but not intimately related. Generally speaking, it should be OK to show options sorted alphabetically and then do whatever you want in the code example. Or maybe I'm missing something else here.

**Comment by OskarStark** [comment]
Ok, I will provide a PR just for the trait 👍

**Pull request closed without merging**
