### PR TITLE
[Reference][Form] Describe the syntax of format option using a link of DateTimeType

### PR DESCRIPTION
**Pull request by elementaire**
I've added a link to describe how to write a valid format. It is the same link from date and birthday types.

### CODE REVIEW

**Comment by javiereguiluz** [comment]
Let's ping @vudaltsov as a Symfony Form expert to help us here. The PHPdoc of the DateTimeType class has a lot of information. Also, the ticket opened at ICU project was answered six years ago: http://icu-project.org/trac/ticket/9421  Can we review the PHPdoc of DateTimeType and see if it's still relevant or outdated? Thanks!

**Comment by elementaire** [comment]
The same link is used in [DateType](http://symfony.com/doc/2.7/reference/forms/types/date.html#format) and [BirthdayType](http://symfony.com/doc/2.7/reference/forms/types/birthday.html#format) docs. It comes from [this template of this documentation](https://github.com/symfony/symfony-docs/blob/master/reference/forms/types/options/date_format.rst.inc). Depends on the answer of @vudaltsov, maybe it should be updated too.

**Review by vudaltsov — APPROVED** [review]

**Comment by vudaltsov** [comment]
@javiereguiluz , I think we should create a separate issue to see if the PHPdoc is still relevant.
What @elementaire proposed can be done in any case.

**Comment by javiereguiluz** [comment]
Thanks for this improvement and congrats on your first Symfony Docs contribution! Thanks to reviewers too!

**Comment by elementaire** [comment]
Should i do something for this to be merged in recent versions of docs too?

**Comment by javiereguiluz** [comment]
@elementaire there's no need to create new PRs. From time to time we merge all changes into the upper (maintained) branches. I've just do that, so your change is now in 2.7, 2.8, 3.4, 4.0, 4.1 and master. In a few hours, when symfony.com docs get rebuilt and caches expire, your change will be published. Cheers!

**Comment by elementaire** [comment]
Great :)

**Pull request merged**
