### PR TITLE
Improve presentation of createSharedEntry

### PR DESCRIPTION
**Pull request by tbredillet**
This is maybe better to display multiple entry because the function createSharedEntry() is made for have multiple files ?

### CODE REVIEW

**Comment by weaverryan** [comment]
Hey @razbounak!

Yes.... but actually, the array syntax won't work in the next version of Encore. So, what I *want* to do instead of encourage people to point to just one file - e.g. `app.js` and then require everything you need from *inside* of that file - e.g. `require('assets/js/vendor.js')`.

I think we should give an example of what your `app.js` might look like - e.g. requiring some items like `jquery` or another module from your code. That would make it more obvious how it works.

Would you like to try making that change?

Cheers!

**Comment by razbounak** [comment]
Ok, perfect
Sorry, I can't create the example alone :D

**Comment by javiereguiluz** [comment]
Any volunteer to help @razbounak create that example? Thanks!

**Comment by javiereguiluz** [comment]
Let's close this for now because the needed changes would be different. Also, although `createSharedEntry()` is not being removed soon, there's a new better alternative called `splitEntryChunks()`, so it's not worth it to keep improving the old method. See https://symfony.com/blog/encore-0-21-0-webpack-4-support-copy-files-support-webpackencorebundle for details.

**Pull request closed without merging**
