### PR TITLE
Update reset.rst

### PR DESCRIPTION
**Pull request by RobertErobert**
Added a note that the examples comes from ButtonType::class. #6864

### CODE REVIEW

**Comment by HeahDude** [comment]
Hello @DJWindless I think it will be easier to review and merge if you do all the changes in one PR, either this one or #7772.

**Comment by DJWindless** [comment]
Hello @HeahDude, sorry for this. This is my first time with github and PR. Next time i will do better :)

**Comment by HeahDude** [comment]
Please don't be sorry :), thank you very much for improving the docs on your first contribution!

**Comment by javiereguiluz** [comment]
I'm closing this as fixed by the alternative solution provided by #7824.

@DJWindless even if your pull request wasn't merged, it helped us notice this issue. So thanks a lot for your help!

**Pull request closed without merging**
