### PR TITLE
update

### PR DESCRIPTION
**Pull request by mysiar**
Update as presented example didn't work, looks like it was from 3.0 branch

### CODE REVIEW

**Comment by xabbuh** [comment]
Thank you for your pull request @mysiar. But this change looks wrong to me. Referencing form types by their FQCN was introduced in Symfony 2.8. Are you sure that you were working with Symfony 2.8 when you experienced this error?

**Comment by mysiar** [comment]
I use latest lts 2.8.* and experienced this problem during following that manual.
After change it works.
That's why I thought that it is wrong

**Comment by xabbuh** [comment]
Can you please show the exact error that you got? You can also give the output of `composer show` in your project please. The issue you experience may be related to some third-party bundle or library.

Anyway, I am closing here as this is not an error in the documentation though.

**Comment by mysiar** [comment]
Error message I get is
Could not load type [name of my Entity]
500 Internal Server Error - InvalidArgumentException

composer.show.txt](https://github.com/symfony/symfony-docs/files/542623/composer.show.txt)

**Comment by xabbuh** [comment]
The error message looks like it is related to your code. The best would be to use [one of the support channels](http://symfony.com/support) and provide the parts of your code that are necessary to help someone understand your issue.

**Pull request closed without merging**
