### PR TITLE
Add annotation to glossary

### PR DESCRIPTION
**Pull request by DerStoffel**
| Q | A |
| --- | --- |
| Doc fix? | no |
| New docs? | yes |
| Applies to | all |
| Fixed tickets | #6175 |

### CODE REVIEW

**Comment by javiereguiluz** [comment]
@DerStoffel thanks for this improvement. I like your definition ... except for the first phrase:

```
Annotations are notes written above your code.
```

Wikipedia [defines annotations](https://en.wikipedia.org/wiki/Annotation) as "metadata" to the source code. I consider that definition more precise. So, if you agree, could you change your first phrase by:

```
Annotations are metadata written alongside your code.
```

**Comment by DerStoffel** [comment]
@javiereguiluz Done and pushed.

I was not sure about metadata, since it is a very biased definition in software-development.
But what works for wikipedia, should also work for us :+1: :smile:

**Comment by xabbuh** [comment]
Not sure if we should add a note saying that annotations are placed in docblocks or if that isn't too much for the glossary. But besides that this looks good to me.

**Comment by DerStoffel** [comment]
Thought about that myself and chose not to. Had the feeling that it might be confusting towards @doc annotations or non-config annotations, which are technically placed in the docbloc, but not only for documentation purposes.

**Comment by xabbuh** [comment]
:+1:

**Comment by WouterJ** [comment]
Hi @DerStoffel! Thanks for creating this pull request.

As you've done a merge in your branch, I couldn't get this in the 2.3 branch cleanly. This is why I took your commits and created a clean branch + new PR: https://github.com/symfony/symfony-docs/pull/6230 I'll merge that one now instead. As the commits are kept, you will still recieve all credits.

**Pull request closed without merging**
