### PR TITLE
[Cookbook][Bundles]fix yaml syntax

### PR DESCRIPTION
**Pull request by mhor**
| Q | A |
| --- | --- |
| Doc fix? | yes |
| New docs? | no |
| Applies to | all |

### CODE REVIEW

**Comment by WouterJ** [comment]
:+1:

**Comment by javiereguiluz** [comment]
:+1:

**Comment by xabbuh** [comment]
Technically, the YAML syntax was valid before, but we need this change so that Sphinx renders the code block successfully. However, the code block will still be rendered without any syntax highlighting as the code block type is `text`. So I think we should either abstain from making this change or also change the code block type to `yaml`.

**Comment by mhor** [comment]
@xabbuh, I changed block type to ``yaml``. This yaml is technically invalid see [https://github.com/symfony/symfony-standard/issues/426](https://github.com/symfony/symfony-standard/issues/426)

**Comment by xabbuh** [comment]
:+1: 

Regarding the syntax, I think I will have to read the spec again and maybe we need to fix the Yaml component in regard of how to treat indicator characters. Thanks for pointing that out @mhor.

**Comment by xabbuh** [comment]
Thinking about this again, I think we should change the type of the code block back to text as the output that you see in your terminal won't be coloured either.

**Comment by mhor** [comment]
I agree with you @xabbuh.  I revert modification of ``code-block``

**Comment by xabbuh** [comment]
Thank you @mhor.

**Pull request merged**
