### PR TITLE
[Form] List Symfony UX form types

### PR DESCRIPTION
**Pull request by wouterj**
Ultimately, I think the Symfony UX docs should be completely moved to this repo. But I'm not sure what exactly the plans/ideas are for this.

Let's start by just advertising Symfony UX in the official docs :)

cc @tgalopin @weaverryan

### CODE REVIEW

**Comment by wouterj** [comment]
Oh my, we already stopped support for 5.2 :sweat_smile: Thanks Carson!

**Comment by 94noni** [comment]
> we already stopped support for 5.2

and 5.3 soon to be as well ^^

**Review by 94noni — APPROVED** [review]
+1 for referencing UX inside the main doc, for now it lives really alone (blog post)

**Comment by javiereguiluz** [comment]
Totally in favor of listing these form types.

My only question is about organization, especially future-proof organization. Do we want to mix UX types with regular types ... or do we group all UX types in a dedicated section to add some text and link explaining that they need Symfony UX, etc. ?

**Comment by wouterj** [comment]
@javiereguiluz I've moved them to their own little section

**Review by OskarStark — APPROVED** [review]

**Comment by javiereguiluz** [comment]
Thanks Wouter.

**Pull request merged**
