### PR TITLE
Remove mention of metadata_cache_driver

### PR DESCRIPTION
**Pull request by Philosoft**
As per
* doctrine/doctrine-bundle recipe (https://github.com/symfony/recipes/commit/b294873ff19d490c9d28c6a5e1120a139c4f3427#diff-2fdea05ded3928f852182177081cdd21c533951c0642388fa1303988702310a0)
* and doctrine/doctrine-bundle itself ([UPGRADE-2.3.md](https://github.com/doctrine/DoctrineBundle/blob/2.4.3/UPGRADE-2.3.md), [commit](https://github.com/doctrine/DoctrineBundle/commit/011cb9622788602505dc3e9f8e518428e9572aa9))

### CODE REVIEW

**Comment by mbabker** [comment]
As of 2.5 it’s no longer deprecated - https://github.com/doctrine/DoctrineBundle/pull/1405

**Comment by javiereguiluz** [comment]
Thanks Aleksandr! But as Michael said, it looks like this change was ultimately reverted. Let's close then.

**Comment by Philosoft** [comment]
omg. peculiar situation.

* 2.4 is the current version of `doctrine/doctrine-bundle`. in which `metadata_cache_driver` **is** deprecated. symfony docs mention that key, but flex recipe does not provide it
* 2.5 is not yet released. `metadata_cache_driver` is back in business again. symfony docs still mention key, but flex recipe still does not provide it

😱 but I totally get the decision for symfony-docs  👍

**Comment by javiereguiluz** [comment]
Actually, I'm going to reopen this ... see https://github.com/symfony/recipes/pull/1019

**Comment by javiereguiluz** [comment]
I can't reopen because the branch is deleted. Sorry for these troubles 😓  We can create the branch/PR again or maybe I can do the changes myself directly. Whatever suits you. Thanks!

**Pull request closed without merging**
