### PR TITLE
[Cache] Make sure the chain cache configuration works

### PR DESCRIPTION
**Pull request by Nyholm**
I just tried the configuration and noticed a few issues. 

~~Im not 100% sure this actually works.~~ Lets wait for https://github.com/symfony/symfony/issues/32139

Im sure now

### CODE REVIEW

**Comment by Nyholm** [comment]
I've updated the PR. 

I tested the new config and it works perfectly.

**Review by nicolas-grekas — APPROVED** [review]

**Comment by javiereguiluz** [comment]
@Nyholm can you please confirm that this must go to 4.3 branch and not to 3.4 or 4.2? Thanks.

**Comment by Nyholm** [comment]
Sorry, no. This is equally true for 3.4.

**Comment by javiereguiluz** [comment]
Thanks Tobias.

**Comment by Nyholm** [comment]
Thank you for the review and thank you for merging

**Pull request merged**
