### PR TITLE
Add use statement for InputDefinition

### PR DESCRIPTION
**Pull request by harikt**
| Q | A |
| --- | --- |
| Doc fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| License | MIT |

I think I send to the right branch.

Thank you

### CODE REVIEW

**Comment by javiereguiluz** [comment]
:+1: thanks @harikt

**Comment by xabbuh** [comment]
:+1: good catch

**Comment by WouterJ** [comment]
Thanks again @harikt, great job! I've merged this into the 2.3 branch, as we're still maintaining that version as well (and the article exists in this version).

**Comment by harikt** [comment]
Thank you @WouterJ :) .

**Pull request closed without merging**
