### PR TITLE
Simple typo fix

### PR DESCRIPTION
**Pull request by Renrhaf**
updated => update

### CODE REVIEW

**Comment by snoek09** [comment]
Good catch! Thanks @Renrhaf :+1: 

Status: reviewed.

**Comment by xabbuh** [comment]
👍

**Comment by javiereguiluz** [comment]
👍

**Comment by xabbuh** [comment]
Good catch, thanks @Renrhaf.

**Comment by Renrhaf** [comment]
Thank you !

**Comment by Guicom** [comment]
Nice job @Renrhaf

**Pull request merged**
