### PR TITLE
Documented the Twig extension priority

### LINKED ISSUE #9096: [TwigBundle] Added priority to twig extensions
See https://github.com/symfony/symfony/pull/24777.

### PR DESCRIPTION
**Pull request by javiereguiluz**
This fixes #9096.

### CODE REVIEW

**Review by rzilin — APPROVED** [review]

**Review by linaori — APPROVED** [review]
LGTM

**Review by gregurco — APPROVED** [review]

**Review by kkreft — APPROVED** [review]

**Comment by Xymanek** [comment]
How will this work if the service is also auto configured?

**Comment by javiereguiluz** [comment]
@Xymanek same as the other tags that allow priority. When using autoconfiguration you get a priority of `0` and can't change it.

**Comment by Xymanek** [comment]
Maybe it makes sense to mention that in docs? Because someone can think that to change priority they need to add a new tag, ending up with the service being tagged twice.

**Comment by javiereguiluz** [comment]
Not sure I follow you. You say *Because someone can think that to change priority they need to add a new tag* ... but that's exactly what you need to do. If you want a priority, you need to add the tag explicitly yourself.

**Comment by Xymanek** [comment]
If you add a tag to auto configured service, won't that service end up with 2 `twig.extension` tags? E.g.:

- Auto configured tag with default priority
- Manual tag with custom priority

**Pull request closed without merging**
