### PR TITLE
Update form_dependencies.rst: fix DI

### PR DESCRIPTION
**Pull request by ReDnAxE**
Fix service definitions for `__construct(EntityManager $em)` argument

### CODE REVIEW

**Comment by xabbuh** [comment]
:+1:

Status: Reviewed

**Comment by xabbuh** [comment]
Good catch, thanks @ReDnAxE.

**Comment by ReDnAxE** [comment]
@xabbuh sorry, but why this PR as been closed without being merged ?

**Comment by HeahDude** [comment]
@ReDnAxE This PR says "closed" because it was merged in 2.7 the oldest maintained branch needing that fix but was targeting master.

It will be merged in newer branches from there.

**Comment by ReDnAxE** [comment]
Ok thank you @HeahDude for the explanation, thank's @xabbuh ^^

**Comment by xabbuh** [comment]
@ReDnAxE Oh sorry, I didn't want to shock you. But @HeahDude explained our process very well. :) We always merge PRs into the lowest affected branch that is still supported and then frequently merge things up from there to master. So your changes will also be available soon on all other branches. :)

**Comment by ReDnAxE** [comment]
@xabbuh my fault ;) indeed I knew it !

**Pull request closed without merging**
