### PR TITLE
Update guard_authentication.rst

### PR DESCRIPTION
**Pull request by andreybolonin**
Fixed const usage, array syntax

### CODE REVIEW

**Comment by javiereguiluz** [comment]
@andreybolonin I'm afraid that we can't use the short array notation because it was decided to keep using the traditional notation, like Symfony does in its source code.

**Comment by javiereguiluz** [comment]
Personally I like the response constants a lot. Let's ask other doc maintainers (@xabbuh and @wouterj) if they agree too.

**Comment by xabbuh** [comment]
I am fine with using the constants for HTTP status codes. I guess that's more readable when you're not too familiar with all the possible codes.

**Review by javiereguiluz — APPROVED** [review]
👍

**Comment by xabbuh** [comment]
Thank you @andreybolonin.

**Pull request closed without merging**
