### PR TITLE
Add docs about console question answer normalizing.

### PR DESCRIPTION
**Pull request by SpacePossum**
Add description about how to use normalizing on an answer given on a question in a console application.

### CODE REVIEW

**Comment by HeahDude** [comment]
👍

Status: Reviewed

**Review by javiereguiluz — APPROVED** [review]
👍 

@SpacePossum I love it when we add docs for undocumented features. Thanks a lot!

I made some rewordings to your original text to match the style of the rest of the documentation. If you don't agree with something, please tell us!

**Comment by SpacePossum** [comment]
thanks @javiereguiluz for fixing the wording, all good :)   
:+1:

**Comment by xabbuh** [comment]
Thank you @SpacePossum.

**Pull request closed without merging**
