### PR TITLE
Added a note about Symfony Validator use outside framework context

### PR DESCRIPTION
**Pull request by mickaelandrieu**
Hi,

I think there is a lot more to say (Translating, object initializers, describe all mappings methods), maybe can we create docs for Validator component ? 

What do you think @lyrixx ?

### CODE REVIEW

**Comment by javiereguiluz** [comment]
There is a 3.5 years old issue about this (https://github.com/symfony/symfony-docs/issues/958) but it seems nobody is willing to work on it.

**Comment by mickaelandrieu** [comment]
@javiereguiluz I think I can do it.

**Comment by stof** [comment]
There is an initial work done in https://github.com/symfony/symfony-docs/pull/3710 but abandoned. You might want to start from it rather than starting from scratch

**Comment by mickaelandrieu** [comment]
thank you @stof 

So: 
- [ ] add a note to the actual documentation that will (probably) link to a new "Validator" section in components documentation;
- [ ] Create a new section "Validator" starting from @WouterJ old pull request;

does it sound good to you ?

**Comment by stof** [comment]
This section should not be in the book at all IMO. the book is talking about the fullstack framework. It is not talking about standalone usage (this is what the component documentation is about).

So I'm not sure this PR is a good idea actually (but the decision is not mine as I'm not one of the documentation maintainers). However, creating the validator component documentation is a very good idea (it is the only missing component)

**Comment by WouterJ** [comment]
@mickaelandrieu thank you for starting over and good luck! I propose to do the following (which is also what I wanted to do):

 * [ ] Create a new Validator section in the Components docs
 * [ ] *(components)* Document how to set up the validator in a standalone
 * [ ] *(components)* Move the current book chapter to a usage chapter in the components
 * [ ] *(components)* Move everything that's about framework specific things (like registering constraint validator by tagging them) back to a new book chapter and rewrite things so it's a smooth read again
* [ ] *(book)* Reread and tweak the new book chapter, so people don't get a too disoriented feeling, switching from book to components each time.

You can take the current translation docs as an example. If you have questions, need help, etc, feel free to leave a comment or ask for help in #symfony-docs on IRC.

**Comment by mickaelandrieu** [comment]
Hi @WouterJ : ok, I will do that.

I need time ... probably make a pull request the next week. Thank you for your help!

**Comment by WouterJ** [comment]
I'm going to close this PR in favor of documenting the component.

**Pull request closed without merging**
