### PR TITLE
5177 change echo and print in examples

### PR DESCRIPTION
**Pull request by snoek09**
| Q | A |
| --- | --- |
| Doc fix? | yes |
| New docs? | no |
| Applies to | all |
| Fixed tickets | #5177 |

Change echo/print in examples to use dump().

### CODE REVIEW

**Comment by weaverryan** [comment]
Hey Henry!

I'm :-1: on this, mostly because we can't use `dump()` anywhere in the components - because you may not have the `VarDumper` component installed in that project. Most of these changes are in the components.

In the framework, `dump()` needs to be used with a `die()`, else it won't show up (it'll show up in the WDT).

@snoek09 can you change the dump()'s in the components to var_dump()? And then add die statements into the framework stuff?

Thanks!

**Comment by weaverryan** [comment]
And to be more clear - the `book` and `cookbook` can be considered "framework" - and `components` is component stuff.

**Comment by snoek09** [comment]
@weaverryan that makes perfect sense. Thanks for clearing that up.

**Comment by snoek09** [comment]
Create a new PR as I deleted my fork: https://github.com/symfony/symfony-docs/pull/5388

**Pull request closed without merging**
