### PR TITLE
Update page_creation.rst

### PR DESCRIPTION
**Pull request by 94noni**
We concat strings :) 🪄 
Used to screenshot https://github.com/symfony/symfony-docs/pull/16346

### CODE REVIEW

**Comment by javiereguiluz** [comment]
I'm not sure about this. If PHP doesn't trigger a warning/notice/error, I think we shouldn't add this change (because it makes code slightly more noisy). I've checked and apparently it works with all current and past PHP versions --> https://3v4l.org/7tSBK

@symfony/team-symfony-docs what do you think about this proposal? Thanks!

**Comment by 94noni** [comment]
Yes, i know it works under the hood :)

But if we push the logic/reflexion of types, we are concatenating an int with 2 strings and concat is for strings

Feel free to close this was mainly to have a screenshot for related PR :)

**Comment by javiereguiluz** [comment]
Let's close this one because it's not strictly necessary and it slightly complicates the code example. Thanks!

**Comment by wouterj** [comment]
Agreed with this decision btw. In docs, the primary function of a code example is to show the feature we are talking about. All things that are not about the feature should be kept to a minimum (but often required to give some sense of context for the code snippet).

So while it's strictly better to explicitly cast to a string here, let's not do it.

**Comment by 94noni** [comment]
Thx for explanations both of you :)

**Pull request closed without merging**
