### PR TITLE
fixed use statement

### PR DESCRIPTION
**Pull request by OskarStark**

### CODE REVIEW

**Comment by OskarStark** [comment]
travis is failing due to:

```
Warning, treated as error:
/home/travis/build/symfony/symfony-docs/security/multiple_guard_authenticators.rst:81: WARNING: unknown document: /security/multiple_user_providers
```

**Comment by javiereguiluz** [comment]
Yes, the problem is exactly this phrase in `multiple_guard_authenticators.rst`:

```rst
If your authenticators need separate providers, you will need to create a 
:doc:`chain of user providers </security/multiple_user_providers>`.
```

The solution is to reword as this:

```rst
If your authenticators need separate providers, you will need to create a 
:doc:`user provider of type "chain" </security/user_provider>`.
```

Or maybe even remove the phrase ... because the next section in that article is: "Multiple Authenticators with Separate Entry Points"  Maybe that's the same or related somehow?

**Comment by xabbuh** [comment]
We do not have any explicit documentation of the chain user provider (we only mention it briefly in some places). So for now I would just remove this paragraph.

**Comment by javiereguiluz** [comment]
Thanks Oskar. The other unrelated issue was fixed in #10524.

**Pull request merged**
