### PR TITLE
Replace wrong classname to HandledStamp

### PR DESCRIPTION
**Pull request by aferrandini**
Fix issue #10740

#SymfonyConHackDay

### CODE REVIEW

**Review by kunicmarko20 — APPROVED** [review]
Nice catch!

**Comment by aferrandini** [comment]
@kunicmarko20 just fresh eyes 👀

**Comment by javiereguiluz** [comment]
Well spotted Ariel. Thanks for fixing it. Another one for the #SymfonyConHackDay !

**Comment by Nyholm** [comment]
#SymfonyConHackDay2018

**Pull request closed without merging**
