### PR TITLE
[2.7] [Serializer] fixes the order of the Serializer constructor arguments.

### PR DESCRIPTION
**Pull request by hhamon**

### CODE REVIEW

**Comment by hhamon** [comment]
Fixing doc typos while preparing my Serializer talk at DrupalCon :D

**Comment by xabbuh** [comment]
:+1:

**Comment by xabbuh** [comment]
Good luck with your talk @hhamon!

**Comment by hhamon** [comment]
It went quite well thanks! The slides are also online: https://speakerdeck.com/hhamon/data-serialization-with-symfony-and-drupal

**Comment by WouterJ** [comment]
Thanks Hugo!

**Pull request merged**
