### PR TITLE
Update remember_me.rst

### PR DESCRIPTION
**Pull request by atailouloute**

### CODE REVIEW

**Comment by wouterj** [comment]
Wow, did you run a PHP linter on our code examples to catch all these? :) 👍 

status: reviewed

**Comment by atailouloute** [comment]
@wouterj No I did not, I was just reading the doc before catching the first one, and then I searched in all files on the repo to make sure that there is always a semicolon at the end of each use statement.

**Comment by wouterj** [comment]
Ah, alright. Thanks for your time to check all files then! (I was thinking about automating it if you used a linter, but I don't think we can automate you 😄)

**Review by javiereguiluz — APPROVED** [review]

**Comment by atailouloute** [comment]
@wouterj I'll think about doing it when I have some time :D

**Comment by xabbuh** [comment]
Thank you @atailouloute.

**Pull request merged**
