### PR TITLE
Remove Yaml doctrine metadata examples

### PR DESCRIPTION
**Pull request by wouterj**
Doctrine 3 is dropping Yaml support. Let's make the docs future proof by not suggesting Yaml anymore. This will avoid new people to start writing Yaml metadata and having to rewrite all them when updating to Doctrine 3 in a few months.

### CODE REVIEW

**Comment by weaverryan** [comment]
Yep, good idea! 👍 

I found one other reference in `reference/configuration/doctrine.rst` - we simply mention `Post.orm.yml` in that file somewhere.

Status: Reviewed

**Comment by xabbuh** [comment]
In #6752 @Ocramius said that it is not settled yet whether the other mapping formats will stay the same. Maybe it's better to wait until a decision was made by the Doctrine team. If we needed to update all other examples anyway (and people would have to adapt all code anyway), it doesn't really matter which format they used before. What do you think?

**Comment by weaverryan** [comment]
Hmm, good point - it seems that other things might change. Let's wait until this is all finalized or nearly finalized. Fortunately, even if someone starts today with YAML, re-mapping that to XML or annotations is an automated process.

**Comment by wouterj** [comment]
Alright, closing then.

**Pull request closed without merging**
