### PR TITLE
Updating to PHP 7.4

### PR DESCRIPTION
**Pull request by ThomasLandauer**

### CODE REVIEW

**Review by OskarStark — COMMENTED** [review]
Currently we support PHP 7.2 so we should use that instead

**Comment by javiereguiluz** [comment]
Oskar, it's true that the minimum PHP version supported by Symfony is 7.2 ... but that's an unsupported version. That's why I think this change could make sense. My vote would be 👍  but I'm not sure if this could introduce any issues.

**Comment by ThomasLandauer** [comment]
The idea was to make it copy-pastable. Nobody who is starting a **new project** (which is the audience of this page) will go for anything prior to 7.4 today.
The existing numbers don't fit for *everybody*, and the new ones won't also - so IMO there can't be any issues ;-)

**Comment by OskarStark** [comment]
Agree then 👍

**Comment by javiereguiluz** [comment]
Thank you Thomas.

**Pull request merged**
