### PR TITLE
Update micro_kernel_trait.rst

### PR DESCRIPTION
**Pull request by amine-betari**
**__DIR__**  returns  **home/aminebetari/Projects/Symfony/my-project/src**

**dirname(__DIR__)** returns **/home/aminebetari/Projects/Symfony/my-project**

So if we keep in this example : 
require `__DIR__.'/vendor/autoload.php';`  we will have an error because the path is not correct 

But if we change by require `dirname(__DIR__).'/vendor/autoload.php';`  we will not have the error because we put the correct path

### CODE REVIEW

**Comment by OskarStark** [comment]
Can you please explain why we should change this? Thanks 🙏

**Comment by amine-betari** [comment]
@OskarStark 

Done !!

**Comment by OskarStark** [comment]
Thank you.
I did all the steps mentioned in the original paragraph. No errors, but when I add your proposed `dirname(__DIR__)` I got the following error:
Screenshot 2019-12-03 11 32 13
Here is my directory:
Screenshot 2019-12-03 11 32 26

**Comment by amine-betari** [comment]
@OskarStark 

current_errors

When i keep the current code i have this errror (PJ)


But when i change by my code, i don't have any errors


N.B : I 'm under linux/ubuntu

**Comment by OskarStark** [comment]
Are you using Apache nginx?
Built in php Webserver or Symfony Webserver?

**Comment by amine-betari** [comment]
@OskarStark 
I'm under WebServer Symfony

**Review by HeahDude — APPROVED** [review]
Thanks for that PR!

**Comment by wouterj** [comment]
Hi @amine-betari!

I think I found the confusion: You are putting the file in `src/index.php`, whereas Oskar is putting it in `index.php`. If you follow the paragraph (and also the recommendation with `symfony serve -d`), the index.php file has to live in the root (and not in `src/`).

To fix the confusion, I wanted to change this to put the filepath in a comment at the start of the codeblock (in commit e588747). Somehow, I completely messed up the commits in this PR, so I picked your commit and opened a new PR that I merged instead: #13088

Thanks for starting this PR and posting screenshots & details to help find out what's wrong here!

**Comment by amine-betari** [comment]
Hi @wouterj 
Thank you the essential for us is to move forward and help the community

**Pull request merged**
