### PR TITLE
Added a note concerning the tearDown method

### PR DESCRIPTION
**Pull request by Meyfarth**
Added a hint to properly close the connection depending on the PHP version.

### CODE REVIEW

**Comment by timglabisch** [comment]
this is not clear enough to me, we should provide a like to some kind of issue related to this.

**Comment by xabbuh** [comment]
I agree with @timglabisch.

@Meyfarth What are the conditions under which you to call the function and when do you have to do it? We should clarify them.

**Comment by Meyfarth** [comment]
I had the problem on my server : when testing with phpunit, I ended up with a "Too many connections" error.
I found this page to solve the problem, but after implementing it, the problem was still there. 
After some research, I found this solution and it worked like a charm.

Link : http://stackoverflow.com/a/26507379

**Comment by WouterJ** [comment]
For the SO question you linked to, it seems like closing the doctrine connection is better: http://stackoverflow.com/a/8518462/1149495

**Comment by Meyfarth** [comment]
I saw that one too, and tried it before finding the "gc_collect_cycles()" solution, with the same result -> Too many connections.

**Comment by javiereguiluz** [comment]
If I understand the linked answer correctly, they suggest to add both `$entityManager->getConnection()->close();` and `gc_collect_cycles()`.

Given that some people are suffering these problems (I suffered them myself too) I think we should make a last effort to finish and merge these changes. Thanks.

**Comment by stof** [comment]
DoctrineBundle 1.4+ closes the connection already on shutdown. No need to do it manually in all your tests (and WebTestcase shutdowns the kernel on teardown)

**Comment by stof** [comment]
btw, I don't see why ``gc_collect_cycles()`` might help here

**Comment by Meyfarth** [comment]
That's the point : there is no logic on that, I just had to do it to make it work, and obviously I'm not the only one who had this problem.

**Comment by stof** [comment]
btw, closing the entity manager is not necessary anymore either with DoctrineBundle 1.4+ as it also does it. So this article might be simplified.

**Comment by stof** [comment]
Actually, I have an idea why ``gc_collect_cycle`` might have an influence. It will force the GC to run, meaning that the container being discarded during the shutdown will then be collected with all services in it, while relying on the refcount alone is not enough because of circular dependencies (see https://github.com/symfony/symfony/issues/13448 for my proposal to help this). If the doctrine connection was GCed, it was of course closed at this time. And another case where it might be needed is for people using a PDO connection directly as they will stay connected until being destructed (either through refcount or GC).

**Comment by WouterJ** [comment]
So, now https://github.com/symfony/symfony/pull/15185 is merged, is this note still needed /cc @stof ?

If so, can we - now we know why this might be needed - formalize a more explicit note (like "If you do/use XXX and get an 'too many connections' error in your tests, add `gc_collect_cycles()` to the `tearDown` of your test").

**Comment by OskarStark** [comment]
@Meyfarth can you please answer to @WouterJ comment?

**Comment by WouterJ** [comment]
@stof can you please tell me whether this is still relevant, now we have a resettable container in Symfony?

**Comment by WouterJ** [comment]
Closing because of the lack of response and because nobody else seems to have this issue. Feel free to comment, there is a reopen button in GitHub :)

**Pull request closed without merging**
