### PR TITLE
Global variable "_self" has been deprecated

### PR DESCRIPTION
**Pull request by XWB**

### CODE REVIEW

**Comment by javiereguiluz** [comment]
Is this really the only alternative to `{% form_theme form _self %}` now that `_self` is deprecated? I feel like we are worsening DX (developer experience) a lot :(  @weaverryan any thought about this?

**Comment by stof** [comment]
@javiereguiluz using the current template as a form theme does not always work (a template without parent cannot be used as form theme, as rendering it would render all block it contains, which include all form theme blocks which must not (and probably cannot) be rendered in place in the template with your current context). And it can also create confusion by mixing blocks used for inheritance of your parent template and blocks used for form theming. My recommendation is to use separate templates for form themes anyway

**Comment by weaverryan** [comment]
Are macros affected? Or is `_self` deprecated only for form theming? I noticed the macro docs on Twig still advertise using `_self` (and I like using macros from my own template)

**Comment by stof** [comment]
@weaverryan there is a special case in Twig to import macros from the current template with ``_self``, without considering it as a usage of the ``_self`` variable to reference the current template object. This will stay possible, even though Twig 2.0 will not expose the current Twig_Template object to template authors

**Comment by weaverryan** [comment]
@stof great - thanks for the explanation!

@javiereguiluz if you want to be able to form theme using things in *this* template, we'll need to think of a different way to do it - e.g. `{% form_theme form '' %}` (I realize that's a bad example - using empty quotes, but you get the idea). It's already changed in Twig, so now it's up to us. I personally *would* like to keep this ability - it makes sense in many cases.

**Comment by stof** [comment]
@weaverryan we could even probably keep supporting it with ``_self``, as done for macros btw (will be a bit harder because of the support of mutliple form themes in the same tag)

**Comment by WouterJ** [comment]
The variable is now undeprecated: https://github.com/twigphp/Twig/issues/1932 It contains the template name instead of instance, but that doesn't break any of the code changed in this PR.

So I have to close this PR. Thanks for your contribution anyway, @XWB!

**Pull request closed without merging**
