### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by noniagriconomie**
I think `by` means like if SymfonyCloud is a CI or something like that
no? (feel free to close)

### CODE REVIEW

**Comment by tucksaun** [comment]
This was indeed not really clear.
The SymfonyCloud build kind-of serve as integration tests, I don't know if it would be more clear but maybe we should mention that is "built by" and made available available for preview **on **?

**Comment by noniagriconomie** [comment]
it just feels weird when i read it, that is why i opened this to find an improvement :)

**Comment by wouterj** [comment]
Let's ping our native @weaverryan here.

We use SymfonyCloud to build & serve a documentation for each pull request + the documentation is served on symfony.com, which runs on SymfonyCloud as well. So it's more "we use SymfonyCloud" than " we're build by SymfonyCloud" imho.

**Comment by javiereguiluz** [comment]
Thank you all for the discussion. To not keep this pull request too long, we decided to merge it but tweak the message. It now reads as follows:

```
Thanks to [SymfonyCloud](https://symfony.com/cloud) for providing an integration
server where Pull Requests are built and can be reviewed by contributors.
```

**Pull request merged**
