### PR TITLE
Fixes typo with reassigning env vars.

### LINKED ISSUE #11304: Wrong env file assignment
In `setup/symfony_server.rst` in the "Docker integration" paragraph there's a typo:
the code should be

`DATABASE_URL=${MYSQL_URL}`  instead of `MYSQL_URL=${DATABASE_URL}`

because you're going to override your local DATABASE_URL value with the autogenerated MYSQL_URL variable provided by the symfony cli tool.

### PR DESCRIPTION
**Pull request by dbrumann**
Fixes #11304

#EUFOSSA

### CODE REVIEW

**Review by xabbuh — APPROVED** [review]

**Review by OskarStark — APPROVED** [review]

**Comment by dbrumann** [comment]
@xabbuh and @OskarStark I added another small change in the paragraph above to make it more clear why this mapping is happening. Please reconfirm this change is still good for you.

**Review by OskarStark — APPROVED** [review]

**Comment by javiereguiluz** [comment]
@dbrumann thanks for fixing this error! I'm sorry I changed again your contribution ... but I wanted to make your (excellent) description a bit more concise to make it easier to read/understand. Thanks!

**Review by maxhelias — APPROVED** [review]

**Comment by dbrumann** [comment]
Thanks @javiereguiluz  your version is even better.

**Comment by wouterj** [comment]
Thanks a lot Denis! It took some tries, but it's perfect now!

**Pull request merged**
