### PR TITLE
[ConfigBuilder] Adding PHP ConfigBuilders for DoctrineBundle

### PR DESCRIPTION
**Pull request by Nyholm**
All doctrine bundle configuration is converted

### CODE REVIEW

**Comment by javiereguiluz** [comment]
Nice! Thank you

**Comment by Nyholm** [comment]
Thank you for merging

**Comment by Kaaly** [comment]
Hi,

i tried to use example for DoctrineConfig like this : 
```
        // config/packages/doctrine.php
        use Symfony\Config\DoctrineConfig;

        return static function (DoctrineConfig $doctrine) {
            $dbalDefault = $doctrine->dbal()
                ->connection('default');
            $dbalDefault->mappingType('enum', 'string');
        };
```

But no way to find `Symfony\Config\DoctrineConfig`.

Did i miss anything ?

**Comment by Nyholm** [comment]
Hey

it should be in your cache folder. The files are generated from your installed bundles.

**Comment by Kaaly** [comment]
ok found it !

Thanks !

**Pull request merged**
