### PR TITLE
Remove assumption about why people read the documentation

### PR DESCRIPTION
**Pull request by TimoBakx**

### CODE REVIEW

**Comment by javiereguiluz** [comment]
Timo, thanks for improving this. I'd go even further and remove this phrase entirely:

> People may read documentation because they know very little about a specific topic or are even completely new to it.

In addition to being a wrong and limited assumption ... it doesn't provide any value.

**Comment by TimoBakx** [comment]
You're right. The sentence after that covers the reason enough. I'll make the changes.

**Review by javiereguiluz — APPROVED** [review]

**Comment by javiereguiluz** [comment]
Thank you Timo.

**Comment by TimoBakx** [comment]
Thank you for the feedback and merging, Javier.

**Pull request merged**
