### PR TITLE
fixed argument order for UniqueEntity

### PR DESCRIPTION
**Pull request by ghost**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no 
| Issues        | none 
| License       | MIT

Updated parameter order to match order in the constructor to prevent showing a IDE warning.

### CODE REVIEW

**Comment by xabbuh** [comment]
We can merge this change as it’s not wrong per se, but I think this should also be reported with your IDE as the order does not matter when using named arguments as we do here.

**Comment by ghost** [comment]
I recently had a similar pull request in symfony/ux. 
https://github.com/symfony/ux/pull/1703

should i ignore this kind of thing in the future?

**Comment by xabbuh** [comment]
feel free to still submit this kind of PRs :)

**Comment by javiereguiluz** [comment]
This kind of PR are no fun for maintainers because it can introduce conflicts when merging into newer branches ... but it's true that the underlying problem (the IDE complaining about this) is very annoying. So, let's try to fix some of these issues until we decide that it's too much.

Thanks @LtMost!

**Pull request merged**
