### PR TITLE
Revert "minor #6479 Update php.rst (carlos-granados)"

### PR DESCRIPTION
**Pull request by wouterj**
This reverts commit fefc8a0426b6a438d7132b3035b1f5e0fab90a42, reversing
changes made to 7819f9e0fb24df69ba382a11be75a2c157c97388.

I messed up badly yesterday evening. This should make things good again. Please review if you have time (I'll merge it later this afternoon).

### CODE REVIEW

**Comment by HeahDude** [comment]
@WouterJ is this related to #6487 somehow? Because actually the reference of `CollectionType` is not among that diff.

**Comment by WouterJ** [comment]
@HeahDude yes, this fixes #6487 and #6486 The change is in the diff, but not the complete diff is shown on GitHub.

**Comment by HeahDude** [comment]
Alright, thanks @WouterJ, I've closed #6488 though.

**Comment by WouterJ** [comment]
I'll merge this now to avoid more troubles for the readers. If someone spots something wrong in the diff of this PR, please comment.

**Pull request merged**
