### PR TITLE
[AssetMapper] Removing PostCSS

### PR DESCRIPTION
**Pull request by ThomasLandauer**
Page: https://symfony.com/doc/6.4/frontend.html

Sorry for the back-and-forth!
2 reasons for deleting it again:
* I was thinking that PostCSS is some de-facto standard, but it isn't.
* It's odd to "recommend" something for CSS, but nothing for JS.

I just suggested to integrate minifying into AssetMapper: https://github.com/symfony/symfony/issues/54070

### CODE REVIEW

**Comment by smnandre** [comment]
Can we remove the entire line now? The goal of this table is to compare Webpack / AM. 

I'm not sure there is added value to list features that are _not_ provided in both cases.

**Comment by ThomasLandauer** [comment]
I added this line cause I wasn't aware that neither is minifying CSS. And since both are not doing it, the docs don't say anything about it - so I figured this would be a nice place to quickly inform people.

**Comment by javiereguiluz** [comment]
@smnandre generally speaking I agree with you (the table should not contain rows with two "no") but in this case I also agree with @ThomasLandauer because minifying CSS is something that many people still think about (although it's no longer important or needed)

**Comment by javiereguiluz** [comment]
Merged! Thanks Thomas.

**Pull request merged**
