### PR TITLE
Update homestead.rst

### PR DESCRIPTION
**Pull request by josedevega**
Just a tip for people using symfony components in their php projects

### CODE REVIEW

**Comment by xabbuh** [comment]
What is the difference when switching to this type?

**Comment by josedevega** [comment]
Hi


Provisioning of /etc/nginx/sites-available file, when type is symfony,*.php
requests return the php sourcecode.

I am sending both .sh files


Regards


> El 22 de julio de 2016 a las 22:45 Christian Flothmann

**Comment by javiereguiluz** [comment]
@josedevega thanks for proposing this improvement. We recently [changed the entire Symfony Docs](http://symfony.com/blog/introducing-the-new-symfony-documentation), so this pull request can no longer be merged. I'm sorry. I've recreated your changes in #6831.

**Comment by josedevega** [comment]
Hi @javiereguiluz 

Thanks for recreating it, I think it is important for the comunity.

Regards

**Comment by xabbuh** [comment]
Thank you for starting this @josedevega!

**Pull request closed without merging**
