### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by beni0888**
| Q | A |
| --- | --- |
| Doc fix? | yes |
| New docs? | no |
| Applies to | all |
| Fixed tickets |  |

### CODE REVIEW

**Comment by javiereguiluz** [comment]
@beni0888 nice catch! Thank you.

Just a comment for the next Pull Requests: when fixing a documentation error, we should always submit it to "the oldest Symfony branch which is still maintained". Currently, that means using "Symfony 2.3" instead of the "Symfony 2.6" version which you have used.

For this pull request it doesn't matter because documentation managers will take care of merging it on 2.3, so you don't have to modify this Pull Request and you don't have to send a new Pull Request. Just keep it in mind for the next Pull Request.

Again, thank you for helping us improving Symfony documentation.

**Comment by beni0888** [comment]
Thanks for your feedback @javiereguiluz , I'll keep it in mind for the next time :)

**Comment by WouterJ** [comment]
Thank you @beni0888!

**Comment by xabbuh** [comment]
@WouterJ We need to backport this to `2.3`.

**Comment by WouterJ** [comment]
@xabbuh yes, I was a bit too quite. If everything went well, it's done now

**Comment by xabbuh** [comment]
Thanks :+1:

**Pull request merged**
