### PR TITLE
Update ProgressBar docs with regress information

### PR DESCRIPTION
**Pull request by jameshalsall**
Doc updates for changes introduced in https://github.com/symfony/symfony/pull/19824

### CODE REVIEW

**Review by wouterj — APPROVED** [review]

**Comment by wouterj** [comment]
👍 
status: reviewed

Thanks a lot for providing the docs along the code PR!

**Comment by jameshalsall** [comment]
Ah, actually I need to update this as the API changed slightly. I will fix it tomorrow.

**Comment by jameshalsall** [comment]
This has now been updated to reflect the new API.

**Comment by jameshalsall** [comment]
@wouterj this needs to be merged for the 3.2 release

**Comment by javiereguiluz** [comment]
:+1:

**Comment by xabbuh** [comment]
Thank you @jameshalsall.

**Pull request closed without merging**
