### PR TITLE
[FrameworkBundle][Serializer] Add new framework bundle option to reference: circular_reference_handler

### PR DESCRIPTION
**Pull request by Nek-**
This PR provides documentation for this other PR https://github.com/symfony/symfony/pull/22011

It should not be merged before the related Symfony PR is merged.

It also fixes missing options in the example YAML config file.

### CODE REVIEW

**Comment by lyrixx** [comment]
LGTM :+1:

**Review by HeahDude — APPROVED** [review]
👍

**Comment by Nek-** [comment]
@javiereguiluz this PR is good to merge I guess.

**Comment by HeahDude** [comment]
This closes #7699.

**Comment by xabbuh** [comment]
Thank you @Nek-.

**Pull request merged**
