### PR TITLE
Complete documentation about mailer integration

### LINKED ISSUE #14066: [Mailer] Add a transport that uses php.ini settings for configuration
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#36131
| PR author(s) | @l-vo
| Merged in    | 5.2-dev

### PR DESCRIPTION
**Pull request by l-vo**
- Complete framework config reference with `Mailer` (based on #14087 plus `message_bus` and `headers` that was added after 4.4)
- Add documentation about `native` DSN protocol (symfony/symfony#36131)

Close #14066

### CODE REVIEW

**Comment by xabbuh** [comment]
Should parts of this be merged into the `4.4` branch?

**Comment by l-vo** [comment]
No `message_bus` and `headers` semantic configuration key were added in 5.x. So is the native mailer transport. I will try to fix conflicts tonight :)

**Comment by l-vo** [comment]
My bad, this PR include mailer configuration which should be available in 4.4. I will do another PR targeting 4.4.

**Comment by l-vo** [comment]
@xabbuh PR rebased + #14565 created to report changes on 4.4

**Comment by wouterj** [comment]
Hi @l-vo! So this was quite a merge :sweat_smile: Just to let you know what I did:

* I merged your new 4.4 PR (#14565) and removed the `headers` setting from it (as it was introduced in 5.2)
* I added the `message_bus` to the 5.1 branch (1da6b0b5e30017e126228a94893ce505ccbeb270), as I believe that's where it was introduced
* I merged this PR, minus all changes that were already done in 5.2. I believe both the native protocol and `headers` option were introduced in 5.2
* At last, I found #14087 which is also from you and had almost the same changes as your new 4.4 branch. I've closed that one, as I believe we both simply forgot about this PR and the changes are now already done.

**Comment by l-vo** [comment]
@wouterj oh sorry for the double PR targeting 4.4, I saw [this comment](https://github.com/symfony/symfony-docs/pull/14083#issuecomment-728825341) and then I forgot I already did a PR targeting 4.4 😅. Thank you for your explanations and your updates on it 👍

**Pull request merged**
