### PR TITLE
Fix: default excluded directories for services

### PR DESCRIPTION
**Pull request by nicoweb**

### CODE REVIEW

**Comment by xabbuh** [comment]
@nicoweb This looks good. 👍 But could you also update the XML and PHP config examples?

**Comment by javiereguiluz** [comment]
This is correct according to the latest recipe: https://github.com/symfony/recipes/blob/3b19bd94886555df1997b441b6cf6a1fab088f3a/symfony/framework-bundle/4.2/config/services.yaml#L18

Thanks @nicoweb.

**Comment by OskarStark** [comment]
Please note, that `Kernel.php` is also missing in the XML and PHP definitions 😃

**Review by xabbuh — APPROVED** [review]

**Review by OskarStark — APPROVED** [review]

**Comment by OskarStark** [comment]
Thank you Nicolas.

**Pull request merged**
