### PR TITLE
[Notifier] add Primotexto bridge

### LINKED ISSUE #19927: [Notifier] Add Primotexto bridge
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#54747
| PR author(s) | @Samael tomas
| Merged in    | 7.2

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 7.2 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

### PR DESCRIPTION
**Pull request by Goazil**
Update documentation to add primotexto : https://github.com/symfony/symfony/pull/54747

closes #19927

### CODE REVIEW

**Comment by OskarStark** [comment]
Please add a versionadded directive below the table, thanks

**Review by OskarStark — APPROVED** [review]

**Comment by OskarStark** [comment]
please rebase on 7.2

**Comment by OskarStark** [comment]
Can you please rebase your PR? Thanks

**Review by xabbuh — APPROVED** [review]

**Comment by javiereguiluz** [comment]
Thanks Samaël! And congrats on your first Symfony Docs contribution 🎉

**Pull request merged**
