### PR TITLE
Fix indentation in some annotations

### PR DESCRIPTION
**Pull request by iamdto**
| Q | A |
| --- | --- |
| Doc fix? | yes |
| New docs? | no |
| Applies to | all |
| Fixed tickets | - |

### CODE REVIEW

**Comment by WouterJ** [comment]
:+1:

**Comment by OskarStark** [comment]
good catch!

**Comment by xabbuh** [comment]
:+1:

**Comment by xabbuh** [comment]
Thank you @iamdto.

**Pull request merged**
