### PR TITLE
Update best_practices.rst

### PR DESCRIPTION
**Pull request by amine-betari**
// there is a public "router" service in the container
       $router = $this->container->get('router');

// this will not Work: MailLogger is a private service
     $mailLogger = $this->container->get(MailLogger::class);

### CODE REVIEW

**Comment by javiereguiluz** [comment]
@amine-betari thanks! This is correct ... but the reword implies that you can access to ALL public services, and that's not true. So ... what if reword this again and say something like this:

```
If you extend the base ``AbstractController``, you can only access to
the most common services (e.g. ``twig``, ``router``, ``doctrine``, etc.).
via ``$this->container->get()`` or ``$this->get()``. Use dependency
injection to fetch the rest of services [...]
```

**Comment by amine-betari** [comment]
@javiereguiluz  done

thank's

**Review by javiereguiluz — APPROVED** [review]

**Review by OskarStark — APPROVED** [review]
I am going to merge it

**Comment by OskarStark** [comment]
Thank you @amine-betari.

**Pull request merged**
