### PR TITLE
Update security.rst

### PR DESCRIPTION
**Pull request by senenh**

### CODE REVIEW

**Comment by OskarStark** [comment]
IMO it looks correct to like it is:
screenshot 2017-11-01 10 02 02

WDYT @javiereguiluz ?

**Review by weaverryan — APPROVED** [review]
Yep, we explicitly say at the top there are 3 steps. So this *should* be numbered :)

**Comment by weaverryan** [comment]
Status: Reviewed

**Comment by weaverryan** [comment]
Thanks @senenh!

**Comment by xabbuh** [comment]
backported to 2.7 in b38ac9b79a0cf5026d53d97d7b732b3ae11982e0

**Pull request merged**
