### PR TITLE
[Security] Fix `versionadded` directive

### PR DESCRIPTION
**Pull request by issamkhadiri1989**
hello

the previous versions of symfony used the Symfony\Component\Security\Core\Security service.

### CODE REVIEW

**Review by OskarStark — APPROVED** [review]

**Comment by OskarStark** [comment]
Friendly ping @chalasr

**Comment by issamkhadiri1989** [comment]
Thank  you @OskarStark  for the approval :)

**Review by chalasr — APPROVED** [review]
Good catch!

**Comment by OskarStark** [comment]
Thank you Issam.

**Pull request merged**
