### PR TITLE
[Console] Fix incorrect example for `CommandCompletionTester`

### PR DESCRIPTION
**Pull request by weitzman**

### CODE REVIEW

**Review by GromNaN — APPROVED** [review]

**Comment by xabbuh** [comment]
I wonder if showing this test does actually serve any purpose then. 🤔

**Comment by OskarStark** [comment]
Maybe @wouterj can help us out here

**Comment by wouterj** [comment]
Thanks for starting this PR!

What about only updating the comment, to make it clear when this is useful? For example:

```php
// If you filter the values inside your own code (not recommended, unless you
// need to improve performance of e.g. a database query), you can test this
// by passing the user input
$suggestions = $tester->complete(['Fa']);
$this->assertSame(['Fabien', 'Fabrice'], $suggestions);
```

**Comment by javiereguiluz** [comment]
@weitzman thanks for this contribution ... however, while merging I reworded it as indicated by @wouterj because I think the intention of this feature is more clear that way. Thanks!

**Pull request merged**
