### PR TITLE
Fix mailer example

### PR DESCRIPTION
**Pull request by rosier**
Changed the type hint to `Symfony\Component\Mailer\Transport\TransportInterface` instead of `Symfony\Component\Mailer\MailerInterface` to get `Symfony\Component\Mailer\SentMessage` from the send method.

### CODE REVIEW

**Review by OskarStark — CHANGES_REQUESTED** [review]
Please keep the message Id example

**Comment by rosier** [comment]
I have now changed the type hint instead of removing the message Id example

**Comment by javiereguiluz** [comment]
@rosier thanks for this contribution!

I personally had issues with this example and I couldn't understand why we didn't show the `SentMessage` example ... so I added it myself ... but now I understand why I was wrong.

Now I'm divided about this. Using `MailerInterface` is great, concise and looks beautiful. Using the `TransportInterface` in the very first mailer example looks ugly in my opinion.

Also, I don't understand why I can't get the SentMessage object with MailerInterface. It looks so obvious and basic to me ... I'm probably missing something here.

**Comment by rosier** [comment]
Using `MailerInterface` you can also send email async using a message bus. In that case there is no sent message yet.

Maybe it's better to revert this example and add an example using `TransportInterface` under
https://symfony.com/doc/current/mailer.html#debugging-emails

**Comment by HeahDude** [comment]
>Maybe it's better to revert this example and add an example using TransportInterface under
https://symfony.com/doc/current/mailer.html#debugging-emails

Or maybe we can add a comment about getting a `SentMessage` only with synch transports.

**Comment by rosier** [comment]
Closing in favor of https://github.com/symfony/symfony-docs/pull/13194

**Pull request closed without merging**
