### PR TITLE
Documented the new label_format option

### PR DESCRIPTION
**Pull request by javiereguiluz**
| Q | A |
| --- | --- |
| Doc fix? | no |
| New docs? | yes |
| Applies to | 2.6+ |
| Fixed tickets | #4286 |

### CODE REVIEW

**Comment by ubermuda** [comment]
Maybe there should be a note that this feature is actually implemented in the template and that it won't work if your form theme does not support it?

**Comment by stof** [comment]
this is a good idea indeed. People using a custom type should be aware they might need to update it.

**Comment by WouterJ** [comment]
ping @javiereguiluz

**Comment by WouterJ** [comment]
Hi @javiereguiluz! Do you maybe have some time to update this, or should I put it on the list for the sprint day?

**Comment by javiereguiluz** [comment]
@WouterJ sadly I'm not motivated to finish this PR, so please put it on the list. Thanks!

**Comment by WouterJ** [comment]
Closing in favor of https://github.com/symfony/symfony-docs/pull/5642

**Pull request closed without merging**
