### PR TITLE
preg_match throw an warning

### PR DESCRIPTION
**Pull request by nicolae-stelian**
The line 139 throw an warning: preg_match(): Unknown modifier ']'. Remove from regular expression the "/" character

### CODE REVIEW

**Comment by WouterJ** [comment]
Can you please replace it with `\/` (which also fixes the issue, but still allows the `/` character)?

status: needs work

**Comment by nicolae-stelian** [comment]
What you think if I write  the regex like that ( I think that is more readable) ?
$wsseRegex = '/UsernameToken Username="([^"]+)",'
                   . ' PasswordDigest="([^"]+)",'
                   . ' Nonce="([a-zA-Z0-9+\/]+={0,2})",'
                   . ' Created="([^"]+)"/';

**Comment by WouterJ** [comment]
To be honest, I don't like concatenation for new lines. We can use the `//x` flag, but then we need to replace all spaces with `\s`, which wouldn't help anything with readability.

For now, let's just change it to `\/`. We can always create a new PR for the line wrapping thing if other maintainers are on your side

**Comment by nicolae-stelian** [comment]
Ok. Thank'you.

**Comment by WouterJ** [comment]
👍 

status: reviewed

**Comment by javiereguiluz** [comment]
👍

**Comment by xabbuh** [comment]
Good catch, thanks @nicolae-stelian.

**Pull request closed without merging**
