### PR TITLE
small wording fixes

### PR DESCRIPTION
**Pull request by OskarStark**
Thanks @HeahDude I applied your comments from my other PR.

### CODE REVIEW

**Comment by OskarStark** [comment]
@HeahDude 

1) You mentioned we should remove this:
`* "Code doesn't match Symfony's CS rules (e.g. use ``[]`` instead of ``array()``)"`

But we should keep it, as of now it doesn't match Symfony CS if you use `array()`, and therefore its correct.

**Comment by OskarStark** [comment]
@HeahDude 

2) You mentioned `the?` on this line and I don't get it 😄 :

`By encapsulating some of its details or maybe adding some comments to explain the overall logic."*`

screenshot 2019-03-06 12 10 36

I created this PR and added your comments here as questions, because I will target the correct branch in my PR (#11080) and do a rebase, so your comments would get lost

**Comment by HeahDude** [comment]
I meant, what about:
```diff
-readable? By encapsulating some of its details or maybe adding some
+readable? By encapsulating some of the details or maybe adding some
```
?

**Comment by javiereguiluz** [comment]
Thanks Oskar! I made the pending change mentioned by Jules while merging.

**Pull request merged**
