### PR TITLE
fixed a typo

### PR DESCRIPTION
**Pull request by RickieL**
fixed a typo

### CODE REVIEW

**Comment by xabbuh** [comment]
:+1:

**Comment by javiereguiluz** [comment]
@RickieL nice catch! Thanks.

**Comment by xabbuh** [comment]
Good catch, thanks @RickieL.

**Comment by RickieL** [comment]
I am learning Symfony, thanks all for such a  good php framework and wonderfull job of the documents.  @xabbuh @javiereguiluz

**Pull request closed without merging**
