### PR TITLE
[Validator] Add `exclude` option to `Cascade`

### PR DESCRIPTION
**Pull request by alexandre-daubois**
Waiting code merge of https://github.com/symfony/symfony/pull/49596

### CODE REVIEW

**Comment by alexandre-daubois** [comment]
It's merged :slightly_smiling_face:

**Comment by OskarStark** [comment]
Please add a versionadded directive, thanks

**Comment by alexandre-daubois** [comment]
Oops, that's added!

**Comment by OskarStark** [comment]
Thank you Alexandre.

**Pull request merged**
