### PR TITLE
[Mailer] Update mailer.rst

### PR DESCRIPTION
**Pull request by ThomasLandauer**
Adding the word "array" cause I searched for it, and since I didn't find it, opened this (bogus) issue: https://github.com/symfony/symfony/issues/37657

Also added `addCc()` explicitly, since I also searched for this ;-)

### CODE REVIEW

**Comment by javiereguiluz** [comment]
I like most of these additions ... but I'm not sure about the array one. You _cannot_ pass an array to these methods; that's why the example uses `->to(...$toAddresses)` instead of `->to($toAddresses)`

**Comment by ThomasLandauer** [comment]
Well, how would you call it? "pass a *splat-operator-splatted* array"? ;-)

Sure we could expand on this aspect more. What about:

> Alternatively, you can pass multiple addresses to each method. If you pass an array, you need to use the splat operator.

But in the end, the code sample shows how to do it :-)

**Comment by javiereguiluz** [comment]
We could rename this:

```
Alternatively, you can pass multiple addresses or an array to each method::
```

As this:

```
These methods are variadic, so you can pass multiple addresses to them::
```

**Comment by ThomasLandauer** [comment]
Well, the very reason for this PR is to get the word "array" onto the page ;-)

**Comment by stof** [comment]
Well, this update is wrong. you **cannot** pass an array to these methods. If you want to pass multiple addresses, you **must** pass them as separate arguments. you *can* use the spread operator of PHP (`...`) to do that from an array you have, but that would still not pass the array to the method.

**Comment by ThomasLandauer** [comment]
I changed it to a comment in the code sample.

If you don't like that either ;-) we could rename the variable in the code sample from `$toAddresses` to `$addressesArray`.

**Comment by javiereguiluz** [comment]
Thomas, we finally merged this! Thanks for your contribution!

We kept the first change ... but we removed the comment (*"use the splat operator if you have an array"*). The code example is literally showing the splat operator in action, so we don't think it's necessary to mention it explicitly in the comment. Thanks!

**Comment by ThomasLandauer** [comment]
Looks like this is not online yet at https://symfony.com/doc/4.4/mailer.html#email-addresses
General question: How often are the pages rebuilt? Or what's the process of getting stuff online after the PR has been merged?

**Pull request merged**
