### PR TITLE
add default option value for collection type

### PR DESCRIPTION
**Pull request by xabbuh**

### CODE REVIEW

**Comment by xabbuh** [comment]
see https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Form/Extension/Core/Type/CollectionType.php#L89

**Review by HeahDude — APPROVED** [review]
Good catch, thx! To replace by the FQCN when merging in newer branches of course ;)

**Comment by xabbuh** [comment]
> To replace by the FQCN when merging in newer branches of course ;)

That's already the case thanks to #8831 :)

**Comment by javiereguiluz** [comment]
Thanks Christian.

**Pull request merged**
