### PR TITLE
Document that you can't pass empty strings to console options

### PR DESCRIPTION
**Pull request by javiereguiluz**
Related to https://github.com/symfony/symfony/issues/21215

### CODE REVIEW

**Comment by xabbuh** [comment]
👍 

Status: Reviewed

**Comment by chalasr** [comment]
I just added a commit that (I think) improves this situation, I think we should look at it before merging this. See https://github.com/symfony/symfony/pull/21228#issuecomment-272689414

**Comment by javiereguiluz** [comment]
I'm putting this PR on hold because the genius @chalasr has managed to solve this issue. See https://github.com/symfony/symfony/pull/21228

**Comment by chalasr** [comment]
@javiereguiluz fixed on master only due to the potential too much important impact, this stays correct for older branches.

**Comment by javiereguiluz** [comment]
@chalasr Thanks!

**Note to mergers**: merge in all branches EXCEPT master.

**Comment by xabbuh** [comment]
Thank you Javier.

**Comment by xabbuh** [comment]
Reverted in 9232842974839e7323f9b5829544391dd2117e1c in the `master` branch.

**Comment by chalasr** [comment]
I'll look for adding a note to explain the behavior change in 3.3 asap today

**Pull request merged**
