### PR TITLE
Update README.markdown

### PR DESCRIPTION
**Pull request by 94noni**
Ref [Symfony Releases Calendar](https://symfony.com/releases)

### CODE REVIEW

**Review by OskarStark — COMMENTED** [review]
The sentence is not true anymore while 5.4 is the lowest branch

**Review by wouterj — APPROVED** [review]
4.4 is still maintained for a year

**Comment by 94noni** [comment]
yes that is why I write 5.4 :)
but I just saw I target 5.4 not 4.4, and if I change the branch on github gui there are tons of fails
can you back port it or should I close and reopen on 4.4 ? thx

**Comment by javiereguiluz** [comment]
Thank you Antoine.

**Pull request merged**
