### PR TITLE
Use https for the installer file

### PR DESCRIPTION
**Pull request by javiereguiluz**
| Q | A |
| --- | --- |
| Doc fix? | yes |
| New docs? | no |
| Applies to | all |
| Fixed tickets | - |

### CODE REVIEW

**Comment by xabbuh** [comment]
@javiereguiluz We should change it in the big picture of the quick tour too.

**Comment by xabbuh** [comment]
And the PR should then be merged into the `2.3` branch.

**Comment by javiereguiluz** [comment]
I've just updated the Quick Tour. I'm really sorry about the branch mismatch. I wanted to create the PR for 2.3 but I forgot to change the branch number.

**Comment by xabbuh** [comment]
@javiereguiluz In the installation chapter, there is one last occurrence of `symfony.phar` when describing the installation on Windows. And there's is also one in the best practices section about creating a new project.

**Comment by javiereguiluz** [comment]
You are right. I've removed all the remaining `symfony.phar` occurrences. Thanks!

**Comment by xabbuh** [comment]
:+1:

**Comment by WouterJ** [comment]
I've put this on hold until we decide on https://github.com/symfony/symfony-installer/pull/152

**Comment by xabbuh** [comment]
@javiereguiluz What is the status here?

**Comment by javiereguiluz** [comment]
Closing it in favor of the new #6012

**Pull request closed without merging**
