### PR TITLE
[book] SC and validation ch changes

### PR DESCRIPTION
**Pull request by talitakz**
| Q | A |
| --- | --- |
| Doc fix? | yes |
| New docs? | no |
| Applies to | all |
| Fixed tickets | x |

### CODE REVIEW

**Comment by javiereguiluz** [comment]
@paxyknox thanks for proposing these improvements. The lack of feedback from reviewers is probably due to the huge set of changes. If there are a lot of changes, next time is better to change just one chapter per pull request.

Before reviewing in detail, I think we should revert all the changes related to titles and headings. The main reason is that these changes break all the existing links (we can prevent this adding some hidden labels, but is a bit boring to do so). Besides, the new doc search engine is able to return good results without adding these words to the section titles.

But before doing any change, let's wait for the opinion of our doc managers @xabbuh and @WouterJ.

**Comment by paxyknox** [comment]
At this point i should probably explain the proposed changes. When I decided to read through these two chapters and propose changes I didn't just looked at chapters as they are but I looked how they are placed in the book as a whole. I tried to determine what a person who might decide to read the book from the beginning to the end would already know then they would hit "Service container" and "Validation" chapters.. So concerning the content - nothing was removed(!) just reordered for a better word and content flow.

Yes. I agree. We should wait for the opining of the doc managers @xabbuh and @WouterJ.

**Comment by xabbuh** [comment]
I need to find some time to review this as this is really a lot of changes. On the first glance they look good but I need to do some deeper reviewing. I cannot promise when I will have the time to do the review but please feel free to ping me if I forget about it.

**Comment by paxyknox** [comment]
Ping ;) Just a friendly reminder. This yet needs to be reviewed.

**Comment by weaverryan** [comment]
Closing: see https://github.com/symfony/symfony-docs/pull/6252#issuecomment-231595552

**Pull request closed without merging**
