### PR TITLE
Typo in When Things Get More Advanced

### PR DESCRIPTION
**Pull request by BallisticPain**
Fixed `{id}` to `{postSlug}` to match the code example.

### CODE REVIEW

**Comment by WouterJ** [comment]
The "it" is refering to the parameter name in the section above it (about paramconverter). It tells you that this code works, as the parameter name equals the property name. Then it shows an example which doesn't work nicely, because parameter name doesn't equal the property name (postSlug in this case).

**Comment by BallisticPain** [comment]
@WouterJ 
Are you just informing me, or asking me to make a change to my commit in order to get this approved?

**Comment by xabbuh** [comment]
@BallisticPain Actually, the section as it is right now is technically correct. Though as you were confused by how it is written right now we can maybe improve this part. Do you have an idea how we could rewrite this to make it easier to understand?

**Comment by javiereguiluz** [comment]
Maybe we can reword a bit the first phrase of the *When Things Get More Advanced* section:

```diff
-This works without any configuration because the wildcard name ``{id}`` matches [...]
+The above example works without any configuration because the wildcard name
+ ``{id}`` matches [...]
```

**Comment by xabbuh** [comment]
sounds good

**Comment by BallisticPain** [comment]
That does sound good to me too. Would you like me to modify?
Apologies for the delay. Holidays and I forgot... ;)

**Comment by WouterJ** [comment]
:+1:

**Comment by xabbuh** [comment]
Thank you @BallisticPain.

**Comment by BallisticPain** [comment]
Happy to be of assistance. I think it's soo exciting to contribute to open-source projects!

**Pull request closed without merging**
