### PR TITLE
use diff code block for config changes too

### PR DESCRIPTION
**Pull request by xabbuh**
We already do that in the PHP code block below and I think doing the same here would make it more easier to follow what you need to do.

### CODE REVIEW

**Review by javiereguiluz — COMMENTED** [review]
I like this idea ... but I'm not sure about this specific case. The diff should add `-` to the previous route and `+` to the uncommented import. Showing the same route commented and uncommented is not that useful in my opinion.

**Comment by xabbuh** [comment]
Showing `-` for the previous route would be wrong as you do not have to remove existing definitions.

**Comment by xabbuh** [comment]
With symfony/recipes#260 we will be able to just remove the whole example. So I suggest that we just wait for it to be merged.

**Comment by weaverryan** [comment]
Closed in favor of #8726

**Pull request closed without merging**
