### PR TITLE
Document routing inline requirements and defaults for host

### PR DESCRIPTION
**Pull request by julienfalque**
Relates to symfony/symfony#37696.

### CODE REVIEW

**Review by wouterj — APPROVED** [review]
Thank you for fast response on closing the PR. This also made me realize your code feature was already merged, congrats!

:+1: let's merge this as well :)

**Review by OskarStark — APPROVED** [review]
The PR is ready, but shall we add an example? In the next major version the versionadded directives will be removed 🧐

**Comment by wouterj** [comment]
Thank you @julienfalque for documenting the changes you proposed to the Symfony code!

@OskarStark is correct about adding an example (as the versionadded will be removed some time in the future). So I've done exactly that in 1ae411b (and also moved the information to the section talking about the `host` setting).

**Comment by julienfalque** [comment]
Thanks @wouterj and @OskarStark!

**Pull request merged**
