### PR TITLE
[Form] Fix custom form type docs

### PR DESCRIPTION
**Pull request by aurimasrim**
1. Fixes the link to the twig config reference
2. Fixes the priority of order of `twig.form_themes` see https://symfony.com/doc/current/reference/configuration/twig.html#form-themes

### CODE REVIEW

**Comment by OskarStark** [comment]
@javiereguiluz maybe do you know if this is true. I am wondering, as we explicitly mention to add it to the beginning before and now it should be changed to the reverse... 🤔 I've never had more than one form_theme...

**Comment by javiereguiluz** [comment]
@OskarStark you made me doubt about this 😓 Let's ask Symfony Form experts like @xabbuh or @HeahDude  Thanks!

**Comment by HeahDude** [comment]
This is true as said in the linked documentation in the PR description.

**Review by HeahDude — APPROVED** [review]
Thanks for that PR!

**Comment by OskarStark** [comment]
Thank you @aurimasrim.

**Pull request merged**
