### PR TITLE
Update security.yml use auto for encoding

### PR DESCRIPTION
**Pull request by CarlSchwan**

### CODE REVIEW

**Review by OskarStark — APPROVED** [review]

**Review by maxhelias — APPROVED** [review]

**Comment by OskarStark** [comment]
Thank you Carl.

**Comment by phansys** [comment]
AFAIK, this is a duplicate of #11767.

**Comment by OskarStark** [comment]
Yours has mich more detail. Could you please rebase @phansys 
? We should merge yours too

**Comment by phansys** [comment]
I rebased #11767 before, it's up to date (I think).
Thank you.

**Pull request merged**
