### PR TITLE
Add service binding to argument name example

### PR DESCRIPTION
**Pull request by kbond**
I just learned this is possible - thought it should be documented.

### CODE REVIEW

**Comment by xabbuh** [comment]
Can you update the other config formats too?

**Comment by kbond** [comment]
I updated the xml/php config examples.

**Review by xabbuh — APPROVED** [review]

**Comment by javiereguiluz** [comment]
Thanks Kevin.

**Comment by javiereguiluz** [comment]
@xabbuh I finally merged this on 4.0 instead of 3.4 because on 3.4 we don't have the `binds` section in this article.

**Comment by xabbuh** [comment]
@javiereguiluz see #9804

**Pull request closed without merging**
