### PR TITLE
Add "allowed_classes" argument for unserialize()

### PR DESCRIPTION
**Pull request by comxd**

### CODE REVIEW

**Comment by wouterj** [comment]
I like this suggestion! :+1: Let's wait to hear what others think.

Status: reviewed

**Review by wouterj — APPROVED** [review]

**Review by weaverryan — COMMENTED** [review]
Hmmm, I don’t understand the option - can you explain? From reading, it seems like it will not allow any classes to be deserialized... but I’m sure I’m mistaken.

**Comment by comxd** [comment]
Hi @weaverryan. Yes, it's a required parameter from version 7.0.0 of PHP. @see http://php.net/manual/en/function.unserialize.php

**Comment by weaverryan** [comment]
It’s not required, right? Just available?

**Comment by comxd** [comment]
Sorry, you are right. It's symply recommended for security reasons.

**Comment by weaverryan** [comment]
Can you explain what it does? Why is it useful here? And what does it protect from? Sorry, I’m just not familiar - and the php.net description didn’t help much :)

**Review by xabbuh — APPROVED** [review]

**Comment by wouterj** [comment]
@weaverryan it disallows initiating classes from the serialized string. For instance, if a hacker is able to change the serialized string in the session, they are able to set the username for instance to some object. This can pose security issues.

Setting it to false gives a php error in this case.

**Comment by xabbuh** [comment]
Thank you @comxd.

**Comment by weaverryan** [comment]
Ah, yes yes. I understand now. I was thinking that this example WAS serializing a User object. But yes, it’s just an array - so it makes sense to restrict a class suddenly being unserialized.

**Pull request closed without merging**
