### PR TITLE
Use Doctor RST 1.59.0

### PR DESCRIPTION
**Pull request by alamirault**
[New rule : Ensure correct format for :phpfunction:](https://github.com/OskarStark/doctor-rst/pull/1688)

### CODE REVIEW

**Review by OskarStark — APPROVED** [review]

**Comment by OskarStark** [comment]
Thank you Antoine.

**Comment by OskarStark** [comment]
I upmerged the PR, please check the builds of the branches to spot any issues, thanks

**Comment by alamirault** [comment]
Looks good, thanks !

**Comment by OskarStark** [comment]
Thank you

**Pull request merged**
