### PR TITLE
always refer to getcomposer.org through HTTPS

### PR DESCRIPTION
**Pull request by xabbuh**
| Q | A |
| --- | --- |
| Doc fix? | yes |
| New docs? | no |
| Applies to | all |
| Fixed tickets |  |

Imho we should promote HTTPS where possible.

### CODE REVIEW

**Comment by dupuchba** [comment]
:+1:

**Comment by WouterJ** [comment]
@xabbuh seems like this is conflicting now (probably your spelling PR)

**Comment by xabbuh** [comment]
rebased this one

**Comment by WouterJ** [comment]
First merge of the day! Thanks Christian.

**Pull request merged**
