### PR TITLE
[Mailer] Fixed a typo in an env var name

### PR DESCRIPTION
**Pull request by javiereguiluz**
I don't know if this is an error or if it's correct ... but it looks wrong to me.

### CODE REVIEW

**Review by OskarStark — COMMENTED** [review]
I would say it was correct before

**Comment by javiereguiluz** [comment]
@OskarStark but what does `$SENDGRID_KEY` mean?

* If it's a PHP var, it should be `$sendgridKey`
* If it's a PHP constant, it should be `SENDGRID_KEY`
* If it's a placeholder, it should be `SENDGRID_KEY`

I'm confused by the leading `$`

**Comment by OskarStark** [comment]
It’s a reused ENV var IIRC

Ref https://github.com/symfony/recipes/pull/598

**Comment by xabbuh** [comment]
@OskarStark is right. The `SENDGRID_KEY` variable is declared on the line above.

**Comment by javiereguiluz** [comment]
Yes! Closing because I now realized my mistake. The empty `SENDGRID_KEY` env var confused me. This is "basic" env var stuff where you access the value of another env var. Sorry!

**Pull request closed without merging**
