### PR TITLE
Remove a caution note about StringUtils::equals() which is no longer true

### PR DESCRIPTION
**Pull request by javiereguiluz**
| Q | A |
| --- | --- |
| Doc fix? | yes |
| New docs? | no |
| Applies to | all |
| Fixed tickets | #5618 |

### CODE REVIEW

**Comment by OskarStark** [comment]
you should fix the headline of this PR ```cauion``` to ```cauTion```

**Comment by javiereguiluz** [comment]
Done :)

**Comment by OskarStark** [comment]
:smile:

**Comment by xabbuh** [comment]
:+1:

**Comment by paragonie-scott** [comment]
Looks good to me :+1:

**Comment by WouterJ** [comment]
:+1:

**Comment by WouterJ** [comment]
Thank you Javier.

**Pull request closed without merging**
