### PR TITLE
[WCM][Form] Rename "always_empty" in PasswordType to "reset_on_submit

### PR DESCRIPTION
**Pull request by snoob**
| Q | A |
| --- | --- |
| Doc fix? | no |
| New docs? | yes |
| Applies to | 2.6+ |
| Fixed tickets | symfony/symfony#6325 |

### CODE REVIEW

**Comment by WouterJ** [comment]
Closing as the upstream PR was also closed. (the issue is still open, so feel free to comment again once the core team decided the PR should still make it into the code)

**Comment by xabbuh** [comment]
@WouterJ Are you sure? symfony/symfony#11616 is still open.

**Comment by snoob** [comment]
Yeah it's still open cause they didn't come to an agreement. The new name (reset_on_submit) is still ambiguous. The new PR is https://github.com/symfony/symfony/issues/6325

**Comment by xabbuh** [comment]
Closing here as it was finally decided to keep the `allow_empty` option (see https://github.com/symfony/symfony/issues/6325#issuecomment-142956892).

Thank you very much anyway for taking of this and for your patience @snoob.

**Pull request closed without merging**
