### PR TITLE
[WIP] Cookbook grammar and style fixes

### PR DESCRIPTION
**Pull request by frne**
This is a follow-up for #4679 

It Fixes some general issues in grammar, style and readability.

(replaces #4693 which was the wrong target branch)

| Q | A |
| --- | --- |
| Doc fix? | yes |
| New docs? | no |
| Applies to | >= 2.3 |
| Fixed tickets |  |

### CODE REVIEW

**Comment by WouterJ** [comment]
@frne can you please fix the 2 outstanding comments?

**Comment by frne** [comment]
@WouterJ Sorry. Will do it next week. I'm on holidays w/o a notebook ;)

**Comment by WouterJ** [comment]
Hi @frne. do you have some time in the coming weeks/days? There will be a [doc sprint day](http://symfony.com/blog/symfony-docs-hack-day-needs-you-on-may-23rd) this Saturday were others can finish this PR if you want (if you want, please tell me so I can put it on the list).

**Comment by frne** [comment]
Sry. Much work these days. Will fix it next week.

**Comment by javiereguiluz** [comment]
I'm finishing this PR in #5427.

@frne don't worry about not having finished your PR. This happens sometimes. I've taken your work and finished in another PR. I've also reused all your original commits so you get the credit for your work. Thanks.

**Comment by xabbuh** [comment]
Thank you for starting this @frne.

**Pull request closed without merging**
