### PR TITLE
[Mailer] Better explain the load-balancing options

### PR DESCRIPTION
**Pull request by javiereguiluz**

### CODE REVIEW

**Comment by javiereguiluz** [comment]
Ping @weaverryan if you can, please review this. I'm not sure my wording is perfectly clear here. Thanks a lot!

**Comment by OskarStark** [comment]
I think you miss the latest change about „failover()“ and „roundrobin()“ here, which was merged in another PR yesterday? Today?

I am currently on a phone 📱

**Comment by javiereguiluz** [comment]
@OskarStark you are right ... but that change was made in 4.4 (as a BC break, but that's OK because it's still experimental). This one improves the explanation from 4.3, which is when this was introduced.

**Comment by OskarStark** [comment]
You are right 👍🏻

**Review by fabpot — COMMENTED** [review]
That's wrong: failover is not about load-balancing as it keeps using the same transport until it breaks. Only  round-robin is about load-balancing.

**Pull request merged**
