### PR TITLE
Mention Rector in the upgrading articles

### PR DESCRIPTION
**Pull request by javiereguiluz**

### CODE REVIEW

**Review by 94noni — APPROVED** [review]
It is more than enough to me
Thx for handling and answering issue

**Review by alamirault — APPROVED** [review]

**Review by xabbuh — APPROVED** [review]

**Review by OskarStark — APPROVED** [review]

**Comment by OskarStark** [comment]
5.4?

**Comment by 94noni** [comment]
Indeed it can be good as 5.4 is actual lts
And ppl may read this page to upgrade for next 6.4 :)

**Comment by xabbuh** [comment]
Thank you Javier.

**Pull request merged**
