### PR TITLE
Fixed example in docs throwing exception.

### PR DESCRIPTION
**Pull request by lukasz-zaroda**
`push` here ends in exception because there is no plugins array, we have to create it.

### CODE REVIEW

**Review by javiereguiluz — COMMENTED** [review]
Just asking: could this be better solved by initializing `bableConfig.plugins` to `[]`?

**Comment by lukasz-zaroda** [comment]
@javiereguiluz I assumed that Encore can add some plugins by default in the future, then my solution would still work just fine, and initializing to [] would overwrite these defaults causing some unexpected problems after an upgrade.

**Comment by lukasz-zaroda** [comment]
Yes, it probably could :) .

**Comment by javiereguiluz** [comment]
The default `babelConfig` of Webpack Encore initializes the `plugins` property to `[]`:

https://github.com/symfony/webpack-encore/blob/3e661e6f16dff6f872f0a156b14f73de7cb889a3/lib/loaders/babel.js#L30-L45

So I guess the current code is correct and we could close this pull request without merging it. We can also ask @weaverryan to verify this. Thanks!

**Comment by javiereguiluz** [comment]
We don't have more feedback about this, so let's close and we'll reopen later if needed. Thanks!

**Pull request closed without merging**
