### PR TITLE
Use Twig highlighter instead of Jinja

### PR DESCRIPTION
**Pull request by wouterj**
Pygments 2 supports the Twig highlighting language, which is (of course) closer to Twig than Jinja is.

Previously, we reverted one occurence of Twig in https://github.com/symfony/symfony-docs/pull/5378 , because people might use older versions locally. I no longer think this is a good reason:
- They can update the versions, Pygments 2 isn't that new
- Now we have platform.sh and travis, building locally isn't recommended/required anymore (if it ever was)

| Q | A |
| --- | --- |
| Doc fix? | yes |
| New docs? | no |
| Applies to | 2.3+ |
| Fixed ticket | - |

This requires https://github.com/fabpot/sphinx-php/pull/31 to be merged first. (and Pygments 2 to be available on symfony.com's server, but I think it already is /cc @javiereguiluz )

### CODE REVIEW

**Comment by javiereguiluz** [comment]
:+1: the new version of Sphinx has been released and the server should be ready (if not, I'll take care of it). Thanks for this improvement. Using anything different thatn `twig` felt unnatural to me.

**Comment by stof** [comment]
Please retrigger the Travis and platform.sh builds now that the extension is updated to support Twig, to see whether it works fine

**Comment by WouterJ** [comment]
Everything works fine now

**Comment by xabbuh** [comment]
:+1:

**Pull request merged**
