### PR TITLE
Change Apache php-fpm proxy configuration

### PR DESCRIPTION
**Pull request by TeLiXj**
| Q | A |
| --- | --- |
| Doc fix? | Yes |
| New docs? | No |
| Applies to | All |
| Fixed tickets |  |

I had problems using ProxyPassMatch and mod_rewrite and now I use SetHandler to send the request to proxy. This change works fine and should be the standar configuration in the future for Apache and php-fpm.
You can read the php developers discussion here http://www.serverphorums.com/read.php?7,956732 or some about problems fixed here http://blog.famillecollet.com/post/2014/03/28/PHP-FPM-and-HTTPD-2.4-improvement

### CODE REVIEW

**Comment by weaverryan** [comment]
Wow, very well-researched @TeLiXj! Thanks very much for this!

**Comment by xabbuh** [comment]
@TeLiXj I just noticed that the introduction now doesn't cover the configuration anymore. I started to reword it, but now I'm wondering if one still needs mod_proxy and mod_proxy_fcgi to be able to use the `SetHandler` directive in the right way. Can you help me with this?

**Comment by TeLiXj** [comment]
Of course, you always need mod_proxy and mod_proxy_fcgi to enable fpm-php on Apache. 
The use of SetHandler only simplifies the way to redirect requests to a FastCGI proxy

**Comment by xabbuh** [comment]
@TeLiXj Thank you, this helps me very much. And by the way, happy new year to you!

**Pull request closed without merging**
