### PR TITLE
remove obsolete versionadded directives

### PR DESCRIPTION
**Pull request by OskarStark**
These are older than the current `3.4` version and should be removed.

@javiereguiluz is this what you meant?
I will proceed after I got some feedback from you

cc @weaverryan

### CODE REVIEW

**Comment by javiereguiluz** [comment]
@OskarStark yes! This is perfect. On each major version we remove manually all versionadded directives that refer to older versions. It makes sense, because if you are reading 3.4 docs, you don't care if something was added in 3.2 or 3.1. Same if you are reading 4.2 docs ... you don't care if some change was made in 3.4 or 4.1.

The directives you removed here were the ones we forgot to remove manually. Thanks.

**Comment by OskarStark** [comment]
@javiereguiluz what do you think of https://github.com/symfony/symfony-docs/pull/11068/commits/ff0c6c30bc8a45e92408aadbf79a56aa8d679626 ?
Otherwise this info is gone or shall it be removed completely?

**Comment by wouterj** [comment]
> Otherwise this info is gone or shall it be removed completely?

I think removing it is fine. It's not really usefull information and IIRC services are private by default in newer symfony versions?

**Comment by xabbuh** [comment]
I am not convinced that we should really make this in the `3.4` branch. It will mean a lot of maintenance work if we do not only remove them once we start the docs for a new major version.

**Comment by OskarStark** [comment]
@xabbuh I am totally fine providing a PR against 4.2 or master, however you guys decide, but this is what I talked about with Javier

**Comment by wouterj** [comment]
In the past, we've used the following guideline (https://github.com/symfony/symfony-docs/issues/4774):

> * Remove all `versionadded` directives - and any other notes related to features changing or being new - for the version (e.g. 2.1) from the master branch. The result is that the next release (which is the first that comes entirely after the end of maintenance of this branch), will have no mentions of the old version (e.g. 2.1).

**Comment by OskarStark** [comment]
Ok so closing this PR and removing all obsolete versionadded directives from master which are not:

.. versionadded:: 4.3

?

**Comment by javiereguiluz** [comment]
@OskarStark your last comment is not correct :) What @wouterj showed is just a specific example ... the "general rule" is ... when a new version is created, all the previous "versionadded" are removed. That's why 4.2 should only have "versionadded:: 4.2" and not "2.x, 3.x, 4.0, and 4.1" (and "2.3" should have "versionadded:: 2.3" but not "2.0, 2.1, and 2.2").

@xabbuh this is what we've always _tried_ to do. Since this is a manual process (and since we "backdocument" things because we have a huge backlog) sometimes we forget about old "versionadded" directives.

Oskar, is it more clear now?

**Comment by OskarStark** [comment]
> Oskar, is it more clear now?

I think I already understood the problem here, and after your explanation, this PR is totally valid (currently not complete, as there are much more `3.3`, `3.2`, `2.x` versionadded-directives in the `3.4` branch) and I should proceed here, right? 🙈 😄

**Comment by OskarStark** [comment]
There are a few more, but they need some rework I guess.

Please review and after merging this I will check `4.2` and `master` for obsolete versionadded directives 👍

**Comment by javiereguiluz** [comment]
@OskarStark we talked about this in the private Symfony Docs team chat ... it turns out **I was completely wrong**. We remove "versionadded" directives when we create a MAJOR version, not a MINOR version. Example:

* 3.4 can contain 3.0, 3.1, 3.2, 3.3 and 3.4 directives ... but not 2.x
* 4.2 can contain 4.0, 4.1, and 4.2 directives ... but not 2.x or 3.x

So, we must close this as "won't merge" and instead, try to find 2.x and 3.x directives in 4.2 branch.

Oskar, I'm terribly sorry for having made you waste your time with this pull request 😢

**Comment by OskarStark** [comment]
> Oskar, I'm terribly sorry for having made you waste your time with this pull request 😢

really no problem, I will try to rework the rule 👍

**Comment by OskarStark** [comment]
In this case the following paragraph should be reworded: https://github.com/symfony/symfony-docs/pull/11081

**Pull request closed without merging**
