### PR TITLE
fix types

### PR DESCRIPTION
**Pull request by garak**
| Q | A |
| --- | --- |
| Doc fix? | yes |
| New docs? | no |
| Applies to | 3.0, master |
| Fixed tickets |  |

### CODE REVIEW

**Comment by javiereguiluz** [comment]
@garak in code we usually use the lowercase variant (`::class`). Maybe we should do the same for docs?

**Comment by garak** [comment]
That's weird, being `CLASS` a constant :disappointed:

**Comment by WouterJ** [comment]
@garak afaik, the constant is `class` (See also the original RFC https://wiki.php.net/rfc/class_name_scalars)

**Comment by garak** [comment]
I see. So, I changed the `::class` case

**Comment by xabbuh** [comment]
:+1:

**Comment by WouterJ** [comment]
:+1: (I'll rebase https://github.com/symfony/symfony-docs/pull/6058 after this one is merged)

**Comment by xabbuh** [comment]
Thank you @garak.

**Pull request closed without merging**
