### PR TITLE
[ExpressionLanguage] Fix redirects and revert merging reference docs with the main guide

### PR DESCRIPTION
**Pull request by wouterj**
Ref https://github.com/symfony/symfony-docs/pull/17724#discussion_r1067921675 for more information about why I believe we shouldn't want to merge the syntax doc in the main guide.

### CODE REVIEW

**Comment by fabpot** [comment]
Merging the spec with the main doc is what we've done for YAML, so it seems consistent to me.
I've no strong opinion though.

**Comment by wouterj** [comment]
Ah, I've missed that move. I must say that I think the same thing about that, I would prefer to keep a separate Yaml syntax reference.

**Comment by fabpot** [comment]
What about moving the YAML and expression language syntax docs under `reference/` then?

**Comment by xabbuh** [comment]
> What about moving the YAML and expression language syntax docs under `reference/` then?

sounds like a good idea to me

**Comment by fabpot** [comment]
Taking over here: #17817

**Comment by fabpot** [comment]
Closing as the other PR has been merged.

**Comment by wouterj** [comment]
Thank you Fabien!

**Pull request closed without merging**
