### PR TITLE
[Messenger] Use same buses names

### PR DESCRIPTION
**Pull request by Lctrs**

### CODE REVIEW

**Review by ogizanagi — APPROVED** [review]

**Review by OskarStark — APPROVED** [review]

**Comment by OskarStark** [comment]
Could you please squash your commits into one? We cannot squash merge it with our tool if there is a merge commit.

Thank you!

**Comment by javiereguiluz** [comment]
@OskarStark the branch name `patch-1` is usually associated with quick edits via gitHub's web interface ... so "squashing" is not possible in a simple way.

**Comment by OskarStark** [comment]
I know but how does the merge commit goes in then? 🧐

**Comment by Lctrs** [comment]
The merge commit is from the built in merge conflict tool of GitHub.

I'm currently on holidays. Will do it when I come back home on august, 1st.

**Comment by Lctrs** [comment]
@OskarStark Should be good now.

**Comment by OskarStark** [comment]
Thank you @Lctrs.

**Pull request merged**
