### PR TITLE
Simplify installation instruction when using npm

### PR DESCRIPTION
**Pull request by DerMonozukurist**

### CODE REVIEW

**Comment by mahalay** [comment]
Please hold... I'd like to add improvements to this PR.

**Comment by mahalay** [comment]
I need to clarify a few things:

1. Can encore be installed in three ways? (i.e., using `yarn`, `npm`, or `composer`)
2. Or is encore installed by either `npm` or `yarn` only, then one has to run `composer require encore`?

The reason I asked for the latter is due to the fact that installing encore using composer doesn't create the expected `node_modules/` directory. Without this directory, a newbie like me won't be able to follow the next set of instructions.

**Comment by mahalay** [comment]
This should be ready for review. I figured that the composer package encore is just there to initialize encore for your Symfony project. But the actual installation is through Yarn or Npm.

**Comment by weaverryan** [comment]
Closing in favor of the identical #8674, because I noticed it first ;).

@mahalay we only need the one PR, we'll merge into all branches.

**Pull request closed without merging**
