### PR TITLE
Documented the Lockable Trait

### LINKED ISSUE #6678: Document the LockableTrait
In Symfony 3.2 console command classes can make use of the `LockableTrait` which leverages the `LockHandler` from the Filesystem component to allow only one running instance of a command (see symfony/symfony#18471).

### PR DESCRIPTION
**Pull request by javiereguiluz**
This fixes #6678

### CODE REVIEW

**Comment by xabbuh** [comment]
Do we really need the first code example? Why not simply document only the second one?

**Comment by javiereguiluz** [comment]
@xabbuh I agree with you. Removed the first example.

**Comment by xabbuh** [comment]
👍 

Status: Reviewed

**Comment by xabbuh** [comment]
Thank you Javier. I have merged this in and added a `versionadded` directive in 50469f23d4b7ca5c89af996782974dac13e5a9c6.

**Pull request closed without merging**
