### PR TITLE
Update email.rst

### PR DESCRIPTION
**Pull request by mikaelz**
Use `name` defined in the controller.

### CODE REVIEW

**Comment by javiereguiluz** [comment]
@mikaelz thanks for your contribution. However, in this case, I'm not sure about the proposed changes. It seems like *You did it! You registered!* is the heading of this email, so there is no need to add a new one before it.

**Comment by mikaelz** [comment]
IN the controller there is name variable defined and not used in the view.
It would be a good example how to pass variable from controller to view.

**Comment by xabbuh** [comment]
As this cookbook article focuses on sending e-mails, I would rather not pass the `name` variable to the template.

**Comment by WouterJ** [comment]
Hi @mikaelz!

I agree with you, if we show how to pass a variable, we should use it in the template as well. I think showing that you can pass variables to a template is quite important detail for some people.

I also agree with @javiereguiluz, that the h3 is the title of the email. That's why I slightly tweaked the template to use the variable below the h3 after merging your PR in c53d20f.

Thanks!

**Pull request closed without merging**
