### PR TITLE
[Console] Remove occurrences of `$defaultName` and `$defaultDescription`

### PR DESCRIPTION
**Pull request by alexandre-daubois**
Fix https://github.com/symfony/symfony-docs/issues/18472

### CODE REVIEW

**Comment by javiereguiluz** [comment]
I like this ... but maybe we should update first the previous versions to mark these two properties as deprecated?

**Comment by alexandre-daubois** [comment]
Yes! Done here :slightly_smiling_face: https://github.com/symfony/symfony-docs/pull/18474

**Review by 94noni — APPROVED** [review]

**Comment by javiereguiluz** [comment]
Thanks a lot Alex!

While merging into 7.0 I didn't remove the `deprecated` directives that you added in #18474. Instead, let's do that as part of the global #18448 PR. Thanks.

**Comment by alexandre-daubois** [comment]
Got it, thanks! 👌

**Pull request merged**
