### PR TITLE
modernize the web server configuration chapter

### PR DESCRIPTION
**Pull request by xabbuh**

### CODE REVIEW

**Review by wouterj — COMMENTED** [review]
We don't seem to document the Apache config file location anywhere. Should we do that, to make clear that `.htaccess` is not recommended?

Other than that, I've never used Apache so I simply trust that you made the correct changes :+1:

**Comment by xabbuh** [comment]
Status: Needs work

**Comment by javiereguiluz** [comment]
@xabbuh do you think that you will find the time (and energy) to finish this ... or do you prefer if someone takes over or even if we close it? Thanks!

**Comment by wouterj** [comment]
continued in #17597

**Comment by xabbuh** [comment]
Oh, I completely forgot this PR. 🙈 Thanks for taking over Wouter!

**Pull request closed without merging**
