### PR TITLE
Remove Yoda Condition Rule from Code Standards

### PR DESCRIPTION
**Pull request by Coffee2CodeNL**
The IDEs have built in checks to prevent this from happening, no need to decrease readability for something so trivial.
Read English We Must!

### CODE REVIEW

**Comment by xabbuh** [comment]
I am :-1: on making this change. The document describes the coding standard of the Symfony core where we indeed want to have Yoda style (IIRC we even have a CS fixer rule enforcing it).

**Comment by greg0ire** [comment]
@xabbuh I could be mistaken but I think this PR proposes to remove Yoda from the coding standard, and to enforce that by configuring the CS fixer rule accordingly, not just to remove it from the document.

**Comment by iSDP** [comment]
@greg0ire you're not mistaken :)

**Comment by iSDP** [comment]
[I've made a poll to measure usage, please vote for what you use](http://www.strawpoll.me/15023680)

**Comment by dunglas** [comment]
The poll is biased, I use both Yoda style and IDE inspections...

**Comment by iSDP** [comment]
@dunglas if you use Yoda, the inspections would never fire.

**Comment by dunglas** [comment]
I have coworkers, and I sometimes work on legacy projects... I sometimes made mistakes too (like not using Yoda and doing an error).

**Comment by iSDP** [comment]
Hm, it does add unnecessary cognitive load while reading code, regular conditions read more naturally.

**Comment by ostrolucky** [comment]
I forbid Yoda conditions by using YodaStyleFixer and setting equal: false, identical: false, less_and_greater: false. 

Here is article I saved regarding those BV from @greg0ire: https://dev.to/greg0ire/why-using-yoda-conditions-you-should-probably-not

In 8 years of my professional career I don't recall any instance of accidental assignment in conditions, so I consider its benefit widely blown out of proportion. I even used AutoIt as main language before PHP, which uses single equals for comparison. Nowadays I regularly use assignments in conditions by purpose.

But we are not all same. I respect whoever uses Yoda style. It certainly reads worse for me, but I accept it if someone prefers opposite. I doubt Symfony will reconsider its use.

**Comment by robfrawley** [comment]
This process should start with a PR in the [symfony/symfony](https://github.com/symfony/symfony) repository. The documentation reflects the realities of the code, not the other way around, and right now the code style defined in the [symfony/symfony](https://github.com/symfony/symfony) project specifies the use yoda syntax.

That said, I prefer yoda style.

**Comment by weaverryan** [comment]
Closing: as @robfrawley said, this is a decision about the core code, so it should be discussed there. The docs just reflect the standards of the core :).

But, which format we should use in the *docs* is a different story. And we typically do *not* use Yoda conditionals in favor of readability.

**Pull request closed without merging**
