### PR TITLE
added blank line after .. versionadded:: directive

### PR DESCRIPTION
**Pull request by OskarStark**

### CODE REVIEW

**Review by weaverryan — APPROVED** [review]
It wasn’t always true, but it looks like it renders for with the line break now. So this is for consistency

**Review by xabbuh — APPROVED** [review]
I wondered about this some time ago, but it seems that the `versionadded` directive now behaves the same as other directives in more recent Sphinx versions.

**Comment by OskarStark** [comment]
> I wondered about this some time ago, but it seems that the versionadded directive now behaves the same as other directives in more recent Sphinx versions.

yes, I talked to Ryan before and we double checked if they get rendered correctly, and thats the case...

**Comment by OskarStark** [comment]
For you guys too 🎊🥳

**Pull request merged**
