### PR TITLE
Use Doctor RST 1.45.0 and new Rule `RemoveTrailingWhitespace`

### PR DESCRIPTION
**Pull request by alamirault**
Follow https://github.com/symfony/symfony-docs/pull/18262

cc @OskarStark

### CODE REVIEW

**Review by OskarStark — APPROVED** [review]

**Review by javiereguiluz — APPROVED** [review]

**Comment by OskarStark** [comment]
Thank you Antoine.

**Comment by OskarStark** [comment]
Upmerged ✅ 

Can you please check the upper branches to @alamirault ? Thanks

**Comment by OskarStark** [comment]
> Can you please check the upper branches to @alamirault ? Thanks

Done ✅

**Comment by alamirault** [comment]
Thank you Oskar

**Pull request merged**
