### PR TITLE
[Uid] Document NilUlid class

### LINKED ISSUE #15469: [Uid] Add NilUlid
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#41802
| PR author(s) | @fancyweb
| Merged in    | 5.4

### PR DESCRIPTION
**Pull request by javiereguiluz**
Fixes #15469.

### CODE REVIEW

**Review by OskarStark — APPROVED** [review]

**Comment by OskarStark** [comment]
Why is the `Code-Blocks` CI check failing? 🤔

**Comment by javiereguiluz** [comment]
I can't understand the failure either. The FQCN is correct, right?

**Comment by OskarStark** [comment]
It is, yes https://github.com/symfony/symfony/blob/6aa60fac88bace3fd7c5b026d95c38bba4ce7259/src/Symfony/Component/Uid/NilUlid.php#L12-L20

@Nyholm can you help us out here?

**Comment by Nyholm** [comment]
Excellent question. The CI job [check out](https://github.com/symfony/symfony-docs/blob/5.4/.github/workflows/ci.yaml#L152-L154) a Symfony application and try to insert the code example there. 

The Symfony application did not have the Uid component installed. I added the component in this PR: https://github.com/symfony-tools/symfony-application/pull/4

**Comment by Nyholm** [comment]
I've now merged in the UID component to all 5.2+ branches. If this CI job is restarted it will (hopefully) pass.

**Comment by OskarStark** [comment]
Thank you Tobias

**Pull request merged**
