### PR TITLE
Fix submit type

### PR DESCRIPTION
**Pull request by sfgn**
Update to the SubmitType form reference to have the correct namespace usage and class name.

### CODE REVIEW

**Comment by xabbuh** [comment]
What if we instead extracted the code example from the description but still reused the explanation?

**Comment by sfgn** [comment]
I think the explanation would be fine, just as long as you don't get the wrong namespace / class name as it can be a little confusing.

**Comment by xabbuh** [comment]
@sfgn Sorry if that was confusing. I don't want to drop the explanation. I would just remove the code example from the included file so to we would only share the explanation between the different types.

**Comment by sfgn** [comment]
You could do it that way but I'd personally prefer the code as it shows you without a doubt the correct namespace and class - but it'd be better to have no code than the one with the wrong info.

**Comment by WouterJ** [comment]
I'm 👎 on this change.

A lot of examples use the wrong form type, as we use one file for all settings. Duplicating these files for each form type means we get what we want to avoid: Lots of files with exactly the same information. If a setting description needs to be updated, we want to only need to update one code example.

Is having an example with a wrong class name really confusing? If it is, feel free to say so. We might need to rethink this decision (for instance, by only including the description in the file and having the code example in each form type file).

**Comment by sfgn** [comment]
It is a bit confusing, but not the worst thing ever. Could we not put namespace and/or class name at the very top of form field documentations instead then?

**Comment by WouterJ** [comment]
> Could we not put namespace and/or class name at the very top of form field documentations instead then?

It's put in the last row of the table at the top of each form type doc.

**Comment by sfgn** [comment]
Ah, apologies I may have just got confused when originally looking at the page and not noticed that it's actually in the table above.

**Comment by HeahDude** [comment]
👎 I agree with @WouterJ on this one even if I think the exact opposite concerning `empty_data` which deserves specific examples to avoid confusion imo.

Here the option works exactly the same so it does not add any value.

**Comment by WouterJ** [comment]
I'm going to close this PR. It's not worth the extra maintainance imo. If someone doesn't agree, feel free to comment (we can always reopen PRs).

**Pull request closed without merging**
