### PR TITLE
chore: Add missing semicolon

### PR DESCRIPTION
**Pull request by TheKhanj**

### CODE REVIEW

**Review by mdoutreluingne — APPROVED** [review]
👍 
(note for the mergers: this can be merged in 5.4)

**Review by OskarStark — APPROVED** [review]

**Comment by OskarStark** [comment]
Thanks @mdoutreluingne these information are very helpful. I added the 5.4 milestone.

@TheKhanj thanks for the fix, we take care of merging it into 5.4 👌🏻

**Comment by javiereguiluz** [comment]
@TheKhanj thanks and congrats on your first Symfony Docs contribution 🎉 

Thanks to reviewers too 🙌

**Comment by TheKhanj** [comment]
Thank you all, I am really flattered, you know I just added a single semicolon :), I didn't expect much appreciation :) :heart:

**Pull request merged**
