### PR TITLE
Fix server configuration for Symfony 4

### PR DESCRIPTION
**Pull request by michaelperrin**
I started this PR from #8679 to add more fixes to it.

There is still one thing that is not correct, about `.htaccess` files that Symfony 4 doesn't provide anymore. This should be part of an other PR (and maybe create a recipe to create these files, I will look into it).

### CODE REVIEW

**Comment by michaelperrin** [comment]
It's not really part of the server configuration, but we should also update the http://symfony.com/doc/master/configuration/override_dir_structure.html article (which deals with the `web` dir as well).

**Review by weaverryan — APPROVED** [review]
This looks great! I've added a separate issue about Apache and also linked to your comment about overriding the directory structure from another issue.

**Comment by weaverryan** [comment]
Thank you Michaël!

**Comment by michaelperrin** [comment]
Thanks @weaverryan! More to come soon 🙂

**Pull request merged**
