### PR TITLE
Minor grammar fix

### PR DESCRIPTION
**Pull request by aalaap**
Removed 'But' at the beginning of the first sentence under 'Types of Caches'.

### CODE REVIEW

**Comment by javiereguiluz** [comment]
👍 

Minor but nice. I like it. Thanks @aalaap

**Comment by aalaap** [comment]
The devil is in the details! :relieved:

**Comment by javiereguiluz** [comment]
Status: Reviewed

**Comment by WouterJ** [comment]
Quick win. Thanks Aalaap!

**Pull request merged**
