### PR TITLE
Fix typo: signifcantly => significantly

### PR DESCRIPTION
**Pull request by ifdattic**
| Q | A |
| --- | --- |
| Doc fix? | yes |
| New docs? | no |
| Applies to | all |
| Fixed tickets |  |

### CODE REVIEW

**Comment by javiereguiluz** [comment]
👍

**Comment by WouterJ** [comment]
Thanks Andrew!

**Comment by WouterJ** [comment]
Btw, @javiereguiluz, do you have any idea why your comment shows up as `👍` in the API instead of `:+1:` (which is the case for other people's comments)? https://api.github.com/repos/symfony/symfony-docs/issues/6483/comments It breaks the core team voter of gh atm.

**Comment by javiereguiluz** [comment]
@WouterJ 😱  I don't know. I don't remember doing anything different.

**Comment by xabbuh** [comment]
@javiereguiluz How do you write your comments? Can this be caused by a saved reply? You can see that your vote is also shown as the icon when you edit your existing comment above.

**Comment by javiereguiluz** [comment]
@xabbuh I write `:+1:` by hand (and I don't have any browser extension that modifies GitHub in any way).

**Comment by ifdattic** [comment]
I also think this article could be improved a little bit. It has a small section about fixing performance issues, but in my opinion it's mostly "here take this, go figure it out yourself". Think that it could use the 80/20 approach an be more like "before investing a lot of time try this trick, it works most of the time". If adding that information the biggest question would be in that format: a paragraph of text, a commented out code, or something else.

In my opinion that should be noted are:
* adding `nfs` type
* changing session directory
* nfs plugin for windows users

This video kind of provides the problem and solution (https://www.youtube.com/watch?v=Kn-O4jq0-r4)

/ping @javiereguiluz @WouterJ @xabbuh

**Pull request closed without merging**
