### PR TITLE
Remove Debugging Guide

### PR DESCRIPTION
**Pull request by weaverryan**
In 3.4, the debugging article has details about `bootstrap.php.cache`, etc. But in 4 (as you can see), it has almost nothing! I think we should remove it (and remove the Guide link on Symfony.com for version 4). The individual `debug:` commands should be documented in those sections - nobody will click "Debug" so they can learn about how to debug something specific (e.g. translations).

Cheers!

### CODE REVIEW

**Review by javiereguiluz — APPROVED** [review]
I like this proposal. I'd be more happy if the debugging commands were already moved to their new locations instead of "losing" them ... but we can do that in a separate PR.

**Comment by weaverryan** [comment]
@javiereguiluz when we merge this, will the guide link automatically disappear on symfony.com (for 4.0 only)? Or does more work need to be done for that?

**Comment by wouterj** [comment]
#7071 😢

**Comment by weaverryan** [comment]
@wouterj Oh no!!! I completely ran over your work :/. I'm sorry. My vote is still to merge this PR... because (as nice as your article is), it doesn't contain a *lot* of content (I like the details on `dump()`, but we should show that elsewhere, and I also have seen that almost everyone knows about this function... somehow).

**Comment by weaverryan** [comment]
@javiereguiluz if you still agree with this proposal, could you remove the Debugging entry from symfony.com? Thanks for removing the other sections on my other PR :)

**Comment by weaverryan** [comment]
ping @javiereguiluz!

This is not super important, but I'd love to finish it :)

**Comment by javiereguiluz** [comment]
I've removed the link to "Debug" ... it will be online after the next deploy. Thanks!

**Pull request merged**
