### PR TITLE
Groups option, missing

### PR DESCRIPTION
**Pull request by goncziakos**

### CODE REVIEW

**Comment by javiereguiluz** [comment]
Ping @goncziakos. Could you please share some details about when this option was added to UniqueEntity? Thanks!

**Comment by wouterj** [comment]
Hi @goncziakos! Looking at the description of this option, I think you might have confused it's naming with [`validation_groups`](https://github.com/symfony/form/blob/master/Extension/Validator/Type/BaseValidatorExtension.php). Are you sure it's called `groups`?

If you agree, please update this pull request so we can merge it.

**Comment by xabbuh** [comment]
I think @goncziakos indeed wants to describe the `groups` option which is defined by the base `Constraint` class and which we show, for example, in http://symfony.com/doc/current/validation/groups.html. However, this option is available in all constraints. So I think we should find a generic description and add it to all constraint reference pages.

**Comment by javiereguiluz** [comment]
Closing as fixed by #11092.

**Pull request closed without merging**
