### PR TITLE
Update simple-example.rst

### PR DESCRIPTION
**Pull request by aleixfabra**

### CODE REVIEW

**Review by Lyrkan — APPROVED** [review]

**Comment by wouterj** [comment]
👍 
status: reviewed

**Review by javiereguiluz — APPROVED** [review]
Nice catch! Thanks.

**Comment by javiereguiluz** [comment]
Note to mergers: this is a duplicate of #8292.

**Comment by xabbuh** [comment]
@aleixfabra thanks for fixing this bug. Sadly, it has been reported before (see #8292 which has been merged in the meantime). So I have to close your PR. I hope to see you back soon with some other contributions.

**Pull request closed without merging**
