### PR TITLE
added examples for squashing

### PR DESCRIPTION
**Pull request by OskarStark**

### CODE REVIEW

**Comment by javiereguiluz** [comment]
@OskarStark thanks for adding this tip about squashing commits.

However, I'd like to propose to not merge this PR and even to remove any reference to commit squashing. Why? Because Symfony project uses a proprietary tool which automatically squashes all commits before merging. That's why on `symfony` and `symfony-doc` we no longer ask users to squash their commits.

The less hurdles we define for collaborating with Symfony, the better.

**Comment by OskarStark** [comment]
Hey @javiereguiluz 

thanks for the detailed answer. I agree with you , but then I would write down explicitly so.

@hurdeless: :+1:

**Comment by javiereguiluz** [comment]
@OskarStark if the Symfony doc managers agree on removing any reference to squashing commits, I agree with you about explaining that we no longer require squashing. Thanks.

**Comment by OskarStark** [comment]
:+1:  lets see, what they say! :smiley:

**Comment by xabbuh** [comment]
For me, that's okay. But I leave the final word to @weaverryan and @WouterJ who do the actual merges.

**Comment by weaverryan** [comment]
+1 - let's remove everything about squashing. Thanks @OskarStark for bringing attention on this - let's make things easier!

**Comment by xabbuh** [comment]
@OskarStark Can you please remove all the squashing stuff then? :)

**Comment by OskarStark** [comment]
#5432

**Comment by xabbuh** [comment]
closing in favor of #5432 then

**Comment by WouterJ** [comment]
Thank you for your patience and great actions on this PR Oskar. You deserve the Documenation Contributor Badge on SensioLabs Connect (which will be awared in a few hours/days)! :)

**Comment by WouterJ** [comment]
Hmm, our merge tool didn't really get which PR I wanted to merge...

**Comment by OskarStark** [comment]
yeah, great, thank you!

@problem: can i help @WouterJ

**Comment by WouterJ** [comment]
I believe I've merged the correct PR now (and I've reverted this merge)

**Comment by OskarStark** [comment]
@WouterJ didn't get the badge already :(

**Comment by xabbuh** [comment]
@OskarStark Is the e-mail address you used in the commit also associated with your SensioLabs Connect account?

**Comment by OskarStark** [comment]
yes it is

**Comment by OskarStark** [comment]
maybe it is, because @WouterJ merged the other PR?

- #5432

**Comment by WouterJ** [comment]
@OskarStark sensiolabs connect uses the commits, and you are the author of some commits in the doc repository: https://github.com/symfony/symfony-docs/commits?author=OskarStark

There has to be something wrong with your emailadress. On the [doc contributors page](http://symfony.com/contributors/doc), you're on place 622 at the moment of writing this comment. As you can see, it displays just your name and no link to your sensiolabs account. This means it can't match your commits to your sensiolabs profile.

**Comment by javiereguiluz** [comment]
@OskarStark this issue happens when the GitHub email is not exactly the same as the SensioLabs Connect profile one. The solution is very easy: you can add any number of emails in your SensioLabs Connect account at https://connect.sensiolabs.com/#!email

However, you say that the email address is the same ... so I'm going to investigate which could be the cause of this problem.

**Comment by OskarStark** [comment]
could this be the problem?

Keep my email address private
We will use OskarStark@users.noreply.github.com when performing web-based Git operations and sending email on your behalf. If you want command line Git operations to use your private email you must

**Comment by WouterJ** [comment]
@OskarStark I think that could be the problem. The solution is to add this email to the email list on your SensioLabs account.

As you can see, the Github API indeed returns your commits with the `OskarStark@users.noreply.github.com` commit: https://api.github.com/repos/symfony/symfony-docs/pulls/5368/commits

**Comment by OskarStark** [comment]
and for this pr is used the web interface completely

**Comment by OskarStark** [comment]
@WouterJ i will do, give me a second

**Comment by WouterJ** [comment]
(be aware that after you added your email, you have to wait until the system rebuilds, so check again tomorrow if everything is fixed)

**Comment by OskarStark** [comment]
ok, i added it, but i'm not sure if i get a confirmation mail to this mailadress

**Comment by javiereguiluz** [comment]
Sadly the badges aren't granted in a retroactive fashion when changing or updating the emails, so we'll need to wait until the next contribution.

**Pull request closed without merging**
