### PR TITLE
Fix: make class clickable

### PR DESCRIPTION
**Pull request by Art4**
Small fix that makes the `Symfony\Component\Serializer\Normalizer\NormalizableInterface` class clickable to see the api.

This affects the maintained branches 3.4, 4.2 and master.

### CODE REVIEW

**Comment by Art4** [comment]
Oh, I see. Will do that.

**Comment by Art4** [comment]
I've changed the branch to 3.4

**Review by javiereguiluz — APPROVED** [review]
Thanks! It looks nice now!

**Comment by javiereguiluz** [comment]
Thanks Artur.

**Pull request merged**
