### PR TITLE
[Framework] Read env var SYMFONY_IDE by default for framework.ide

### PR DESCRIPTION
**Pull request by 94noni**
Fix https://github.com/symfony/symfony-docs/issues/16232
friendly ping @GromNaN (very useful :))

### CODE REVIEW

**Comment by GromNaN** [comment]
Thank you @94noni. Could you update the default value also.

**Comment by 94noni** [comment]
@GromNaN please see https://github.com/symfony/symfony-docs/pull/16315/commits/bb2b5fbd95f73b7f94d313f7d32127141d5be851 if it is what you meant, thanks

**Comment by javiereguiluz** [comment]
Thanks Antoine.

**Comment by javiereguiluz** [comment]
Please note that while merging this, I removed the entire config example that used an env var, because the good thing of this feature is that you only need to configure the `SYMFONY_IDE` env var and do nothing else.

**Pull request merged**
