### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by SofHad**
| Q | A |
| --- | --- |
| Doc fix? | yes |
| New docs? | no |
| Applies to | all |
| Fixed tickets | no |

The word "performant" doesn't exist.

### CODE REVIEW

**Comment by stof** [comment]
the optimized autoloader is not more powerful. It is faster (which is what the French word ``performant`` means)

**Comment by javiereguiluz** [comment]
@SofHad thanks for reporting this error! Indeed, the `performant` word doesn't officially exist in English. We should reword that paragraph and talk about the great performance boost that provides that Composer option.

**Comment by SofHad** [comment]
+1 for faster.
The ``--optimize-autoloader`` flag makes Composer's autoloader much faster and more efficient ...

**Comment by xabbuh** [comment]
"faster" sounds reasonable.

**Comment by WouterJ** [comment]
I like "[...] improves the performance of Composer's autoloader"

I also like "performant". As Symfony is a french built (and maintained) framework, we have some occurences for French words which should not cause much confusion (and aren't really important). However, it confused you enough to create a PR, so maybe we should remove it here :)

**Comment by SofHad** [comment]
@WouterJ 
OK,  this is done :)

**Comment by WouterJ** [comment]
I'm sorry @SofHad, but it seems like this PR was lost in our list. Meanwhile, someone else improved this sentence and the rest of the article: #5003 That's the reason I'm closing this one. I would still like to thank you for contributing!

**Pull request closed without merging**
