### PR TITLE
Move python dependencies inside a virtualenv

### PR DESCRIPTION
**Pull request by damz**

### CODE REVIEW

**Comment by javiereguiluz** [comment]
Error log:

```
Found 15695 commits.

Building application 'symfonydocs' (runtime type: php, tree: 83ed7d9)
  Generating runtime configuration.
  
  Installing build dependencies...
    Installing python build dependencies: virtualenv
  
  Moving the application to the output directory
  Executing build hook...
    New python executable in /app/.virtualenv/bin/python
    Installing setuptools, pip, wheel...done.
    make: Entering directory `/app/_build'
    sphinx-build -b html -c . -d ./doctrees   ../ ./html
    make: Leaving directory `/app/_build'
    Can not perform a '--user' install. User site-packages are not visible in this virtualenv.
    Can not perform a '--user' install. User site-packages are not visible in this virtualenv.
    make: sphinx-build: Command not found
    make: *** [html] Error 127
  
  E: Error building project: The build hook failed with status code 2. Aborted build.

E: Error building the project: Unable to build project, aborting deployment.
```

**Comment by damz** [comment]
@javiereguiluz Thanks for that, I have access to it through the backend.

**Comment by damz** [comment]
It looks like sphinx 1.3.6 is failing to build now :( Looking to see if upgrading it helps.

**Comment by damz** [comment]
This works. It looks like it started failing because we use `pip --user`, and that broke when, because of a change in dependencies, `pip` wanted to upgrade a system package.

So there are really two issues here:

* The first is that the older version of `pip` that ships with Debian Jessie breaks in that case (it incorrectly tries to remove the system package);
* The build dependencies that you have are not pinned, so it ended up braking because of changes of upstream dependencies (possibly [when jinja2 ended up requiring markupsafe>=0.23](https://github.com/pallets/jinja/commit/5453db1711eeb33c68ed1126764ab691b81d1472), but that's a guess).

I also have a more intrusive version (pinning all the Python dependencies) at #7404.

**Comment by robfrawley** [comment]
Looks like you came to the same conclusion of the platform.sh support team! ;-) I'm :-1: for the more intrusive version, though I do like offering a requirements file that allows for people to quickly get up and running, with just the sphinx-php requirement.

**Comment by javiereguiluz** [comment]
Closing it in favor of #7404.

**Pull request closed without merging**
