### PR TITLE
little typo event_dispatcher.rst

### PR DESCRIPTION
**Pull request by SpacePossum**
(also in the 4 line, not in 2)

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Comment by xabbuh** [comment]
Thank you for fixing this typo @SpacePossum. However, it looks like this is not present in any of the maintained branches (which are `2.7`, `2.8`, `3.4`, `4.0`, `4.1`, and `master`). Thus, I unfortunately need to close here.

**Comment by SpacePossum** [comment]
no worries @xabbuh , however @ https://symfony.com/doc/current/event_dispatcher.html this typo is still present

**Comment by SpacePossum** [comment]
i.e. https://github.com/symfony/symfony-docs/edit/4.0/event_dispatcher.rst

**Review by xabbuh — APPROVED** [review]

**Comment by xabbuh** [comment]
Oh indeed, you are absolutely right. Sorry, I totally missed that . We'll merge it into the `2.7` branch.

**Comment by javiereguiluz** [comment]
Thank you @SpacePossum.

**Comment by SpacePossum** [comment]
thanks @ricknox , @xabbuh and @javiereguiluz :+1:  :)

**Pull request closed without merging**
