### PR TITLE
Corrected titles of test tools and use safe url for phpspec

### PR DESCRIPTION
**Pull request by lex111**
Just another small improvement :smiley:

### CODE REVIEW

**Comment by javiereguiluz** [comment]
I do appreciate this kind of fixes because it's important to display the right name.

I was curious about "phpspec" so I checked their website. I saw that they call themselves `phpspec` (all lowercased). See https://www.phpspec.net/en/stable/manual/introduction.html  However, on Twitter they call themselves `PhpSpec` See https://twitter.com/phpspec  So, what can we do here?

**Comment by lex111** [comment]
However on the [page of their organization](https://github.com/phpspec), it's written - `PHPSpec Framework`, let's use this name, in the end it most corresponds to the language (PHP is an abbreviation).

**Comment by javiereguiluz** [comment]
Thanks for the insights! Let's merge it (on 2.8 branch, the oldest maintained branch now that 2.7 is deprecated)

**Comment by lex111** [comment]
Oh, again I made a mistake with the branch, because of what the commit will not be under my authorship, not that it worries me, but it's a little kind of frustrating.

**Comment by xabbuh** [comment]
@lex111 no need to worry, it's still your authorship (see 428120aa77b8ee84591dc26a9938590ffe79ab89) :)

**Comment by javiereguiluz** [comment]
@lex111 don't worry about the branch issue. Even if you target the right branch, the result will be the same. Because of the merging process of Symfony (both docs and code) each PR results in two commits: one with your authorship and another one for the merger.

You can see this in action here: https://github.com/symfony/symfony-docs/commits/master?after=3235d06602938d7b8887d9907ef6b258539b8170+139

merge

**Comment by lex111** [comment]
@xabbuh @javiereguiluz  I get it, thanks for the explanation! :smile:

**Pull request closed without merging**
