### PR TITLE
[2.6] Don't use deprecated features

### PR DESCRIPTION
**Pull request by wouterj**
| Q | A |
| --- | --- |
| Doc fix? | yes |
| New docs? | no |
| Applies to | 2.6+ |
| Fixed tickets | - |

### CODE REVIEW

**Comment by xabbuh** [comment]
:+1: Technically,we would not merge this into the `2.6` branch anymore as it is not supported as of today. However, I think we should not be too strict and merge it nonetheless.

@WouterJ @weaverryan @javiereguiluz What do you think?

**Comment by WouterJ** [comment]
ping @weaverryan @javiereguiluz 

I think we should merge this into the 2.7 branch now 19 days have past :)

**Comment by weaverryan** [comment]
Sorry for no reply! I say 2.7, but I agree with you @xabbuh, we don't need to be strict on the rules in the docs. :thumbsup:

**Comment by xabbuh** [comment]
It's in the `2.7` branch now. :)

**Pull request closed without merging**
