### PR TITLE
Fix typo in SVG image

### PR DESCRIPTION
**Pull request by BenMorel**
`Addres` => `Address`

### CODE REVIEW

**Comment by javiereguiluz** [comment]
Thanks for fixing this! However, the full fix requires to fix the original image file (stored in https://github.com/symfony/symfony-docs/tree/4.4/_images) and then exporting it to SVG and optimizing it with svgo. It's a cumbersome process, so we can do it for you if you prefer.

**Comment by BenMorel** [comment]
Hi, the original image file is the one I edited, isn't it? Should I just optimize it with svgo?

**Comment by javiereguiluz** [comment]
Sorry, I meant the original image in https://github.com/symfony/symfony-docs/tree/4.4/_images/sources. which requires installing a certain application, etc.

**Comment by BenMorel** [comment]
Oh right, I'm happy to let you do it then! 😉

**Comment by javiereguiluz** [comment]
Closing in favor of #15271. Thanks!

**Pull request closed without merging**
