### PR TITLE
Updated apache configuration to match v2.4 changes about authorizations

### PR DESCRIPTION
**Pull request by devantoine**
See: http://httpd.apache.org/docs/2.4/upgrading.html#run-time

### CODE REVIEW

**Comment by xabbuh** [comment]
I wish you a happy new year @devantoine!

I thought about it again and I think we should change the example in the following way:

* Keep the configuration example the way it is at the moment, but add the Apache 2.4 syntax example as a comment. The reason to keep the old syntax here is that with Apache 2.4 you actually don't have good reasons to use mod_php5.
* Remove the note below the config examples. It's not very easy to spot there.

What do you think?

**Comment by devantoine** [comment]
Hey, happy new year too @xabbuh!

I see there has been some edits on the file. If I remember correctly the caution block wasn't there when I did the PR.

Maybe put the two blocks at the same place, stating that the first one is for Apache < 2.4 while the second one is for higher versions?

Or it can stay as it is, I don't mind since it's stated explicitly.

**Comment by javiereguiluz** [comment]
It seems that you agree on showing something like this:

```apacheconf
<Directory /var/www/project/web>
    # enable the .htaccess rewrites
    AllowOverride All

    # Apache 2.2 configuration
    Order allow,deny
    Allow from All

    # Apache 2.4+ configuration
    # Require all granted
</Directory>
```

If that's the case, @devantoine could you please update your pull request? It'd be nice to have this addition merged as soon as possible. Thanks!

**Comment by WouterJ** [comment]
Closing this PR as it seems like someone else already updated the article with a new section specific for Apache 2.4: http://symfony.com/doc/current/cookbook/configuration/web_server_configuration.html#using-mod-php-php-cgi-with-apache-2-4

**Pull request closed without merging**
