### PR TITLE
Minor rewording for the security:checker article

### PR DESCRIPTION
**Pull request by javiereguiluz**
Installing the bundle is not enough ... you must enable it also.

### CODE REVIEW

**Review by wouterj — APPROVED** [review]
What about "is installed and enabled in your application" and keeping the `composer require` command?

**Comment by javiereguiluz** [comment]
@wouterj I don't like the idea of showing the `composer` command because I don't want to duplicate this kind of installation instructions. But if others agree with you, I'll do the changes. Meanwhile I did the other changes that you suggested. Thanks.

**Comment by xabbuh** [comment]
To me this sounds fine. Someone not using the Standard Edition (which has the SensioDistributionBundle enabled by default) will probably have no problem in finding out how to install a package using Composer.

Status: Reviewed

**Comment by xabbuh** [comment]
Thank you Javier.

**Pull request closed without merging**
