### PR TITLE
[minor] Use correct code block

### PR DESCRIPTION
**Pull request by Nyholm**
We use `html+php` on all other places with short open syntax.

### CODE REVIEW

**Comment by OskarStark** [comment]
You can extend the DOCtor rule if you like to spot these issues

**Comment by Nyholm** [comment]
It was just this one =)

I've looked at all other code block =)

Btw, we have `html+twig` and `twig`. What is the difference?

**Comment by wouterj** [comment]
> Btw, we have html+twig and twig. What is the difference?

Same as with php and html+php. `{{ form_row(form) }}` is twig, `<div>{{ form_label(form) }}</div>` is html+twig

**Comment by javiereguiluz** [comment]
Thank you! Merged in 4.4 and up

**Pull request merged**
