### PR TITLE
add empty h1 tags to html template

### PR DESCRIPTION
**Pull request by ArlingtonHouse**
First Example tutorial needs the tag in order to work.

### CODE REVIEW

**Comment by javiereguiluz** [comment]
I don't understand this proposal. Why is that empty tag needed?

**Comment by javiereguiluz** [comment]
Closing because this doesn't look necessary and we don't have more information. Thanks!

**Comment by javiereguiluz** [comment]
I'm reopening this because it's really needed. I just stumbled upon this issue when trying to solve this problem: https://github.com/symfony/webpack-encore/issues/210

@ArlingtonHouse I'm really sorry that I closed your pull request and I apologize for that!

**Review by javiereguiluz — APPROVED** [review]

**Comment by weaverryan** [comment]
I just tweaked the PR to fix the legitimate issue in a different way.

**Comment by weaverryan** [comment]
Thank you @ArlingtonHouse!

**Pull request merged**
