### PR TITLE
Clarify usage of handler channel configuration

### PR DESCRIPTION
**Pull request by shkkmo**
See: https://github.com/symfony/monolog-bundle/blob/master/DependencyInjection/MonologExtension.php#L88

I believe this applies to all versions of Symfony, so should be merged into the branches of documentation for all of them.

### CODE REVIEW

**Comment by xabbuh** [comment]
Thank you for this suggestion @shkkmo. I think you are right with what you suggest. I just think we should maybe not embed it into this paragraph, but add it to its own `caution` block or the like to make it more outstanding and easier to spot. What do you think?

**Comment by xabbuh** [comment]
It will look like this:

```rst
.. caution::

    A handler that should log only messages for certain channels must be
    a top-level handler. Handlers nested in filters, groups or other handlers
    will receive every messages regardless of the channel.
```

I think the best place would be just below the configuration block.

**Comment by shkkmo** [comment]
@xabbuh Is this better?

**Comment by javiereguiluz** [comment]
👍 

Status: reviewed

@shkkmo thanks for contributing this improvement. There are some very minor syntax issues in your pull request, but contributors can easily fix them when merging your work. Thanks!

**Comment by WouterJ** [comment]
Thanks @shkkmo!

I've merged your PR into the 2.7 version of the docs (we dropped 2.3 support in the meantime). Afterwards, I've fixed the syntax to comply with our doc standards in 65a20c8.

**Pull request closed without merging**
