### PR TITLE
data transformers cookbook service definition typo

### PR DESCRIPTION
**Pull request by intrepion**

### CODE REVIEW

**Comment by xabbuh** [comment]
:+1: great catch @intrepion

**Comment by xabbuh** [comment]
Thank you Oliver.

**Comment by intrepion** [comment]
This fix also needs to be put in the 2.6 and 2.7 branches.  Since this typo was included in the merges yesterday by @weaverryan

**Comment by xabbuh** [comment]
We merge branches up on a regular basis. So they will get the FIGC automatically soon. :)

**Pull request merged**
