### PR TITLE
simply use orphanRemoval=true, instead of re-doing it badly by hand, in the controller.

### PR DESCRIPTION
**Pull request by docteurklein**

### CODE REVIEW

**Comment by xabbuh** [comment]
@docteurklein Can you update the pull request according to the comments?

**Comment by WouterJ** [comment]
Ref https://github.com/symfony/symfony-docs/issues/3602

**Comment by WouterJ** [comment]
HI @docteurklein! We organize a [doc sprint day](http://symfony.com/blog/symfony-docs-hack-day-needs-you-on-may-23rd) this Saturday. It would be great if you could join and finish this PR. But, we can also put it on a list so others can finish this PR (or you can work on it in the next few weeks). I would love to hear what you want :)

**Comment by docteurklein** [comment]
hey :) sorry for such a delay! I observe the comments and @stof rightly put me in doubt wether my fix worth being added.
Anyway I'll be in holidays for the next 3 weeks and won't be able to participate sorry.

But I'd be pleased to see it handled by someone else :)

**Comment by stof** [comment]
@WouterJ this is indeed the wrong fix for the issue

**Comment by javiereguiluz** [comment]
Can someone please shed some light on the details about how to possibly fix this pull request? Thanks.

**Comment by xabbuh** [comment]
Don't we just talk about what was written by @stof in https://github.com/symfony/symfony-docs/pull/4634/files#r21890140 or do I miss something?

**Comment by WouterJ** [comment]
I'm going to close this PR as we all seem to agree that using orphanRemoval is not solving the same problem as the original code.

If you don't agree, just comment :)

**Pull request closed without merging**
