### PR TITLE
[Controller Description] Fix typos and class link

### PR DESCRIPTION
**Pull request by rendler-denis**
- fix typo in first code example from $name to $max
- add link to the Request class instead of just make the name bold

### CODE REVIEW

**Comment by wouterj** [comment]
Thanks for the typo fix, that's correct!

However, in reStructured Text (the markup language used), you can't nest inline markup. So your code doesn't work either (see also the [platform.sh build of this PR](http://pr-6913-6qmocelev2lwe.eu.platform.sh/controller.html#the-request-object-as-a-controller-argument)). Can you please update this PR (by adding a new commit to the patch-4 branch) to remove all markup around `Request` (so just making it bold, no literals or API references)? Thanks! (if you don't have the time, just comment and we'll do it during the merge)

status: needs work

**Comment by rendler-denis** [comment]
Hello, @wouterj! Thanks for the heads-up. I wasn't aware of this limitation and I should have checked the deployment results. It is a good lesson for the future PRs. 
I updated the mark-up as you suggested. 
Thanks, Denis!

**Comment by wouterj** [comment]
👍 
status: reviewed

Thanks for your quick reactions! (if you have some time, please remove the single backticks around Request as well)

**Comment by rendler-denis** [comment]
@wouterj, changes done! :)

**Comment by wouterj** [comment]
Perfect! Thanks again Denis! Fyi, I've merged the changes in 2.7 and will merge them into the newer versions from there

**Pull request closed without merging**
