### PR TITLE
Moved the requirements file

### PR DESCRIPTION
**Pull request by javiereguiluz**

### CODE REVIEW

**Comment by javiereguiluz** [comment]
As expected, this failed:

```
Executing build hook...
    Could not open requirements file: [Errno 2] No such file or directory: './platform/requirements.txt'
    make: sphinx-build: Command not found
    make: *** [html] Error 127
    New python executable in /app/.virtualenv/bin/python
    Installing setuptools, pip, wheel...done.
    Requirement already satisfied: pip==9.0.1 in ./.virtualenv/lib/python2.7/site-packages
    Requirement already satisfied: wheel==0.29.0 in ./.virtualenv/lib/python2.7/site-packages
    make: Entering directory `/app/_build'
    sphinx-build -b html -c . -d ./doctrees   ../ ./html
    make: Leaving directory `/app/_build'
```

**Comment by javiereguiluz** [comment]
No luck with the updated file path:

```
 Executing build hook...
    Could not open requirements file: [Errno 2] No such file or directory: '/app/.platform/requirements.txt'
    make: sphinx-build: Command not found
    make: *** [html] Error 127
```

Any other idea or should we close this?

**Comment by javiereguiluz** [comment]
Another fail in the last attempt:

```
Could not open requirements file: [Errno 2] No such file or directory: '../.platform/requirements.txt'
```

**Comment by javiereguiluz** [comment]
Another fail:

```
Could not open requirements file: [Errno 2] No such file or directory: './.platform/requirements.txt'
```

**Comment by javiereguiluz** [comment]
@damz do you know if it's possible to more the `requirements.txt` file to the `.platform/` directory and reference it in the `.platform.app.yaml` file. We've tried all kinds of file paths but none worked. Thanks!

**Comment by robfrawley** [comment]
@javiereguiluz You can just use what I'd done in #7402

**Comment by javiereguiluz** [comment]
... and it worked 🎉  @robfrawley thanks! You saved us!

**Comment by robfrawley** [comment]
I still feel strongly that both Travis and Platform build using the same environment: https://github.com/symfony/symfony-docs/pull/7402/files#diff-354f30a63fb0907d4ad57269548329e3R9 :-)

**Comment by javiereguiluz** [comment]
Can we merge this? It's a minor change but it will help us remove this internal file. Thanks!

**Comment by xabbuh** [comment]
Thank you Javier.

**Pull request closed without merging**
