### PR TITLE
[Serializer] add note on Custom Normalizer page about cacheable performance

### LINKED ISSUE #12061: Mention CacheableSupportsMethodInterface in "Create your own Normalizer"
Introduced in 4.1, blog post: https://symfony.com/blog/new-in-symfony-4-1-faster-serializer

It is mentioned, but only in "performance" subpart of docs: https://symfony.com/doc/current/components/serializer.html#performance

General serializer docs regarding Normalizers: https://symfony.com/doc/current/components/serializer.html#normalizers

Creating your own Normalizer misses this completely:  https://symfony.com/doc/current/serializer/custom_normalizer.html

### PR DESCRIPTION
**Pull request by maxhelias**
Fix https://github.com/symfony/symfony-docs/issues/12061

### CODE REVIEW

**Comment by wouterj** [comment]
If I understand this correctly, this section only makes sense when creating a custom normalizer (as the build-in normalizers already implement this). Is there a reason to keep this section in `/serializer`, or should we instead only put it in `/serializer/custom_normalizers`?

**Comment by maxhelias** [comment]
Indeed yes, after it's always interesting to know it. Tell me, what do you prefer?

**Comment by maxhelias** [comment]
@wouterj what would you like to do with this ? move all in the custom normalizer or keep it as it is ?

**Comment by wouterj** [comment]
Sorry, I somehow missed your reaction. Yes, I'm in favor of moving the performance section to the custom normalizer article.

**Review by wouterj — APPROVED** [review]

**Comment by javiereguiluz** [comment]
Maxime, thanks for improving this. I'm sorry it took us so long to merge.

**Pull request merged**
