### PR TITLE
[Cookbook][Configuration] update text to use SetHandler (not ProxyPassMatch)

### PR DESCRIPTION
**Pull request by xabbuh**
| Q | A |
| --- | --- |
| Doc fix? | yes |
| New docs? | no |
| Applies to | all |
| Fixed tickets |  |

This reflects the changes to the default configuration introduced with #4708 in the introduction.

### CODE REVIEW

**Comment by xabbuh** [comment]
@TeLiXj For `ProxyPassMatch` we have a sentence below the config example talking about a subpath of the document root:

> When you run your Symfony application on a subpath of your document root,
    the regular expression used in ``ProxyPassMatch`` directive must be changed
    accordingly

Do we need something similar for `SetHandler`?

**Comment by TeLiXj** [comment]
I couldn't test this tip with ProxyPassMatch, but now with SetHandler I created a php file with phpinfo() on a subfolder of my web folder and I can see "Server API    FPM/FastCGI "... it works without any modification in SetHandler

**Comment by xabbuh** [comment]
Thank you @TeLiXj. In this case it makes sense to move the description for the modified `ProxyPassMatch` description to a comment.

**Comment by weaverryan** [comment]
Great attention to detail on this :). Thanks @xabbuh!

**Pull request merged**
