### PR TITLE
Set twig service as private

### PR DESCRIPTION
**Pull request by ifdattic**
| Q | A |
| --- | --- |
| Doc fix? | yes |
| New docs? | no |
| Applies to | 2.3 |
| Fixed tickets |  |

### CODE REVIEW

**Comment by xabbuh** [comment]
:+1: (I thought we already changed this, but it must have been another file)

**Comment by ifdattic** [comment]
The previous one was in best practices

**Comment by weaverryan** [comment]
:thumbsup: Looks like I'm about to merge a bunch of your PR's ;)

**Comment by ifdattic** [comment]
Yea, currently my day starts with a breakfast and then 90 minutes of reading documentation :D

**Pull request merged**
