### PR TITLE
added xabbuh to the list of the Symfony core team member

### PR DESCRIPTION
**Pull request by fabpot**
Congrats!

### CODE REVIEW

**Comment by WouterJ** [comment]
Congratulations @xabbuh!

**Comment by javiereguiluz** [comment]
Congratulations Christian! You really deserve it.

**Comment by aitboudad** [comment]
:+1: Congratulations @xabbuh

**Comment by xabbuh** [comment]
Thank you!

**Comment by weaverryan** [comment]
Hey, I know this guy! Congrats to you my friend! Well-deserved. This PR is perfect, except that maybe your name should be above mine ;).

**Pull request merged**
