### PR TITLE
[HttpFoundation][Fix] Component version

### PR DESCRIPTION
**Pull request by 20uf**
Hello,

Small PR to correct the version of the component HttpFoundation in the composer.json.

Regards,

### CODE REVIEW

**Review by javiereguiluz — COMMENTED** [review]
In theory, ^3.0 will also install 3.2. The proposed change would be mandatory if we use some feature that it's only available in 3.2 version. Otherwise, the minimum version can be as low as we want.

But on the other hand, this change wouldn't hurt us either. So I don't know what to say about this proposal :)

**Comment by 20uf** [comment]
All right!

I would say to answer that, that it's subtle and that your best be explicit.

**Comment by xabbuh** [comment]
The drawback is that we would have to make this change on every branch (in theory, we would then also have to change the constraint to `^3.1` on the `3.1` branch). I am not sure if we really want to do that.

**Comment by 20uf** [comment]
In this case would not it be more judicious to leave only composer command:

`composer require symfony/http-foundation`

There is no such notion of composer.json on other docs, eg:

- http://symfony.com/doc/current/components/event_dispatcher.html#installation
- http://symfony.com/doc/current/components/console.html
- ...

**Comment by 20uf** [comment]
Hello @xabbuh @javiereguiluz.

A solution for this PR? What do we do?

**Comment by javiereguiluz** [comment]
I agree with the last comment. We could remove the `composer.json` contents example entirely.

## Before

```rst
To use this component, add it as a dependency of the project:

.. code-block:: terminal

    $ composer require symfony/http-foundation

Running this command will also automatically download the Symfony
HttpFoundation component and install it under the ``vendor/`` directory.
A ``composer.json`` and a ``composer.lock`` file will be generated as well,
containing the new requirement:

.. code-block:: json

    {
        "require": {
            "symfony/http-foundation": "^3.0"
        }
    }

The code block shows the content of the ``composer.json`` file (the actual
version may vary).
```

## After

```rst
To use this component, add it as a dependency of the project:

.. code-block:: terminal

    $ composer require symfony/http-foundation

Running this command will also automatically download the Symfony
HttpFoundation component and install it under the ``vendor/`` directory.
A ``composer.json`` and a ``composer.lock`` file will be generated as well,
containing the new requirement.
```

**Comment by 20uf** [comment]
Hello @xabbuh @javiereguiluz.

Are the latest changes right for you? We are ISO with other documentation.

Regards

**Review by javiereguiluz — APPROVED** [review]
:+1:

Status: reviewed

**Review by HeahDude — APPROVED** [review]

**Comment by xabbuh** [comment]
Thank you @20uf.

**Pull request closed without merging**
