### PR TITLE
Updated the configuration reference for the new asset configuration

### PR DESCRIPTION
**Pull request by javiereguiluz**
| Q | A |
| --- | --- |
| Doc fix? | yes |
| New docs? | no |
| Applies to | 2.7+ |
| Fixed tickets | #4982 (partially) |

This PR replaces #5170 which is impossible to merge.

### CODE REVIEW

**Comment by stof** [comment]
please fix the build

**Comment by stof** [comment]
@javiereguiluz ping

**Comment by sarcher** [comment]
Bumping this as it is likely to receive more attention with the removal of assetic and people exploring alternate strategies; my team ran into it this week while integrating webpack. I was going to submit a PR myself but found this one.

**Comment by javiereguiluz** [comment]
I'm going to close this old PR because I'm going crazy trying to fix all the errors.

@WouterJ @xabbuh it looks like these changes are already merged in the docs: http://symfony.com/doc/current/reference/configuration/framework.html#assets

**Pull request closed without merging**
