### PR TITLE
Encore: add documentation for Encore.configureDevServerOptions()

### PR DESCRIPTION
**Pull request by Kocal**
Hi :wave:,

This PR add documention for the new method `Encore.configureDevServerOptions()` implemented in https://github.com/symfony/webpack-encore/pull/693.

Thanks :)

### CODE REVIEW

**Comment by javiereguiluz** [comment]
Hugo, thanks for this nice contribution! We merged it in 3.4 (and all the upper branches) and added a `versionadded` directive to tell readers when did Encore add this method. Thanks!

**Comment by Kocal** [comment]
Oh sorry, once again I forgot about the base branch on GitHub :sweat_smile: 
Thanks!

**Comment by cristi-contiu** [comment]
Hello! Was 0.28.4 released? I can only find 0.28.3 in https://github.com/symfony/webpack-encore/releases. Thanks!

**Comment by javiereguiluz** [comment]
It's not released yet ... but it will soon, that's why we added this to the docs. Cheers!

**Pull request merged**
