### PR TITLE
Fix nonexistent controller method

### PR DESCRIPTION
**Pull request by amansilla**
| Q | A |
| --- | --- |
| Doc fix? | yes |
| New docs? | no |
| Applies to | 2.3 |
| Fixed tickets | #5272 |

### CODE REVIEW

**Comment by amansilla** [comment]
The documentation for version 2.4 is also affected by this error. Do anybody knows if I need to create a different pull request for the fix in the version 2.4?

**Comment by javiereguiluz** [comment]
@amansilla it won't be necessary to create a PR for Smyfony 2.4, because we no longer update that version. We only keep updating the active Symfony versions, which right now are 2.3, 2.6, 2.7, 2.8 and master.

**Comment by amansilla** [comment]
@javiereguiluz thanks for the info, now tests are passing on travis. Is there anything to do yet?

**Comment by xabbuh** [comment]
@amansilla Thank you so much for catching this error and for providing a perfect pull request! It will be merged as soon as one of our mergers has some time.

@weaverryan @WouterJ Please remember to revert this commit after merging when merging it up into the `2.6` branch.

**Comment by WouterJ** [comment]
Thanks for this fix Antonio! Nice catch.

**Pull request merged**
