### PR TITLE
Add environment variables

### PR DESCRIPTION
**Pull request by ProfM2**
Add server environment variables, specifically for production use.

### CODE REVIEW

**Review by javiereguiluz — APPROVED** [review]
@ProfM2 I like this, thanks for contributing it. However, using env vars is optional (even in Symfony 4), so I reworded your config to mention that it's optional. Thanks!

**Comment by xabbuh** [comment]
There are more virtual host config examples on this page. Should we update them all? And what about the Nginx example config?

**Comment by javiereguiluz** [comment]
I wouldn't add them in the other Apache examples ... but if someone knows nginx, please tell us which is the equivalent config to add. Thanks!

**Comment by xabbuh** [comment]
```nginx
# optionally set the value of the environment variables used in the application
# fastcgi_param APP_ENV prod;
# fastcgi_param APP_SECRET <app-secret-id>;
# fastcgi_param DATABASE_URL "mysql://db_user:db_pass@host:3306/db_name";
```

That should do the trick.

**Review by ProfM2 — COMMENTED** [review]
Looks good.

**Comment by javiereguiluz** [comment]
@ProfM2 thank you for helping us improving this. It was a nice first contribution to Symfony Docs. Congrats!

**Pull request merged**
