### PR TITLE
[Security][Guard] Added a picture for Guard Authenticator

### PR DESCRIPTION
**Pull request by a-ast**
This illustration shows how GuardAuthenticationListener calls methods of Guard Authenticator.

### CODE REVIEW

**Comment by ogizanagi** [comment]
Looks great!

Beware that returning null from `GuardAuthenticatorInterface::getCredentials()` will try other guard authenticators before returning a response [in case of multiple guards authenticators](http://symfony.com/doc/current/security/multiple_guard_authenticators.html#multiple-authenticators-with-shared-entry-point). Thus, authentication is skipped, but only for this guard.

**Comment by a-ast** [comment]
You are right @ogizanagi, but it is always a big question: either to put all details to a picture or keep it simpler.

**Review by wouterj — APPROVED** [review]
Love it! 👍

**Comment by xabbuh** [comment]
Thank you for this really beautiful improvement @a-ast!

**Pull request closed without merging**
