### PR TITLE
Fixed routing method example

### PR DESCRIPTION
**Pull request by carletex**
| Q | A |
| --- | --- |
| Doc fix? | yes |
| New docs? | no |
| Applies to | all |

### CODE REVIEW

**Comment by OskarStark** [comment]
looks ok to me

**Comment by carletex** [comment]
Hey @OskarStark,

sorry for not explaining properly. Above the code block, you can read:

**Suppose you have a contact form with two controllers - one for displaying the form (on a GET request) and one for processing the form when it's submitted (on a POST request). This can be accomplished with the following route configuration:**

and below:

**Despite the fact that these two routes have identical paths (/contact), the first route will match only GET requests and the second route will match only POST requests. This means that you can display the form and submit the form via the same URL, while using distinct controllers for the two actions.**

In the current code, there is only one controller for the /contact route which accept the GET and POST method. I tried to fix the code using two diferent controllers associated with the same route, but with diferent methods, like the text says.

Thanks.

**Comment by WouterJ** [comment]
The example was changed, as it was recommending not-so-good practices. Instead of fixing the code example, the text should be fixed.

However, maybe we should remove this completely, see https://github.com/symfony/symfony-docs/issues/5583 for some background

**Comment by carletex** [comment]
Thank you @WouterJ,

I should have searched for open issues before creating this pull request. I'm closing the PR and I will be following this in the thread you mentioned.

**Pull request closed without merging**
