### PR TITLE
Improved the image for Doctrine + Web Debug Toolbar

### LINKED ISSUE #7301: Issues with images inside notes and tips
At the end of this section http://symfony.com/doc/current/doctrine.html#fetching-objects-from-the-database  the image inside the TIP is too small. Check if this happens in other pages too.

image-admonition

### PR DESCRIPTION
**Pull request by javiereguiluz**
This fixes #7301. The image file renaming is recommended because all images from the Symfony Docs are flattened in a single `_images/` directory. We should start "namespacing" image file names to avoid collisions.

### Before

before_image

### After

after_image

### CODE REVIEW

**Comment by xabbuh** [comment]
@javiereguiluz Does that mean it's worthless (or could even hurt us) when using subdirectories inside the `images` directory?

**Comment by javiereguiluz** [comment]
@xabbuh I'm afraid so :(

**Comment by xabbuh** [comment]
In this case, I suggest that we do not use subdirectories at all which would allow us to detect conflicts ourselves earlier. What do you think?

**Comment by javiereguiluz** [comment]
I'd recommend to finish this PR first and then we can discuss about the best strategy for the naming of images. Thanks!

**Comment by javiereguiluz** [comment]
Please, let's merge this to fix the image problem. Thanks!

**Comment by xabbuh** [comment]
Thank you @javiereguiluz.

**Pull request closed without merging**
