### PR TITLE
Removed "http_basic" config from the login form cookbook

### PR DESCRIPTION
**Pull request by javiereguiluz**
| Q | A |
| --- | --- |
| Doc fix? | yes |
| New docs? | no |
| Applies to | all |
| Fixed tickets | #5763 |

### CODE REVIEW

**Comment by stof** [comment]
:+1:

**Comment by xabbuh** [comment]
I think you should then remove the paragraph about HTTP basic auth that you quoted in #5763 too.

**Comment by javiereguiluz** [comment]
@xabbuh removed the mentioned paragraph.

**Comment by xabbuh** [comment]
:+1:

**Comment by weaverryan** [comment]
Thanks Javier!

**Pull request merged**
