### PR TITLE
[Security] Allow an array of pattern in firewall configuration

### PR DESCRIPTION
**Pull request by alexandre-daubois**
Related to https://github.com/symfony/symfony/pull/51128

### CODE REVIEW

**Comment by javiereguiluz** [comment]
Thanks a lot Alex!

**Comment by javiereguiluz** [comment]
**There's been an error here** while merging. I can't see this merged in `symfony/symfony-docs`, only in my own fork: https://github.com/javiereguiluz/symfony-docs/commit/53b234e26477a8a31ee224d52deec932e57567ac

@alexandre-daubois please, don't delete your original branch until we find out what happened here. Thanks!

**Comment by OskarStark** [comment]
Thank you Alexandre.

**Comment by OskarStark** [comment]
It worked @javiereguiluz

**Pull request merged**
