### PR TITLE
Change sess_time from unsigned to signed

### PR DESCRIPTION
**Pull request by vyk12**
cf. https://github.com/symfony/symfony/issues/25665

This made my production system down for a couple of minutes

### CODE REVIEW

**Comment by javiereguiluz** [comment]
@vyk12 thanks for this contribution! As you can see, there is some issue with the pull request and it contains hundreds of old commits instead of just your commit. Don't worry, this happens occasionally (and has happened to me lots of times!). If solving this is not simple, you can close this pull request and create a new one with this change: https://github.com/symfony/symfony-docs/pull/9506/commits/1251bc22b91d0cee3217d9cea5c5e530865a0ea5 Thanks!

**Comment by vyk12** [comment]
@javiereguiluz I'm sorry but I'm not used to make pull requests, and I therefore don't know how to solve the issue (I don't know where to begin with either of your 2 solutions.) However, I am curious about how to fix this.

1/ You say it can be solved, how?
2/ How can I create a pull request from the change you indicate? I thought this was what I did...

I just clicked the "edit this page" button on the Symfony documentation, and GitHub led me there. I have to admit I don't really know what I'm doing!

**Comment by javiereguiluz** [comment]
I don't know how to solve this on the web interface of GitHub (the one you use when clicking on "Edit this page"). When using Git locally, I'd fetch the latest contents from the main repo (`git fetch upstream`), I'd merge my local branch (`git checkout 2.7 && git merge upstream/2.7`) ... now you can find conflicts and in this case it would be complex to fix because there will be a lot ... and then I create a new pull request (`git checkout -b continue_9506 upstream/2.7`), make the changes and submit the result to GitHub to create the pull request there.

In any case, this time the change you propose is very small, so you can easily create the pull request again. This is what I'd recommend you:

1) Close this pull request
2) Delete your existing Symfony fork. Click on "Settings" of this repo: https://github.com/vyk12/symfony-docs
3) Browse this page: https://symfony.com/doc/current/doctrine/pdo_session_storage.html
4) Select the oldest maintained Symfony version that contains the bug.
5) Click on "Edit this page" and make the change again.

Hopefully the pull request will be clean this time :)

**Comment by vyk12** [comment]
Thanks a lot @javiereguiluz !

**Pull request closed without merging**
