### PR TITLE
DumpFile() third argument is deprecated and doesn't exists anymore in…

### PR DESCRIPTION
**Pull request by mickaelandrieu**
DumpFile() third argument is deprecated and doesn't exists anymore since [3.0.*](https://github.com/symfony/symfony/blob/3.0/src/Symfony/Component/Filesystem/Filesystem.php#L539)

### CODE REVIEW

**Comment by wouterj** [comment]
👍 
status: reviewed

I think we should merge this in 2.7, as it's deprecated in 2.3. Documenting deprecated features doesn't make a lot of sense here imo.

(btw, 3.0 has reached eom, so this should not be merged in 3.0).

**Comment by mickaelandrieu** [comment]
Hi @wouterj,
 if docs remains published and online (regarding the 3.0), we should fix it, right ?
My only interest here is to not publish errors, regardless the maintenance status of versions :D 

Mickaël

**Comment by wouterj** [comment]
> My only interest here is to not publish mistakes, regardless the maintenance status of versions :D

That's not something we do in the docs. Eom versions will have eom docs. Otherwise, we end up maintaining all branch versions (even 2.0).

Please note that eom version docs will have a big yellow warning at the top: http://symfony.com/doc/2.3/components/filesystem And the eom versions don't exists in the version checker.

**Comment by mickaelandrieu** [comment]
> Please note that eom version docs will have a big yellow warning at the top: http://symfony.com/doc/2.3/components/filesystem And the eom versions don't exists in the version checker.

Ok, I believed every "published" versions of docs were maintained (and so on, the others one were discontinued).

Following what you say, the 3.0 should have the "yellow banner" very soon ? Do you want me to edit the branch of this contribution (from 3.0 to 3.1 ?).

Mickaël

**Comment by wouterj** [comment]
> Following what you say, the 3.0 should have the "yellow banner" very soon ? Do you want me to edit the branch of this contribution (from 3.0 to 3.1 ?).

Yes, I'll push @javiereguiluz to add it when he's back from his holiday ;)

If possible, please rebase and change this PR on 2.7.

**Comment by mickaelandrieu** [comment]
arf, wanted to try the change base edit button ^^

=> PR redone => https://github.com/symfony/symfony-docs/pull/6909

**Comment by wouterj** [comment]
@mickaelandrieu why didn't the edit button work?

**Comment by mickaelandrieu** [comment]
@wouterj hmm I'd say because there is a big difference between 2.7 and 3.0... it's not a rebase button, it's only made a push on a new base, regarless the origin branch of the contribution (I've started on 3.0 so, all commits from 3.0 were added).

The button is fine for another mistake: If I have started my contribution in 2.7 branch and pushed it on 3.0, I can re edit my contribution to select the "good" branch.

**Pull request closed without merging**
