### PR TITLE
Update performance preload configuration

### PR DESCRIPTION
**Pull request by noniagriconomie**
Small addition regarding this PHP ini config

### CODE REVIEW

**Comment by javiereguiluz** [comment]
In which scenarios would be necessary to define this config option?

**Comment by noniagriconomie** [comment]
at work I had to add this line to one of our k8s helm chart, the line with the preload config file alone was not working
maybe we should just say to verify that this config is present/enabled?

**Comment by javiereguiluz** [comment]
My own opinion is that we shouldn't merge this if it's only needed in "obscure" scenarios such as "kubernetes helm charts". The docs should be as general purpose as possible and this would only introduce a little complication which is not needed by the majority of people. But let's wait for more opinions.

**Comment by noniagriconomie** [comment]
@javiereguiluz indeed you are right, lets close for now
thx for your time

**Comment by michaljusiega** [comment]
`opcache.preload_user` option is necessary to run preloading IMO :)

**Pull request closed without merging**
