### PR TITLE
Fix bad wording on autoconfigure clause

### LINKED ISSUE #10847: Not clear about how services are automatically load
Hello, I almost had a fight with a coworker because I was saying `autoconfigure: true` does not automatically register services. :smile: He finally told me "see, it's written in the doc !!".

This was obviously due to a misunderstanding of the documentation.

```
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
```

It does not actually automatically register services, but tag them as [...].

https://github.com/symfony/symfony-docs/blob/master/service_container.rst#creatingconfiguring-services-in-the-container

What do you think?

### PR DESCRIPTION
**Pull request by Nek-**
Fix #10847

### CODE REVIEW

**Review by OskarStark — COMMENTED** [review]
I am against this change, in the end it configures your services, but using tags is only the way of doing, you could also auto configure by interface or something else 👎

**Comment by OskarStark** [comment]
Why the “Waiting Code Merge” label? @xabbuh

**Comment by Nek-** [comment]
@OskarStark https://github.com/symfony/recipes/pull/517

**Comment by javiereguiluz** [comment]
Closing because the related proposal (https://github.com/symfony/recipes/pull/517) was closed without merging. @Nek- I'm sorry about this. Sometimes the small changes are the ones that take too much time and generate endless discussions.

**Pull request closed without merging**
