### PR TITLE
[FrameworkBundle] Added doc for ControllerTrait::isFormValid

### PR DESCRIPTION
**Pull request by lyrixx**
https://github.com/symfony/symfony/pull/24576

### CODE REVIEW

**Comment by javiereguiluz** [comment]
Closing because the related proposal (https://github.com/symfony/symfony/pull/24576) was closed without merging.

**Comment by lyrixx** [comment]
Thanks for closing this PR. I forgot

**Comment by eXtreme** [comment]
@javiereguiluz @lyrixx shouldn't this be reopened now as https://github.com/symfony/symfony/pull/24576 was merged?

**Comment by lyrixx** [comment]
@eXtreme You are right. I'm not able to re-open the PR. I will open a new one instead.
Thanks for the reminder

**Pull request closed without merging**
