### PR TITLE
Add possible values for widget_type

### PR DESCRIPTION
**Pull request by ghost**
| Q | A |
| --- | --- |
| Doc fix? | yes |
| New docs? | no |
| Applies to | all |
| Fixed tickets |  |

The documentation does not list which values are possible for widget_type. These two are the ones I extracted from the Symfony2 source code.

### CODE REVIEW

**Comment by xabbuh** [comment]
What do you think about reusing the description that we already have for the [widget option](http://symfony.com/doc/current/reference/forms/types/date.html#widget) of the `date` type (as it is basically the same)?

**Comment by XitasoChris** [comment]
Sure, that sounds even better.

**Comment by xabbuh** [comment]
@XitasoChris Will you be able to do the change? I think this would be ready to be merged then.

**Comment by XitasoChris** [comment]
@xabbuh Should I just copy it or move it to a new file and then include it on both pages?

**Comment by xabbuh** [comment]
@XitasoChris There already is the file `/reference/forms/types/options/date_widget.rst.inc`. Can it be reused or are there slight differences between both form types?

**Comment by XitasoChris** [comment]
@xabbuh The form types should be identical, but the block you pointed out has a different headline ("widget") whereas we need "date_widget" here.

**Comment by xabbuh** [comment]
@XitasoChris Indeed, I would then move the description itself to its own file.

**Comment by XitasoChris** [comment]
@xabbuh Done.

**Comment by xabbuh** [comment]
@XitasoChris Thanks, this looks really nice! :+1:

**Comment by weaverryan** [comment]
Wow, really really nice job re-using the existing description. Thanks @XitasoChris and xabbuh!

**Pull request closed without merging**
