### PR TITLE
Modify method on route logout in security.rst

### PR DESCRIPTION
**Pull request by rschillinger**
There is an error regarding the method of the logout route in the controller.

### CODE REVIEW

**Comment by javiereguiluz** [comment]
Good catch! Thanks and congrats on your first Symfony Docs contribution 🎉

**Comment by xabbuh** [comment]
What is the reason for this change (we recently made this in #18353)? And why only doing this for one config format?

**Comment by javiereguiluz** [comment]
I merged this because, if I'm right, there's no need for the logout route to be `POST`. It can be a normal `GET` request. I also checked the Symfony Demo app and we use a `GET` there.

I forgot about the other config formats. I'll do the changes and commit it directly.

**Comment by javiereguiluz** [comment]
The other config formats have been updated in https://github.com/symfony/symfony-docs/commit/0453493150efc481826d76e931eb82aaab44cf01

**Pull request merged**
