### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by adouiri**
update usage.rst

### CODE REVIEW

**Comment by wouterj** [comment]
Hi @adouiri! Nice catch & fix!. However, it seems like you edited the text in another branch than you're targetting this PR. Can you please rebase this PR or create a new one with the 3.4 branch as base?

If you need any help, feel free to comment and I'll do my best :)

**Review by javiereguiluz — COMMENTED** [review]
Please, add also the `Added in ...` information:

```rst
.. versionadded:: 3.4
    The ``reset()`` method was introduced in Symfony 3.4.
```

**Comment by adouiri** [comment]
Thanks @wouterj , i juste create a new one with the 3.4 branch as base .
https://github.com/symfony/symfony-docs/pull/8479

**Comment by wouterj** [comment]
Great! Closing this one in favor of #8479 then

**Pull request closed without merging**
