### PR TITLE
Rename Doctrine generator id fields

### PR DESCRIPTION
**Pull request by boedah**
Bring the Doctrine generator examples in line with the findUserProducts examples

### CODE REVIEW

**Comment by boedah** [comment]
Now that I think of it, maybe it would be better to leave the property/method named `id/getId()`, e.g. since `id` is the default for `ManyToOne` relations, and it is generally assumed that an Entity has a `getId()` method.
So the `findUserProducts` examples would need to be changed.

**Comment by javiereguiluz** [comment]
@boedah after thinking about this, I reach the same conclusions as your second message. Yes, your proposed change adds more precision to this ... but would require to do lots of changes elsewhere and would in effect complicate things. So, let's close this one without merging. Thanks!

**Comment by boedah** [comment]
@javiereguiluz yep. So I would make a new PR changing the example `findUserProducts` to use `getId()`, makes sense?
I would also change it in the ULID examples.

**Comment by javiereguiluz** [comment]
Yes, unless necessary for some reasons, all our examples assume `id`/`getId()` for the entity identifier. Thanks.

**Pull request closed without merging**
