### PR TITLE
This feature does not seem to work.

### PR DESCRIPTION
**Pull request by vlajos**
This feature does not seem to work.
I added a note for some details/alternative solution.

### CODE REVIEW

**Review by javiereguiluz — CHANGES_REQUESTED** [review]
I'm sorry but we don't link to issues/errors in the docs. If this is a bug, Monolog must fix it. If it's not a bug and the feature was removed, we need to remove this article too.

**Comment by vlajos** [comment]
Sorry. I am not too familiar with the Symfony ecosystem.
What is the best channel to
 * step towards the fixes
 * help the users to be able to work around the issue
?

**Comment by javiereguiluz** [comment]
@vlajos sorry if my previous reply wasn't clear 😅  I meant that we don't need to need to caution our readers about bugs because those bugs are eventually fixed (hopefully quickly). A different thing would be if this feature has been removed by Monolog ... then we need to reword or remove this article. In any case, the question is: is this a Monolog bug? If yes, are they going to fix it? Thanks!

**Comment by vlajos** [comment]
Hi,
After rereading the other issue I think they have fixed the bug in their newer versions.
If I understand well the old version works with old symfony, the new works with new symfony, just the old monolog(/+-bundle) does not play well with new symfony.
Could this be fixed somehow with dependencies? I am not too sure.

Anyway I agree that putting this to the documentation might be too strong... :-)

Best regards,
Lajos

**Comment by javiereguiluz** [comment]
@vlajos thanks for investigating this issue. Given that this is already fixed, we can close here. Since Monolog uses a different versioning than Symfony, users can easily update that dependency to get the latest bug fixes. Thanks!

**Pull request closed without merging**
