### PR TITLE
Making it more clear where Request::setTrustedProxies should go

### PR DESCRIPTION
**Pull request by weaverryan**
... And trying out the `diff` format! I know we lose the `php` formatting, but in this case, it seems superior.

### CODE REVIEW

**Comment by javiereguiluz** [comment]
About the *"diff + syntax highlighting"* feature, I've only found this old article: https://blaxpirit.com/blog/1/diffs-with-syntax-highlight.html  So it looks complicated to get it done with Pygments.

**Comment by javiereguiluz** [comment]
I've opened a "feature request" in the Pygments repository about "diff + highlighting" --> https://bitbucket.org/birkenfeld/pygments-main/issues/1339/add-support-for-using-the-diff-lexer-code

**Comment by javiereguiluz** [comment]
I like this proposal a lot, but currently it looks like this:

original

However, given that [red-green color blindness](https://en.wikipedia.org/wiki/Color_blindness) affect to 8% of people, I guess this will be confused by a mistake where we made a typo and put a `+` in the code.

I propose to change this to show the `+` and `-` on the left margin:

improvement_1

Another proposal for which I'm not sure would be to display a green/red background color on the changes, to make them stand out more:

improvement_2

---

My vote would be yes to 1) and no to 2). What do others think? Thanks!

**Comment by HeahDude** [comment]
I'm definitely 👍  for aligning left margin, and I'm also 👍 for the background color, looks more like a diff to me.

**Comment by weaverryan** [comment]
I agree with @HeahDude! I like both the left margin align and the light green background (which obviously GitHub does - that's always a good source to follow). IF possible, it would be great to make the `+` not selectable - possibly via a `:before` `content` CSS selector - it's what we use on our code blocks on KnpU (https://knpuniversity.com/screencast/javascript/window-global-vars).

@javiereguiluz are you proposals possible? Or are we going to need to hack through some sphinx code to do this?

**Comment by javiereguiluz** [comment]
Luckily we can do these changes just with CSS.

---

Let's consider a GitHub diff as a reference:

diff-github

This is the default Pygments style:

diff-before

And this is the design that has been proposed to symfony.com private repo:

diff-after

We can't do the same as GitHub because the Pygment markup is not advanced enough to highlight the specific chars changed on each line.

**Comment by javiereguiluz** [comment]
The changes in the `diff` styles have already been merged on symfony.com ... so it's safe now to merge this. Thanks!

**Review by javiereguiluz — APPROVED** [review]
👍

**Comment by weaverryan** [comment]
Woohoo! That was quick work! Thanks!

**Pull request merged**
