### PR TITLE
Call isSubmitted() before calling isValid()

### PR DESCRIPTION
**Pull request by yceruto**
Forward-compatibility fix

### CODE REVIEW

**Comment by xabbuh** [comment]
Do we do this everywhere else in the docs for Symfony 2.7? If so, are there other places we will have to update too?

**Comment by wouterj** [comment]
👍 
status: reviewed

A quick `git grep "isValid()"` shows there are more cases that needs to be fixed. Imo, this PR can be merged as is (and we can create a follow up PR fixing the other ones). However, if you have time, you can also include the other fixes in this PR.

```
best_practices/forms.rst:for clarity. This isn't technically needed, since ``isValid()`` first calls
components/form.rst:        if ($form->isValid()) {
components/form.rst:            if ($form->isValid()) {
controller.rst:        if ($form->isValid()) {
controller/upload_file.rst:        if ($form->isValid()) {
form/direct_submit.rst:        if ($form->isValid()) {
form/direct_submit.rst:            if ($form->isValid()) {
form/direct_submit.rst:            if ($form->isValid()) {
form/dynamic_form_modification.rst:            if ($form->isValid()) {
form/form_collections.rst:            if ($form->isValid()) {
form/form_collections.rst:            if ($editForm->isValid()) {
form/multiple_buttons.rst:    if ($form->isValid()) {
form/without_class.rst:        if ($form->isValid()) {
forms.rst:        if ($form->isSubmitted() && $form->isValid()) {
reference/forms/types/file.rst:        if ($form->isValid()) {
security/acl.rst:            if ($form->isValid()) {
```

**Comment by yceruto** [comment]
Okay, I'll do it.

**Comment by yceruto** [comment]
Updated!

Status: Needs Review

**Comment by wouterj** [comment]
Awesome! Thanks for the great work & quick response!

status: reviewed

**Comment by javiereguiluz** [comment]
👍

**Comment by wouterj** [comment]
Thanks. It's much better now!

**Pull request closed without merging**
