### PR TITLE
Worflow Component: Add events which are dispatched

### PR DESCRIPTION
**Pull request by tomaszhanc**
More evnts are going to be dispatched - not only 'guard' events.

### CODE REVIEW

**Comment by HeahDude** [comment]
Thank you for this first contribution, but those event are now documented, and this place does not seem appropriate since this is a section about guard only.

So I'm 👎 on this, in the current state.

**Comment by xabbuh** [comment]
@HeahDude You are right about the example making use of the guard event. However, the section itself just is about events in general. So maybe we can keep the example, but remove the events reference part and link to the new section instead?

**Comment by HeahDude** [comment]
👍 Agreed!

**Comment by tomaszhanc** [comment]
@HeahDude Hi. The article is named 'How to Use the Workflow' so I thought is not only for how to use guards. I can change it but I can't find a place where all events are documented. Can you help me somehow with that?

**Comment by HeahDude** [comment]
@tomaszhanc Sorry for the delay. I'm closing here as https://github.com/symfony/symfony-docs/pull/7884 as been merged in the meantime.

**Pull request closed without merging**
