### PR TITLE
Make sure one can copy NPM command

### PR DESCRIPTION
**Pull request by Nyholm**
Comments cannot be copies

https://symfony.com/doc/current/frontend/encore/installation.html#installing-encore-in-symfony-applications

### CODE REVIEW

**Comment by javiereguiluz** [comment]
Thanks for this Tobias. I understand the issue ... but I wonder if showing two fully-working examples would make some people think that they need to run both commands.

Maybe we should allow to copy commented contents in commands (except the prompt contents)?

**Review by dbrumann — APPROVED** [review]

**Comment by Nyholm** [comment]
> but I wonder if showing two fully-working examples would make some people think that they need to run both commands.

I doubt that is the case. 

I like that I cannot copy comment, but could one only excluded comments like

```
# Cannot copy me
# $ echo "can copy me since I start with '# $'"
```

**Comment by dbrumann** [comment]
I think it's already clear from the surrounding text that this an alternative to yarn.

If I remember correctly yarn/npm will issue a warning to the user if they encounter each others lock file. I think both the text in the docs and that warning should be enough hints to prevent issues.

**Comment by javiereguiluz** [comment]
You made me change my mind. I've merged this in 3.4 (and all the other branches). Thanks!

**Pull request merged**
