### PR TITLE
Fix Typo $response->setEtag(..)

### PR DESCRIPTION
**Pull request by gmorel**
instead of $response->setETag(..)

Keep up the good work !

### CODE REVIEW

**Review by javiereguiluz — APPROVED** [review]
:+1:

@gmorel super nice catch! Thanks.

---

Beware that in `Symfony/Component/HttpFoundation/Response.php` the method is: `public function setEtag($etag = null, $weak = false)`

but in `sensio/framework-extra-bundle/Configuration/Cache.php`, the method is `public function setETag($expression)`

Should this inconsistency (`setEtag` vs `setETag`) be reported to Symfony?

**Comment by xabbuh** [comment]
> Should this inconsistency (`setEtag` vs `setETag`) be reported to Symfony?

@javiereguiluz IMO yes

**Comment by javiereguiluz** [comment]
@xabbuh done in https://github.com/sensiolabs/SensioFrameworkExtraBundle/issues/461

**Comment by xabbuh** [comment]
Thank you @gmorel.

**Pull request closed without merging**
