### PR TITLE
Added a note about cache_limiter

### LINKED ISSUE #12747: Missing hint that setting cache-limiter as defined in the docs resets all session configuration
At https://symfony.com/doc/4.3/reference/configuration/framework.html#cache-limiter there should be some hint saying that setting

```
# config/services.yaml
parameters:
    session.storage.options:
        cache_limiter: 0
```

resets session parameters like "cookie_samesite", "cookie_secure" and "cookie_httponly" to their default value.

### PR DESCRIPTION
**Pull request by javiereguiluz**
Fixes #12747.

### CODE REVIEW

**Comment by javiereguiluz** [comment]
@nicolas-grekas this was reported as an issue in #12747. Could you please verify if this is the expected behavior or if this might be a bug *(or half-implemented feature)* in Symfony code? Thanks!

**Comment by nicolas-grekas** [comment]
I don't know about this behavior.
The code has a comment saying:
> use "0" to prevent headers from being sent entirely

I don't know if this is the same as what is described in the linked issue.

@codegain might have more links to explain this?

**Comment by codegain** [comment]
@nicolas-grekas I was working on a project were these settings were set in `framework.yaml`:

```
session:
    storage_id: 'PHPSESSID'
    cookie_samesite: 'lax'
    cookie_secure: true
```

I set `cache_limiter` to `nocache` (via the container parameter as described in the docs). However, some days later I discovered that the `samesite` and `https` attributes of my session cookies disappeared. After I deleted the `cache_limiter` container parameter and re-logged into my application, the attributes appeared again. 

I think the `session.storage.options` parameter somehow overrides all or some session config from `framework.yaml`. Unfortunately I didn't have enough time to look further into it.

**Comment by javiereguiluz** [comment]
I'm closing this because we're not sure about these changes ... but I've left the related issue #12747 open to further investigate this. Thanks!

**Pull request closed without merging**
