### PR TITLE
Use Doctor RST 1.48.0

### PR DESCRIPTION
**Pull request by alamirault**
Ping @OskarStark

### CODE REVIEW

**Review by OskarStark — APPROVED** [review]

**Comment by OskarStark** [comment]
Thank you Antoine.

**Comment by OskarStark** [comment]
I upmerged this PR; can you please check the 6.3 branch and afterwards the 7.0 too? Thanks

**Comment by OskarStark** [comment]
Btw, I also released 1.48.1 with your bugfix

**Comment by alamirault** [comment]
I checked on 6.3 and 7.0. It's ok

**Pull request merged**
