### PR TITLE
Fix log directory parameter

### PR DESCRIPTION
**Pull request by merguezzz**
kernel.logs_dir instead of kernel.log_dir

### CODE REVIEW

**Review by dbrumann — APPROVED** [review]

**Comment by dbrumann** [comment]
Good catch :+1:

The parameter is deprecated anyway, but having this wrong in the 4.3 and 4.4 docs can be annoying.

**Comment by OskarStark** [comment]
Do you know since when its deprecated?

Because there is a `.. deprecated::` missing:
https://symfony.com/doc/3.4/reference/configuration/kernel#log-directory
https://symfony.com/doc/current/reference/configuration/kernel.html#log-directory

**Comment by dbrumann** [comment]
It's deprecated since 4.2, see https://github.com/symfony/symfony/blob/bfd308ff4ada2adb235c8db71350aa49cdf5d6d3/src/Symfony/Component/HttpKernel/Kernel.php#L683-L688

**Comment by OskarStark** [comment]
I created a PR to add the missing directive:
https://github.com/symfony/symfony-docs/pull/12581

**Review by OskarStark — APPROVED** [review]

**Comment by OskarStark** [comment]
Good catch, thanks @merguezzz.

**Pull request merged**
