### PR TITLE
Update error_pages.rst

### PR DESCRIPTION
**Pull request by amine-betari**

### CODE REVIEW

**Comment by amine-betari** [comment]
@wouterj @javiereguiluz 
What to you think about this ?

**Comment by javiereguiluz** [comment]
Thanks for this contribution. Sadly, we have multiple PRs about the same thing. See #12687 and #12692, so we'll need to merge all these PRs carefully and keep the best of each one. Thanks.

**Comment by amine-betari** [comment]
@javiereguiluz noted 

Thank you

**Comment by javiereguiluz** [comment]
@amine-betari at the end we decided to merge #12687 instead of this one because it makes more changes needed in this article. Thanks for understanding and thanks for your contribution even if this time it didn't make it.

**Pull request closed without merging**
