### PR TITLE
[VarDumper] Fix rendering of inline code

### PR DESCRIPTION
**Pull request by kevin-verschaeve**
A small piece of code that is not rendered correctly on the varDumper component

### CODE REVIEW

**Comment by javiereguiluz** [comment]
This is tricky. We did this on purpose because the `:class:` feature doesn't work with placeholders like `EXCLUDE_*`  so we decided to link to the class and append the `EXCLUDE_*` text at the end of it, so the link to Symfony API works.

Maybe we can fix this with a little reword:

```rst
* A bit field of ``EXCLUDE_*`` constants from the 
  :class:`Symfony\\Component\\VarDumper\\Caster\\Caster` class.
```

**Comment by kevin-verschaeve** [comment]
Oh I see. 

Yes we can do as you propose or keep as it is but removing some unwanted backquotes

image

See, there is twice 2 backquotes that prevent the rendering and complicate reading. We can just remove them.

Tell me, what is the best, I will update the PR

**Comment by kevin-verschaeve** [comment]
@javiereguiluz it seems that just adding a space fix the issue :)

**Review by boninir — APPROVED** [review]

**Comment by javiereguiluz** [comment]
I like your solution! Let's merge it (on 3.4 branch). Thanks!

**Pull request merged**
