### PR TITLE
docker-compose autobuild

### PR DESCRIPTION
**Pull request by marfillaster**
docker-compose
- local setup  127.0.0.1:8000
- autobuild using watchman

Requirements:

- docker-compose 1.10.0+ and latest docker engine

How to run:
docker-compose up

### CODE REVIEW

**Comment by javiereguiluz** [comment]
@marfillaster thanks for this contribution! Could you please share the requirements and exact steps one must follow to use this?

I guess the requirements is only to download and install Docker community edition from https://www.docker.com/get-docker but then ... which exact commands should I execute to run this? Thanks!

**Comment by marfillaster** [comment]
Added the requirement and how to run

**Comment by javiereguiluz** [comment]
I'm really interested in adding simple Docker support for this repository. However, I'd like to ask you about the proposal to include "watchman" too. Although is cool that you change some file and docs are built automatically ... I don't think it's that bad to run that command manually yourself. So, could we remove "watchman" in order to simplify things and easy future maintenance? Thanks!

**Comment by javiereguiluz** [comment]
@marfillaster we finally merged this! Sorry it took us so long and thanks for your help! By the way, I created a new pull request to tweak a bit one of the commands you proposed. See #10490.

**Pull request closed without merging**
