### PR TITLE
Update groups.rst

### PR DESCRIPTION
**Pull request by ThomasLandauer**
Integrating the findings of https://github.com/EasyCorp/EasyAdminBundle/issues/2673#issuecomment-476299467

Please fix the link to [guess your form types] - I don't know how to link to an anchor in the docs!

### CODE REVIEW

**Comment by javiereguiluz** [comment]
Thanks! Personally I find this article a bit complex ... and we keep adding more and more complexity to it ... but maybe it's the way it should be because the underlying is confusing/complex/full of edge cases.

**Comment by ThomasLandauer** [comment]
Well, I've seen many Symfony pages that are worse than this one ;-) It took me hours to figure the details out yesterday - just wanted to share that.

And whenever anything doesn't work like one could expect, it's always better to explain it...

**Comment by wouterj** [comment]
First of all: Thank you for your pull request! It's definitely appreciated that you put time into finding out internal logic and make it available to the rest of the community through documentation!

However, I can also see Javier's point. Can't we reduce the note to "Validation groups are ignored while guessing form types and options"? That would be a short warning and will give enough information I think to understand the "weird" behaviour. What do you think?

**Comment by xabbuh** [comment]
I agree with @wouterj.

**Comment by ThomasLandauer** [comment]
First of all: https://github.com/symfony/symfony-docs/pull/11222 is by far more important! This one here is only a side product.

Sorry guys, I can't see why you're always so hesitant to include *more details*. Do you really think that it's *easier* for anybody to figure it out themselves?? Compared to spending another minute to read it?

> "Validation groups are ignored while guessing form types and options"

"ignored" is ambiguous here: Will it apply all constraints (i.e. ignore the `groups` setting), or will it ignore the constraints that are in a group? Besides, it only covers my first list point, not the second:

> If you don't let Symfony guess your form types, no constraints will be considered at all in the form's view.

**Comment by wouterj** [comment]
Yes, less verbose docs is better. Nobody likes to (or will actually) read very verbose documentation. People will skip sentences, meaning they'll almost certainly miss the important bit. If you only type the important information and leave out any verbose details that aren't needed, you "force" the reader to read the important bits.

Anyway, I'm going to close this PR as there hasn't been any activity for over a year. Besides, I just discovered that this information is already inside the documentation (for the past 9 years) on the form type guessing section, which also makes more sense to me: https://github.com/symfony/symfony-docs/commit/7a82a8950d7231cc182f9b04fe3ca02a4b268234

**Pull request closed without merging**
