### PR TITLE
[WIP] Contact everyone doc

### PR DESCRIPTION
**Pull request by franckranaivo**

### CODE REVIEW

**Comment by javiereguiluz** [comment]
~Closing because the contents of this pull request look wrong and the title gives spam vibes.~

@franckranaivo if your pull request is legit, please tell us and we'll reopen. Thanks!

**Comment by wouterj** [comment]
I think it was meant as a doc PR for https://github.com/symfony/symfony/pull/46395 (the contact everyone notifier bridge), but something went wrong :)

**Comment by javiereguiluz** [comment]
Ah. Ok. Let's reopen then.  Sorry @franckranaivo 🙏 . If you cannot remove the unrelated commits from this PR we can close it again to create a new PR. If you need any help, please ask us. Thanks!

**Comment by franckranaivo** [comment]
Ah yes it was meant for https://github.com/symfony/symfony/pull/46395 as i was requested to create a PR for the docs. Actually I created one for 6.2, but @carsonbot said that it was not maintained anymore. Then I switched to 6.1 and saw other commits after that. 
Should I close maybe this one and create another PR from 6.2 ? @javiereguiluz .
I apologize if I did wrong as it is my first PR on docs also.

**Comment by wouterj** [comment]
No worries! For some reason, your commit appears to be lost (none of the 6 commits listed in this PR appear to be yours). So yes, I think the only way to fix this is to try to submit a new one (for the 6.2 branch).

> Actually I created one for 6.2, but @carsonbot said that it was not maintained anymore. Then I switched to 6.1 and saw other commits after that.

Ah yeah. Carsonbot has a little issue with dev branches created before entering development phase (the 6.2 development phase starts at June 1st, but we created the branch in advance to prepare the 6.1 release). 6.2 is the correct branch for the PR :)

**Pull request closed without merging**
