### PR TITLE
Added info how to disable the mock session

### PR DESCRIPTION
**Pull request by ThomasLandauer**
Should be explained somewhere...

### CODE REVIEW

**Comment by xabbuh** [comment]
I can see that this information is somehow useful. But I don't think that this file is the right place as it describes the usage of the HttpFoundation component without using the full framework. Thus, you probably won't have such a `config_test.yml` file.

**Comment by ThomasLandauer** [comment]
Well, since you didn't suggest a better place, I guess there is none :-)
What about just adding: "If you're using the full framework..."

**Review by javiereguiluz — APPROVED** [review]
I can't find any better place to put this, so let's merge it as is. Thanks!

**Comment by xabbuh** [comment]
#8994 proposes to explain the mock file handler too

**Comment by javiereguiluz** [comment]
@xabbuh I'm confused by all this. What do you propose to do to solve this and #8994?

**Comment by xabbuh** [comment]
I am not sure yet. But I am also a bit confused about the changes themselves. The text talks about disabling the mock session storage, but if I don't miss anything, the following config example does the exact opposite.

**Comment by javiereguiluz** [comment]
Let's close this because in the configuration reference of the Framework Bundle we already explain this option (https://symfony.com/doc/current/reference/configuration/framework.html#storage-id) so it's better to not mention in the component docs too. Thanks!

**Pull request closed without merging**
