### PR TITLE
Update security_checker.rst

### PR DESCRIPTION
**Pull request by shreypuranik**
Adding a minor addition to the Tip note about integrating security checker with continuous integration workflow.

### CODE REVIEW

**Comment by javiereguiluz** [comment]
@shreypuranik thanks for this contribution!

The way I understood your contribution is like this: "be careful, if you add this command and there are vulnerabilities, the build will fail". The way it's explained looks like a bad thing ... but that's precisely what we want to emphasize: add this command to your CI, because when there are vulnerabilities, it will fail.

I've reworded it a bit to make this more clear. Is it OK to you? Thanks.

**Comment by shreypuranik** [comment]
Hi @javiereguiluz, thanks for reviewing so promptly. I completely agree with your amended commit, as it certainly reads a lot more transparently. I have added a minor line to emphasise the non-zero exit code. Hope thats ok? Thanks,

**Comment by javiereguiluz** [comment]
@shreypuranik I'm afraid I don't agree with your last proposal 😓  I think it's redundant with the first phrase, which also talks about non-zero exit code.

**Comment by shreypuranik** [comment]
@javiereguiluz Thanks for reviewing. I have just pushed up a further commit which removes the additional line about the non-zero exit code.

**Comment by javiereguiluz** [comment]
Thank you @shreypuranik! We merged it in the 3.4 branch and we'll merge it in the upper branches automatically later.

**Pull request closed without merging**
