### PR TITLE
Fix words according context

### PR DESCRIPTION
**Pull request by richardpq**
| Q | A |
| --- | --- |
| Doc fix? | yes |
| New docs? | no |
| Applies to | 2.3+ |
| Fixed tickets | n/a |

### CODE REVIEW

**Comment by richardpq** [comment]
** Applies to ---> 2.3+

**Comment by richardpq** [comment]
After submit this PR, I noticed that this should applied to 2.3+ (I made the PR to 2.8), should I close this and submit a new PR from 2.3?

**Comment by xabbuh** [comment]
:+1: Perfect pull request!

By the way, you don't need to worry about the right target branch. We have a nice tool that we use to merge which is able to do the rebase when merging.

**Comment by richardpq** [comment]
@xabbuh perfect! thanks for the tip.

**Comment by WouterJ** [comment]
:+1:

**Comment by xabbuh** [comment]
Thank you @richardpq.

**Comment by xabbuh** [comment]
Thanks for this perfect pull request Richard. Your changes have been squashed before being merged. That's why your pull request is shown as closed instead of merged.

**Comment by richardpq** [comment]
@xabbuh I'm glad to help, but what you mean by "Your changes have been squashed before being merged", when should I expect to see these changes :D?

**Comment by xabbuh** [comment]
@richardpq Squashed means that the two commits of your pull request have been merged to one. In fact I would have expected the changes to be already visible, but I do not know the exact time the documentation is built.

@javiereguiluz Can you help us here?

**Comment by javiereguiluz** [comment]
@xabbuh it should be visible by now because doc is generated daily very early in the morning (European Time).

**Comment by richardpq** [comment]
@xabbuh Thanks again for your explanation.

@javiereguiluz I don't see changes yet, maybe because LATAM's cache or something like that, If I don't see by tomorrow, should I ping you?

**Comment by javiereguiluz** [comment]
@richardpq I don't see the changes either. This is probably a bug. I'll take a look, but feel free to ping me. Thanks!

**Comment by javiereguiluz** [comment]
It took some time, but the new doc is available on symfony.com. Thanks for your contribution and for your patience.

**Comment by richardpq** [comment]
Great! have nice weekend

On Sat, Dec 12, 2015 at 5:44 AM, Javier Eguiluz <notifications@github.com>
wrote:

> It took some time, but the new doc is available on symfony.com. Thanks
> for your contribution and for your patience.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/symfony/symfony-docs/pull/5989#issuecomment-164138517>
> .
>



-- 
*Atte.*
*Richard R. Perez Q.*

**Pull request closed without merging**
