### PR TITLE
Documented the compiler passes priorities

### LINKED ISSUE #6671: [3.2] Document compiler pass priorities
In Symfony 3.2, besides configuring the compiler pass type, you can also configure a priority.

Refs https://github.com/symfony/symfony/pull/18022

### PR DESCRIPTION
**Pull request by javiereguiluz**
This fixes #6671.

### CODE REVIEW

**Comment by stof** [comment]
I would add that the default priority is ``0``

**Comment by HeahDude** [comment]
👍

Status: Reviewed

**Comment by xabbuh** [comment]
:+1:

**Comment by xabbuh** [comment]
Thank you Javier.

**Pull request closed without merging**
