### PR TITLE
Collections add example without JQuery

### PR DESCRIPTION
**Pull request by kunicmarko20**
I needed this example without JQuery, so I thought it could maybe be in the docs. If there is no place for plain javascript or maybe we don't want to confuse people, just close it.

### CODE REVIEW

**Comment by javiereguiluz** [comment]
In my opinion, we should remove all jQuery examples from the docs and switch them to plain JavaScript. @xabbuh @weaverryan do you agree? Thanks!

**Comment by xabbuh** [comment]
Do we have many other examples using jQuery?

**Comment by kunicmarko20** [comment]
I know there is 2 more around removing and adding the collections [here](https://symfony.com/doc/current/form/form_collections.html#allowing-new-tags-with-the-prototype).

**Comment by javiereguiluz** [comment]
We can change the other jQuery examples ni a different PR if you prefer. Also, shouldn't we remove the original jQuery example in this PR and only display the JavaScript one?

**Comment by kunicmarko20** [comment]
@javiereguiluz if this is the way you want to go then yes, Initially my idea was to just provide both examples.

**Comment by kunicmarko20** [comment]
Since I don't have time to check all examples and provide Javascript replacement and I don't think there is a point of having just one example in javascript and other in jquery I am gonna close this.

**Pull request closed without merging**
