### PR TITLE
Integrate the "Create your own framework" tutorial

### PR DESCRIPTION
**Pull request by javiereguiluz**
This is a follow-up of the stalled #4455 PR. I've made most, but not all, of the changes proposed by reviewers.

Specifically, I haven't changed the occurrences of `we` by `you`. The reason is that it's too much work. The original PR (submitted 8 months ago) died for that reason. So here it is my question: could we bypass the `we -> you` changes to merge it as soon as possible and fix that in further pull requests?

### CODE REVIEW

**Comment by fabpot** [comment]
I agree that changing the we to you would be great, but merging this PR fast would be even better. There is quite a lof of traffic on this tutorial on my blog and as it becomes more outdated by the day, I would really like to redirect people in the official Symfony docs instead.

**Comment by xabbuh** [comment]
I would be fine with merging this in the short-term if we could get rid of the numbers in the filenames. That way we could later discuss if the structure will stay the same or if we need/want to split contents further without having weird/misleading URLs (the FOSRestBundle had something similar recently when splitting a chapter).

**Comment by javiereguiluz** [comment]
@xabbuh I've just removed the numbers from the file names. I'm also willing to do any other big change that you consider necessary before merging this tutorial (except for the mentioned `we -> you` change).

**Comment by xabbuh** [comment]
@javiereguiluz Seems that some internal references need to be updated too.

**Comment by stof** [comment]
I agree about merging this. However, changing we -> you should still be done as a separate PR to keep consistency in the doc. So if you don't do it yourselves, please open an issue to tell people about it.

**Comment by xabbuh** [comment]
@weaverryan @WouterJ What do you think about merging this as is and tweak in subsequent pull requests?

**Comment by fabpot** [comment]
Let's do it :)

**Comment by dupuchba** [comment]
That's really cool :-) :+1:

**Comment by weaverryan** [comment]
:thumbsup: - I've merged it in. It's way too big anyways to get perfect - so now let's see all those small changes :). Thanks!

**Pull request merged**
