### PR TITLE
Fix typo in UserType class

### PR DESCRIPTION
**Pull request by Dorozhko-Anton**
delete extra ';'

### CODE REVIEW

**Comment by javiereguiluz** [comment]
:+1: I totally forgot to fix this error in #5794. By the way, this change must be merged in 2.3 branch. But don't worry, there is no need to create a new pull request with the right branch. Our doc managers will change the branch while merging the changes.

**Comment by OskarStark** [comment]
:+1:

**Comment by WouterJ** [comment]
:+1:

**Comment by WouterJ** [comment]
Thanks @Dorozhko-Anton! I've merged your fix into the 2.3 version of the docs and will merge it in the newer versions from there.

**Pull request closed without merging**
