### PR TITLE
remove assetic dic tags. Fix #7274

### LINKED ISSUE #7274: Update reference/dic_tags.rst
The article still mentions `assetic.*` tags.

### PR DESCRIPTION
**Pull request by garak**

### CODE REVIEW

**Comment by xabbuh** [comment]
:+1:

Status: Reviewed

**Comment by javiereguiluz** [comment]
@garak I'm sorry but, could you please rebase this to make it mergeable again? Thanks!

**Review by javiereguiluz — APPROVED** [review]

**Comment by garak** [comment]
Rebased

**Comment by HeahDude** [comment]
@garak Could you please take care of @xabbuh's comment in #7274? Also this should target 3.2. Thanks!

**Comment by javiereguiluz** [comment]
@garak I'm really really sorry but I must close this pull request without merging it. Why? Because we're doing massive changes on all Symfony Docs articles and we've made this very same change as part of the revamp of the frontend articles in #8750. Thanks for understanding it!

**Pull request closed without merging**
