### PR TITLE
Added info on doctrine metadata implications on validation

### PR DESCRIPTION
**Pull request by ThomasLandauer**
It took me a while to figure this out. So I think it should be explained _somewhere_. I'm not sure if this is the right place, and I'm also not sure if the information is comprehensive.
Just wanted to get somehing going about 'Doctrine and validation' somewhere in the docs.

### CODE REVIEW

**Comment by ogizanagi** [comment]
This feature is actually provided by type guessers (especially the Doctrine ORM one). it does not work only for the `length` attribute, but for many other usages.
However, it only works when not specifying any type for the given field in the form, but let the symfony registered type guessers do the work for you. So I don't think this particular note should be added.

It's more or less explained in [Creating a custom Type Guesser](http://symfony.com/doc/current/components/form/type_guesser.html).

**Comment by ThomasLandauer** [comment]
I'm not sure that we're talking about the same thing.

When I create a form like here: http://symfony.com/doc/current/book/forms.html#creating-form-classes
...and in the Entity I set the length to 10, I get the `maxlength` attribute in HTML. However, when I do submit more than 10 characters, I don't get any error message from the validator. This is only the case when I add a rule in validation.yml too.

The DoctrineOrmTypeGuesser, is this enabled by default? If no, where do I have to enable it?

**Comment by ogizanagi** [comment]
@ThomasLandauer : I confirm we're talking about the same thing. Types guessers are not about validation, they guess the form type to use and some attributes like `required` or other html attributes.
Type guessers shipped with Symfony are based on Symfony's Validator & Doctrine metadata.

See:

- [DoctrineORMTypeGuesser](https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Doctrine/Form/DoctrineOrmTypeGuesser.php)
- [ValidatorTypeGuesser](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Extension/Validator/ValidatorTypeGuesser.php)

Input type, required, max length & pattern html attributes are guessed thanks to them.

The `DoctrineOrmTypeGuesser` is enabled by default.
But as I said, type guessers are only active for fields for which you didn't specified explicitely a type when creating the form.

**Comment by ThomasLandauer** [comment]
OK, my point is: Being a smart framework, I (personally) would have expected that Symfony automatically uses my Doctrine metadata for validation (i.e. true server-side validation). Since this is not the case, I think it should be explained *somewhere* that the user is expected to repeat the ORM rules in validation.yml.

I think the entire form chapter should be reorganised, prioritizing more on real use-cases (linke this one, namely binding a form to a database entity) and less on exotic features like forms with multiple submit buttons. In other words: Before you can tell people about validation groups, you should tell them how validation works at all :-)

I don't insist on my particular wording, neither on this very location. But, again, since binding a form to a database entity is a standard use-case, it should be explained somewhere how validation works in this case.

**Comment by weaverryan** [comment]
Hey guys!

Catching up on some old PR's :). I definitely agree with you @ThomasLandauer, and when I went through the current docs (which *have* been restructured already in many of the ways you suggested), I found out that I think we now have this covered: the forms chapter talks about field option guessing, what it does, and how it works: http://symfony.com/doc/current/forms.html#field-type-options-guessing. And, this conversation comes *after* talking about real, server-side validation.

So, I'm going to close this PR as finished - please feel free to open a PR if you think we could clarify further.

Thanks!

**Comment by ThomasLandauer** [comment]
Um, now the entire "Forms and Doctrine" subsection (https://github.com/ThomasLandauer/symfony-docs/blob/dbe120598ca6fd38b38adff456a2247d3849645b/book/forms.rst#forms-and-doctrine) of the forms chapter is gone!
Was this moved to a separate article?? Can't find it anywhere.....

So while being better in general, the new version of the chapter is even worse than the old one, regarding the interplay with Doctrine. Which is the most widely used use-case of a form, after all.

**Pull request closed without merging**
