### PR TITLE
Added the VarDumper to the debug/debugging page

### PR DESCRIPTION
**Pull request by hiddewie**
Issue #6342.

I've added a little example of the `VarDumper` component.

### CODE REVIEW

**Comment by snoek09** [comment]
Should we also add here how to use VarDumper in Twig?
Or should we instead link to `components/var_dumper.rst`?

**Comment by hiddewie** [comment]
I think the most important part about the VarDumper is its usage in PHP code. A link to the Components article is more useful in my opinion.

**Comment by wouterj** [comment]
Hi @hiddewie! Thanks for starting this!

I've taken your commit and included it in https://github.com/symfony/symfony-docs/pull/7071. I've also did some minor rewrites of your text in that PR. Let me know what you think!

Thanks again, I hope to see more of these great PRs in the future!

**Comment by hiddewie** [comment]
Great, looks good!

Thank you!

**Pull request closed without merging**
