### PR TITLE
Update Doc : Symfony 4.3 - Swift Mailer

### PR DESCRIPTION
**Pull request by TheGarious**
Review Example, erase HelloBundle architecture by templates architecture.

### CODE REVIEW

**Review by weaverryan — APPROVED** [review]
I didn’t notice any other bad bundle references in the doc.

**Comment by TheGarious** [comment]
In doc Symfony v4.4, this reference of bundle exist.

**Comment by javiereguiluz** [comment]
Gary, thank you very much for fixing this error! Congrats on your first Symfony Docs contribution too!

**Comment by javiereguiluz** [comment]
We merged this in "4.4" and "master" branches too. There are other occurrences of "HelloBundle" in the docs ... but all of them look legitimate to me because they are used when talking about bundles. Cheers!

**Pull request merged**
