### PR TITLE
[Finder] Add case insensitive sort

### PR DESCRIPTION
**Pull request by hmoreau**
Add a second argument to `sortByName()` method to select between case sensitive and case insensitive sort.

### CODE REVIEW

**Comment by javiereguiluz** [comment]
@hmoreau thanks for this contribution! Will you have some time to rebase this PR into 6.2 branch and remove the unrelated commits? Thanks!

**Comment by hmoreau** [comment]
Sure, rebase is done

**Review by OskarStark — COMMENTED** [review]
Look alike the rebase does not worked 🤔

**Comment by hmoreau** [comment]
Here is what I did :
```
git remote add upstream https://github.com/symfony/symfony-docs.git
git fetch upstream
git rebase upstream/6.2
git push
```
Is there something else to do ?

**Comment by OskarStark** [comment]
You rebased on 6.2, but the target branch of this PR is `6.1`

**Comment by hmoreau** [comment]
Oh yes you are right, thank you.
I tried to change to 6.2, but I got the error : 
`There are no new commits between base branch '6.2' and head branch 'CASE_INSENSITIVE_FILE_LIST'`

**Comment by hmoreau** [comment]
May be it is easier if I make a new PR from scratch?

**Comment by javiereguiluz** [comment]
@hmoreau yes please, create a new PR with the right commit with your changes. Thanks!

**Pull request closed without merging**
