### PR TITLE
Minor - Remove deprecated self::$container

### PR DESCRIPTION
**Pull request by jmontoyaa**

### CODE REVIEW

**Review by maxhelias — APPROVED** [review]

**Comment by tcheuD** [comment]
Duplicate of #15487

**Comment by ker0x** [comment]
Not a duplicate as it's not the same file 😉

**Comment by tcheuD** [comment]
> Not a duplicate as it's not the same file 😉

My bad, didn't notice :)

**Review by OskarStark — APPROVED** [review]

**Comment by OskarStark** [comment]
Thank you Julio.

**Pull request merged**
