### PR TITLE
Fix - Added missing entity_manager

### PR DESCRIPTION
**Pull request by KhanMaytok**
Added missing entity_manager  to arguments in services.yml

### CODE REVIEW

**Comment by xabbuh** [comment]
Can you explain why you think this change is necessary? The code of the `TokenAuthenticator` being shown doesn't make use of the entity manager at all if I don't miss anything.

**Comment by KhanMaytok** [comment]
Get the error:

    Type error: Argument 1 passed to AppBundle\Security\TokenAuthenticator::__construct() must be an instance of Doctrine\ORM\EntityManager, none given

**Comment by xabbuh** [comment]
Did you make some additional changes to the `TokenAuthenticator` in your project compared to what it looks like in the docs?

**Comment by javiereguiluz** [comment]
@KhanMaytok I agree with @xabbuh. There's no need to make this change because the `TokenAuthenticator` showed in the example doesn't use the database. Maybe you need to inject the entity manager in your particular case, and that's perfectly fine! ... but for this example, I'm afraid it's not needed.

**Pull request closed without merging**
