### PR TITLE
[Router] Fix custom router loader service declaration

### PR DESCRIPTION
**Pull request by michaelperrin**
The service tag was not declared correctly.

### CODE REVIEW

**Comment by xabbuh** [comment]
Did you try this? Symfony 3.3 should support this notation IIRC.

**Comment by michaelperrin** [comment]
@xabbuh I did try this (I can give you the link to the repo if needed). And it doesn't work on Symfony 3.3.

What Symfony 3.3 introduced is a short syntax to define arguments (see [here](http://symfony.com/blog/new-in-symfony-3-3-simpler-service-configuration#short-syntax-for-service-configuration)).
In the current docs, it doesn't work as `routing.loader` is passed as if it were an argument, instead of a tag.

**Review by GuilhemN — APPROVED** [review]
This change was indeed wrong, good catch :+1:

**Review by xabbuh — APPROVED** [review]
checked this with @GuilhemN and this is indeed the right fix

**Comment by xabbuh** [comment]
Good catch, thanks @michaelperrin.

**Pull request merged**
