### PR TITLE
[Mime] Allow to embed images as CSS backgrounds

### LINKED ISSUE #16492: [Mime] Fix embed logic for background attributes
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#45376
| PR author(s) | @flack
| Merged in    | 6.1

### PR DESCRIPTION
**Pull request by javiereguiluz**
Fixes #16492.

### CODE REVIEW

**Comment by flack** [comment]
I don't think this is correct: What I implemented in symfony/symfony#45376 is only support for the old-timey `background=""` attribute, not for CSS `background-image` (see also the PR description). It could be added realtively easily and it would certainly be nice to have, but it's not implemented as of now

**Comment by javiereguiluz** [comment]
@flack thanks for telling me about this error. I've fixed it in https://github.com/symfony/symfony-docs/commit/b39f0de537a9c69b43baa7c678cf30684d44216b Cheers!

**Comment by flack** [comment]
@javiereguiluz sorry, but that's still not right. What I implemented was only support for this:

```html
<div background="cid:some-img.png"></div>
```

So really the HTML attribute `background`, not the CSS property by the same name

**Comment by javiereguiluz** [comment]
@flack fixed again! Thanks.

See https://github.com/symfony/symfony-docs/commit/868e311329d3f4a1e5d794bda220e5b599b03993

**Pull request merged**
