### PR TITLE
Updated default validation mapping directory

### PR DESCRIPTION
**Pull request by zairigimad**
Change the default mapping directory

### CODE REVIEW

**Review by OskarStark — COMMENTED** [review]
No need to adjust the xml example?
Sorry I am currently on a phone and cannot double check it 👍🏻

**Review by HeahDude — CHANGES_REQUESTED** [review]
Thanks for that PR, the other formats below (XML and PHP) need indeed to be updated as well

**Comment by zairigimad** [comment]
> Thanks for that PR, the other formats below (XML and PHP) need indeed to be updated as well

@HeahDude done

**Review by OskarStark — APPROVED** [review]

**Comment by OskarStark** [comment]
Thank you Zairig.

**Pull request merged**
