### PR TITLE
Ensure that the entity is updated.

### PR DESCRIPTION
**Pull request by yceruto**
| Q | A |
| --- | --- |
| Doc fix? | yes |
| New docs? | no |
| Applies to | All |
| Fixed tickets | #5448 |

### CODE REVIEW

**Comment by WouterJ** [comment]
Thank you @yceruto! I've labelled it as finished, although I'm not sure if it's correct (I don't know much about the logic behind these file upload chapters). So I let other doc maintainers decide whether to merge it or not.

Please also note that this article is likely to be removed soon: https://github.com/symfony/symfony-docs/issues/2346#issuecomment-115739439

**Comment by xabbuh** [comment]
I remember that we recently had an issue/pull request were someone requested a similar change. Unfortunately, I cannot find it anymore.

**Comment by yceruto** [comment]
the problem lies in this https://github.com/symfony/symfony-docs/commit/15ccf24a60db0491bacba9886d8329efe87e20cb

**Comment by xabbuh** [comment]
:+1: We really need to facelift the article, but this change should at least fix the issue described in #5448.

**Comment by weaverryan** [comment]
Thanks @yceruto for the fix!

**Pull request closed without merging**
