### PR TITLE
Adds exception template variable available in custom error pages

### PR DESCRIPTION
**Pull request by dbrumann**
Alongside `status_code` and `status_text` you also have access to `exception` template variable in custom error pages.

### CODE REVIEW

**Comment by wouterj** [comment]
If I look at [the `TwigErrorRenderer`](https://github.com/symfony/symfony/blob/bd42f129df054d1a85360620f1c7d6c7a5168329/src/Symfony/Bridge/Twig/ErrorRenderer/TwigErrorRenderer.php#L51-L62), this variable contains a flat PHP string that is generated by the `HtmlErrorRenderer`. Are we sure we get an exception object in this variable?

**Comment by dbrumann** [comment]
I am just playing around with it and I got an error when assuming it was a string:
```
[2020-02-22T09:49:00.650785+00:00] request.CRITICAL: Uncaught PHP Exception Error: "Object of class Symfony\Component\ErrorHandler\Exception\FlattenException could not be converted to string" at /Users/dbr/workspace/error-demo/var/cache/prod/twig/ac/ac9e7bd5dee35e014b7f05a2dc891d2edd36162209f88af6abe5aa1fb054ffb1.php line 69 {"exception":"[object] (Error(code: 0): Object of class Symfony\\Component\\ErrorHandler\\Exception\\FlattenException could not be converted to string at /Users/dbr/workspace/error-demo/var/cache/prod/twig/ac/ac9e7bd5dee35e014b7f05a2dc891d2edd36162209f88af6abe5aa1fb054ffb1.php:69)"} []
```

I will have another look into it, to make sure it wasn't a fluke.

**Review by wouterj — APPROVED** [review]
Nevermind, you're completely correct. The [`HtmlErrorRenderer`](https://github.com/symfony/symfony/blob/bd42f129df054d1a85360620f1c7d6c7a5168329/src/Symfony/Component/ErrorHandler/ErrorRenderer/HtmlErrorRenderer.php#L73) returns `$exception->setAsString(...)`, which does not return a string :man_facepalming: . Using fluent PHP methods in this way makes code really confusing to read imho.

Anyway, this PR is correct. :+1:

**Comment by dbrumann** [comment]
I agree, it's a bit unfortunate. I will open an issue in symfony/symfony to straighten out the naming there and then update the docs accordingly.

**Comment by javiereguiluz** [comment]
Thanks Denis.

**Pull request merged**
