### PR TITLE
Update access_control.rst

### PR DESCRIPTION
**Pull request by kockodev**
Extend documentation with IP netmask

### CODE REVIEW

**Comment by javiereguiluz** [comment]
@rapemer just asking. Do this work in Symfony 2.7 too? If yes, then we'll merge this on 2.7 branch. Thanks.

**Comment by rapemer** [comment]
@javiereguiluz since this commit https://github.com/symfony/symfony/commit/d9ac57123dff6d29e8e62d81cc06df7c4673be21#diff-23b6cd28961e2f301e71e2632ba728ab is available in IpUtils ... Since this PR https://github.com/symfony/symfony/issues/7249 is documentation fully supported.

**Comment by javiereguiluz** [comment]
Thanks! So, it's available sin Symfony 2.3 and we'll then merge it on 2.7 branch. But there's no need for you to rebase this. We'll do that when merging. Thanks!

**Comment by javiereguiluz** [comment]
@rapemer this was a very nice first contribution to Symfony Docs. Thank you!

**Pull request closed without merging**
