### PR TITLE
Updated the Symfony Versions Roadmap image

### PR DESCRIPTION
**Pull request by javiereguiluz**
| Q | A |
| --- | --- |
| Doc fix? | yes |
| New docs? | no |
| Applies to | all |
| Fixed tickets | #5470 |

### CODE REVIEW

**Comment by stof** [comment]
:+1: 

Btw, which tool are you using to generate them ?

**Comment by javiereguiluz** [comment]
I've created the image with Apple Keynote, which is the tool I use for anything related to "design".

**Comment by xabbuh** [comment]
:+1:

**Comment by OskarStark** [comment]
would be cool to do this with css :)

**Comment by weaverryan** [comment]
Looks great - so thankful for your design skills @javiereguiluz :)

**Pull request merged**
