### PR TITLE
[Validator] Showcase custom validator constraint required option

### LINKED ISSUE #16674: [Validator] Allow creating constraints with required arguments
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#45072
| PR author(s) | @norkunas
| Merged in    | 6.1

### PR DESCRIPTION
**Pull request by norkunas**
Closes #16674

### CODE REVIEW

**Comment by wouterj** [comment]
Hi! Thank you for your quick response.

I think it's best to create a new example (directly after the first one), e.g. "You can use `#[HasNamedArguments]` or `getRequiredOptions()` to make some constraint options required". This also allows us to add a "versionadded" box:

```rst
.. versionadded:: 6.1

    The ``#[HasNamedArguments]`` attribute was introduced in Symfony 6.1.
```

If you agree, are you able to make the changes? :)

**Comment by norkunas** [comment]
Hi, will update tomorrow :)

**Review by wouterj — APPROVED** [review]
Looking good, thank you!

**Comment by javiereguiluz** [comment]
Thank you Tomas.

**Pull request merged**
