### PR TITLE
[Form] Add new prototype_options

### PR DESCRIPTION
**Pull request by michaelKaefer**
Related PR: https://github.com/symfony/symfony/pull/45605

### CODE REVIEW

**Comment by michaelKaefer** [comment]
Sorry, this is not finished yet.

**Comment by michaelKaefer** [comment]
From my side this is finished now. But it still waits for code merge.

**Comment by michaelKaefer** [comment]
The code was merged now, so this could also be reviewed/merged.

**Comment by javiereguiluz** [comment]
Michael, thanks a lot for implementing this feature and providing its docs! We've merged this into 6.1 (minor comment:  we added the missing `.. versionadded:: 6.1` directive while merging). Cheers!

**Comment by allok** [comment]
@javiereguiluz Please look at this pull, we all need it.

**Pull request merged**
