### PR TITLE
[Forms] Add empty_data to the form HiddenType

### LINKED ISSUE #13401: [Forms] HiddenType: `empty_data` is missing completely
The option `empty_data` is missing at https://symfony.com/doc/3.4/reference/forms/types/hidden.html

Here's an example: https://stackoverflow.com/a/54583057/1668200

### PR DESCRIPTION
**Pull request by osavchenko**
Fixes #13401.

### CODE REVIEW

**Comment by javiereguiluz** [comment]
Thank you Oleksandr.

**Comment by xabbuh** [comment]
Please note that I agree with this change, but that blindly using the `empty_data` option is not the general solution for the problem laid out in #13401. Furthermore, the `empty_data` option is available in all other form types too. So maybe someone would like to submit a PR syncing all of them?

**Comment by osavchenko** [comment]
I thought about it, but decide to solve this issue first. Will double check other options for this and other form types.

**Comment by osavchenko** [comment]
@xabbuh I have a question about other options. Could you please advise me?

We have [HiddenType](https://symfony.com/doc/3.4/reference/forms/types/hidden.html) which is inherited from [FormType](https://symfony.com/doc/3.4/reference/forms/types/form.html) and of course, some options are missed here, but I have checked TextType which is also inherited from FormType and on [TextType](https://symfony.com/doc/3.4/reference/forms/types/text.html) we can find missed inherited options too. So, should we document all inherited options even if it looks useless like a label for the hidden type or we should use some rules for documenting options?

**Comment by HeahDude** [comment]
ref https://github.com/symfony/symfony-docs/pull/6265#issuecomment-220782524

**Comment by osavchenko** [comment]
@HeahDude Your notice was about `DEFAULT_PLACEHOLDER`?

**Pull request merged**
