### PR TITLE
Move annotations example to front

### PR DESCRIPTION
**Pull request by ifdattic**
| Q | A |
| --- | --- |
| Doc fix? | yes |
| New docs? | no |
| Applies to | 2.3 |
| Fixed tickets |  |

### CODE REVIEW

**Comment by stof** [comment]
it should be done in all files, not only in 1

**Comment by ifdattic** [comment]
As this is the best practice I think most of them have annotations moved to the front, this is just one of the leftover.

**Comment by weaverryan** [comment]
Thanks @ifdattic!

**Comment by weaverryan** [comment]
Oh, and I think there are more that don't show annotations or don't show them first, but we will re-work those little by little.

**Comment by ifdattic** [comment]
So far I found only two of them. Still have about half of components section to read and some other misc pages if I will find any of them will send a PR

**Pull request merged**
