### PR TITLE
Adds potential phar troubleshooting to quick tour

### PR DESCRIPTION
**Pull request by sclarson**
| Q | A |
| --- | --- |
| Doc fix? | yes |
| New docs? | no |
| Applies to | all |
| Fixed tickets | none |

### CODE REVIEW

**Comment by xabbuh** [comment]
Thank you for your contribution @sclarson. I have just a few questions: Is this a common issue? On which OS did you experience it? Is the setting turned off by default there?

**Comment by sclarson** [comment]
This happened on arch linux for me.  I don't have access to anything else right now but can verify osx/windows tonight.  I did run across someone in the symfony forums with a similar issue on a synology.  A better step than specific phar debugging information may be to make a note about running php app/check.php and verifying everything no errors/warnings.

**Comment by javiereguiluz** [comment]
@sclarson when using the Symfony Installer, the `app/check.php` is run automatically and the list of errors is displayed to the user.

**Comment by sclarson** [comment]
That makes sense. So the only zero feedback path would be phars not being
enabled.

**Comment by sclarson** [comment]
It looks like this only impacts arch for the linux distros.  Tried Ubuntu/Fedora/Debian on the linux side and both macports and homebrew in osx.

**Comment by weaverryan** [comment]
Thanks for the patch and research on this @sclarson! But, I'm :-1: on this: we need to be very careful with the quick tour especially, to only include the most important and applicable information (so it doesn't get really long with edge cases - a killer for docs). If this is a problem that is common enough, I think it would need to be addressed during the installer "install" process.

**Pull request closed without merging**
