### PR TITLE
Minor rewordings for the "deprecated" service option

### PR DESCRIPTION
**Pull request by javiereguiluz**
| Q | A |
| --- | --- |
| Doc fix? | no |
| New docs? | no |
| Applies to | 2.8+ |
| Fixed tickets | - |

Proposed changes are minor. If you don't agree with them, just close this pull request. There is no need to discuss about this. Thanks.

### CODE REVIEW

**Comment by stof** [comment]
:+1:

**Comment by xabbuh** [comment]
:+1: I like them.

**Comment by OskarStark** [comment]
:+1:

**Comment by weaverryan** [comment]
:thumbsup:

**Pull request merged**
