### PR TITLE
Link to AsseticBundle

### PR DESCRIPTION
**Pull request by xavierleune**
AsseticBundle is not a part of symfony anymore.

### CODE REVIEW

**Comment by xabbuh** [comment]
With #5973 we now have some more information about the removal and how to install the bundle manually. I guess that should be sufficient. What do you think?

**Comment by xabbuh** [comment]
Hm, looks like the build process on symfony.com didn't update the page. @javiereguiluz can you take a look what is going wrong there?

**Comment by xavierleune** [comment]
Of course, I missed this PR. Thx for reviewing!

**Comment by xabbuh** [comment]
Don't worry about that. It's hard to spot when it isn't open anymore. And luckily your PR made me aware of the fact that we needed to merge changes from older branches up to newer versions.

**Pull request closed without merging**
