### PR TITLE
[Contributing][Code] fix list item terminators

### PR DESCRIPTION
**Pull request by xabbuh**

### CODE REVIEW

**Comment by javiereguiluz** [comment]
👍 

By the way, we need to update this document to replace all the `should be` by `must be`

**Comment by xabbuh** [comment]
@javiereguiluz I updated the wording in this PR too.

**Comment by javiereguiluz** [comment]
Great! Thanks.

**Comment by javiereguiluz** [comment]
Status: Reviewed

**Comment by WouterJ** [comment]
:+1:

**Pull request merged**
