### PR TITLE
Scalingo is another PaaS which supports Symfony

### PR DESCRIPTION
**Pull request by yannski**

### CODE REVIEW

**Comment by javiereguiluz** [comment]
Thanks! Merged in 4.3 (and higher) branches

**Comment by OskarStark** [comment]
Why not `3.4` @javiereguiluz 🤔 ?

**Comment by javiereguiluz** [comment]
I tried 3.4 first ... but in 3.4 we had full articles for each platform ... which we removed in 4.3 to replace them by a list of services.

**Comment by yannski** [comment]
Thanks for merging!

**Pull request merged**
