### PR TITLE
Add an example how to adjust ts-loader settings

### PR DESCRIPTION
**Pull request by Steveb-p**
https://symfony.com/doc/current/frontend/encore/typescript.html - show how to set up custom `ts-loader` options. Sample comes from `index.js`.

https://github.com/symfony/webpack-encore/blob/f5a17a47b5fcd23ff991bd7154385185c7f54e2f/index.js#L956-L979

### CODE REVIEW

**Comment by javiereguiluz** [comment]
@Lyrkan could you please review this proposed change? Thanks!

**Review by Lyrkan — APPROVED** [review]
Looks good to me.

Only (really) minor concern: I wonder if it would also be clear for newcomers that the whole callback thing is optional and they can just call `.enableTypeScriptLoader()` without any parameter.

In Encore's `index.js`' comments we usually show both versions to avoid any ambiguity... but maybe I'm worrying about nothing :)

**Comment by Steveb-p** [comment]
@Lyrkan current page already has an example just above the one that this PR adds, where there is no parameter. I had considered it sufficient, as it is a continuation of the example.

I'll adjust it into a diff instead to clearly show that it's an optional parameter that is only required if a specific ts-loader adjustment is needed.

**Comment by Lyrkan** [comment]
> @Lyrkan current page already has an example just above the one that this PR adds, where there is no parameter. I had considered it sufficient, as it is a continuation of the example.

Oh, my bad then, I didn't expand the top part of the file :)

> I'll adjust it into a diff instead to clearly show that it's an optional parameter that is only required if a specific ts-loader adjustment is needed.

Good idea!

**Pull request merged**
