### PR TITLE
Make the samples compliant with the API

### PR DESCRIPTION
**Pull request by mickaelandrieu**
| Q | A |
| --- | --- |
| Doc fix? | [yes] |
| New docs? | [no](PR # on symfony/symfony if applicable) |
| Applies to | [>=2.0] |
| Fixed tickets | [no] |

See http://api.symfony.com/2.3/Symfony/Component/DependencyInjection/Extension/ExtensionInterface.html and http://api.symfony.com/2.3/Symfony/Component/DependencyInjection/Extension/Extension.html

This contribution may be applied to all versions (2.0 -> 3.0-dev).

### CODE REVIEW

**Comment by xabbuh** [comment]
Personally, I like `$configs` more than `$config` as it puts emphasize on the fact that the argument can be various configurations that will then be merged into one.

**Comment by mickaelandrieu** [comment]
@xabbuh agree but why the API doesn't reflect this statement? I mean: should we update the related classes instead of update docs?

**Comment by xabbuh** [comment]
@mickaelandrieu Possibly because the passed argument does not necessarily have to be composed from different sources (or it was not thought about that initially).

**Comment by OskarStark** [comment]
:+1:  for ```$configs```, beacause it is type hinted as ```array```

**Comment by mickaelandrieu** [comment]
@OskarStark so, you agree we have to update the code instead of docs ?

**Comment by WouterJ** [comment]
:+1: for updating the code. It's from waaaay back, where it was passed just a single configuration. (see for instance this commit from 2010: https://github.com/symfony/symfony/blob/a79ad894f920e2f78d1f09f25901e91a74430686/src/Symfony/Framework/DoctrineBundle/DependencyInjection/DoctrineExtension.php)

**Comment by OskarStark** [comment]
yes @mickaelandrieu

**Comment by xabbuh** [comment]
So I think we can safely close here and see if we can improve the code instead. Thank you for triggering this discussion anyway, Mickaël. :)

**Pull request closed without merging**
