### PR TITLE
[Messenger] Document the validation middleware

### LINKED ISSUE #10474: [Messenger] Document the validation middleware
Original PR: https://github.com/symfony/symfony/pull/26648

An issue was already opened some times ago: https://github.com/symfony/symfony-docs/issues/9641
and closed by https://github.com/symfony/symfony-docs/commit/2099d4811bdcd7736f7df45d4cfbdc310ed9b213 but there is actually no mention to the `ValidationMiddleware` and how to use it (`ValidationFailedException` should also be explained, as it allows getting the violations).

Only the `ValidationConfiguration` is mentioned in https://symfony.com/doc/current/components/messenger.html#adding-metadata-to-messages-envelopes but I think this middleware deserves its own section/guide.

### PR DESCRIPTION
**Pull request by 94noni**
Close https://github.com/symfony/symfony-docs/issues/10474

I took inspiration on the doc https://symfonycasts.com/screencast/messenger/other-middleware#validation-doctrine-transaction-etc-middleware

Reference this doc https://github.com/symfony/symfony-docs/pull/14969 so I added next to it

### CODE REVIEW

**Comment by ogizanagi** [comment]
Thanks for opening this.
I think we could mention as well the [`ValidationStamp`](https://github.com/symfony/symfony/blob/6.1/src/Symfony/Component/Messenger/Stamp/ValidationStamp.php) to configure validation groups. It's already mentioned in [this part](https://symfony.com/doc/current/components/messenger.html#adding-metadata-to-messages-envelopes), but this possibility would be more discoverable next to the validation middleware samples.

**Comment by 94noni** [comment]
Ok I’ll add a ref link here

**Comment by 94noni** [comment]
@ogizanagi done :)

**Review by ogizanagi — APPROVED** [review]

**Review by Nek- — APPROVED** [review]

**Comment by Nek-** [comment]
Thanks this is nice @94noni . I hope it will be merged soon!

**Comment by wouterj** [comment]
Thank you @94noni, this is great!

As this middleware was introduced in 4.1, I've rebased your PR on 4.4 (and changed the PHP config to use the legacy format). While merging these changes up, I've added the original changes in this PR on the 5.3 branch (ref 0aea09a7f),

**Pull request merged**
