### PR TITLE
Update the Apache Router article to deprecate it entirely

### PR DESCRIPTION
**Pull request by javiereguiluz**
It partially solves the problem pointed in #6781.

### CODE REVIEW

**Comment by wouterj** [comment]
As we now have a per-version redirection mechanism, we can just remove this article (and the other remaining placeholder articles) and add a redirection.

**Comment by weaverryan** [comment]
I agree with Wouter - let's delete this article entirely in 3.0, and just redirect to a routing page or something. If that's confusing to the user, they'll do some digging and find out what happened.

Status: Needs Work

**Comment by javiereguiluz** [comment]
I've finished the requested changes.

**Comment by xabbuh** [comment]
👍 

Status: Reviewed

**Comment by xabbuh** [comment]
Thank you @javiereguiluz!

**Pull request closed without merging**
