### PR TITLE
Update logger service channel name

### PR DESCRIPTION
**Pull request by dubbs**
This looks like it should be `acme` instead of `app`.

### CODE REVIEW

**Comment by xabbuh** [comment]
I think I would change the channel in the config examples to `app` instead. What do you think?

**Comment by HeahDude** [comment]
Hello @dubbs, good catch for this first contrib.

I agree with @xabbuh, would you like to update your PR accordingly? Thanks!

**Comment by dubbs** [comment]
Sure, I'll change the example from `acme` to `app`.

**Comment by javiereguiluz** [comment]
@dubbs we're sorry it took us so long to merge your contribution. We ended up solving it differently, but you discovered and reported the bug, so thank you!

**Pull request merged**
