### PR TITLE
Added Link to Cmder

### PR DESCRIPTION
**Pull request by c33s**
Cmder is a wrapper around Conemu, Clink and Git which really help to use the cli on windows.

### CODE REVIEW

**Comment by javiereguiluz** [comment]
@c33s thanks for this proposal. The `cmder` project looks really nice. Sadly I don't use Windows, so I cannot test it myself. Let's ask the opinion about this to some Symfony experts who are Windows users: @WouterJ @iltar  Thanks!

**Comment by iltar** [comment]
@javiereguiluz I have never used it before (only gitbash and powershell). I'll give it a shot when I have some time at home as I use linux at work.

**Comment by celdia** [comment]
I'm linux user. If not, I'll test it in this Fourth Symfony Docs Hack Day.

**Comment by WouterJ** [comment]
Just tested this on Windows and it's a pretty nice-looking tool. Thanks for submitting the change Julian! (for added greatness, this PR is merged using cmder!)

**Pull request merged**
