### PR TITLE
[Form] improve installation instructions

### PR DESCRIPTION
**Pull request by xabbuh**
see https://github.com/symfony/symfony-docs/pull/6626#discussion_r65048004 (this now is in line with how we have documented for the 3.x versions)

### CODE REVIEW

**Comment by Ener-Getick** [comment]
:+1:

**Comment by WouterJ** [comment]
I think we should start using `composer require ...` in these examples, what do you think?

status: needs work

**Comment by javiereguiluz** [comment]
@WouterJ yes!

**Comment by wouterj** [comment]
closing in favor of https://github.com/symfony/symfony-docs/pull/6855

**Pull request closed without merging**
