### PR TITLE
Reworded the user checker aliases explanation

### PR DESCRIPTION
**Pull request by javiereguiluz**
The original explanation looked confusing to me. Let's see if others agree.

### CODE REVIEW

**Comment by xabbuh** [comment]
I agree that the new explanation is more clear than the existing one. However, I wonder if we need it at all. Is this information really necessary?

**Comment by javiereguiluz** [comment]
@xabbuh I think I agree. I don't understand why Symfony does this and I don't know why a developer should know this. But I've never used a user checker, so I could be missing something important.

**Comment by xabbuh** [comment]
@javiereguiluz It's useful to simplify some internal code of the SecurityBundle, but I don't think that's anything we need to document. At least, I would not add the note here as it may lead to more confusion than necessary. If we wanted to document this, I would vote for creating a dedicated article that explains how to hook into the SecurityBundle.

**Comment by javiereguiluz** [comment]
@xabbuh I've removed it :)

**Comment by xabbuh** [comment]
👍 

Status: Reviewed

**Comment by xabbuh** [comment]
@javiereguiluz Was it intended to target the `2.8` branch instead of `2.7`?

**Comment by javiereguiluz** [comment]
It was intended because at the beginning of the article one can read:

```
.. versionadded:: 2.8
    The ability to configure a custom user checker per firewall was introduced
    in Symfony 2.8.
```

**Comment by xabbuh** [comment]
Thank you Javier.

**Pull request closed without merging**
