### PR TITLE
Update micro_kernel_trait.rst

### PR DESCRIPTION
**Pull request by StepanMe**
"This method builds and configures..." instead of "This methods builds and configures"

### CODE REVIEW

**Comment by weaverryan** [comment]
Of course! Thank you Stepan!

**Comment by xabbuh** [comment]
I have cherry picked this for the `2.8` in f0b833af9bbc57df3ecbf965b4010a34f46c399e too.

**Comment by weaverryan** [comment]
Ah, thanks. I even thought about that, and forgot it exists in 2.8!

**Comment by StepanMe** [comment]
I don't know why, but some images are not shown in "current" version of docs. In previous versions (3.2)  they are OK.
For example, on page _http://symfony.com/doc/current/doctrine/associations.html_ I see alt text of image ("../_images/mapping_relations.png") instead of the image (`http://symfony.com/doc/current/_images/mapping_relations.png`).

But link `http://symfony.com/doc/current/_images/mapping_relations.png` has a 301 redirect to `http://symfony.com/doc/3.3/_images/mapping_relations.png`. Seems it does not work correctly.

The same problem on some other pages of current version of the docs :(

**Pull request merged**
