### PR TITLE
[VarDumper] Doc for the Data::seek() method

### PR DESCRIPTION
**Pull request by nicolas-grekas**
Ref. https://github.com/symfony/symfony/pull/19672

### CODE REVIEW

**Comment by wouterj** [comment]
👍 
status: reviewed

**Comment by javiereguiluz** [comment]
I'm not sure the following can be fully understood --> `a subkey of some arrays, objects or resources.` ... but I think this is hard to explain without an example. What about:

```
:method:`Symfony\\Component\\VarDumper\\Cloner\\Data::seek`
    Dumps contents partially starting from the given key (for arrays) or property name
    (for objects).
```

---

Unrelated to this, but I'd also like to change the following:

```
Allows limiting ... -> Limits ...
Allows removing ... -> Removes ...
Allows dumping ...  -> Dumps ...
```

**Comment by nicolas-grekas** [comment]
@javiereguiluz updated

**Comment by javiereguiluz** [comment]
👍 

Status: reviewed

**Comment by xabbuh** [comment]
Thank you @nicolas-grekas.

**Pull request merged**
