### PR TITLE
Fix typo in translation.rst

### PR DESCRIPTION
**Pull request by zatikbalazs**
| Q | A |
| --- | --- |
| Doc fix? | yes |
| New docs? | no |
| Applies to | all |
| Fixed tickets |  |

### CODE REVIEW

**Comment by stof** [comment]
The title of the PR is weird.

**Comment by zatikbalazs** [comment]
Thank you for pointing it out. I fixed it.

**Comment by OskarStark** [comment]
Status: Reviewed

**Comment by xabbuh** [comment]
Thank you @zatikbalazs. I have merged your pull request into the `2.3` branch. That's why it is shown as closed.

**Pull request closed without merging**
