### PR TITLE
Updates in performance.rst

### PR DESCRIPTION
**Pull request by Erdou**
…with generated APCu loader

### CODE REVIEW

**Comment by xabbuh** [comment]
Thank you for your first contribution @Erdou. You are absolutely right with the changes you propose. However, I am afraid that this greatly overlaps with the ongoing work from #7960. Maybe you would like to merge your changes with the changes done by @javiereguiluz?

@javiereguiluz Or should we merge here and you rebase your changes on top of that?

**Comment by Erdou** [comment]
Thank you for your feedback @xabbuh 
I'll merge here, then @javiereguiluz can take it back :)

**Comment by Erdou** [comment]
@xabbuh @javiereguiluz Merge done and I also improved a few minor stuff, but Travis is not happy and I cannot understand why. A little help will be appreciated here :)

**Comment by javiereguiluz** [comment]
@Erdou the error comes from this change:

error

The `single: ...` thing is part of the `.. index::` directive and must be indented.

**Comment by Erdou** [comment]
@javiereguiluz Thanks it passes now :) 
I let you and @xabbuh take it from here. Don't hesitate to tell me if I can help more
And sorry for the fuzzy merge, it was my first time merging and commiting into a Github PR

**Comment by xabbuh** [comment]
@javiereguiluz Can you have a look here?

**Comment by javiereguiluz** [comment]
Closing it in favor of #9161.

**Pull request closed without merging**
