### PR TITLE
[Mailer] Removing all `n/a`s

### PR DESCRIPTION
**Pull request by ThomasLandauer**
Page: https://symfony.com/doc/current/mailer.html#using-a-3rd-party-transport

Reason: The page is getting longer and longer...

Besides, I would merge those 2 tables with the 3rd party providers; listing each one *twice* doesn't make much sense to me.

### CODE REVIEW

**Comment by OskarStark** [comment]
Why not 👍🏻

**Review by OskarStark — APPROVED** [review]

**Comment by OskarStark** [comment]
For 6.4

**Comment by ThomasLandauer** [comment]
You mean I should merge the lists in 6.4? But there were new entries added in 7.2, isn't this going to be a merging nightmare?

**Comment by javiereguiluz** [comment]
I disagree with this change. It's true that it looks like unnecessary information, but in my opinion, this is useful.

If we show nothing, readers don't know if that option doesn't exist or if the docs need some update. But, if we explicitly say that something it's not available, then it's very clear that the docs checked this.

**Comment by xabbuh** [comment]
I think I tend to agree with Javier.

**Comment by OskarStark** [comment]
Makes sense @javiereguiluz 

Thanks for proposing

**Pull request closed without merging**
