### PR TITLE
Fixed query_builder option

### PR DESCRIPTION
**Pull request by HeahDude**
doc fix: 2.3+

ref https://github.com/symfony/symfony-docs/pull/6594#discussion_r64135339

### CODE REVIEW

**Comment by xabbuh** [comment]
:+1:

**Comment by xabbuh** [comment]
You could also update the text to something like this:

```rst
The value of this option can either be a ``QueryBuilder`` object, a Closure or ``null``.
```

**Comment by HeahDude** [comment]
Ok then #6594 will need a rebase.

**Comment by HeahDude** [comment]
Fixed

**Comment by WouterJ** [comment]
Thanks Jules! I'm sorry for -1'ing you in #6594, you were 100% correct.

**Comment by WouterJ** [comment]
Oh btw, I just made a minor improvement in 31de26f

**Comment by HeahDude** [comment]
@WouterJ  👍

**Pull request merged**
