### PR TITLE
Update http_fundamentals.rst

### PR DESCRIPTION
**Pull request by wouthoekstra**
Modern browsers do support PUT and DELETE, see for example http://stackoverflow.com/questions/165779/are-the-put-delete-head-etc-methods-available-in-most-web-browsers.

### CODE REVIEW

**Comment by xabbuh** [comment]
We should probably explain that all modern browsers support these methods in XHR, but that HTML forms still can only use GET and POST.

**Comment by wouthoekstra** [comment]
You're right. I'll get on to it :)

**Comment by xabbuh** [comment]
Oh, and we also have a part talking about this at http://symfony.com/doc/current/cookbook/routing/method_parameters.html#faking-the-method-with-method. Could you please address that section too?

**Comment by 1emming** [comment]
:+1: @wouthoekstra for taking care of this :)

**Comment by xabbuh** [comment]
This looks good! :+1:

**Comment by xabbuh** [comment]
@wouthoekstra By the way, we don't receive notifications when new commits are pushed to a pull request (I just discovered your update "accidentally"). So next time it's better to leave a comment after you did some changes. :)

**Comment by wouthoekstra** [comment]
Ah thx for the tip xabbuh, didn't know that! Glad the alterations are okay :)

**Comment by weaverryan** [comment]
I like it very much - nice work @wouthoekstra! I've merged this into the 2.3 branch (and we'll merge to other branches from there) and added a minor tweak at sha: f9ef3ee179067cdb550fcd8ac045ee166c694ae8

Cheers!

**Comment by wouthoekstra** [comment]
Sounds good! Sorry, I understood only after my pull request that I should have made the request on the 2.3 branch, not on the latest one.

**Comment by tiemevanveen** [comment]
Nice! @weaverryan you've just merged @wouthoekstra's first Pull! :+1: :grinning:

**Pull request closed without merging**
