### PR TITLE
[Form][FrameworkBundle] Replace render() with new renderForm() in form documentation

### LINKED ISSUE #14844: [FrameworkBundle] Add renderForm() helper setting the appropriate HTTP …
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#39843
| PR author(s) | @dunglas
| Merged in    | 5.3-dev

### PR DESCRIPTION
**Pull request by javiereguiluz**
This adds some missing changes to #15105 and fixes #14844.

### CODE REVIEW

**Comment by javiereguiluz** [comment]
Don't merge yet. Let's wait for https://github.com/symfony/symfony/pull/40799 to decide the best way of solving this.

**Comment by javiereguiluz** [comment]
After the latest changes made on `handleForm()`, I propose to not use it to document form handling. The reason is that the resulting code looks a bit messy.

Traditional form handling:

```php
#[Route('/{id}/edit', name: 'conference_edit', methods: ['GET', 'POST'])]
public function edit(Request $request, Conference $conference): Response
{
    $form = $this->createForm(ConferenceType::class, $conference);
    $form->handleRequest($request);
    if ($form->isSubmitted() && $form->isValid()) {
        $this->getDoctrine()->getManager()->flush();

        return $this->redirectToRoute('conference_index', [], Response::HTTP_SEE_OTHER);
    }

    return $this->render('conference/edit.html.twig', [
        'conference' => $conference,
        'form' => $form->createView(),
    ]);
}
```

Form handling with `handleForm()`:

```php
#[Route('/{id}/edit', name: 'conference_edit', methods: ['GET', 'POST'])]
public function edit(Request $request, Conference $conference): Response
{
    return $this->handleForm(
        $request,
        $this->createForm(ConferenceType::class, $conference),
        function (FormInterface $form) use ($conference) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute(
                'conference_show',
                ['id' => $conference->getId()],
                Response::HTTP_SEE_OTHER
            );
        },
        function (FormInterface $form) {
            return $this->render('conference/edit.html.twig', [
                'form' => $form->createView(),
            ]);
        }
    );
}
```

-----


However, since this `handleForm()` method does some additional tasks needed when using Stimulus ... we could document it in the docs related to Stimulus. What do you think?

**Comment by nicolas-grekas** [comment]
renderForm() [is back](https://github.com/symfony/symfony/pull/41178), so that this PR might be good to merge now :)

**Comment by nicolas-grekas** [comment]
Should be updated for https://github.com/symfony/symfony/pull/41190

**Pull request merged**
