### PR TITLE
[Swiftmailer] create Message by mailer service.

### PR DESCRIPTION
**Pull request by aitboudad**
| Q | A |
| --- | --- |
| Doc fix? | yes |
| New docs? | no |
| Applies to | all |

It complete the PR: #4808

### CODE REVIEW

**Comment by stof** [comment]
This seems weird to me. Messages should be created the Swiftmailer way IMO

**Comment by WouterJ** [comment]
@stof can you explain why? Without any knowledge about the subject, I would say that the proposed way is better, as it doesn't advocate anti patterns.

**Comment by timglabisch** [comment]
i think this is smarter? :+1:

**Comment by weaverryan** [comment]
If you dig deep enough, it looks like `createMessage` on `Swift_Mailer` is the same as the `Swift_Message::newInstance()` approach (the first uses Swift's odd DIC). The disadvantage is that you don't get auto-complete with this change. Even if your IDE knows that the `mailer` service returns a `Swift_Mailer` instance, the `createMessage()` method (for some reason) simply states `@return object`.

I see some practical disadvantages, so :-1:  for me.

Cheers!

**Comment by timglabisch** [comment]
the cool thing about `createMessage` is that you could replace the service and overwrite the method. this doesnt work if you use something like ::newInstance.

**Comment by stof** [comment]
@WouterJ if you don't want to use anti-patterns, don't use Swiftmailer. It uses static service location everywhere anyway (and in very weird ways as it even uses it when calling the parent constructor).

@timglabisch extending the mailer to change the creation of the message looks like the wrong extension point to me. The mailer is here to send messages, not to compose them

**Comment by WouterJ** [comment]
Hmm, I think the decision is to not do this. In that case, #4808 has to be reverted

**Pull request closed without merging**
