### PR TITLE
Fixed typo in path

### PR DESCRIPTION
**Pull request by timhovius**
The path in the config.yml is wrong and causes an error

### CODE REVIEW

**Comment by xabbuh** [comment]
:+1:

**Comment by timhovius** [comment]
This issue is valid for Symfony versions >= 2.3

**Comment by WouterJ** [comment]
The best practices naming convention is to use lowercase characters only for template directories and names. Can you please make the template locations use lowercase instead in this article, @timhovius? (we can do it too while merging this PR)

**Comment by timhovius** [comment]
I changed it, thanks for your comment!

**Comment by weaverryan** [comment]
Awesome, thanks Tim!

**Comment by timhovius** [comment]
It's not fixed for Symfony versions >= 2.3 except version 2.7 now. Can you apply my fix it for those versions too?

**Comment by xabbuh** [comment]
@timhovius Thanks for the heads up. I backported it in fdfc2cbe9ddb95f0e211fd7031f5b3f75234d753.

**Pull request closed without merging**
