### PR TITLE
[Fix pipeline] multiple_kernels.rst must respect doctor-rst

### PR DESCRIPTION
**Pull request by alamirault**
https://github.com/symfony/symfony-docs/pull/18186#issuecomment-1537537502

`apps` -> `applications`

`ContainerConfigurator $container` -> `ContainerConfigurator $containerConfigurator`

### CODE REVIEW

**Comment by OskarStark** [comment]
Not sure about the directory. I mean maybe we should keep/allow apps here. 

I would not change the director structure just to make a tool happy, but if it doesn't matter and it is just an example and no best practice, we can rename it to applications directory

cc @nicolas-grekas @javiereguiluz

**Comment by nicolas-grekas** [comment]
:-1: on my side, the current names are better to me.

**Comment by alamirault** [comment]
I reverted `applications` to `apps` and set violations in whitelist.

For doctor-rst, I think exclude all file is not good because it will hide other violations. I created PR https://github.com/OskarStark/doctor-rst/pull/1395 in order to exclude some rules by file when is needed

**Comment by javiereguiluz** [comment]
Antoine, thanks for fixing this and for the updates after the reviewers comments.

**Comment by javiereguiluz** [comment]
Note: GitHub shows this as closed, but it was merged. See https://github.com/symfony/symfony-docs/commit/e56283988a03dce7a0a4f8c60b9aca42640bdfd5

**Comment by nicolas-grekas** [comment]
I wouldn't have merged the change of var name, it's not consistent with the name in the recipe we used at the time:
https://github.com/symfony/recipes/blob/main/symfony/framework-bundle/4.4/src/Kernel.php

nor with the name in the trait we use now:
https://github.com/symfony/symfony/blob/6222f8eaf8498f75fcc018157386d7290a68d0bd/src/Symfony/Bundle/FrameworkBundle/Kernel/MicroKernelTrait.php#L49

and it's longer without adding much.

I'd propose reverting. Sorry...

**Comment by alamirault** [comment]
For consistency we standardized the name of the `ContainerConfigurator $containerConfigurator` https://github.com/symfony/symfony-docs/issues/17381 and `ContainerBuilder $containerBuilder` https://github.com/symfony/symfony-docs/pull/17683 in all docs and doctor-rst ensure this naming.

If we revert this name, all doc must also be reverted IMO and not only this part

**Comment by javiereguiluz** [comment]
@nicolas-grekas yes, I see that there's a minor inconsistency between the code and the docs about this variable name. We decided to make that change in the past (in the PRs mentioned by @alamirault) to make docs as self-explanatory and clear as possible.

Ideally, we'd like to make the same change in the code ... but we know that for code is not that important and also, changing the name in code is more troublesome than in docs. Thanks.

**Comment by javiereguiluz** [comment]
@nicolas-grekas yes, I see that there's a minor inconsistency between the code and the docs about this variable name. We decided to make that change in the past (in the PRs mentioned by @alamirault) to make docs as self-explanatory and clear as possible.

Ideally, we'd like to make the same change in the code ... but we know that for code is not that important and also, changing the name in code is more troublesome than in docs. Thanks.

**Comment by nicolas-grekas** [comment]
$containerConfigurator is not the name we recommend in config files either, see eg
https://github.com/symfony/symfony/blob/6.3/src/Symfony/Bundle/FrameworkBundle/Resources/config/console.php

I see no need for consistency between those two examples.

**Comment by nicolas-grekas** [comment]
Sorry for the take but I would be fine reverting https://github.com/symfony/symfony-docs/pull/17683 also. The previous contributors thoughts $container was an appropriate name, and I still agree with them today, no need for the extra word in the name IMHO.

**Pull request closed without merging**
