### PR TITLE
Strip YAML trailing newline

### PR DESCRIPTION
**Pull request by mikemix**
Previous YAML resulted in a trailing newline!

### CODE REVIEW

**Comment by mikemix** [comment]
Previous example

    <div>({{ 'num_of_apples'|trans({apples: 5}) }})</div>

Was leading to:

    <div>(5
    )</div>

Which is rendered as `(5 )` instead of `(5)`.

**Comment by javiereguiluz** [comment]
@mikemix thanks for this. However, I find this syntax a bit confusing ... if we don't add this, where's the newline added? Is the newline visible to end users in the web page? Thanks.

**Comment by mikemix** [comment]
@javiereguiluz think of yourself as a regular bloke who wants to create application translations. So he visits the docs and sees the examples. Lets create a simple one:

```
ui:
  article_count: >
      {count, plural,
        one   {one article}
        other {# artlces}
      }
```

And lets use it:

    <h1>Articles ({{ 'ui.article_count|trans({'count': 5}) }}')</h1>

You would expect this to be `<h1>Articles (5 articles)</h1>` right? But this is going to be `<h1>Articles(5 articles )</h1>` - notice the whitespace before ending parenthesis.

This is because a newline was added, the generated html looks as follows:

```
<h1>Articles (5 articles
)</h1>
```

**Comment by javiereguiluz** [comment]
@mikemix you explained it perfectly! Thanks for such a great and detailed explanation. Let's merge this. Thanks ... and congrats on your first Symfony Docs contribution!

**Pull request merged**
