### PR TITLE
Update standards to match actual practices

### PR DESCRIPTION
**Pull request by jvasseur**
| Q | A |
| --- | --- |
| Doc fix? | yes |
| New docs? | no |
| Applies to | 2.3 |
| Fixed tickets |  |

We don't add phpdoc if it doesn't add any meaningful information, so i removed the line saying all methods should be documented. Maybe we should replace it by a phrase explaining what should be documented ?

### CODE REVIEW

**Comment by javiereguiluz** [comment]
I agree with your second idea. Instead of removing the phrase, let's improve it:

```
Add PHPDoc blocks for all classes, methods, and functions, except when the
comments are trivial (e.g. basic getter and setter methods).
```

**Comment by jvasseur** [comment]
Updated with the phrase you suggested.

**Comment by Soullivaneuh** [comment]
I'm :-1: for this for one reason: 

```
except when the
comments are trivial (e.g. basic getter and setter methods).
```

This is not accurate at all. We should precise when the comment should be here, and when not.

For example, basic getter could / should have a phpdoc to precise the type. This is used by most of the IDE.

**Comment by WouterJ** [comment]
I think almost all methods (even simple getters and setters) are documented in Symfony core. I agree that it isn't enforced as strict as other standards, but I still think we should keep the standard as it is.

However, Symfony tends to seperate public API from internal methods/properties/classes more and more. Many methods that don't have any PHPdoc are internal methods (e.g. event listener methods). Maybe we should update this to *"Add PHPDoc blocks for all classes, methods, and functions that are part of the public API;"* What do you think?

**Comment by xabbuh** [comment]
Well, actually we indeed usually do reject adding "useless" PHP doc.

**Comment by TomasVotruba** [comment]
What would be really helpful and clear to ready would be some examples.

E.g.

### Correct commenting

```php
// type is obvious from typehint
public function setPerson(Person $person)
{
    // ...
}

// param is unknown scalar type
/**
 * @param int $count
 */
public function setCount($count)
{
}

// returns unknown scalar type
/**
 * @return bool
 */
public function isReady()
{
    // ...
}
```


### Incorrect commenting

Usecases you are talking about...

**Comment by javiereguiluz** [comment]
What should we do with this proposal? I don't think we can put this in words with absolute precision because adding or not some PHPdoc is sometimes subjective. I'd merge it as is.

**Comment by TomasVotruba** [comment]
:+1:

**Review by xabbuh — APPROVED** [review]

**Comment by weaverryan** [comment]
I've merged this at sha: 241dfde5d38b541ef43c6cdd4363c7e258ab2e12 and tweaked the wording at sha: 0aa25f8f33047b1e3809fd82c150557c14b516d5

Thanks!

**Pull request closed without merging**
