### PR TITLE
Add Body tag to see the web debug toolbar

### PR DESCRIPTION
**Pull request by rmed19**
Add body tag on the response content to see the web debug toolbar.

| Q | A |
| --- | --- |
| Doc fix? | yes |
| New docs? | no |
| Applies to | 2.3+ |
| Fixed tickets | #5616 |

### CODE REVIEW

**Comment by javiereguiluz** [comment]
At first I was divided about this change. It "complicates" the code for no apparent reason (the user will have a real page instead of using the `Response()` directly).

However, later in the same chapter we tell the reader:

```
If you refresh now, you'll be logged in! The web debug toolbar even tells you who
you are and what roles you have:
```

Since the toolbar doesn't show up if you don't have a closing `</body>` tag, I think this change is the right thing to do. So now I'm :+1:

**Comment by xabbuh** [comment]
:+1:

**Comment by xabbuh** [comment]
Thank you Mohammed.

**Comment by rmed19** [comment]
Hi @xabbuh,
this change should be add to all symfony 2.* documentation not only the 2.3.
Should I create a new pull request?

**Comment by javiereguiluz** [comment]
@rmed19 don't worry about that. Changes are always merged in the oldest branch and then, from time to time, they merge old branches into newer ones. So in a few hours/days, this change will be merged into 2.7, 2.8 and master.

**Comment by xabbuh** [comment]
@rmed19 I just merged branches up so your changes are now also available in 2.7, 2.8 and master and they will be visible soon when the documentation is rebuilt. :)

**Pull request merged**
