### PR TITLE
[Routing][DX] Exposed "utf8" options, and defaults "locale" and "format"

### PR DESCRIPTION
**Pull request by HeahDude**
Documentation for symfony/symfony#30508

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
I didn't review the full page: where do we tell about the router-wide default options?
Because to me that's where the utf8 option makes the most sense. See https://github.com/symfony/recipes/blob/master/symfony/routing/4.2/config/packages/routing.yaml
Note that this makes me wonder if we should merge this PR and the one on Symfony...

**Comment by HeahDude** [comment]
@nicolas-grekas While this is a default in the framework routing page, this PR is about DX when using the component standalone. We have two pages for almost all components (one is about integration but not here):

- framework routing https://symfony.com/doc/current/routing.html
    No examples need `utf8` option because we required `annotations` which has the config we linked.
    Maybe we could even add a not there to explain how to set it to `false`.
- routing component (what I edit here) https://symfony.com/doc/current/components/routing.html
   No integration.

**Comment by nicolas-grekas** [comment]
configuring the defaults are also possible when using the component standalone

**Comment by HeahDude** [comment]
https://github.com/symfony/symfony/pull/30508 has been merged.

**Comment by javiereguiluz** [comment]
Jules, this was a lovely contribution. Thanks a lot!

**Pull request merged**
