### PR TITLE
Removed unused imports in TaskController

### PR DESCRIPTION
**Pull request by phpfour**
Fixed the imports in `TaskController.php` when using form type

### CODE REVIEW

**Comment by OskarStark** [comment]
Please have a look at DOCtor-RSR, thanks

**Comment by phpfour** [comment]
Hi @OskarStark I'ved fixed the error in `forms.rst`...however, not sure how to fix this issue: 

image

**Comment by phpfour** [comment]
Created a PR for version `4.4` here with the same changes: https://github.com/symfony/symfony-docs/pull/12995

**Comment by javiereguiluz** [comment]
@phpfour we merged your other pull request. We merged it in 4.3 ... and then "upmerge" the same changes in all the other branches (4.4, 5.0 and master). So, we can close this pull request. Thanks!

**Pull request closed without merging**
