### PR TITLE
Not use contraction

### LINKED ISSUE #17743: Consistency using contractions or not: `It's/It is` `You're/You are`...
Consistency is important. We should use always contractions or not.

IMO I prefer to not use contraction for symfony-docs. Are you agree with this ?

I can make PR for each group (avoiding huge review)

## am

I found 0 occurences of `I'm`
I found 1 occurences of `I am`

## are

I found 254 occurences of `you're`
I found 162 occurences of `you are`

I found 1 occurences of `we’re`
I found 20 occurences of `we are`

I found 0 occurences of `they’re`
I found 135 occurences of `they are`

## is

I found 367 occurences of `it's`
I found 301 occurences of `it is`

## have

I found 59 occurences of `you've`
I found 250 occurences of `you have`

I found 4 occurences of `we've`
I found 20 occurences of `we have`

I found 0 occurences of `they've`
I found 11 occurences of `they have`

## will

I found 97 occurences of `you'll`
I found 250 occurences of `you will`

I found 9 occurences of `it'll`
I found 121 occurences of `it will`

I found 9 occurences of `we'll`
I found 6 occurences of `we will`

I found 2 occurences of `they'll`
I found 17 occurences of `they will`

## would

I found 16 occurences of `you'd`
I found 31 occurences of `you would`

I found 0 occurences of `it'd`
I found 19 occurences of `it would`

I found 0 occurences of `we'd`
I found 2 occurences of `we would`

I found 0 occurences of `they'd`
I found 2 occurences of `they would`

### PR DESCRIPTION
**Pull request by alamirault**
Fix #17743

TODO

- [ ] Fix doctor-rst https://github.com/OskarStark/doctor-rst/pull/1244
- [ ] Check breaking links

### CODE REVIEW

**Comment by javiereguiluz** [comment]
I'd like to ask what's the motivation behind this.

I thought that contractions like "it's" vs "it is" are so common that they are not considered vulgar or low-quality English. Maybe I'm missing something.

**Comment by weaverryan** [comment]
I'm a native English speaker (so my opinion only represents a minority of users), but I like contractions. I don't see the need for consistency. Sometimes I'd like to be casual, while other times I would really like to make a point, with a slightly different voice (<---- purposeful example in the previous statement of speaking inconsistently on purpose).

Cheers!

**Comment by wouterj** [comment]
I like Ryan's point, as the last sentence did indeed feel the way it was meant to - even for a non-native like me (although, you could say I've become quite native concerning reading text written Ryan 😉).

One of the things I like about writing docs for Symfony is the touch of casualness surrounded by the Symfony brand. While I've learned to not use contractions when writing academic papers, I think we should not strive to become too close to an academic paper.

**Comment by OskarStark** [comment]
Well explained 👍🏻

Let's close then

**Comment by alamirault** [comment]
It's clear !

Thanks for sharing your point of views

**Pull request closed without merging**
