### PR TITLE
Updated form aliases to FQCNs for forms in book and component

### PR DESCRIPTION
**Pull request by hiddewie**
| Q | A |
| --- | --- |
| Doc fix? | yes |
| New docs? | no |
| Applies to | 2.8+ |
| Fixed tickets | #5588 |

For the 3.0 branch, all FQCNs should be updated to use the `::class` constant.

### CODE REVIEW

**Comment by weaverryan** [comment]
@hiddewie, this is awesome! This slipped through the cracks - but I just labeled #5588 as having a PR, so thanks!

I really want to show people `TextType::class` - it's *so* much better. But we *do* need to show people the full class name... but if we show that everywhere, it'll look really unusable and people on 5.5 will use the long class name, not knowing the alternative.

I think we should use the `TextType::class` style everywhere, and show the long class version just once per article, commented-out. Like:

```php
->add('task', TextType::class)
// if you're using 5.3 or 5.4, you must use the string class name
// ->add('task', 'Symfony\Component\Form\Extension\Core\Type\TextType')
```

What do you think? Can you make that change? Did you grep the codebase to find all the spots to update or is this just "many" of the spots?

Thanks a lot for this - it's a big change and has been on my list - your help is huge :)

**Comment by hiddewie** [comment]
Thank you for the positive feedback. 

I personally also REALLY prefer the `::class`, but because of PHP <5.6 support reasons I thought it would be too early using (almost) only that notation. But if you say this is OK, I will update the PR.

**Comment by hiddewie** [comment]
I've added more changes to the PR, as I found many more places where the old form types were referenced.

**Comment by hiddewie** [comment]
Please tell me if there need to be more places where the PHP < 5.6 way must be used.

**Comment by weaverryan** [comment]
Thanks @hiddewie! This was a GREAT start. I continued at #5909. I would very much appreciate your review - I will merge one way or another on Sunday.

**Pull request merged**
