### PR TITLE
Update Doc of csrf_protection configuration in framework level

### PR DESCRIPTION
**Pull request by wnunezc**
Update Doc of csrf_protection configuration in framework level, this configuration requires an example to clarify its implementation

### CODE REVIEW

**Comment by wnunezc** [comment]
can someone help me i don't understand the last error i received.

**Comment by RosemaryOrchard** [comment]
> can someone help me i don't understand the last error i received.

You're trying to merge all the docs from 6.0 into 4.4 for starters. I'd suggest cherry-picking the changes you intended over to a new branch from 4.4.

**Comment by wnunezc** [comment]
@RosemaryOrchard no idea how to do that ... if someone is interested in doing it ... I'm not going to add more things ...

**Comment by xabbuh** [comment]
@arcanisgk FYI, I have changed the target branch to `6.0`. We can do the switch while merging. :)

**Comment by wnunezc** [comment]
> @arcanisgk FYI, I have changed the target branch to `6.0`. We can do the switch while merging. :)

let's hope they do the merge

**Comment by javiereguiluz** [comment]
Thanks Walter! This is now merged.

**Comment by wnunezc** [comment]
Estaré dando apoyo; con la documentacion en todo lo que encuentre que no me parezca estar claro para usuarios nuevos. esto ayuda a la curva de aprendizaje. saludos.

I will be giving support; with the documentation in everything I find that does not seem to me to be clear for new users. this helps the learning curve. Regards.

**Pull request merged**
