### PR TITLE
Remove "Symfony3 will use"

### PR DESCRIPTION
**Pull request by alexisLefebvre**
Since Symfony 3 has been released, using "will" is unnecessary

### CODE REVIEW

**Comment by javiereguiluz** [comment]
👍

**Comment by wouterj** [comment]
👍

**Comment by alexislefebvre** [comment]
Should the text *, but for now* in the sentence after Symfony3 structure be removed too?

**Comment by wouterj** [comment]
Hmm, on second review, I think we should remove all lines from 159 to the end and update the file structure shown above this section with the new Symfony 3 structure.

Can you please make this change? (If it's not possible, please comment and we'll take care of finishing this PR)

**Comment by wouterj** [comment]
Status: needs work

**Review by javiereguiluz — APPROVED** [review]
👍

**Comment by javiereguiluz** [comment]
@wouterj I've made the changes you asked for.

**Comment by alexislefebvre** [comment]
@javiereguiluz  Thanks for the changes, I didn't know how to apply the suggestion from wouterj.

**Comment by xabbuh** [comment]
But wouldn't this be confusing for people working with the Standard Edition on Symfony 2.7/2.8?

**Comment by javiereguiluz** [comment]
@xabbuh you are right. I've changed the base branch to 3.1 using GitHub's interface. Now it shows some conflicts. Can those conflicts be solved when merging? Thanks.

**Comment by xabbuh** [comment]
Actually, there is no real difference to what we already have in 3.1 right now. So what should we do here?

**Comment by alexislefebvre** [comment]
The [2.7](https://symfony.com/doc/2.7/best_practices/creating-the-project.html#extending-the-directory-structure) and [2.8](https://symfony.com/doc/2.8/best_practices/creating-the-project.html#extending-the-directory-structure) documentation still mention *Symfony3 will use*. Should I open another PR in order to correct this on the 2.x branch?

**Comment by xabbuh** [comment]
Well, so actually this is just about changing the wording for Symfony 2.x? Was this what we had in the first commit?

**Comment by alexislefebvre** [comment]
@xabbuh More or less, the first commit lacked the changes you applied after. I'm a little bit lost now. Can the changes be rebased to 2.7 instead of 3.1?

**Comment by xabbuh** [comment]
@alexislefebvre What I mean is that the changes done in the second commit are not necessary if we decide to merge this into `2.7` which I would prefer.

**Comment by alexislefebvre** [comment]
If I understand correctly, we have to keep the *classic* directory structure for Symfony 2.* branch because the best practices are not supposed to change before the 3.* branch. So I will revert the last commit and rebase the changes on 2.7.

**Comment by alexislefebvre** [comment]
I reverted the last commit. I tried to rebase on 2.7 but this is ignored in this PR. Can you please rebase it on 2.7?

**Comment by xabbuh** [comment]
Thank you @alexislefebvre. I have merged your pull request into the `2.7` branch.

**Pull request closed without merging**
