### PR TITLE
Code style standardization on form type options

### PR DESCRIPTION
**Pull request by mimol91**
| Q | A |
| --- | --- |
| Doc fix? | yes |
| New docs? | no |
| Applies to | all |
| Fixed tickets | ~ |

I m not quite sure how to set proper name for bool attributes.
I read on SF Code standards "For type-hinting in PHPDocs and casting, use bool (instead of boolean or Boolean)", however I change it to boolean. (Most commonly used)

### CODE REVIEW

**Comment by WouterJ** [comment]
Thank you for the work you've done. However, I think most of these changes are covered by https://github.com/symfony/symfony-docs/pull/4956 and https://github.com/symfony/symfony-docs/pull/4671 Can you please remove all changes that are also in one of those 2 PRs, so we're left with only the remaining issues?

**Comment by mimol91** [comment]
Is there any git command to remove this changes if there are on other commits?
I would rather not want to do it manually.
It is not any problem for me to wait until  PR #4956 #4671 will be merged

**Comment by WouterJ** [comment]
Yes, that's fine by me

**Comment by mimol91** [comment]
@WouterJ 
Hello. I merged changes.
Please let me know if it is OK

**Comment by xabbuh** [comment]
:+1: looks great

**Comment by WouterJ** [comment]
Hi @mimol91! Thanks for your work and taking care of updating this PR. Something still went wrong while trying to merge it, so I started a new branch and cherry-picked you commit. This resulted in a new PR: https://github.com/symfony/symfony-docs/pull/5365 (you're still the author of the commit). I'll merge that PR, so I'll close this PR.

Thanks again!

**Comment by mimol91** [comment]
@WouterJ 
Thanks. Good Job

**Pull request closed without merging**
