### PR TITLE
Removed all 2.x versionadded directives

### PR DESCRIPTION
**Pull request by wouterj**
Replaces https://github.com/symfony/symfony-docs/pull/5585

### CODE REVIEW

**Comment by javiereguiluz** [comment]
:+1: @WouterJ thanks for this nice PR.

**Comment by WouterJ** [comment]
Updated the PR by removing even more references to Symfony 2.x

**Comment by xabbuh** [comment]
looks like a label was removed by these changes that is still referenced somewhere

**Comment by WouterJ** [comment]
Yep, fixed it now

**Comment by xabbuh** [comment]
Thank you Wouter.

**Pull request closed without merging**
