### PR TITLE
[Serializer] Add documentation about the (de)serialization of interfaces and abstract classes

### LINKED ISSUE #9011: [Serializer] Serialize and deserialize from abstract classes
This new serializer feature allows to serialize and de-serialize abstract classes. Such feature is especially useful when dealing with domain objects. See https://github.com/symfony/symfony/pull/24375.

@sroze the description you added in your pull request is very easy to understand. Maybe you could reuse it or expand it to add some docs about this feature that you added to Symfony? Thanks!

### PR DESCRIPTION
**Pull request by sroze**
Fixes #9011

Add documentation for symfony/symfony#24375

### CODE REVIEW

**Comment by sroze** [comment]
@javiereguiluz something like that?

**Review by javiereguiluz — APPROVED** [review]
@sroze thanks for providing the docs for the feature that you also contributed. I like the example a lot because it's easy to follow and understand. I made some minor tweaks to it. Thanks!

**Comment by sroze** [comment]
Thanks @javiereguiluz

**Comment by javiereguiluz** [comment]
It's merged now! Samuel, thanks for this and all your other Symfony related work.

**Pull request merged**
