### PR TITLE
Document the use of ignored_attributes context option

### PR DESCRIPTION
**Pull request by alanpoulain**
This documentation was missing since this PR was merged for 4.2: https://github.com/symfony/symfony/pull/28709

### CODE REVIEW

**Comment by javiereguiluz** [comment]
@alanpoulain just asking because I don't know this component well: does this pull request fully document the changes made in https://github.com/symfony/symfony/pull/28709? Thanks.

**Comment by alanpoulain** [comment]
I don't know. But at least it documents this missing thing.

**Review by dunglas — APPROVED** [review]

**Comment by dunglas** [comment]
@javiereguiluz no, there is the new default context to document, but it's not very useful while https://github.com/symfony/symfony/pull/28927 isn't finished/merged.

I'll take care of documenting this feature (and the other one I introduced recently).

**Comment by dunglas** [comment]
Actually, we should merge #11067 instead of this one.

**Comment by javiereguiluz** [comment]
As suggested, we're closing this in favor of #11067, which was just merged.

@alanpoulain I'm sorry this time your contribution wasn't merged ... but we're looking forward to receive more contributions from you in the future. Thanks!

**Pull request closed without merging**
