### PR TITLE
Fixed minor typo

### PR DESCRIPTION
**Pull request by axzx**

### CODE REVIEW

**Comment by apfelbox** [comment]
I actually think, that the previous version is correct. In the end, the top-level `fingers_crossed` handler is wrapping swift, so it is indeed a "mail" handler.

**Comment by HeahDude** [comment]
Yes but the convention is to have a `fingers_crossed` called `main` https://github.com/symfony/symfony-standard/blob/3.4/app/config/config_prod.yml#L12, so I do think it is typo too.

**Review by HeahDude — APPROVED** [review]
Good catch!

**Comment by apfelbox** [comment]
@HeahDude ah, didn't know that. Nevermind then 😉

**Comment by javiereguiluz** [comment]
Thank you @axzx.

**Pull request closed without merging**
