### PR TITLE
[minor] [2.8] Encourage use of tilde operator in version constraints

### PR DESCRIPTION
**Pull request by phansys**
| Q | A |
| --- | --- |
| Doc fix? | no |
| New docs? | no |
| Applies to |  |
| Fixed tickets |  |

Before:

```
2.3.*
```

After

```
~2.3
```

### CODE REVIEW

**Comment by xabbuh** [comment]
I don't think that this a good idea. The reason is that we have different versions of the documentation and imo it would be confusing if you got, for example, Symfony 2.7 when you actually followed the documentation for Symfony 2.6.

**Comment by javiereguiluz** [comment]
:-1: I agree with @xabbuh on this. We must be careful because `~2.x` and `2.x.*` produce very different results.

**Comment by cordoval** [comment]
I always use tilde with 3 numbers to avoid precisely that. But there are many flavors to these. What about inserting a paragraph about ^ and ~ perhaps.

**Comment by phansys** [comment]
This is the reason why I used ```MAJOR.MINOR.PATCH``` at [patch_version.rst](https://github.com/symfony/symfony-docs/pull/5540/files#diff-e621107d9b0c705093e349a1c72ac82cR18).

**Comment by cordoval** [comment]
yes good change @phansys

**Comment by javiereguiluz** [comment]
@phansys yes, that change is right. But what about all the other changes? In `components/form/introduction.rst` for example you changed `2.3.*` by `~2.3`.

**Comment by phansys** [comment]
I agree with the exposed issue @javiereguiluz, and I think we could use the solution proposed by @cordoval, where ```2.3.*``` becomes ```~2.3.0```. What do you think?

**Comment by javiereguiluz** [comment]
Well, `~2.3.0` is 1 character longer than `2.3.*` and personally, the latter is easier to understand. To me, `2.3.*` is read as `2 point 3 whatever`, but `~2.3.0` is read as `similar to 2 point 3 point 0`

**Comment by phansys** [comment]
I know @javiereguiluz, I don't know if it is "better", but this proposal is intended to standardize the used operators in order to aim users to use tilde instead asterisk (regardless here, in these cases the ```*``` is well used).
https://getcomposer.org/doc/articles/versions.md#tilde:
>As you can see it is mostly useful for projects respecting semantic versioning.

**Comment by WouterJ** [comment]
I agree with @javiereguiluz that using `2.3.*` is easier to understand, which is the main goal of any example code in the documentation imo.

**Comment by phansys** [comment]
I agree with the premise that this way (with asterisk) is better to understand and which is the main goal of the doc's examples, but IMO, beginners tends to use the same syntax they see for everything else.
BTW, since the majority of votes are against this change, I think it could be closed as ```won't fix```.

**Pull request closed without merging**
