### PR TITLE
[DependencyInjection][Improve] Constant YAML with expression language]

### PR DESCRIPTION
**Pull request by 20uf**
Hi,

Continuation of the PR #7395 for the 2.7 branch.

Regards,

### CODE REVIEW

**Review by javiereguiluz — APPROVED** [review]
👍 

Status: reviewed

**Comment by javiereguiluz** [comment]
**Note to mergers**: to be merged only in 2.7 and 2.8; not in 3.x branches.

**Comment by 20uf** [comment]
@javiereguiluz,

We have an error on [build](https://travis-ci.org/symfony/symfony-docs/builds/204224673): 
``` shell
...
writing output... [100%] validation/translations
Warning, treated as error:
/home/travis/build/symfony/symfony-docs/service_container/parameters.rst:254: WARNING: unknown document: Expression Language component /components/expression_language
```

What I do not reproduce locally


``` shell
cd _build && make html
...
writing output... [100%] service_container/parameters                                                                                                                                                                       
generating indices... genindex
writing additional pages... search
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded.
```

An idea ?

**Comment by javiereguiluz** [comment]
@20uf yes! I made a mistake when writing the link to the document. See that the `:doc:` syntax is different when you want to customize the label of the link. Hopefully it's fixed now!

**Comment by 20uf** [comment]
Thank  you  @javiereguiluz

**Review by HeahDude — APPROVED** [review]
Great addition, thanks!

**Comment by xabbuh** [comment]
Thank you @20uf.

**Pull request merged**
