### PR TITLE
[Messenger] Add documentation for RouterContextMiddleware

### LINKED ISSUE #14952: [FrameworkBundle][Messenger] Added RouterContextMiddleware
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#39688
| PR author(s) | @jderusse
| Merged in    | 5.3-dev

### PR DESCRIPTION
**Pull request by jderusse**
fixes #14952

### CODE REVIEW

**Comment by OskarStark** [comment]
Nice feature, thanks, can you add a short example on how to get this info/context in the message handler? Thanks 😃

**Comment by jderusse** [comment]
> can you add a short example on how to get this info/context in the message handler

Hmm... This is not aimed to be used by the message handler, and I don't have any use-case for this.

The purpose of this feature is to make `UrlGenerator` working out of the box, without providing `asset.request_context` parameters

```
$this->urlGenerator->generate('route', [], UrlGeneratorInterface::ABSOLUTE_URL);
// before: http://localhost/my_route
// after: https://my-real-domain:81/my_route

```

**Comment by OskarStark** [comment]
Ah so you don't care about it directly, and just use the urGenerator which takes the provided request context into account?

**Comment by jderusse** [comment]
> Ah so you don't care about it directly, and just use the urGenerator which takes the provided request context into account?

yes, exactly. Main use case: Generating an email with link to your application, and the template is rendered by the consumer (the `message` contains only the template + few parameters)

**Comment by javiereguiluz** [comment]
Jérémy thanks a lot for providing these docs. While merging we did some rewording in the explanation, but we left the essence of your contribution intact. Thanks!

**Pull request merged**
