### PR TITLE
Remove AppBundle

### PR DESCRIPTION
**Pull request by roukmoute**
The twig file is in `app/Resources/views`.
Fix error `Unable to find template "AppBundle:Form:fields.html.twig"`

### CODE REVIEW

**Comment by stof** [comment]
Using the ``Form/fields.html.twig`` notation would be better, as this is what we use almost everywhere in the doc now

**Comment by stof** [comment]
note that this notation can be used only for Twig, not for PHP templates

**Comment by WouterJ** [comment]
Actually, it should be `form/fields.html.twig`.

**Comment by stof** [comment]
the PHP example needs to keep using the ``:Form`` notation yeah

**Comment by WouterJ** [comment]
@roukmoute can you please update the first 3 code blocks to use `form/fields.html.twig` and the other 3 to `:form:fields.html.twig`?

If you don't have time, feel free to say so and I'll finish this PR.

**Comment by roukmoute** [comment]
Is it OK ?

**Comment by WouterJ** [comment]
Thank you for creating this PR & the patience with such a slow merge!

I've merged your PR into the 2.3 version of the docs (resulting in a closed status on GitHub) and will merge it into the newer versions from there. I've also changed the format a little bit (to not use the colon syntax for twig and reference PHP files in the second code example) in 4a41252.

Thanks again! :christmas_tree:

**Pull request closed without merging**
