### PR TITLE
Fix form/validation directory path

### PR DESCRIPTION
**Pull request by nemo-**
| Q | A |
| --- | --- |
| Doc fix? | yes |
| New docs? | no |
| Applies to | 2.3 and higher |
| Fixed tickets |  |

### CODE REVIEW

**Comment by xabbuh** [comment]
:+1: but if I am not mistaken we need to merge this into the `2.7` branch (Symfony 2.3 still uses PSR-0 for autoloading)

**Comment by nemo-** [comment]
Hi, thanks for replying !
To fulfill your recommendation, should I create another PR with that fix based on 2.7 or update this one ?

**Comment by xabbuh** [comment]
@nemo- All is fine, I think we man make the rebase when merging your PR.

**Comment by weaverryan** [comment]
Awesome catch, thanks @nemo-! I've merged this into the 2.7, per xabbuh's comment

**Pull request closed without merging**
