### PR TITLE
Added an article about private console commands

### PR DESCRIPTION
**Pull request by javiereguiluz**
This documents https://github.com/symfony/symfony/pull/20029.

### CODE REVIEW

**Comment by xabbuh** [comment]
In symfony/symfony#20266 we renamed the attribute from `$private` to `$hidden` and inversed its meaning. We need to reflect that here.

Status: Needs work

**Comment by wouterj** [comment]
ping

**Comment by wouterj** [comment]
Updated the PR, please review

**Review by javiereguiluz — COMMENTED** [review]
👍 

Thanks @wouterj for making the needed updates.

**Comment by xabbuh** [comment]
Thank you Javier.

**Pull request closed without merging**
