### PR TITLE
Added jQuery symfony-collection plugin to Form collection docs

### PR DESCRIPTION
**Pull request by hiddewie**
Issue #6943.

I've added a few lines in the form cookbook about form collections. I have placed the content at the bottom because the whole document is concerned.

If another branch must be targeted I will rebase the changes.

### CODE REVIEW

**Comment by snoek09** [comment]
Looks good :+1: Thanks @hiddewie!

Status: reviewed.

**Comment by xabbuh** [comment]
👍

**Comment by javiereguiluz** [comment]
👍

**Comment by xabbuh** [comment]
Thank you @hiddewie.

**Pull request closed without merging**
