### PR TITLE
Fix mem leak in example doctrine testing

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q | A |
| --- | --- |
| Doc fix? | yes |
| New docs? | no |
| Applies to | all |
| Fixed tickets | https://github.com/symfony/symfony/issues/18236 |

### CODE REVIEW

**Comment by javiereguiluz** [comment]
:+1:

**Comment by xabbuh** [comment]
What about adding a comment that explains why we set it to `null` here? People might wonder otherwise what's the reason for this statement is.

**Comment by weaverryan** [comment]
:+1: Note would be cool - I'm fine either way

**Comment by xabbuh** [comment]
We can add the note while merging.

**Comment by WouterJ** [comment]
Thanks! This is now merged. I've added a very minor comment in 4186c32 to explain that this is not a redundant line of code.

**Pull request merged**
