### PR TITLE
Update doctrine full default configuration

### PR DESCRIPTION
**Pull request by xelaris**
| Q | A |
| --- | --- |
| Doc fix? | yes |
| New docs? | no |
| Applies to | all |
| Fixed tickets |  |

This PR updates the full default configuration example to fit the latest DoctrineBundle version 1.3.0. I have also tried to harmonize the Yaml and Xml version related to example values.

### CODE REVIEW

**Comment by weaverryan** [comment]
After a conversation with @Ocramius (https://github.com/doctrine/DoctrineBundle/pull/360#issuecomment-68607391), we decided that we think it's best if this document exists in DoctrineBundle. Then, we would link to it (or perhaps embed their RST file during build - we have not done something like this before) from our reference section.

So, we should add any reference stuff that *we* have here to DoctrineBundle, then delete our reference file. Any issues?

Thanks!

**Comment by xabbuh** [comment]
We would still not be able to render the document for different versions of the DoctrineBundle as long as we don't add it to http://symfony.com/doc/bundles/, right?

**Comment by weaverryan** [comment]
@xabbuh That's right. So perhaps we should add that bundle there, then use an external link on the reference page to whatever version of that page best fits with each version of Symfony. Then of course, they can change the version on that page. Sound ok to you?

**Comment by stof** [comment]
@weaverryan then, the question is whether other DoctrineBundle articles should also be moved to the bundle repo or no.

**Comment by weaverryan** [comment]
@Ocramius and I had decided that only this reference article would live over there - the others would stay here. It's not an exact science, but having the config over there helps them keep that inline with the code (make a PR for both). Everything else is "usage" documentation, and since we put more attention into symfony/symfony-docs, they're better over here.

@xabbuh you're right - we should add it to http://symfony.com/doc/bundles/ so it renders nicely, then link to it externally (we'd always link to their current version). 

I just opened up #4863 for this, so I'll close this. Any config changes should be made to *this* file, and we'll hopefully link to it soon: https://github.com/doctrine/DoctrineBundle/blob/master/Resources/doc/configuration.rst

**Comment by stof** [comment]
@xelaris can you send this updated configuration reference to the DoctrineBundle repo ?

**Comment by stof** [comment]
The reference in DoctrineBundle is now uptodate. @javiereguiluz please render it on symfony.com and then the doc team will be able to get rid of the page maintained in the symfony-docs repo.

**Pull request closed without merging**
