### PR TITLE
[Session] Update incorrect default value for session.handler_id

### PR DESCRIPTION
**Pull request by Nyholm**
See config [definition](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php#L557) and [how it is being used](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L949).

### CODE REVIEW

**Comment by wouterj** [comment]
`null` and `~` are the same in Yaml afaics, so they should both be A, right? The other changes seem correct to me.

**Comment by Nyholm** [comment]
Thank you.. But how will this line ever be true?

https://github.com/symfony/symfony/blob/73a3b838b742f103033218a2758548b829d27061/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L949

**Comment by Nyholm** [comment]
Because the default value is only there if we dont set `handler_id`. Fair.

**Comment by Nyholm** [comment]
PR description is updated

**Review by wouterj — APPROVED** [review]

**Comment by javiereguiluz** [comment]
Thank you Tobias.

**Comment by Nyholm** [comment]
Thank you for merging

**Pull request merged**
