### PR TITLE
[Validator] Added array validation example to raw values

### PR DESCRIPTION
**Pull request by wouterj**
This example was removed from the component's README and it has some value imo.

Finishes https://github.com/symfony/symfony-docs/pull/7161

### CODE REVIEW

**Comment by Koc** [comment]
fixes #5354

**Comment by Koc** [comment]
@wouterj can you also add example of validation lists (`All` constraint)?

**Comment by xabbuh** [comment]
Thank you @wouterj.

**Comment by xabbuh** [comment]
@Koc Do you want to open a new PR with the additions you have in mind?

**Pull request merged**
