### PR TITLE
Alias Monolog\Formatter\JsonFormatter instead of creating a new one

### PR DESCRIPTION
**Pull request by B-Galati**
Let me know if I am wrong but I thought it would be more reliable to use MonologBundle service instead of creating a new one.

### CODE REVIEW

**Comment by xabbuh** [comment]
Should we remove the whole service instead and use `monolog.formatter.json` in the config below instead?

**Comment by B-Galati** [comment]
This solution leverage autowiring which can be "cool" to showcase in the doc.

**Comment by B-Galati** [comment]
I updated base branch to 3.4

**Comment by javiereguiluz** [comment]
We need some Monolog expert to review this. Thanks!

**Comment by B-Galati** [comment]
Friendly ping @Seldaek @lyrixx @stof

**Comment by lyrixx** [comment]
This change [is valid](https://github.com/symfony/monolog-bundle/blob/master/Resources/config/monolog.xml#L30), but I have the same concern as @xabbuh 

anyway :+1:

**Comment by javiereguiluz** [comment]
@B-Galati thanks for this contribution. However, while merging, we did some changes to finally remove the service and use the built-in Monolog service instead in the configuration. Both Christian and Grégoire expressed some concerns, so I think it's OK to do that. Thanks.

**Comment by B-Galati** [comment]
@javiereguiluz Thanks for the heads up!

**Pull request merged**
