### PR TITLE
Added a help note about the __toString() method in User classes

### PR DESCRIPTION
**Pull request by javiereguiluz**
This partially fixes #6463.

### CODE REVIEW

**Comment by xabbuh** [comment]
:+1:

Status: Reviewed

**Comment by weaverryan** [comment]
@javiereguiluz I don't think you linked the right issue. Why should we add this?

**Comment by wouterj** [comment]
@weaverryan correct issue is https://github.com/symfony/symfony-docs/pull/6574

I'm still 👎 for the same reasons:

 * You implement `UserInterface`, so it's never converted to a string.
 * The whole concept of allowing to pass a string, UserInterface or object with __toString() is just too bad to even talk about. I'll submit a WIP PR this week to the code repository to remove this. In sort, all objects used as user just need to implement `UserInterface`, let's forget about the objects that can be converted to a string.

**Comment by weaverryan** [comment]
@wouterj I understand your point... in fact, I understand it so well, that I can't figure out what the bug/problem was in the original #6574 that this was fixing?

**Comment by xabbuh** [comment]
So what do you here?

**Comment by javiereguiluz** [comment]
Closing it because doc voters don't agree with it.

**Pull request closed without merging**
