### PR TITLE
[Form] Minor reword in the Choice type

### PR DESCRIPTION
**Pull request by javiereguiluz**
This will hopefully avoid issues like #11925.

### CODE REVIEW

**Comment by xabbuh** [comment]
Reading the related issue it occurs to me that the reporter was referring to options of the `DateIntervalType`. Maybe we need to add a sentence like there too.

**Comment by javiereguiluz** [comment]
I've added more examples in the DateIntervalType docs. Thanks!

**Review by ovgray — COMMENTED** [review]
The comments at lines 86, 119, 172, 187, 214 and 331 of the changed dateinterval.rst file are incorrect.

The comment at line 86 should say "values displayed to users range from 0 to 30 (both inclusive)". The other comments also misstate what the end of the displayed range would be.

The fact that these errors were made in trying to clarify this "feature" only illustrates how unintuitive the feature is.

**Comment by javiereguiluz** [comment]
I tested in the Symfony Demo app:

```php
->add('foo', DateIntervalType::class, [
    'mapped' => false,
])
```

image

```php
->add('foo', DateIntervalType::class, [
    'mapped' => false,
    'months' => range(1, 12),
])
```

image

```php
->add('foo', DateIntervalType::class, [
    'mapped' => false,
    'months' => array_combine(range(1, 12), range(1, 12)),
])
```

image

**Comment by adrx** [comment]
Your test proves my point about the comment at line 186 (not 187 as my first comment said) of dateinterval.rst. 

The values displayed to users when ‘months’ is set to range(1, 12) range from 0 to 11, not 0 to 12 as your comment says.

**Comment by javiereguiluz** [comment]
@adrx you are right! I was looking at the wrong comments! Sorry.

**Review by OskarStark — APPROVED** [review]

**Pull request merged**
