### PR TITLE
Adding caution box about no other form allowed

### PR DESCRIPTION
**Pull request by ThomasLandauer**
I'm not sure about the blockquote formatting...

### CODE REVIEW

**Comment by xabbuh** [comment]
I am not sure about this change. You usually do not have a controller listening to the route configured with the check path. That’s why I do not see why there should be any form at all.

**Comment by ThomasLandauer** [comment]
But if the username is wrong, the `check_patth` needs to display the login form, doesn't it? At least, that's what the page says at https://symfony.com/doc/current/security.html#form-login

> Don't let this controller confuse you. Its job is only to render the form: the form_login authenticator will handle the form submission automatically. If the user submits an invalid email or password, that authenticator will store the error ***and redirect back to this controller,*** where we read the error (using AuthenticationUtils) so that it can be displayed back to the user.

The use case I'm looking at is a login form being part of the site's menu (i.e. present on every page). In this case it's not so obvious what to use as `check_path`.

BTW: "skittles" ≈ "bowling" ;-)

**Comment by xabbuh** [comment]
It redirects back to the route that is used to render the initial login form.

**Comment by javiereguiluz** [comment]
Folks, what should we do here? Merge, Close, Reword? Thanks.

**Comment by OskarStark** [comment]
Not merge from my side

**Comment by javiereguiluz** [comment]
Feedback agrees on closing without merging, so let's close it. Sorry!

**Pull request closed without merging**
