### PR TITLE
Mentioning svelte as a valid loader override type

### PR DESCRIPTION
**Pull request by weaverryan**
Hi!

Minor tweak for https://github.com/symfony/webpack-encore/pull/781

We could also document svelte itself, though there is also a proposed UX svelte component which, if merged, would be an even better option (and it would leverage this new feature in Encore).

Cheers!

### CODE REVIEW

**Comment by javiereguiluz** [comment]
Thanks Ryan!

I added `Waiting Code Merge` label because I think we need a new release/tag on Encore repository before merging this.

**Comment by zairigimad** [comment]
Hello Ryan what about a new page like this one to demonstrate the `enableSvelte` ?
https://symfony.com/doc/current/frontend/encore/reactjs.html

**Comment by weaverryan** [comment]
@zairigimad Yes, probably - but it should also mention https://github.com/symfony/ux/pull/498 and both React and Vue pages need to be updated to mention to mention their UX components as well. I'd love if someone made a PR to the docs for all of that ;)

**Comment by zairigimad** [comment]
> @zairigimad Yes, probably - but it should also mention [symfony/ux#498](https://github.com/symfony/ux/pull/498) and both React and Vue pages need to be updated to mention to mention their UX components as well. I'd love if someone made a PR to the docs for all of that ;)

I can add a note 🗒️ in React an Vue pages to mentien symfony ux :D

**Comment by javiereguiluz** [comment]
Ryan, thanks for tagging a new Encore release. This is now merged.

**Pull request merged**
