### PR TITLE
[Book][Routing] Add example about how to match multiple methods

### PR DESCRIPTION
**Pull request by xelaris**
| Q | A |
| --- | --- |
| Doc fix? | no |
| New docs? | yes |
| Applies to | 2.3+ |
| Fixed tickets |  |

### CODE REVIEW

**Comment by weaverryan** [comment]
I like this, but I'd actually like to solve it in an easier way: add a commented-out example in the previous section:

```yml
contact_process:
    path:     /contact
    defaults: { _controller: AppBundle:Main:processContact }
    methods:  [POST]
    # or to match GET *or* POST methods
    # methods: [GET, POST]
```

What do you think @xelaris?

**Comment by javiereguiluz** [comment]
I usually prefer concise explanations, as proposed by @weaverryan. But in this case, I think it could be better to show a verbose explanation as proposed by @xelaris. Adding a comment is not clear enough for me. Let's ask @xabbuh and @WouterJ for their opinion about this. Thanks.

**Comment by xabbuh** [comment]
I would have said that the example proposed by @weaverryan would be clear enough.

@javiereguiluz Do you think from your experience about talking with beginners that this is something not so obvious (even with commented out example)?

**Comment by javiereguiluz** [comment]
@xabbuh I don't know which would be the opinion of newcomers. It was just a personal comment. Let me show you a pair of screenshots explainig why I said that.

We have this:

before1

And Ryan proposes to add a comment:

after1

It's not a bad idea at all. But my concern is ... what would happen with the other 3 config formats? For example, consider the case of "annotations":

Before:

before2

After:

after2

But I think we could find a solution: what if we use `GET` for `contactAction ()` and `GET` + `POST` for `processContactAction()`?

**Comment by weaverryan** [comment]
I hadn't thought about the annotations format, so I agree with Javier. But making the process handle get or post might be confusing since it has the same URL as the above, and so will never match in GET. I'm in favor of actually merging as is, after making all this fuss (the additions actually small - mostly code block).

**Comment by WouterJ** [comment]
What about using `[POST, PUT]` (for instance) for processContactForm?

**Comment by weaverryan** [comment]
Oh, that's a cool idea - I can't believe I didn't think of that! +1 for making the previous example use Post and Put instead of this new section. @xelaris can you make that change?

Thanks!

**Comment by xabbuh** [comment]
Oh yeah, that's indeed a great idea @WouterJ.

**Comment by xelaris** [comment]
I like the idea of changing the existing example to demonstrate how to match multiple methods and I changed the PR as suggested by @WouterJ. But I have two points about the current state of this PR:
* I noticed that the example doesn't work well with the best practices, as it uses two actions to display and process the form. This was actually a reason for the first version of this PR.
* I'm in doubt if `PUT` is a suitable method to send a contact form.

I'm +1 with @javiereguiluz suggestion to change the `processContactAction()` method to match `GET` and `POST`. This would kill two birds with one stone: Demonstrate how to match multiple routes and fulfill the best practise.
To make the example more consistent then, I suggest to rename `processContactAction` to `contactFormAction` and use a comment like `// ... display and process a contact form` and to change `contactAction` to `newsAction` with route `/news` or something and use a comment like `// ... display your news`.

What are your opinion about this?

**Comment by xabbuh** [comment]
@xelaris Good point with the best practices. But wouldn't we then don't have an example with only one allowed method when choosing your solution?

**Comment by xelaris** [comment]
@xabbuh The `newsAction` with route `/news`would match only `GET`.

**Comment by xabbuh** [comment]
Good point, looks like a good idea then.

**Comment by xelaris** [comment]
I have changed the PR to apply the latest proposal. What do you think about it?

**Comment by xabbuh** [comment]
:+1: from me

**Comment by weaverryan** [comment]
LOVE it.  Thanks @xelaris - you rock for your patience and ideas!

**Pull request merged**
