### PR TITLE
Missing Namespace from event dispatcher

### PR DESCRIPTION
**Pull request by TheGarious**

### CODE REVIEW

**Review by maxhelias — APPROVED** [review]

**Comment by maxhelias** [comment]
I missed, it should be in 4.4

**Comment by OskarStark** [comment]
It is correct, but will not add so much additional value, its mostly clear through the filepath, I am against this change, sorry.

**Comment by TheGarious** [comment]
I add this because many page have and don't have namespace or filepath.

**Comment by maxhelias** [comment]
I am in favor of this kind of addition and making it uniform over the examples. This allows the beginner to have a better reference in their project

**Comment by OskarStark** [comment]
We discussed this in the team and I agree this is helpful for beginners 👍

**Comment by OskarStark** [comment]
Thank you Gary.

**Comment by TheGarious** [comment]
Thanks you @OskarStark

**Pull request merged**
