### PR TITLE
[Messenger] fix xml block

### LINKED ISSUE #16451: [Messenger] "reset_on_message" location is inconsistent
https://symfony.com/doc/current/messenger.html#stateless-worker

The `reset_on_message` key is in different locations for YAML, XML and PHP.

YAML example has the `reset_on_message` key under the `messenger` key

XML example has the `reset_on_message` attribute on the child `<framework:transport>` element, and not the parent `<framework:messenger>`

PHP example has the `reset_on_message` method on the `TransportConfig` config helper, not on the parent `MessengerConfig`.

The PHP example, at least on Symfony 5.4, should be as follows in order to work correctly.

```php
$messenger = $framework->messenger();

$messenger->resetOnMessage(true);
```

### PR DESCRIPTION
**Pull request by kbond**
Fixes #16451.

### CODE REVIEW

**Review by ogizanagi — APPROVED** [review]
What about adding a note about the fact it'll be the default as of Symfony 6.0 and add a note about disabling this behavior explicitly using `--no-reset` (as explained in https://github.com/symfony/symfony-docs/pull/16763)?

**Comment by kbond** [comment]
Note added.

**Review by ogizanagi — APPROVED** [review]
Perfect 👌🏻

**Comment by javiereguiluz** [comment]
Thanks Kevin!

**Pull request merged**
