### PR TITLE
Update access_control.rst

### PR DESCRIPTION
**Pull request by asandjivy**
The correct keyword is "roles"

### CODE REVIEW

**Comment by wouterj** [comment]
Both `roles` and `role` is possible,but let's use `roles` indeed :)

Status: reviewed
👍

**Comment by asandjivy** [comment]
ok! i knew about ip | ips but i didn't know about role.
Thank you :)

**Comment by wouterj** [comment]
@asandjivy fyi, most plural configuration options are possible in singular format as well (to support XML).

**Comment by asandjivy** [comment]
ok thanks :+1:

**Comment by wouterj** [comment]
Aaannnd it's merged now, thanks!

(fyi, it's merged into 2.7, the oldest maintained version, and I'll merge it into the newer versions later today)

**Pull request closed without merging**
