### PR TITLE
Minor grammar fix.

### PR DESCRIPTION
**Pull request by maxolasersquad**

### CODE REVIEW

**Comment by xabbuh** [comment]
:+1: 

@weaverryan What do you think?

**Comment by weaverryan** [comment]
Definitely :+1:

**Comment by xabbuh** [comment]
Thank you David.

**Comment by xabbuh** [comment]
FYI, this was merged into the `2.3` branch. That's why your pull request is being seen as closed (branches are regularly merged into higher branches, so it will soon be available in the `2.7` branch too).

**Pull request closed without merging**
