### PR TITLE
Added a reference to the Foundation form theme

### PR DESCRIPTION
**Pull request by totophe**
| Q | A |
| --- | --- |
| Doc fix? | no |
| New docs? | yes |
| Applies to | N/A |

See pull request: https://github.com/symfony/symfony/pull/12587

### CODE REVIEW

**Comment by xabbuh** [comment]
The code PR has been merged. Congrats @totophe! This is ready to be reviewed.

**Comment by xabbuh** [comment]
:+1:

**Comment by totophe** [comment]
:-) thanks

**Comment by xabbuh** [comment]
Thank you @totophe. I merged your pull request and added the theme to the example Twig configuration in 0776efe.

**Comment by totophe** [comment]
Thanks @xabbuh :+1:

**Pull request closed without merging**
