### PR TITLE
Promote builtin serializer instead of JMS

### PR DESCRIPTION
**Pull request by javiereguiluz**
| Q | A |
| --- | --- |
| Doc fix? | no |
| New docs? | yes |
| Applies to | all |
| Fixed tickets | #5069 |

### CODE REVIEW

**Comment by stof** [comment]
I'm not sure this should be done in the 2.3 branch. The 2.3 serializer is far from competing with JMSSerializer (the 2.7 serializer can)

**Comment by javiereguiluz** [comment]
@stof is right: serializer has improved a lot in the most recent versions of Symfony, so  let's merge it in 2.7 branch then.

**Comment by xabbuh** [comment]
@javiereguiluz Did you check if your changes can be cleanly applied on the `2.7` branch? @dunglas did quite some changes on that branch.

**Comment by WouterJ** [comment]
-1, JMS Serializer still has more features than the Symfony Serializer.

**Comment by dunglas** [comment]
@WouterJ it has more features, but are those extra features useful for the average project?
Promoting the built-in Serializer has many advantages:
- no external dependency required
- no license issue
- usage very similar to other components (XML and YAML mappings for instance)

Any one interested in a more advanced solutions can, as for any other part of the framework, check Packagist, blog posts and so on then install another library.

To move forward, what features of JMSSerializer you miss in the built-in Component?

**Comment by WouterJ** [comment]
I don't know what features are missing from the Serializer component (I don't use either one). However, I believe there still are some differences. What about listing reasons why one would use the JMS one or the Symfony one? (you already made a good start in your comment)

**Comment by dunglas** [comment]
I'll said: use JMSSerializer if you want to deal in an advanced manner with XML or Doctrine, if you want to use a bundle using JMSSerializer and if you don't care about the license issue. In any other case, use the built-in Serializer.

**Comment by jrobeson** [comment]
@dunglas : can you be more specific? What are some specific things that you can do with the JMSSerializerBundle that you can't do with with the Symfony Serializer?

**Comment by dunglas** [comment]
@jrobeson There is no way to do things doable with `@XmlValue`, `@XmlAttribute` etc with JMSSerializer... The only solution is to create a custom normalizer (and there is no plan to add such things because IMO creating a custom normalizer is cleaner than "polluting" the entity with such annotations).

**Comment by jrobeson** [comment]
so only XML stuff?

**Comment by dunglas** [comment]
@jrobeson mainly, but the design of JMSSerializer and Symfony Serializer are different on many points (type handling, extension, group and versions management).

**Comment by xabbuh** [comment]
One thing that I am currently missing, but for which I didn't find the time to dig into the code to find out how to do it properly are discriminator maps.

**Comment by javiereguiluz** [comment]
I think it's time to make a decision regarding this PR, so we can merge it or close it. Thanks.

**Comment by dunglas** [comment]
:+1: to merge it

**Comment by javiereguiluz** [comment]
Closing it in favor of #5429, which uses the right 2.7 branch.

**Pull request closed without merging**
