### PR TITLE
[Testing] [PHPUnit-Bridge] Troubleshooting

### PR DESCRIPTION
**Pull request by sylfabre**
This PR documents a new solution to an issue I'm having with ClockMock related to https://bugs.php.net/bug.php?id=76788.

I was the original author of the current Troubleshooting section and came across another use-case

### CODE REVIEW

**Comment by sylfabre** [comment]
I don't understand what's wrong with https://github.com/symfony/symfony-docs/runs/1815088336?check_suite_focus=true

It looks like the syntax I can find in other files like https://github.com/symfony/symfony-docs/blob/5.x/components/yaml.rst line 179

**Comment by javiereguiluz** [comment]
Thanks Sylvain! The reported error was about using `.. code-block:: php` which is not allowed in Symfony Docs because we use instead the shortcut `::` 

We fixed that while merging this. Thanks!

**Comment by sylfabre** [comment]
@javiereguiluz thank you for the merge and the explanation 👌 

Do I need to submit a PR for 5.x too? Or does it gets merged "there" too?

**Comment by javiereguiluz** [comment]
There's no need to submit PR for upper branches because we "upmerge" all PR in all supported branches. Cheers!

**Pull request merged**
