### PR TITLE
Fixed code block under "Custom Messages"

### PR DESCRIPTION
**Pull request by superhaggis**
Very minor typo correction!

### CODE REVIEW

**Comment by javiereguiluz** [comment]
@superhaggis it *looks* like a typo ... but it's not :)

It's a "magic feature" of the format we use to write the docs. If you put `::` in the line before some code block, it's highlighted with the default language you configured (PHP in our case).

So, this `::` magic avoids us to repeat thousands of times this --> 

```
.. code-block:: php
```

**Comment by javiereguiluz** [comment]
Of course I understand your Pull Request wrong ... not only you know the `::` trick, but you correctly fixed it. I'm really sorry 😊  🙏  🙇

**Review by javiereguiluz — APPROVED** [review]
👍

**Review by HeahDude — APPROVED** [review]
Good catch!

**Comment by xabbuh** [comment]
Good catch, thanks @superhaggis.

**Pull request closed without merging**
