### PR TITLE
Fixed null description of query_builder option

### PR DESCRIPTION
**Pull request by HeahDude**
doc fix: 2.8+

ref https://github.com/symfony/symfony/pull/13990#issuecomment-220788142

### CODE REVIEW

**Comment by HeahDude** [comment]
I've opened https://github.com/symfony/symfony/pull/18830

**Comment by HeahDude** [comment]
Ping, symfony/symfony#18830 is merged now.

**Comment by xabbuh** [comment]
👍 

Status: Reviewed

**Comment by WouterJ** [comment]
Thanks for taking care of this issue @HeahDude! I've merged your PR and then made things a bit shorter (and removed the unclear "default loading" phase) in 94c0f45. As always, feel free to comment if you don't agree.

**Pull request merged**
