### PR TITLE
Add isSubmitted call

### PR DESCRIPTION
**Pull request by DanielSiepmann**
Streamline with http://symfony.com/doc/current/book/forms.html#handling-form-submissions
Following best practice: http://symfony.com/doc/current/best_practices/forms.html

### CODE REVIEW

**Comment by javiereguiluz** [comment]
@DanielSiepmann thanks for submitting this fix. I agree that we should comply with the best practices here. By the way, could you please swap the order of the methods:

```php
if ($form->isSubmitted() && $form->isValid()) {
```

**Comment by WouterJ** [comment]
:+1:

**Comment by DanielSiepmann** [comment]
Thanks, I've updated that and will match the order in #5970, too.

**Comment by xabbuh** [comment]
:+1:

**Comment by WouterJ** [comment]
Thanks for your quick reactions Daniel! I've now merged this into the 2.3 docs and will merge it into the latest versions from there (fyi, that's why this PR is marked as closed).

**Pull request closed without merging**
