### PR TITLE
Fix variable name in code snippet

### PR DESCRIPTION
**Pull request by freiondrej**

### CODE REVIEW

**Review by kunicmarko20 — APPROVED** [review]
Thank you and congrats on your first contribution!

**Comment by kunicmarko20** [comment]
Just checked and the issue exists also on 3.4

**Comment by javiereguiluz** [comment]
@freiondrej thank you! We merged it in 3.4 and we'll merge in the upper branches automatically later.

**Comment by freiondrej** [comment]
@javiereguiluz thanks :)

**Comment by javiereguiluz** [comment]
Note: we must close this PR manually because the proprietary tool we use in Symfony to merge PRs doesn't close them when we change the branch while merging.

**Pull request closed without merging**
