### PR TITLE
Update page_creation.rst

### PR DESCRIPTION
**Pull request by ahmedsliman**

### CODE REVIEW

**Comment by javiereguiluz** [comment]
Ahmed, thanks for this contribution.

I'm not native in English ... but I'm not sure about this change. According to https://english.stackexchange.com/questions/128477/does-the-verb-after-set-of-agree-with-set-or-the-plural-noun-that-follows the verb should probably match "instructions" instead of "a set". But I'm going to ask some native English friends in the Symfony community to check this.

**Comment by andyexeter** [comment]
Native English speaker here. The upvoted answer on StackExchange which @javiereguiluz linked to pretty much hits the nail on the head. 

In this instance, the singular 'tell' is grammatically correct.

**Comment by javiereguiluz** [comment]
Andy, thanks a lot for your review!

Ahmed, we're closing this without merging because the current docs are correct ... but please, keep sending other pull requests to improve things. Thanks!

**Review by pbowyer — COMMENTED** [review]
This change should not be made. In most cases `tells` would be correct, but in the context of this complex paragraph, `tell` is the correct word.

**Pull request closed without merging**
