### PR TITLE
question

### PR DESCRIPTION
**Pull request by OskarStark**
@javiereguiluz

### CODE REVIEW

**Comment by javiereguiluz** [comment]
If I recall it correctly, the opinions about global or local PHPUnit installation are still divided. Personally I think that PHPUnit should always be installed globally using the PHAR provided by PHPUnit project. But this is just my opinion.

**Comment by OskarStark** [comment]
Does a Link exists which show both options?

**Comment by javiereguiluz** [comment]
The official docs explain both methods: https://phpunit.de/manual/current/en/installation.html

**Comment by OskarStark** [comment]
imo we can close this ticket

**Comment by xabbuh** [comment]
@OskarStark Is the thing you initially wanted to change not relevant anymore (by the way, you can close your own pull requests yourself :))?

**Comment by OskarStark** [comment]
:)

@xabbuh thanky i know this, but i think that the link to PHPUnit is enough to point out where to find more instructions.

bildschirmfoto 2015-07-09 um 10 05 20

We don't have to explicitly show a link to the installation imo.

**Pull request closed without merging**
