### PR TITLE
[DependencyInjection] Use constructor property promotion (CPP)

### PR DESCRIPTION
**Pull request by OskarStark**

### CODE REVIEW

**Review by alamirault — APPROVED** [review]

**Review by javiereguiluz — APPROVED** [review]
I like CPP a lot ... the only thing I dislike is that I put the arguments in one line when the constructor only has one argument. But I guess this is just a matter of personal taste, so let's merge this!

Thanks Oskar.

**Comment by alexislefebvre** [comment]
Since Symfony 6.2 requires PHP 8.1+, the `readonly` keyword is available. Is there a reason not to use it in these examples?

Example:

```diff
- private MailerInterface $mailer,
+ private readonly MailerInterface $mailer,
```

**Comment by OskarStark** [comment]
Can you please open a separate issue about this topic? Thanks

**Comment by OskarStark** [comment]
I merged and upmerged this PR

**Comment by javiereguiluz** [comment]
Thanks for merging and solving all conflicts 🙏

**Pull request merged**
