### PR TITLE
Use Doctor RST 1.41.0 and new rule `TitleUnderlineLengthMustMatchTitleLength`

### PR DESCRIPTION
**Pull request by MrYamous**
Following https://github.com/OskarStark/doctor-rst/pull/1337

### CODE REVIEW

**Comment by OskarStark** [comment]
Can you please check the CI errors? Thanks

**Comment by MrYamous** [comment]
I guess CI for 6.2 and 6.3 will be broken too after merge

**Review by OskarStark — APPROVED** [review]

**Comment by OskarStark** [comment]
Thank you @MrYamous.

**Comment by OskarStark** [comment]
I unmerged the PR, can you please check 6.2? Thanks

**Pull request merged**
