### PR TITLE
missing constraint example from the old readme

### PR DESCRIPTION
**Pull request by CoolGoose**

### CODE REVIEW

**Review by javiereguiluz — COMMENTED** [review]
I'm not sure about this change.

Even if your example is perfectly correct, when a component doc has several pages, in the first page we usually show just one example of how to use it.

But let's wait to hear more opinions about this.

**Comment by xabbuh** [comment]
Don't we already have a dedicated section in how to validate arrays? I think we should rather link there instead of duplicating its contents then.

**Comment by CoolGoose** [comment]
@xabbuh somehow I missed this reply, do you want me to close this and put the example on the validate array section ? 
I think this is a cleaner and simpler example, especially since this is standalone

**Comment by xabbuh** [comment]
@CoolGoose Yeah, if we want to make improvements, it should be done here: http://symfony.com/doc/current/validation/raw_values.html

**Comment by wouterj** [comment]
Hi @CoolGoose! I've taken your commit and moved the content you added to the `raw values` sub-guide in: https://github.com/symfony/symfony-docs/pull/7805 Thanks for adding this example back in the docs, I think that makes a lot of sense!

**Pull request closed without merging**
