### PR TITLE
Removing a section about Roles that I think has no real use-case

### PR DESCRIPTION
**Pull request by weaverryan**
Hi guys!

| Q | A |
| --- | --- |
| Doc fix? | no |
| New docs? | no |
| Applies to | 2.3+ |
| Fixed tickets | n/a |

This came up after a conversation with someone on Twitter that got hung up on this section (they were also new to Doctrine, so the ManyToMany relationship was a bit challenging). But it occurred to me that this section is totally unnecessary for beginners, and maybe totally unnecessary for _everyone_. Is there a real-use case for this?

It was added 4 years ago at sha: 5a2824b6, and it's original purpose was to talk
about Roles as domain objects. If this has a real-use case, then we should clarify
what it is, and move it to its own cookbook. This is a details that beginners are
trying to deal with, unnecessarily.

Thanks!

### CODE REVIEW

**Comment by javiereguiluz** [comment]
:+1: I fully agree with you.

**Comment by xabbuh** [comment]
:+1: This will also (in a way) fix #5183.

**Comment by WouterJ** [comment]
:+1:

**Comment by stof** [comment]
:+1:

**Comment by weaverryan** [comment]
Thanks guys - sounds like a home run :)

**Pull request merged**
