### PR TITLE
Update upload_file.rst for handling FileException

### PR DESCRIPTION
**Pull request by LS05**
#9642 
Handled FileException in coding examples. We need to discuss how to handle specific file exceptions ;)

### CODE REVIEW

**Review by javiereguiluz — APPROVED** [review]
I like this! I'll wait for more opinions before merging it. Thanks!

**Comment by LS05** [comment]
@javiereguiluz I have fixed a typo in there! :)

**Review by HeahDude — APPROVED** [review]
This is really nice, thanks for this contribution!

**Comment by LS05** [comment]
Thank you @HeahDude ! Looking forward to do more :)

**Comment by javiereguiluz** [comment]
@LS05 this is now merged! We merged it in 2.8 branch (and we'll merge in the other branches automatically later). By the way, we slightly modified this when merging to add the missing import of the `FilexException` class. Cheers!

**Pull request closed without merging**
