### PR TITLE
[Translation] Fix invalid caution block

### PR DESCRIPTION
**Pull request by alexandre-daubois**

### CODE REVIEW

**Review by xabbuh — DISMISSED** [review]

**Review by OskarStark — DISMISSED** [review]

**Comment by OskarStark** [comment]
Hmm looks like I broke the PR while switching to 5.4, can you please create a new one? 🤔 Sorry

**Comment by alexandre-daubois** [comment]
No worries! It seems it's been fixed anyway :+1:

**Comment by xabbuh** [comment]
indeed, this was fixed in the meantime with #17827

**Comment by OskarStark** [comment]
Ok that's the explanation 👍

**Pull request closed without merging**
