### PR TITLE
Change Sql Field name because it's reserved

### PR DESCRIPTION
**Pull request by rmed19**
| Q | A |
| --- | --- |
| Doc fix? | yes |
| New docs? | no |
| Applies to | 2.3+ |
| Fixed tickets | #5566 |

### CODE REVIEW

**Comment by javiereguiluz** [comment]
@rmed19 :+1: for changing the name. However, I'd like to propose a different new name. What if we use `created_at` name, which is more common for PHP applications? In any case, please don't change anything until we have the opinion of the documentation managers. Thanks.

**Comment by WouterJ** [comment]
:+1:

**Comment by WouterJ** [comment]
Thank you @rmed19 for catching this error. Congratz on your first ever doc contribution! You'll receive the doc contributor badge within some days.

I've renamed the column to `created_at`, as proposed by @javiereguiluz in 0134123 after merging your PR. If you don't agree with this change, feel free to comment.

**Comment by rmed19** [comment]
Yes,  created_at is more common, so it's will be better to change created_date to it

**Pull request merged**
