### PR TITLE
[Config] Allow changing the path separator

### LINKED ISSUE #9090: [Config] allow changing the path separator
See https://github.com/symfony/symfony/pull/22253

### PR DESCRIPTION
**Pull request by javiereguiluz**
This fixes #9090.

### CODE REVIEW

**Review by rzilin — APPROVED** [review]

**Comment by crevillo** [comment]
Another question here. is possible to set a separator having more than one char? Also, are there anything that we shouldn't use as separator to avoid problems?

**Comment by bburnichon** [comment]
There are currently no limitation about separator being a single char. It could be any length. There are also no restriction about separator you can use. Currently, it is meant for display keys in a nice consistent manner. In my use case, I wished to use a `/` as separator as some configuration keys had `.` in names already.

**Comment by javiereguiluz** [comment]
Cool. Since there are no special constraints (length, allowed chars, etc.) there's no need to mention it. We usually only document constraints or things you can't do. Thanks!

**Comment by crevillo** [comment]
:+1:

**Pull request merged**
