### PR TITLE
Update routing.rst

### PR DESCRIPTION
**Pull request by amine-betari**
We suppose we have thie URL :
http://127.0.0.1:8000/share/symfony//ezplatform/php/drupal/wordpess

**path** => symfony/ezplatform/php/drupal
**token** => wordpess

### CODE REVIEW

**Comment by amine-betari** [comment]
@javiereguiluz did you test it ?

**Comment by wouterj** [comment]
Indeed, `$token` will not be empty (unless marked as optional). We should maybe tell that the last one only get the last path and the rest of the match is matched by the first argument. Are you willing to change this note?

**Comment by amine-betari** [comment]
@wouterj  

Done

**Comment by wouterj** [comment]
Hi! Thanks for your quick responses! I've now merged it and did some minor fixes in 35ed391 afterwards.

**Pull request merged**
