### PR TITLE
fix #6602

### LINKED ISSUE #6602: CsrfExtension namespace wrong in the documentation
The documentation for the [form component](http://symfony.com/doc/current/components/form/introduction.html#csrf-protection) uses `Symfony\Component\Security\Extension\Csrf\CsrfExtension` which is not defined. 

I believe the correct class is `Symfony\Component\Form\Extension\Csrf\CsrfExtension`.

Am I right? If so I can do a pull request to update the doc.

### PR DESCRIPTION
**Pull request by yamiko-ninja**
Fixes namespace for Extension in the docs

### CODE REVIEW

**Comment by HeahDude** [comment]
👍

**Comment by javiereguiluz** [comment]
👍 

Doc maintainers: according to Symfony API the fix is correct since 2.3:

form_extension_api

**Comment by xabbuh** [comment]
:+1:

**Comment by WouterJ** [comment]
Great catch Robert! This typo was introduced in the 2.7 version of the docs, so I've merged this PR into that version as well (I'll merge it into newer versions from there).

**Pull request closed without merging**
