### PR TITLE
Mentioned the identity translator of TranslationExtension

### LINKED ISSUE #8452: [TwigBundle] register an identity translator as fallback
Minor change, but maybe we need to reword or add some note somewhere about forms and translations. See https://github.com/symfony/symfony/pull/24358

### PR DESCRIPTION
**Pull request by javiereguiluz**
This fixes #8452.

### CODE REVIEW

**Comment by xabbuh** [comment]
Is that really something we want to document? Isn't it unnecessary noise for users reading the document which is already quite long?

**Comment by javiereguiluz** [comment]
Not sure if we want to document it ... but the current docs say: "you must install the translator component when using built-in form themes". That's wrong thanks to this fallback.

**Comment by xabbuh** [comment]
Maybe we should then rather just delete that outdated sentence?

**Comment by javiereguiluz** [comment]
@xabbuh you are right. Let's keep things unchanged. It's obvious that you must install the Translation component to translate things, so it's OK to say *"you must install Translation"*. The only difference is that if you forgot that, you'll see an error in old Symfony versions and now you'll see contents untranslated, making it obvious that you must install the translation component. So, let's close. Thanks!

**Pull request closed without merging**
