### PR TITLE
Syntax to create an email

### PR DESCRIPTION
**Pull request by grelu**
With swiftmailer 6.0.1 and Symfony 3.2.8, the good syntax to create an email is :
$message = new \Swift_Message('Hello Email');

### CODE REVIEW

**Comment by weaverryan** [comment]
We can't assume that users have 6.0 yet. But, the `Swift_Message` class isn't new... so does this syntax also work in Swiftmailer 5?

Also, there are other spots we need to update - you can find them if you run:

```
git grep newInstance
```

Thanks - we have to make sure the details are correct, but this is a good change. And the old way definitely does *not* work in Swiftmailer 6

**Comment by grelu** [comment]
It's my first contribution. Should I create a new pull request ? I have updated the other spots.
Thanks.

**Comment by grelu** [comment]
Apparently, no, it's a new method to create a message in 6.0. I have read the 5.x version of the documentation and it is not the same way of doing things : 
https://github.com/swiftmailer/swiftmailer/blob/5.x/doc/messages.rst
So, what should I do now ? (I have committed the other spots changes)

**Comment by weaverryan** [comment]
Hmm, but check out the `Swift_Message::newInstance()` class on the 5.x branch - https://github.com/swiftmailer/swiftmailer/blob/5.x/lib/classes/Swift/Message.php#L73-L76. It's not doing anything special: just creating a new instance of itself. So it looks like the docs were just not using the new method. Even going WAY back to version 4.0... I can't see a reason why we were using `newInstance` instead of simply `new Swift_Message()`.

**Comment by weaverryan** [comment]
In other words 👍 - I think this is ready for merge... and into the 2.7 branch: this syntax appears to always have been valid.

Status: Reviewed

**Comment by grelu** [comment]
Perfect !

**Review by javiereguiluz — APPROVED** [review]
I agree with Ryan. The `newInstance()` method didn't do anything special in 5.x version, so it's safe to update this.

👍  @grelu thanks for fixing this and congrats on your first contribution to docs!

**Comment by grelu** [comment]
You're welcome and thank you !

**Review by xabbuh — APPROVED** [review]

**Comment by xabbuh** [comment]
Thank you @grelu.

**Pull request closed without merging**
