### PR TITLE
csrf_token_generator and csrf_token_id documentation

### PR DESCRIPTION
**Pull request by xabbuh**
| Q | A |
| --- | --- |
| Doc fix? | no |
| New docs? | yes (symfony/symfony#6554, symfony/symfony#9587) |
| Applies to | 2.4+ |
| Fixed tickets | #3059, #5942 |

### CODE REVIEW

**Comment by xabbuh** [comment]
Deprecations will only be triggered starting with Symfony 2.8. But as the new options have been introduced with Symfony 2.4 we should describe them in the 2.7 docs too (there is no need to start using the old options in a new application).

**Comment by ogizanagi** [comment]
:+1:

**Comment by xabbuh** [comment]
ping @weaverryan @WouterJ @javiereguiluz Let's finish this soon. We are getting a lot of pull requests all wanting to fix this. What do you think?

**Comment by weaverryan** [comment]
Nice job with this! It looks like this was a rare time when a change in core slipped past having (at least) an issue about it on the docs. Thanks!

**Pull request merged**
