### PR TITLE
[Config] Add ExprBuilder::ifEmpty()

### PR DESCRIPTION
**Pull request by ogizanagi**
After https://github.com/symfony/symfony/pull/19764

### CODE REVIEW

**Comment by wouterj** [comment]
Can you please add `(since Symfony 3.2)` after the list item?

**Comment by ogizanagi** [comment]
@wouterj : Added :)

**Comment by ogizanagi** [comment]
Code repository PR is now merged :)

**Comment by wouterj** [comment]
Cool! Let's merge this one as well then.

👍 
status: review

**Comment by weaverryan** [comment]
Awesome, thanks Maxime!

**Pull request merged**
