### PR TITLE
Add documentation about quiet configuration

### LINKED ISSUE #13008: [PHPUnitBridge] Improved deprecations display
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#35271
| PR author(s) | @greg0ire
| Merged in    | 5.1-dev

### PR DESCRIPTION
**Pull request by l-vo**
Fixes #13008.

### CODE REVIEW

**Comment by javiereguiluz** [comment]
@l-vo thanks for this contribution! Do you know if this is also available in Symfony 4.4 ... or should we merge only in 5.1 and up?

**Comment by l-vo** [comment]
Yes the feature has been added in 5.1 so 5.1 is the proper target branch 🙂

**Comment by javiereguiluz** [comment]
Thanks! I've found the related issue and updated the description of your PR with it.

**Comment by javiereguiluz** [comment]
It's merged now. Thanks Laurent!

**Comment by greg0ire** [comment]
Thanks @l-vo !

**Comment by l-vo** [comment]
@javiereguiluz  @greg0ire You're welcome 👍

**Pull request merged**
