### PR TITLE
Update http_client.rst

### PR DESCRIPTION
**Pull request by ThomasLandauer**
Integrating the findings of https://github.com/symfony/symfony/issues/38082#issuecomment-690529165

### CODE REVIEW

**Review by Nyholm — CHANGES_REQUESTED** [review]
Thank you for this PR. It seams incomplete and not really related to the context or the comment you linked.

**Comment by ThomasLandauer** [comment]
Well, the linked issue is about the question how to add a custom header when doing a file upload. Since @nicolas-grekas confirmed that what I guessed is indeed the right way, I'd like to include this.

Why do you think it's incomplete? Which changes do you suggest?

**Comment by ThomasLandauer** [comment]
@nicolas-grekas Could you please take a look and approve this?

**Review by nicolas-grekas — APPROVED** [review]

**Comment by OskarStark** [comment]
Thank you Thomas.

**Pull request merged**
