### PR TITLE
Removed the glossary

### PR DESCRIPTION
**Pull request by wouterj**
| Q | A |
| --- | --- |
| Doc fix? | yes |
| New docs? | no |
| Applies to | all |
| Fixed tickets | #5462 |

It's funny that 99% of the `:term:` usages were located in sentences describing a term. So we didn't loose any information there. In some cases, I've tweaked the sentence a bit not loose any important information.

As for the genindex mentioned by @xabbuh in the issue, I believe this one is created automatically by Sphinx based on all `.. index::` directives in the documentation. When removing the glossary, the genindex will automatically not include the terms anymore (/cc @javiereguiluz please confirm).

### CODE REVIEW

**Comment by xabbuh** [comment]
@WouterJ I am more concerned about the link to the glossary in the navigation. Would be bad if a link led to a non-existing page.

**Comment by weaverryan** [comment]
:+1:, but only after Javier is able to remove the Glosaary link on http://symfony.com/doc/current/index.html

**Comment by WouterJ** [comment]
Ah, missed that link. Indeed, we should wait until the link is removed from the index

**Comment by WouterJ** [comment]
ping @javiereguiluz Did you already create a PR to remove the glossary link?

**Comment by WouterJ** [comment]
I'm sorry to bother you again, @javiereguiluz, but what is the status of this?

**Comment by xabbuh** [comment]
ping @javiereguiluz :)

**Comment by TomasVotruba** [comment]
:+1: 

Ping @javiereguiluz - only this needs to be done here: https://github.com/symfony/symfony-docs/pull/5464#issuecomment-116745229

**Comment by javiereguiluz** [comment]
The glossary has now been unlinked from the Symfony Docs index (it will be public after the next deployment).

**Comment by WouterJ** [comment]
Thanks @javiereguiluz! I've rebased this PR, it's ready to merge once symfony.com is redeployed.

status: reviewed

**Comment by TomasVotruba** [comment]
@WouterJ Thank you!

**Pull request closed without merging**
