### PR TITLE
Reworded the note about supressing form validation

### PR DESCRIPTION
**Pull request by javiereguiluz**
This replaces #6461 according to reviewer's comments.

@HeahDude please check if this PR is correct according to your comment here: https://github.com/symfony/symfony-docs/pull/6461#issuecomment-318842780

### CODE REVIEW

**Review by HeahDude — APPROVED** [review]
Thank you very much!

**Comment by weaverryan** [comment]
Awesome :)

**Comment by wouterj** [comment]
Can we please keep a note/tip directive stating that this does not disable extra field or file upload size handling?

**Comment by weaverryan** [comment]
@wouterj can you open a pr or issue - I honestly don’t understand enough about all the details to know for sure about your question

**Comment by HeahDude** [comment]
See https://github.com/symfony/symfony-docs/pull/8956.

**Pull request merged**
