### PR TITLE
Update links

### PR DESCRIPTION
**Pull request by thewilkybarkid**
| Q | A |
| --- | --- |
| Doc fix? | yes |
| New docs? | no |
| Applies to | 2.3 |
| Fixed tickets |  |

### CODE REVIEW

**Comment by thewilkybarkid** [comment]
Damn, didn't change the branch (meant 2.3, not 2.8). Sorry!

**Comment by javiereguiluz** [comment]
:+1: thanks for fixing this. @thewilkybarkid don't worry about the branch, our doc managers will change it when merging this change.

**Comment by xabbuh** [comment]
:+1:

**Comment by xabbuh** [comment]
Thank you @thewilkybarkid.

**Comment by xabbuh** [comment]
Just FYI, I merged this into the `2.3` branch. That's why your PR is displayed as closed instead of merged.

**Pull request closed without merging**
