### PR TITLE
Update direct_submit.rst

### PR DESCRIPTION
**Pull request by KamilKubicki**
$form->isSubmitted()  - seems to be not relevant here as we submit the form in an explicit way and verify before the POST method (and not GET to show the twig view).

### CODE REVIEW

**Comment by xabbuh** [comment]
I think I would still keep the method call even if it's technically not needed. But having it allows to not run into any issues once you decide to replace the `submit()` call with `handleRequest()`.

**Comment by KamilKubicki** [comment]
> I think I would still keep the method call even if it's technically not needed. But having it allows to not run into any issues once you decide to replace the `submit()` call with `handleRequest()`.

I do agree, however the way documentation shows, the code avoids using `handleRequest()` and does use `submit()`. The title is 'How to use Submit...'. It might be confusing.

**Comment by xabbuh** [comment]
Yes, but something looking at the application later will likely not know which part of the documentation the original author of these lines of code read when writing it.

**Comment by javiereguiluz** [comment]
Let's close this one without merging. Kamil, you are technically correct and we thank you for contributing this ... but regarding the `isSubmitted()` method we use it everywhere to be super explicit about the code behavior. Thanks for understanding!

**Pull request closed without merging**
