### PR TITLE
Documented HTTP caching and user sessions

### PR DESCRIPTION
**Pull request by Toflar**
As promised in https://github.com/symfony/symfony-docs/issues/9647.

### CODE REVIEW

**Comment by javiereguiluz** [comment]
@Toflar thanks a lot for this contribution! It's perfectly explained nad it's easy to follow.

However, I made some rewords to make the explanations more concise. We do this routinely not only for the readers, but also for us, to make contents easier to maintain. Thanks!

**Comment by Toflar** [comment]
It's perfectly fine. Rewording by the same people makes sure the readers have a consistent reading experience, it's perfect! Thank you very much!

**Comment by Toflar** [comment]
BTW: What's the policy to use `.. versionadded:: 4.1`? Should we maybe also use that here?

**Comment by javiereguiluz** [comment]
And it's merged!! Thanks Yanick!

**Pull request merged**
