### PR TITLE
[TwigBundle] Add documentation about generating absolute URL with the asset function

### PR DESCRIPTION
**Pull request by romainneutron**
| Q | A |
| --- | --- |
| Doc fix? | no |
| New docs? | yes (symfony/symfony#10451) |
| Applies to | 2.5+ |

### CODE REVIEW

**Comment by 12th** [comment]
If use absolute_url() for image from the CLI the url is without host, because masterRequest is empty. 
Please tell me how get absolute url for image, for example in email?

**Comment by weaverryan** [comment]
@12th check out this: http://symfony.com/doc/current/cookbook/console/sending_emails.html. By setting the request information on the router's request context, it will be used when generating the absolute URL for assets.

**Comment by WouterJ** [comment]
@weaverryan with the new Asset component, that does no longer work (see for instance, https://github.com/symfony/symfony/issues/15448)

**Comment by weaverryan** [comment]
@WouterJ Ah thanks - I was looking at the code PR tied to this, but not looking at the more recent updates. In that case, you'll need to work around this for now: i.e. hardcoding the host name in the email and using non-absolute URL's to the assets with that, or perhaps manually setting the host on the Request object (I'm assuming the second idea would work - but I haven't tried it).

**Pull request merged**
