### PR TITLE
typo fix in pre authenticated

### PR DESCRIPTION
**Pull request by zefrog**
Simple typo in pre_auth cookbook entry

### CODE REVIEW

**Comment by javiereguiluz** [comment]
:+1: nice catch!

**Comment by WouterJ** [comment]
:+1:

**Comment by OskarStark** [comment]
:+1: thank you @zefrog

**Comment by WouterJ** [comment]
Thanks @zefrog! I've merged this into the 2.7 branch. This typo was introduced in 2.6, but we no longer support 2.6 as Symfony 2.6.x reached end of maintaince.

**Pull request closed without merging**
