### PR TITLE
Deprecated the web_profiler.position option

### LINKED ISSUE #8466: Deprecated the web_profiler.position option
https://github.com/symfony/symfony/issues/23528

### PR DESCRIPTION
**Pull request by javiereguiluz**
This fixes #8466.

### CODE REVIEW

**Comment by xabbuh** [comment]
Didn't we just remove deprecated options in the past?

**Comment by javiereguiluz** [comment]
I don't know ... but I guess we need to document deprecated versions and remove them in the first Symfony version which doesn't include them (master/4.0 in this case).

**Comment by weaverryan** [comment]
@xabbuh that *does* sound a little bit familiar. But adding the option as deprecated and removing it in 4.0 (like we do with other things) makes sense to me.

**Review by weaverryan — APPROVED** [review]

**Comment by xabbuh** [comment]
Thank you Javier.

**Comment by xabbuh** [comment]
as merging branches up already caused conflicts I removed these changes when merging into the `master` branch

**Pull request merged**
