### PR TITLE
Fix event_dispatcher AappBundle typo

### PR DESCRIPTION
**Pull request by ThomasLomas**
| Q | A |
| --- | --- |
| Doc fix? | yes |
| New docs? | no |
| Applies to | all |
| Fixed tickets | - |

This is a typo that exists in 2.5 onwards.

Should I also submit PRs for the newer versions too?

### CODE REVIEW

**Comment by stof** [comment]
@ThomasLomas a single PR is enough. Each branch is merged into newer branch regularly

**Comment by ThomasLomas** [comment]
@stof Ah great stuff.

**Comment by javiereguiluz** [comment]
:+1: thanks @ThomasLomas.

Fixes should only be done in *"the oldest, but still maintained, branch in which the error occurs"*. This usually means committing fixes to 2.3, but in this case it's OK to commit to 2.5 (in 2.3 it doesn't appear and 2.4 is no longer maintained). Then, the code managers will get you commit and apply it upwards to every maintained branch (2.6, 2.7, 3.0-dev)

**Comment by WouterJ** [comment]
Thank you @ThomasLomas!

However, this was already fixed in the 2.3 branch (https://github.com/symfony/symfony-docs/commit/0f6e0455922812d5e473a22c89fcd10d88d9bd9d) the problem is that the 2.3 branch isn't merged into the 2.5 branch yet. I'll try to merge the branches this week.

I'm going to close this PR for that reason, otherwise it'll cause even more merge conflicts :) Thanks again and I hope I can merge other PRs of you in the future!

**Comment by xabbuh** [comment]
@WouterJ I guess the reason is that this was merged after 2.5 reached the end of maintenance.

**Comment by ThomasLomas** [comment]
Ok thanks @WouterJ

**Pull request closed without merging**
