### PR TITLE
Move some articles from wrong sections

### PR DESCRIPTION
**Pull request by sylvaincombes**
| Q | A |
| --- | --- |
| Doc fix? | no |
| New docs? | no |
| Applies to | 2.3 |
| Fixed tickets | #4416 |

### CODE REVIEW

**Comment by WouterJ** [comment]
Looks good to me.

Only thing I wonder is whether this will break older (not maintained) versions as the redirection maybe applies there as well. We desperately need version based redirection.

However, that's not a problem you caused. The PR is perfect!

**Comment by weaverryan** [comment]
@sylvaincombes It looks like we're still missing an update to at least one link: https://travis-ci.org/symfony/symfony-docs/builds/63781352

**Comment by WouterJ** [comment]
Sorry to bother you again without merging this PR @sylvaincombes, but it seems like one of the articles was updated and is now introducing a merge conflict. Can you please rebase? (if you don't know how to do it, we can help you or do it for you)

**Comment by WouterJ** [comment]
Thank you @sylvaincombes! I've continued your work in https://github.com/symfony/symfony-docs/pull/5575 (using your commits, so you still get the credits)

**Pull request closed without merging**
