### PR TITLE
[Config] [Configuration] Add `$_ENV` and `$_SERVER` example with .env

### PR DESCRIPTION
**Pull request by alexandre-daubois**
Fixes https://github.com/symfony/symfony-docs/issues/17693

### CODE REVIEW

**Comment by xabbuh** [comment]
Is it really a common use case to access environment variables through the superglobal arrays? I usually reference them inside my service configuration with `%env(...)%` instead (values are injected into services this way instead of having code depend on global state).

**Comment by alexandre-daubois** [comment]
I wouldn't say it is "common" but this is something that can happen, especially when using the Dotenv component as a standalone. But I may add a note to inform that best practices is to inject env vars through `%env()%` maybe?

**Comment by xabbuh** [comment]
I think I would put it the other way around: Show examples how to make use of the env processor in the DI config and add a short sentence explaining that you *could* also access the value through the superglobal arrays.

**Comment by alexandre-daubois** [comment]
I moved the paragraph below the examples with `%env()%` and reworded a bit to indicates that env vars _may_ be accessed in the code. Is it better? 🙂

**Comment by javiereguiluz** [comment]
Thanks Alex!

Similar to Christian, I was a bit concerned about this. So, while merging I "demoted" this explanation to a `note` and added a message to warn readers that they should really not use this in Symfony apps. See https://github.com/symfony/symfony-docs/commit/3a4b017939560a1805514d08e7da588ec47846f4

**Pull request merged**
