### PR TITLE
Update entity_provider.rst

### PR DESCRIPTION
**Pull request by araujo0205**
Is not necessary create repository.

### CODE REVIEW

**Comment by xabbuh** [comment]
In this example it is required because further down we implement a custom `loadUserByUsername()` method in this `UserRepository` class.

**Comment by araujo0205** [comment]
So I find it interesting to put a note that you do not need this repository. What do you think ?

**Comment by xabbuh** [comment]
What we can do is to remove the `repositoryClass` configuration in the first mapping example like you did here. But we will then need to expand the section below where we talk about the repository and show how to configure that class in your entity.

**Comment by HeahDude** [comment]
Hello @araujo0205 would you like to address @xabbuh's comment or do you want we to take over? Thanks!

**Comment by araujo0205** [comment]
I @HeahDude,you can take this change.
Thanks.

**Comment by javiereguiluz** [comment]
Let's close this as "won't fix" because creating a repository for each entity is a practice we want to promote. Thanks!

**Pull request closed without merging**
